### PR TITLE
Project and controller

### PR DESCRIPTION
**Pull request by svouse**
**Summary:** Implements all non-export Project methods, and the methods that are directly needed in the new implementations.

**Goal:** Maintain functionality, add viable methods.

**Specifically Includes:**
- Implementation of Project methods
- Implementation of has(blockType) for BlockLibrarySet, change of its return type
- Changed name of addBlockDefinition in block_library.js (we know what we're adding to a block library)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/122)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/project_controller.js, line 168 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSe_r--ZOpPXD9cEDg:-KpSe_r--ZOpPXD9cEDh:brte854) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L168)):*
> ```JavaScript
>   addBlockDefinition(blockDef, libraryName) {
>     this.project.addBlockDefinition(blockDef, libraryName);
>     this.tree.addBlockNode(blockDef.name, libraryName);
> ```

Nit: use `blockDef.type()` since we have that getter function?
(Though I suppose it doesn't really matter all Too Much)

---

*[src/controller/project_controller.js, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSeR9uJqnJUbDARS94:-KpSeR9uJqnJUbDARS95:b-hbuo32) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L273)):*
> ```JavaScript
>   rename(resource, newName) {
>     //TODO: restrict names.
>     resource.setName();
> ```

Did you mean to pass in a parameter?

---

*[src/model/block_library_set.js, line 72 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSetPv-6DMRlFKfgMO:-KpSetPv-6DMRlFKfgMP:b-qd6ec9) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/block_library_set.js#L72)):*
> ```JavaScript
> 
>   /**
>    * Returns whether or not a named block is in the library set.
> ```

I suggest you rename this function to `getLibrary()`because the name of the function makes it sound like this returns a boolean (though it does offer the same/more information than would a `hasBlock()` function). Also possibly reword the jsdoc to correspond.

---

*[src/model/block_library_set.js, line 74 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSfYp73Idd5FFYW5Io:-KpSfYp73Idd5FFYW5Ip:b-bic3aw) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/block_library_set.js#L74)):*
> ```JavaScript
>    * Returns whether or not a named block is in the library set.
>    * @param {string} blockType The name of the block to be found.
>    * @return {Object} The block library that has the block or null.
> ```

`@return {?BlockLibrary}`?
(the `?` means could be null, I believe)

---

*[src/model/project.js, line 116 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSg3eUgStEZ6X_SYBp:-KpSg3eUgStEZ6X_SYBq:b14lhs) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L116)):*
> ```JavaScript
> 
>   /**
>    * Adds a block definition to the project.
> ```

"[...] to the given BlockLibrary in the Project." ?

---

*[src/model/project.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSgKhIAd_O85buVuXQ:-KpSgKhIAd_O85buVuXR:bd0xzjb) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L122)):*
> ```JavaScript
>    */
>   addBlockDefinition(blockDef, libraryName) {
>     const library = this.librarySet.has(blockType);
> ```

Is it `has()` or `hasBlock()` that you meant to call? I don't think I see a `has()` function in `BlockLibrary`.

---

*[src/model/project.js, line 229 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSfSfuZlrtm5CsxG17:-KpSfSfvxeSHz8FGRW3q:b7sx5co) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L229)):*
> ```JavaScript
>    */
>   hasBlock(blockType) {
>     return this.librarySet.hasBlock(blockType);
> ```

If the library set class's `hasBlock()` now returns a `BlockLibrary`, this return type should also return a `BlockLibrary`. (Or you might also rename it per my previous comment.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/project_controller.js, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSgUR4m2KM0Yp-J_FO:-KpSgUR5IRKTVYw0OdG9:b4z3rn3) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L273)):*
> ```JavaScript
>   rename(resource, newName) {
>     //TODO: restrict names.
>     resource.setName();
> ```

Not using `newName`.  Use it or remove it.

---

*[src/model/block_library_set.js, line 72 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSetPv-6DMRlFKfgMO:-KpSgeG6gs-DUI9uU87I:b-6vben7) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/block_library_set.js#L72)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I suggest you rename this function to `getLibrary()`because the name of the function makes it sound like this returns a boolean (though it does offer the same/more information than would a `hasBlock()` function). Also possibly reword the jsdoc to correspond.
</blockquote></details>

+1.  If you want, you can also have a function called `hasBlock` or `has` that just returns whether this function returned `null`.  (Sorry, convoluted phrasing.)

The question there is whether you would ever use it rather than using the version that returns the library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/controller/project_controller.js, line 168 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSe_r--ZOpPXD9cEDg:-KpVunh7yGvnsbhrdeAX:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L168)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: use `blockDef.type()` since we have that getter function?
(Though I suppose it doesn't really matter all Too Much)
</blockquote></details>

Done.

---

*[src/controller/project_controller.js, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSeR9uJqnJUbDARS94:-KpVupK9_-YPoxsFPHfy:b-usyf7x) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L273)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Did you mean to pass in a parameter?
</blockquote></details>

Whoops; using it now.

---

*[src/controller/project_controller.js, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSgUR4m2KM0Yp-J_FO:-KpVusQNKA0QDAVb3yNC:b-usyf7x) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/controller/project_controller.js#L273)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Not using `newName`.  Use it or remove it.
</blockquote></details>

Whoops; using it now.

---

*[src/model/block_library_set.js, line 72 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSetPv-6DMRlFKfgMO:-KpVv4oZujQ6IYdxmzF7:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/block_library_set.js#L72)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

+1.  If you want, you can also have a function called `hasBlock` or `has` that just returns whether this function returned `null`.  (Sorry, convoluted phrasing.)

The question there is whether you would ever use it rather than using the version that returns the library.
</blockquote></details>

Done.

---

*[src/model/block_library_set.js, line 74 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSfYp73Idd5FFYW5Io:-KpVvNB0uiCk4Q06DNTp:b9fx4qj) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/block_library_set.js#L74)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`@return {?BlockLibrary}`?
(the `?` means could be null, I believe)
</blockquote></details>

Cool thanks

---

*[src/model/project.js, line 116 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSg3eUgStEZ6X_SYBp:-KpVx6j69z1P5gQFj03L:bqqfopm) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L116)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

"[...] to the given BlockLibrary in the Project." ?
</blockquote></details>

Done. (also changed from name to just the library itself)

---

*[src/model/project.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSgKhIAd_O85buVuXQ:-KpVwrLRarQ1EpYB14dH:b3cof7d) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L122)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Is it `has()` or `hasBlock()` that you meant to call? I don't think I see a `has()` function in `BlockLibrary`.
</blockquote></details>

changed to getLibrary

---

*[src/model/project.js, line 229 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpSfSfuZlrtm5CsxG17:-KpVxdD_a0cvKRWcanHO:b-wfdcx7) ([raw file](https://github.com/google/blockly-devtools/blob/9dd45d9a5b4d9de77ba60faf9a0f6aa82497e675/src/model/project.js#L229)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

If the library set class's `hasBlock()` now returns a `BlockLibrary`, this return type should also return a `BlockLibrary`. (Or you might also rename it per my previous comment.)
</blockquote></details>

made a has

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122#-:-KpW-noPZJw1DDV7t9iw:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
:

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/model/project.js, line 122 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWDXMLw3jH9PjYY7nZ:-KpWDXMLw3jH9PjYY7n_:bclm9u3) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/project.js#L122)):*
> ```JavaScript
>    */
>   addBlockDefinition(blockDef, libraryName) {
>     library.add(blockDef);
> ```

This is equivalent to the single line `getLibrary(libraryName).add(blockDef)`. I recommend removing the this to avoid later maintenance.

---

*[src/model/project.js, line 214 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWElmi2FLXxR_GtgJN:-KpWElmjB_eUSRy6Map-:b-bypbx8) ([raw file](https://github.com/google/blockly-devtools/blob/c82377c60a06b227b881f504632708f5ba282790/src/model/project.js#L214)):*
> ```JavaScript
>    */
>   //TODO #52: move warning from BlockLibraryController to ProjectController.
>   isDirty() {
> ```

Is this being replaced with something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122#-:-KpWEaBCDm8YixU32Ml7:b3kr9)*

**Comment by rachel-fenichel** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/model/block_library_set.js, line 85 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWH-M4kCT8wpmDm9Sj:-KpWH-M4kCT8wpmDm9Sk:bgc8qh) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/block_library_set.js#L85)):*
> ```JavaScript
>    * @return {?BlockLibrary} The block library that has the block or null.
>    */
>   getBlock(blockType) {
> ```

This name still doesn't match what the function is doing.  `getLibrary`?  `getContainingLibrary`?

---

*[src/model/project.js, line 121 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWHBPmzVSCx-GqTMUy:-KpWHBPmzVSCx-GqTMUz:b-pe63e2) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/project.js#L121)):*
> ```JavaScript
>    * @param {!BlockLibrary} library The library to add it to.
>    */
>   addBlockDefinition(blockDef, libraryName) {
> ```

Now you're using an undefined variable.  Eslint should be warning you about these things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/model/project.js, line 121 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWHBPmzVSCx-GqTMUy:-KpWHc2HW0CNFqbXon3g:b-z54wn) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/project.js#L121)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Now you're using an undefined variable.  Eslint should be warning you about these things.
</blockquote></details>

I'll check out my configuration

---

*[src/model/project.js, line 122 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWDXMLw3jH9PjYY7nZ:-KpWGwKsCPKf8AEJi0XB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/project.js#L122)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This is equivalent to the single line `getLibrary(libraryName).add(blockDef)`. I recommend removing the this to avoid later maintenance.
</blockquote></details>

Done.

---

*[src/model/project.js, line 214 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWElmi2FLXxR_GtgJN:-KpWHoYxu9IRag8K19_i:b-i7z10x) ([raw file](https://github.com/google/blockly-devtools/blob/c82377c60a06b227b881f504632708f5ba282790/src/model/project.js#L214)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Is this being replaced with something else?
</blockquote></details>

Yup; warnIfUnsaved in either the EditorController or the controllers it manages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by svouse** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/model/block_library_set.js, line 85 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/122#-KpWH-M4kCT8wpmDm9Sj:-KpWIBqaa1jjaYmG6sly:by331hg) ([raw file](https://github.com/google/blockly-devtools/blob/04c6407e40023d04c63a89cc2f774c64b7753139/src/model/block_library_set.js#L85)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This name still doesn't match what the function is doing.  `getLibrary`?  `getContainingLibrary`?
</blockquote></details>

Fixed (should've been getLibrary)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122#-:-KpWIsrieyd2M7eGOD8J:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/122#-:-KpWJ8VKf8w926ztvrkP:bnfp4nl)*

**Pull request merged**
