### PR TITLE
BlockEditorView on page load

### PR DESCRIPTION
**Pull request by chynu**
**Completed:**
 - `factory_base` block now shown on page load.
 - save/delete buttons update properly (model-side storage not fully implemented)
 - displaying the block definition
 - Preview, generator stub, and block definitions populate correctly

**In progress:**
 - Updating on changes to editor workspace

**Dependencies (necessary to fully test):**
 - library sets / block library / blockdefinition object functions

NOTE: Rearranged some of the HTML (pretty trivial, but added lots of additions/deletions in this PR's diff that aren't really changes).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/113)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLm99y-Z8Pzx0sOat8:-KpLm99y-Z8Pzx0sOat9:bmcd3v5) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/block_editor_controller.js#L33)):*
> ```JavaScript
> goog.provide('BlockEditorController');
> 
> goog.require('BlockDefinition');
> ```

Requires BlockLibrary and BlockEditorView

---

*[src/controller/block_editor_controller.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLoO8Y-OM65v0jhmts:-KpLoO8Y-OM65v0jhmtt:bfrhuap) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/block_editor_controller.js#L140)):*
> ```JavaScript
>    */
>   updateGenerator(block) {
>     // REFACTORED: Moved in from factory.js:updatePreview()
> ```

Just a notation question: does/should factory.js contain a similar note saying the function was moved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLrDBQOldbi0OPTXNU:-KpLrDBQOldbi0OPTXNV:bs2kuzj) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/app_controller_2.js#L34)):*
> ```JavaScript
> goog.require('AppView');
> goog.require('EditorController');
> goog.require('FactoryUtils');
> ```

Requires NavigationTree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by chynu** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLrDBQOldbi0OPTXNU:-KpLrbt8HfmEOWMPz0CW:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/app_controller_2.js#L34)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Requires NavigationTree
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLm99y-Z8Pzx0sOat8:-KpLrGihfuZOLRT9KBBj:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/block_editor_controller.js#L33)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Requires BlockLibrary and BlockEditorView
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLoO8Y-OM65v0jhmts:-KpLrHlWEHMjBxr9hHvE:b9ol4bg) ([raw file](https://github.com/google/blockly-devtools/blob/7debfcc5b9e077786bf6e025c3cf5c79209cdace/src/controller/block_editor_controller.js#L140)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Just a notation question: does/should factory.js contain a similar note saying the function was moved?
</blockquote></details>

Ohh, I've been forgetting about that. 
Removed refactored code from original files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/editor_controller.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsCLHPgVYSDifLdhU:-KpLsCLHPgVYSDifLdhV:b2zvrd5) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L99)):*
> ```JavaScript
>    */
>   isDefinedBlock(block) {
>     // REFACTORED: from wfactory_controller.js
> ```

remove code from wfactory_controller.js

---

*[src/view/app_view.js, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsfn0x3Iwwo7OZ3Ht:-KpLsfn0x3Iwwo7OZ3Hu:b-3eylj6) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/view/app_view.js#L459)):*
> ```JavaScript
>   addBlockFactoryEventListeners() {
>     console.log('listeners called');
>     // REFACTORED: Moved in from app_controller.js
> ```

remove from app_controller.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/app_view.js, line 485 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLtLomu8WbNhR4r1bt:-KpLtLonPqOOLhOMo4H1:b7xvuj1) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/view/app_view.js#L485)):*
> ```JavaScript
>    */
>   openBlock(blockType) {
>     this.blockEditorView.openBlock(blockType);
> ```

Is this function necessary here? (as opposed to just calling blockEditorView.openBlock)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by chynu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/editor_controller.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsCLHPgVYSDifLdhU:-KpLv4z8DdUPTWLc37Oq:b-xgfrz4) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L99)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

remove code from wfactory_controller.js
</blockquote></details>

I think I might have already removed it (unless I am completely missing something) (?) Unless you're talking about the one in `wfactory_model.js` which is different, I believe.

---

*[src/view/app_view.js, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsfn0x3Iwwo7OZ3Ht:-KpLuwsbVw9wKUwaB8f2:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/view/app_view.js#L459)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

remove from app_controller.js
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 485 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLtLomu8WbNhR4r1bt:-KpLuxC1-o3uCakYlnVN:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/view/app_view.js#L485)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Is this function necessary here? (as opposed to just calling blockEditorView.openBlock)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/editor_controller.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLtuAl5QTcv96F9QnY:-KpLtuAl5QTcv96F9QnZ:btwob5w) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L73)):*
> ```JavaScript
>      * @type {(!ToolboxController|!WorkspaceController|!BlockEditorController)}
>      */
>     this.currentEditor = this.blockEditorController;
> ```

maybe change name because this isn't always a BlockEditorController?

---

*[src/controller/new_block_popup_controller.js, line 37 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLwOk2kt7uYvqno22X:-KpLwOk2kt7uYvqno22Y:b-jj1we) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/new_block_popup_controller.js#L37)):*
> ```JavaScript
>   /**
>    * @constructor
>    * @param {AppController2} AppController2 object which controls the application
> ```

missing param name. Also aside: maybe we can just switch AppController2 to AppController sooner rather than later? We could change the name of AppController if namespace is a worry/we still want to work off of the file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
*[src/controller/editor_controller.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsCLHPgVYSDifLdhU:-KpLwryXYFzCO4NWN3Us:be899jg) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L99)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think I might have already removed it (unless I am completely missing something) (?) Unless you're talking about the one in `wfactory_model.js` which is different, I believe.
</blockquote></details>

Yup sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by chynu** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/editor_controller.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLtuAl5QTcv96F9QnY:-KpLxwQV_8dhx1wyQwD2:b-eqd77x) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L73)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

maybe change name because this isn't always a BlockEditorController?
</blockquote></details>

Resolved as per private discussion

---

*[src/controller/editor_controller.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLsCLHPgVYSDifLdhU:-KpLxHUeh3uxTjVdSIsI:b-3y6g8a) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/editor_controller.js#L99)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Yup sorry
</blockquote></details>

No problem :) 

---

*[src/controller/new_block_popup_controller.js, line 37 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpLwOk2kt7uYvqno22X:-KpLxM2P47yryAfj2el2:b-ji6sw7) ([raw file](https://github.com/google/blockly-devtools/blob/27c7700c1033dcb935524d05e73c6b9af44f91cb/src/controller/new_block_popup_controller.js#L37)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

missing param name. Also aside: maybe we can just switch AppController2 to AppController sooner rather than later? We could change the name of AppController if namespace is a worry/we still want to work off of the file
</blockquote></details>

Done.

@ aside: That is true. I keep pushing it off because it takes an annoying amount of time to change it all completely w/o reference errors and I want to get features finished, haha.

I can do it for the next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by svouse** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113#-:-KpLy9Imgu3FMs9Rx49G:bnfp4nl)*

**Review by svouse — APPROVED** [review]

**Comment by rachel-fenichel** [comment]
Reviewed 8 of 13 files at r1, 2 of 3 files at r2, 4 of 4 files at r3.
Review status: 14 of 15 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 60 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpME-XpdVq5mo6Uwhe5:-KpME-Xqb_AqiOXo0wyq:b-1ph7st) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L60)):*
> ```JavaScript
>     this.currentLibrary = new BlockLibrary('MyFirstLibrary');
> 
>     // Creating a default library, adds a sample block to library
> ```

Is this "Creates a default library and adds a sample block to that library" or "Creating a default library adds a sample block to that library"?

Either way, period at the end of the sentence.

---

*[src/controller/block_editor_controller.js, line 87 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEGV5TgIBaru-zjh-:-KpMEGV5TgIBaru-zjh0:b-mzvk8q) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L87)):*
> ```JavaScript
>     // Opens block in workspace when first creating the BlockEditorController.
>     // this.openBlock(this.view.blockDefinition);
>     // The above was commented out because it depends on not yet implemented
> ```

When will this be fixed?  If not within the day, make an explicit todo.

---

*[src/controller/block_editor_controller.js, line 90 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMENpdkinrtb9kYDAx:-KpMENpdkinrtb9kYDAy:bieem6y) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L90)):*
> ```JavaScript
>     // model functions.
> 
>     // Refreshes previews (preview block, block definition, generator stub).
> ```

This comment just repeats what the code says.  Leave it out.  If someone wants to know which previews are being the doc on the function definition will be sufficient.

---

*[src/controller/block_editor_controller.js, line 106 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEblbzD-EtQG_N1wl:-KpMEblbzD-EtQG_N1wm:bnl1erg) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L106)):*
> ```JavaScript
>   /**
>    * Opens a given BlockDefinition to be edited in Block Editor view. If the
>    * given BlockDefinition does not exist, creates a new BlockDefinition under
> ```

How would someone have a BlockDefinition (rather than just a string for the name) when that BlockDefinition doesn't exist in the library?  Where would they get it from?

---

*[src/controller/block_editor_controller.js, line 108 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEjeoIJLfYCSGXVg9:-KpMEjeoIJLfYCSGXVgA:b-bawehg) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L108)):*
> ```JavaScript
>    * given BlockDefinition does not exist, creates a new BlockDefinition under
>    * that name and then displays it.
>    * @param {BlockDefinition} blockDefinition BlockDefinition object
> ```

Non-null

---

*[src/controller/block_editor_controller.js, line 177 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMF-rhp0BKG5GoZs3c:-KpMF-rhp0BKG5GoZs3d:b-vpevmx) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L177)):*
>   const format = blockDef[0];
>     const format = blockDef[1];
???

---

*[src/controller/block_editor_controller.js, line 179 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMFrpzim0oheHD0PU-:-KpMFrpzim0oheHD0PU0:bqvlosi) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L179)):*
> ```JavaScript
>     const format = blockDef[1];
> 
>     if (!code.trim()) {
> ```

Code is not defined.  Was the second `format` supposed to be `code` instead?

---

*[src/controller/block_editor_controller.js, line 193 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMFacajVU8ni9JMpfB:-KpMFacajVU8ni9JMpfC:b89ki50) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L193)):*
> ```JavaScript
>       this.renderPreviewBlock_(blockType);
>       // Warn user if block type is invalid.
>       this.warnUser_(blockType);
> ```

`warnUser_` doesn't always warn the user--it executes some logic and warns the user in given cases.  So rename it to `maybeWarnUser_`

---

*[src/controller/block_editor_controller.js, line 246 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMG4YaCrMiBibQLLow:-KpMG4YaCrMiBibQLLox:btkh67o) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L246)):*
> ```JavaScript
>     }
> 
>     if (format == 'JSON') {
> ```

Should use constants for these.

---

*[src/controller/block_editor_controller.js, line 291 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGGJUGWLQXbZt1zgd:-KpMGGJUGWLQXbZt1zge:b-fli67g) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L291)):*
> ```JavaScript
>       rootBlock.setWarningText('A core Blockly block already exists ' +
>           'under this name.');
> ```

Delete unused newline.

---

*[src/controller/block_editor_controller.js, line 297 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGHvlc3tFDrRqYL_i:-KpMGHvlc3tFDrRqYL_j:b-fli67g) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L297)):*
> ```JavaScript
>       rootBlock.setWarningText('You cannot save a block with the default ' +
>           'name, "block_type"');
> ```

Delete unused newline.

---

*[src/controller/new_block_popup_controller.js, line 90 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGTlaLu-AAD-1KuXI:-KpMGTlaLu-AAD-1KuXJ:bkny3ir) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/new_block_popup_controller.js#L90)):*
> ```JavaScript
>    */
>   checkDuplicate() {
>     const hasDuplicate = this.appController.project.hasBlock($("#block_name").val());
> ```

Single quotes, while you're changing this line.

---

*[src/view/block_editor_view.js, line 31 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGhDJHnoM1DqVO3SD:-KpMGhDJHnoM1DqVO3SE:b-8qnkog) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/view/block_editor_view.js#L31)):*
> ```JavaScript
> 
> goog.provide('BlockEditorView');
> goog.require('BlockDefinition');
> ```

Newline between provide and requires, and between groups of requires in different namespaces.  So this should be
```
goog.provide('BlockEditorView');

goog.require('BlockDefinition');

goog.require('goog.dom');
goog.require('goog.dom.classlist');
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Comment by AnmAtAnm** [comment]
Minor comments, then :lgtm:  

---

Review status: 14 of 15 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 58 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMHLD5sMLVrK1Y-SVz:-KpMHLD5sMLVrK1Y-SW-:bx7vu62) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L58)):*
> ```JavaScript
>      * @type {!BlockLibrary}
>      */
>     this.currentLibrary = new BlockLibrary('MyFirstLibrary');
> ```

I'm surprised to see this change from definition to library. This is block editor, right?  Is it temporary during the transition from the old model?

---

*[src/controller/block_editor_controller.js, line 63 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMHG-JrIfIti6-cyoA:-KpMHG-KccGrDgrGYwdB:b3bnp2r) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L63)):*
> ```JavaScript
>     this.project.addBlockLibrary(this.currentLibrary);
>     const firstBlock = new BlockDefinition('block_type');
>     this.currentLibrary.addBlockDefinition(firstBlock);
> ```

I'm guessing we don't need to assign any block or library before the project controller assigns the block and library from the tree or popup dialog.

---

*[src/controller/block_editor_controller.js, line 246 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMG4YaCrMiBibQLLow:-KpMP8c_7zokZ8e6nkQK:bfl7ldp) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L246)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Should use constants for these.
</blockquote></details>

e.g., `FORMAT_JSON = 'JSON'` somewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113#-:-KpMPn57xhPsDoUmJM0v:bp2v87r)*

**Comment by chynu** [comment]
Review status: 11 of 15 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 58 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMHLD5sMLVrK1Y-SVz:-KpMS3mahRH2b4b7C2Ik:bpq0kox) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L58)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm surprised to see this change from definition to library. This is block editor, right?  Is it temporary during the transition from the old model?
</blockquote></details>

Ah, I realized this field is not necessary. I removed it.

---

*[src/controller/block_editor_controller.js, line 60 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpME-XpdVq5mo6Uwhe5:-KpMITQCQsxq7C6jAwqI:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L60)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Is this "Creates a default library and adds a sample block to that library" or "Creating a default library adds a sample block to that library"?

Either way, period at the end of the sentence.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 63 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMHG-JrIfIti6-cyoA:-KpMSXZ-_IyNZAlftK66:b-bjs50d) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L63)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm guessing we don't need to assign any block or library before the project controller assigns the block and library from the tree or popup dialog.
</blockquote></details>

Hm, I was thinking of pre-populating the editor with a sample BlockDefinition ('block_type') and BlockLibrary in case the user exits the popup. This is only created on load, so it will happen only once when the user opens a new project. I was thinking of deleting the BlockDefinition (type 'block_type') if the user goes through with initializing a BlockDefinition through the popup. If they exit halfway through, there will be a default one in the editor that the user can manually build as well.

---

*[src/controller/block_editor_controller.js, line 87 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEGV5TgIBaru-zjh-:-KpMIXm0gvnhZObk-y5E:b-hukn99) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L87)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

When will this be fixed?  If not within the day, make an explicit todo.
</blockquote></details>

Added TODO.

---

*[src/controller/block_editor_controller.js, line 90 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMENpdkinrtb9kYDAx:-KpMIf1fIfTVVguRMXXq:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L90)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This comment just repeats what the code says.  Leave it out.  If someone wants to know which previews are being the doc on the function definition will be sufficient.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 106 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEblbzD-EtQG_N1wl:-KpMJ6sf8m3GxJ3B_Yfp:bs9vcy4) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L106)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

How would someone have a BlockDefinition (rather than just a string for the name) when that BlockDefinition doesn't exist in the library?  Where would they get it from?
</blockquote></details>

Oh... I realized I don't need this function.

---

*[src/controller/block_editor_controller.js, line 108 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMEjeoIJLfYCSGXVg9:-KpMP7qI9UMvEYJYONJP:bqfzuvi) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L108)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Non-null
</blockquote></details>

(Removed function)

---

*[src/controller/block_editor_controller.js, line 177 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMF-rhp0BKG5GoZs3c:-KpMIv7PbIaNM37q5Iec:b-si7kfc) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L177)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

>   const format = blockDef[0];
>     const format = blockDef[1];
???
</blockquote></details>

Oh.. I meant it to be `code`.

---

*[src/controller/block_editor_controller.js, line 179 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMFrpzim0oheHD0PU-:-KpMIxKAK_VdMpoZfJ7w:bv7jf92) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L179)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Code is not defined.  Was the second `format` supposed to be `code` instead?
</blockquote></details>

Yes, that was a bad typo.

---

*[src/controller/block_editor_controller.js, line 193 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMFacajVU8ni9JMpfB:-KpMPLcBU-LPGGq2Roi8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L193)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

`warnUser_` doesn't always warn the user--it executes some logic and warns the user in given cases.  So rename it to `maybeWarnUser_`
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 246 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMG4YaCrMiBibQLLow:-KpMQDcqtOdUdDl0wl6F:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L246)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

e.g., `FORMAT_JSON = 'JSON'` somewhere.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 291 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGGJUGWLQXbZt1zgd:-KpMQLg-2Zi1teQeT7qa:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L291)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Delete unused newline.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 297 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGHvlc3tFDrRqYL_i:-KpMQLzpGxOWpsCtnQ0O:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/block_editor_controller.js#L297)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Delete unused newline.
</blockquote></details>

Done.

---

*[src/controller/new_block_popup_controller.js, line 90 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGTlaLu-AAD-1KuXI:-KpMRNZwq8UOKTrRm3ys:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/controller/new_block_popup_controller.js#L90)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Single quotes, while you're changing this line.
</blockquote></details>

Done.

---

*[src/view/block_editor_view.js, line 31 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/113#-KpMGhDJHnoM1DqVO3SD:-KpMRQFqwfO_THnQ48_M:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/07544e29ba57dd443bfcb56b63a51aae9ec45648/src/view/block_editor_view.js#L31)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Newline between provide and requires, and between groups of requires in different namespaces.  So this should be
```
goog.provide('BlockEditorView');

goog.require('BlockDefinition');

goog.require('goog.dom');
goog.require('goog.dom.classlist');
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/113)*

**Pull request closed without merging**
