### PR TITLE
Refactor: Workspace Factory View

### PR DESCRIPTION
**Pull request by chynu**
Refactored 17/17 functions from `wfactory_view.js` to refactor files. Did not move over some functions that are no longer relevant to DevTools.

For future: implement functions. Tidy code.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/84)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/factory_utils.js, line 1148 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP653REN08wGIFl6vu:-KoP653REN08wGIFl6vv:bqtk3kf) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/factory_utils.js#L1148)):*
> ```JavaScript
>  * @param {!Function} func Function to be executed on click.
>  */
> FactoryUtils.bindClick = function(el, func) {
> ```

weird/possibly not there nit; is this e1 in the documentation and el in the param/everywhere else? Or is the font just silly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84)*

**Comment by AnmAtAnm** [comment]
Two comments following our offline discussion.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/factory_utils.js, line 1163 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP5jDNQs46co7Mwoqb:-KoP5jDNQs46co7Mwoqc:buvg68o) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/factory_utils.js#L1163)):*
> ```JavaScript
>  * @param {!Blob} data Blob containing contents to download
>  */
> WorkspaceFactoryView.prototype.createAndDownloadFile = function(filename, data) {
> ```

replace `WorkspaceFactoryView.prototype` with `FactoryUtils`.

---

*[src/view/toolbox_editor_view.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP707SJHlGRAlk2cj2:-KoP707SJHlGRAlk2cj3:b-ajlqfr) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/view/toolbox_editor_view.js#L94)):*
> ```JavaScript
>    * @return {!Element} DOM element created for tab
>    */
>   addCategoryTab(name, id) {
> ```

This and the following methods sound like controller (or even model) methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84#-:-KoP7lXGZtH6-73CcH7q:bmjiulv)*

**Comment by chynu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/factory_utils.js, line 1148 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP653REN08wGIFl6vu:-KoP9v_x0M91gOj5J-Jm:bg447fq) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/factory_utils.js#L1148)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

weird/possibly not there nit; is this e1 in the documentation and el in the param/everywhere else? Or is the font just silly
</blockquote></details>

Good catch--just the documentation had e1. Renamed param to `element` for clarity.

---

*[src/factory_utils.js, line 1163 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP5jDNQs46co7Mwoqb:-KoPA9f9T2ZBMG9jjjGo:bg49q8k) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/factory_utils.js#L1163)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

replace `WorkspaceFactoryView.prototype` with `FactoryUtils`.
</blockquote></details>

Oops.. done.

---

*[src/view/toolbox_editor_view.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/84#-KoP707SJHlGRAlk2cj2:-KoPABHhlt5meE2I4p-m:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/75b2cfc1cb11284cdeb6e6e502c7f22b20dd0359/src/view/toolbox_editor_view.js#L94)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This and the following methods sound like controller (or even model) methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84#-:-KoPEtj2bl0x_1d4t9BI:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 5 files at r2.
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84#-:-KoPFQpmckbfW7zpr22h:bnfp4nl)*

**Comment by svouse** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/84#-:-KoPFZSKSP7VutdVc_ne:bnfp4nl)*

**Pull request merged**
