### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by svouse**
beginning of the refactor (empty files and classes added; will be filled in future refactor pull requests).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/48)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/library.js, line 33 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHahQxw25X7NdNiLoD:-KnHahQxw25X7NdNiLoE:b-6lr8hy) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/library.js#L33)):*
> ```JavaScript
> 
>   //TODO: Add functions.
> }
> ```

Nit: Newline

---

*[src/model/toolbox.js, line 37 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcUERwJmHNzpEgD1t:-KnHcUERwJmHNzpEgD1u:b-pixmbk) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L37)):*
> ```JavaScript
>    * @param {string} newName New name of toolbox.
>    */
>   setName(newName) {
> ```

Is this true of all project resource types? Do we need a base class?

---

*[src/model/toolbox.js, line 42 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcIOAS2oGzrpRKTjl:-KnHcIOAS2oGzrpRKTjm:byapicr) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L42)):*
> ```JavaScript
>   /**
>    * Adds block to toolbox.
>    * @returns {boolean} True if added succesfully.
> ```

When would this fail?

---

*[src/model/toolbox.js, line 59 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcCvCHC76Rr587c44:-KnHcCvCHC76Rr587c45:b-bn4qj0) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L59)):*
> ```JavaScript
>    * Exports toolbox as JS file.
>    */
>   exportJs() {
> ```

Does this require a file name?  Does it return a success/failure signal? Does it return a promise or use a callback to prevent blocking the UI?

---

*[src/model/toolbox.js, line 66 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHbvkodOL0uO4NM2Fc:-KnHbvkodOL0uO4NM2Fd:b-bn4qj0) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L66)):*
> ```JavaScript
>    * Exports toolbox as XML file.
>    */
>   exportXml() {
> ```

Does this require a file name?  Does it return a success/failure signal? Does it return a promise or use a callback to prevent blocking the UI?

---

*[src/model/toolbox.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHbgxn8eewc8ofIj6s:-KnHbgxn8eewc8ofIj6t:bwuwdfb) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L73)):*
> ```JavaScript
>    *
>    */
>   moveCategory() {
> ```

If you don't know what the function will do or need as parameters, its probably best to leave it out for now. Or leave it as a TODO comment.

---

*[src/model/toolbox.js, line 82 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHb_Wu4T-Mv3Ds-lMH:-KnHb_Wu4T-Mv3Ds-lMI:bdya067) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L82)):*
> ```JavaScript
>    * @param {string} categoryName Name of category.
>    */
>   categoryIsInToolbox() {
> ```

Add param to the function declaration.

---

*[src/model/toolbox.js, line 91 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHb8zLUziSAgaukdi-:-KnHb8zLUziSAgaukdi0:b-s8w4uw) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L91)):*
> ```JavaScript
>    * @param {string} blockName Name of block.
>    */
>   blockIsInToolbox() {
> ```

I'm not sure this method is useful. A toolbox can contain multiple instances of a block with the same type, or even (theoretically, but not recommended) the same block id.

---

*[src/model/toolbox.js, line 96 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHaxo9yfI07x5XrrCU:-KnHaxo9yfI07x5XrrCV:bexk4pj) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L96)):*
> ```JavaScript
> 
>   /**
>    * Returns true if all blocks within this toolbox is empty.
> ```

"Returns true if this toolbox does not contain any blocks in any category."

---

*[src/model/workspace.js, line 22 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcljWLWTZi01Qots7:-KnHcljWLWTZi01Qots8:b-ij9mh2) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/workspace.js#L22)):*
> ```JavaScript
> 
> /**
>  * @fileoverview Workspace object. Contains references to controller and view.
> ```

The controller and view are not the important parts here.
"Contains a set of positioned blocks, often used to initialize a app's blank workspace."

---

*[src/model/workspace.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcbUlNemzHIJJuQY9:-KnHcbUlNemzHIJJuQYA:bbzpgfb) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/workspace.js#L32)):*
> ```JavaScript
>   }
> 
>   //TODO: Add functions.
> ```

This is a perfect way to defer decisions until you know more.

---

*[src/model/workspace.js, line 33 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcjHGYYqt3unVASAZ:-KnHcjHGYYqt3unVASA_:b-y4uj6u) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/workspace.js#L33)):*
> ```JavaScript
> 
>   //TODO: Add functions.
> }
> ```

Nit: newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by chynu** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/toolbox.js, line 37 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcUERwJmHNzpEgD1t:-KnHdfhaTnN99FWOPS7W:b-dj66aa) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L37)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Is this true of all project resource types? Do we need a base class?
</blockquote></details>

Do you mean a class from which Toolbox, Workspace, and Library would extend? That is a good idea.

---

*[src/model/toolbox.js, line 42 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcIOAS2oGzrpRKTjl:-KnHdoDtl1lTuj_YPuwF:b-gtdbu3) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L42)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

When would this fail?
</blockquote></details>

I was thinking it would fail when the name is already taken/ is an invalid toolbox name. Or would this kind of decision be made at the controller level?

---

*[src/model/toolbox.js, line 59 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcCvCHC76Rr587c44:-KnHgBdYoBHN4ocVMHaH:b-ia0w90) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L59)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Does this require a file name?  Does it return a success/failure signal? Does it return a promise or use a callback to prevent blocking the UI?
</blockquote></details>

I believe we are planning on doing popups and file naming in the controller part, and that exportJs() here would deal with just generating the string for the JS file. The JSdoc comment wasn't very clear; I've updated it now.

---

*[src/model/toolbox.js, line 66 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHbvkodOL0uO4NM2Fc:-KnHgOhnxaKhKgXwlgOg:bt5e9t5) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L66)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Does this require a file name?  Does it return a success/failure signal? Does it return a promise or use a callback to prevent blocking the UI?
</blockquote></details>

Updated JSdoc.

---

*[src/model/toolbox.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHbgxn8eewc8ofIj6s:-KnHect6BIFF6nwKEY_y:bsta957) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L73)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

If you don't know what the function will do or need as parameters, its probably best to leave it out for now. Or leave it as a TODO comment.
</blockquote></details>

Noted. I deleted it for now since I don't think we will need it for the refactor.

---

*[src/model/toolbox.js, line 82 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHb_Wu4T-Mv3Ds-lMH:-KnHfN1rQSkjxjvpasOI:b-896fja) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L82)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Add param to the function declaration.
</blockquote></details>

Done!

---

*[src/model/toolbox.js, line 91 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHb8zLUziSAgaukdi-:-KnHey0RWzw077tsYL6V:bdckxmt) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L91)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm not sure this method is useful. A toolbox can contain multiple instances of a block with the same type, or even (theoretically, but not recommended) the same block id.
</blockquote></details>

Hm.. yes, that is true. I removed the method.

---

*[src/model/toolbox.js, line 96 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHaxo9yfI07x5XrrCU:-KnHfLp8DUfHhu4pM2iy:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L96)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

"Returns true if this toolbox does not contain any blocks in any category."
</blockquote></details>

Done.

---

*[src/model/workspace.js, line 22 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcljWLWTZi01Qots7:-KnHfKxBm1td_rPvfVGq:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/workspace.js#L22)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The controller and view are not the important parts here.
"Contains a set of positioned blocks, often used to initialize a app's blank workspace."

</blockquote></details>

Done.

---

*[src/model/workspace.js, line 33 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcjHGYYqt3unVASAZ:-KnHfJ5BUBaSzWC6jj3J:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/workspace.js#L33)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by rachel-fenichel** [comment]
Reviewed 7 of 8 files at r2, 1 of 4 files at r3, 4 of 5 files at r4.
Review status: 9 of 10 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/model/block_group.js, line 27 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLC9-SHv7nzIF4AO3s:-KnLC9-TNe5MQaBfl3ta:b-av7psn) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/block_group.js#L27)):*
> ```JavaScript
>  */
> 
> class BlockGroup {
> ```

FYI You may end up giving this a different name in the future.  A "Block Group" in Blockly usually refers to a group of connected blocks (that are snapped together).

---

*[src/model/block_group.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLDGWTJh7enirs58tb:-KnLDGWTJh7enirs58tc:b-mjyodf) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/block_group.js#L28)):*
> ```JavaScript
> 
> class BlockGroup {
> 	constructor() {
> ```

Spaces, not tabs.

---

*[src/model/workspace.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLDhvE_RL-gtJT2CrA:-KnLDhvE_RL-gtJT2CrB:b-ut20it) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/workspace.js#L28)):*
> ```JavaScript
>  */
> 
> class Workspace extends BlockGroup {
> ```

I'm very concerned about calling this a Workspace.  That is already almost an overloaded term in Blockly.  You're going to have Blockly Workspaces and this type of Workspace, and it's going to be confusing.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by AnmAtAnm** [comment]
Reviewed 3 of 7 files at r5.
Review status: 7 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/block_collection.js, line 23 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLXo9au-j3GY2LMfAw:-KnLXo9au-j3GY2LMfAx:b-1rcw3r) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/block_collection.js#L23)):*
> ```JavaScript
> /**
>  * @fileoverview The BlockCollection class is a collection of blocks. It is the
>  *    parent class for all potential groupings of blocks in Blockly DevTools.
> ```

I recommend something more abstract.  Just "ProjectArtifact" or "Resource", a base class that manages the filename mappings, export locations, load/save methods, and the dirty/unsaved changes flag.

---

*[src/model/library.js, line 27 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLWjwiz7qE5NMoeAky:-KnLWjwiz7qE5NMoeAkz:b-6xdpbq) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/library.js#L27)):*
> ```JavaScript
>  */
> 
> class Library extends BlockCollection {
> ```

Rename BlockLibrary.

I'm also not sure that Workspaces and Toolboxes have much to share, given the category structure of toolboxes. But that can be determined later.

---

*[src/model/toolbox.js, line 42 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcIOAS2oGzrpRKTjl:-KnLYRVj6ok4P84hKtUm:b-a1uofe) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L42)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I was thinking it would fail when the name is already taken/ is an invalid toolbox name. Or would this kind of decision be made at the controller level?
</blockquote></details>

Cool. Please add that to the @return doc.

---

*[src/model/toolbox.js, line 59 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnHcCvCHC76Rr587c44:-KnLYb7fa0zh_lkW2zEZ:b-uw5yw5) ([raw file](https://github.com/google/blockly-devtools/blob/f99779b1358539a533dd486b61b0f3c710d26fcf/src/model/toolbox.js#L59)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I believe we are planning on doing popups and file naming in the controller part, and that exportJs() here would deal with just generating the string for the JS file. The JSdoc comment wasn't very clear; I've updated it now.
</blockquote></details>

OKay. then rename this `buildJavaScriptString()` or similar.

---

*[src/model/toolbox.js, line 78 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLYlpYpXpZUPfjrH2D:-KnLYlpYpXpZUPfjrH2E:bvfo23p) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/toolbox.js#L78)):*
> ```JavaScript
>    * @returns {string} String representation of XML file to be exported.
>    */
>   exportXml() {
> ```

Per above comment, this might be `buildXmlString()` (or just buildXml() if it returns a DOM Document or Element).

---

*[src/model/workspace_preload.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLDhvE_RL-gtJT2CrA:-KnLVx7RBggjFjsVJniA:b9k26u2) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/workspace_preload.js#L28)):*
> I'm very concerned about calling this a Workspace.
Alternative suggestion?  WorkspaceBlocks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 7 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/block_collection.js, line 23 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLXo9au-j3GY2LMfAw:-KnL_sUUT2jE028nrp5p:b-khgs2j) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/block_collection.js#L23)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I recommend something more abstract.  Just "ProjectArtifact" or "Resource", a base class that manages the filename mappings, export locations, load/save methods, and the dirty/unsaved changes flag.
</blockquote></details>

I'm confused by this comment.  It looks like you're talking about a different class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by svouse** [comment]
Review status: 7 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/block_collection.js, line 27 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLC9-SHv7nzIF4AO3s:-KnLaavsU6AuQEEKRiEz:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/block_collection.js#L27)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

FYI You may end up giving this a different name in the future.  A "Block Group" in Blockly usually refers to a group of connected blocks (that are snapped together).
</blockquote></details>

Done.

---

*[src/model/block_collection.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLDGWTJh7enirs58tb:-KnLaa5QdO496nuUygi1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/9454817f2f556e19ff76f319395cdcd4cce1f84f/src/model/block_collection.js#L28)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Spaces, not tabs.
</blockquote></details>

Done.

---

*[src/model/block_collection.js, line 23 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLXo9au-j3GY2LMfAw:-KnL_lHL916DF4_T3xmz:bnnlqqc) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/block_collection.js#L23)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I'm confused by this comment.  It looks like you're talking about a different class.
</blockquote></details>

Renamed it to Resource and updated the documentation.

---

*[src/model/library.js, line 27 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/48#-KnLWjwiz7qE5NMoeAky:-KnL_rvk-Zxuuh4weXJ8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/6a7fcaa68ffc7ff6bc868c116dcad8ff62989d90/src/model/library.js#L27)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Rename BlockLibrary.

I'm also not sure that Workspaces and Toolboxes have much to share, given the category structure of toolboxes. But that can be determined later.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by AnmAtAnm** [comment]
Reviewed 3 of 9 files at r5.
Review status: 8 of 10 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/48#-:-KnLdJLsI78ELXbFWsIU:bnfp4nl)*

**Pull request merged**
