### PR TITLE
Workspace & Toolbox Editor: Export (JS/XML)

### PR DESCRIPTION
**Pull request by chynu**
Can now export workspace contents as javascript and xml files.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/152)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/factory_utils.js, line 1340 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqO_I8oLjpQSuSJaTiT:-KqO_I8oLjpQSuSJaTiU:b-7552jz) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1340)):*
> ```JavaScript
>  * @recursive
>  */
> FactoryUtils.addAttributes = function(obj, tabChar) {
> ```

Reason for moving this to FactoryUtils?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by rachel-fenichel** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/factory_utils.js, line 1340 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqO_I8oLjpQSuSJaTiT:-KqOrmdenUdw--g4kbjD:bx7jxoy) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1340)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Reason for moving this to FactoryUtils?
</blockquote></details>

+1, I'm also wondering about that.

---

*[src/factory_utils.js, line 1347 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOrs2XrQTmTryjjwj_:-KqOrs2XrQTmTryjjwja:bjmrnfg) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1347)):*
> ```JavaScript
>   for (var key in obj) {
>     if (key == 'grid' || key == 'zoom') {
>       var temp = tabChar + key + ' : {\n' + addAttributes(obj[key],
> ```

Nit: for clarity and since this is getting a line break anyway, line break right before `addAttributes`.  The style guide generally says to break at higher syntactic levels where possible, and you can fit all of the `addAttributes` call on one line that way.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqOsMzp_9jlwwjLwgYj:b4etjjh) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
> ```JavaScript
>         return;
>       }
>       fileName = prompt('File name for workspace blocks:',
> ```

Same comment as I had in #150 about needing to validate user input.

---

*[src/controller/workspace_controller.js, line 537 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsfgohO4aHXquHp4E:-KqOsfgohO4aHXquHp4F:b-ox2q1d) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L537)):*
> ```JavaScript
> 
>     // XML ASSIGNMENT STRING (not to be executed)
>     const jsFromXml = `
> ```

Is this string the same as the one you used in #150?  If so, it might belong in FactoryUtils.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 541 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOtdg8ba1Ohes1aDWY:-KqOtdg8ba1Ohes1aDWZ:b7v51e6) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L541)):*
> ```JavaScript
> if (!${xmlStorageVariable}) {
>   ${xmlStorageVariable} = {};
> }
> ```

Same comment from #150:

    ${xmlStorageVariable} = ${xmlStorageVariable} || Object.create(null);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 556 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOuzv4vZRqXXnqo7jR:-KqOuzv4vZRqXXnqo7jS:b-972qbg) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L556)):*
> ```JavaScript
>    * @param {!Object} obj Object representing the options selected in the current
>    *     configuration.
>    * @param {string} tabChar The tab character.
> ```

"The string representing a tab"? As `tab`, so it could be a group of spaces.

---

*[src/controller/workspace_controller.js, line 562 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOvFC-5rSxwM8HchSu:-KqOvFC0tfJNooyp95uP:b-t55gex) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L562)):*
> ```JavaScript
>    * @private
>    */
>   addAttributes_(obj, tabChar) {
> ```

The naming confuses me. But I see this is just imported from somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by chynu** [comment]
Review status: 2 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/factory_utils.js, line 1340 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqO_I8oLjpQSuSJaTiT:-KqP7RP2AOx8EMpc6G6U:b-wawyq4) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1340)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

+1, I'm also wondering about that.
</blockquote></details>

Ah, I forgot to remove this. This is a duplicate function -- the real one is in `WorkspaceController` (renamed to `stringifyOptions_()`.

---

*[src/factory_utils.js, line 1347 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOrs2XrQTmTryjjwj_:-KqP7czJFXeZI7E8RYgB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1347)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Nit: for clarity and since this is getting a line break anyway, line break right before `addAttributes`.  The style guide generally says to break at higher syntactic levels where possible, and you can fit all of the `addAttributes` call on one line that way.
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqP7j99gs-w-6GvgOm-:bxu114l) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Same comment as I had in #150 about needing to validate user input.
</blockquote></details>

(Removed the prompt for same reason as #150)

---

*[src/controller/workspace_controller.js, line 537 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsfgohO4aHXquHp4E:-KqPBjXLNwc6pk6S1NIM:b-pkzskx) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L537)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Is this string the same as the one you used in #150?  If so, it might belong in FactoryUtils.
</blockquote></details>

Moved to a FactoryUtils function.

---

*[src/controller/workspace_controller.js, line 541 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOtdg8ba1Ohes1aDWY:-KqPBlP5DxACZrft39Rs:bd8kqmz) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L541)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Same comment from #150:

    ${xmlStorageVariable} = ${xmlStorageVariable} || Object.create(null);
</blockquote></details>

Done (in the FactoryUtils function).

---

*[src/controller/workspace_controller.js, line 556 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOuzv4vZRqXXnqo7jR:-KqPBnYJh0r9i2SbhNTC:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L556)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

"The string representing a tab"? As `tab`, so it could be a group of spaces.
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 562 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOvFC-5rSxwM8HchSu:-KqPBoItdUjDFRcZE4CY:bdsdlv3) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L562)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The naming confuses me. But I see this is just imported from somewhere else.
</blockquote></details>

True--I renamed it to `stringifyOptions_()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by rachel-fenichel** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqPEXUuPL33BpwSbMXF:b-ohelsv) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

(Removed the prompt for same reason as #150)
</blockquote></details>

Acknowledged, but you should make an issue that covers validation of names that people give to their resources.

For instance, windows isn't case-sensitive.  Should you check for that?  What about names containing slashes and backslashes?  You have to check these things somewhere.

---

*[src/controller/workspace_controller.js, line 537 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsfgohO4aHXquHp4E:-KqPFED5LdOvT97-hHDS:bl0k2q5) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L537)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Moved to a FactoryUtils function.
</blockquote></details>

It's still here.  You might be missing a commit.

---

*[src/view/workspace_editor_view.js, line 149 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqPEyTQ8pUmWmXHsE0e:-KqPEyTQ8pUmWmXHsE0f:b-4j3tit) ([raw file](https://github.com/google/blockly-devtools/blob/7e7b0b9bd4f5b6c0e553872f4321ad118ff0f039/src/view/workspace_editor_view.js#L149)):*
> ```JavaScript
>    */
>   init(controller) {
>     console.log('init() called');
> ```

Remove these logs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1348 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqPDBg3rC4kFuayn4lI:-KqPDBg3rC4kFuayn4lJ:b-gd9k5y) ([raw file](https://github.com/google/blockly-devtools/blob/7e7b0b9bd4f5b6c0e553872f4321ad118ff0f039/src/factory_utils.js#L1348)):*
> ```JavaScript
>   // XML ASSIGNMENT STRING (not to be executed)
>   const jsFromXml = `
> // If ${xmlStorageVariable} does not exist.
> ```

Nit: Remove comment that largely describe exactly what idiomatic code does.

---

*[src/controller/workspace_controller.js, line 537 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsfgohO4aHXquHp4E:-KqPDq1R_5C47OFALyNy:b-4j8k4c) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L537)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Moved to a FactoryUtils function.
</blockquote></details>

I'm not seeing this.  Do you mean in the other PR or in the future?

---

*[src/controller/workspace_controller.js, line 556 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOuzv4vZRqXXnqo7jR:-KqPEXbR14sfylLtiv5s:btnbtpy) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L556)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Per offline, the parameter should be named `indent`.  This is a single indent, but rather the accumulation of all indents prior to this function call (where each indent is a `'\t'`)

---

*[src/controller/workspace_controller.js, line 520 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqPGAMQ1UswbvK0idMI:-KqPGAMQ1UswbvK0idMJ:bqbx8na) ([raw file](https://github.com/google/blockly-devtools/blob/7e7b0b9bd4f5b6c0e553872f4321ad118ff0f039/src/controller/workspace_controller.js#L520)):*
> ```JavaScript
>    * @returns {string} String representation of JS file to be exported.
>    */
>   generateWorkspaceContentsFile(workspaceContents) {
> ```

Remove old version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by chynu** [comment]
PR responses pre-merge.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1348 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqPDBg3rC4kFuayn4lI:-KqPJ2ZsS9ONtFeBZxVu:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7e7b0b9bd4f5b6c0e553872f4321ad118ff0f039/src/factory_utils.js#L1348)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: Remove comment that largely describe exactly what idiomatic code does.
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqPJ5wjv00vQpb7T2l8:b-axck65) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Acknowledged, but you should make an issue that covers validation of names that people give to their resources.

For instance, windows isn't case-sensitive.  Should you check for that?  What about names containing slashes and backslashes?  You have to check these things somewhere.
</blockquote></details>

I made an issue #156 for this, and created an empty function for this in #150.

---

*[src/controller/workspace_controller.js, line 537 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsfgohO4aHXquHp4E:-KqPJ_wOWGbKYUdAMVin:b-oaguni) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L537)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm not seeing this.  Do you mean in the other PR or in the future?
</blockquote></details>

Oops... removed now.

---

*[src/controller/workspace_controller.js, line 556 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOuzv4vZRqXXnqo7jR:-KqPJwENBVfUikRWG5mB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L556)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Per offline, the parameter should be named `indent`.  This is a single indent, but rather the accumulation of all indents prior to this function call (where each indent is a `'\t'`)
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 149 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqPEyTQ8pUmWmXHsE0e:-KqPK1zUTS-DektKwM8V:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7e7b0b9bd4f5b6c0e553872f4321ad118ff0f039/src/view/workspace_editor_view.js#L149)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove these logs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152#-:-KqPU0p5B4vKXABnlapM:b-gumoux)*

**Comment by chynu** [comment]
Merged code in #150 with this PR, since they both have similar code that deal with similar concepts.

**Comment by rachel-fenichel** [comment]
One more thing, then lgtm.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqPdgr26B63qqlCb46F:biyvt2i) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I made an issue #156 for this, and created an empty function for this in #150.
</blockquote></details>

Now that the function exists, call it here (on the `let fileName = resource.name;` line) as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152#-:-KqPe-iGahf_FkT1moQC:bm0ckbx)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/factory_utils.js, line 1340 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqO_I8oLjpQSuSJaTiT:-KqPbqlJUCodf6ieQm2f:b-7b6jcg) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/factory_utils.js#L1340)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Ah, I forgot to remove this. This is a duplicate function -- the real one is in `WorkspaceController` (renamed to `stringifyOptions_()`.
</blockquote></details>

Note: This is the real one, now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 2 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152#-:-KqPhDzYc1M1Bv2ks37s:bnfp4nl)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 493 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/152#-KqOsMzp_9jlwwjLwgYi:-KqPvuXNN423DsIqkg0w:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59757c96c11d82f8b52c85d40e108c5e57ccdcd4/src/controller/workspace_controller.js#L493)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Now that the function exists, call it here (on the `let fileName = resource.name;` line) as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/152)*

**Pull request merged**
