### PR TITLE
JSUnit Tests

### PR DESCRIPTION
**Pull request by chynu**
- Moved utility functions to `src/factory_utils.js` (pre-existing file).
 - Added JSUnit test folder/files (to run tests, just load `tests.html`)
 - Added tests for adding escape (`FactoryUtils.addEscape()`) and preventing eval of code outside of comments in exported toolboxes (`WorkspaceFactoryGenerator.evaluateMarkedCode()`).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/41)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Reviewed 6 of 9 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/factory_utils.js, line 1009 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5Ue1xwxF9ufIPfO9Y:-Kn5Ue1xwxF9ufIPfO9Z:bmqc4vk) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/src/factory_utils.js#L1009)):*
> ```JavaScript
>  * whitespace between tags.
>  */
> FactoryUtils.splitXmlWithNewline = function(xmlString) {
> ```

Since this function specifically outputs JavaScript strings concatenated, name the function as such.
Also, add a TODO to support multiline XML input, with pretty printing indent preserved.

---

*[src/factory_utils.js, line 1048 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5U3DvQGK-m_CpyOke:-Kn5U3DvQGK-m_CpyOkf:bnxq9gd) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/src/factory_utils.js#L1048)):*
> ```JavaScript
> /**
>  * Adds escapes to special characters so that JavaScript code can be run
>  * correctly upon importing toolboxes or workspaces.
> ```

Either add a parameter to denote which style of quote you are using, or edit the doc comment to specify it is intended for single quoted strings (in which case, also delete the double quote case, below).

---

*[src/factory_utils.js, line 1056 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5VdfXbx2CBuYwQNO2:-Kn5VdfXbx2CBuYwQNO3:b-bwgji2) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/src/factory_utils.js#L1056)):*
> ```JavaScript
>   string = string.replace(/\\/g, '\\\\');
>   // Escape single quote
>   string = string.replace(/\'/g, '\\'+'\'');
> ```

For the life of me, I don't see what changed here.

---

*[tests/wfactory_input_test.js, line 78 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5W0oOBhdPRu3C9MXb:-Kn5W0oOBhdPRu3C9MXc:b-lwg80r) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L78)):*
> ```JavaScript
>  * addEscape() test with random words, large number of tests.
>  */
> function test_addEscapeWithWords_random() {
> ```

I'm not sure this add value to what the prior test does.  Also, random tests aren't reproducible tests, and may be a "flaky" test if a small subset of cases aren't repeatable (sometime succeeds, sometimes fails, given the same build and input).

Since, you have the other test, remove this one.

---

*[tests/wfactory_input_test.js, line 98 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WdbfMZpbT9FesVrj:-Kn5WdbfMZpbT9FesVrk:b-9gw5rx) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L98)):*
> ```JavaScript
>  * addEscape() test with big words.
>  */
> function test_addEscapeWithBigWords() {
> ```

As before, I don't see that this adds value over test_addEscapeWithWords_ordered. And the same note about randomness in tests.

---

*[tests/wfactory_input_test.js, line 117 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WzWSJxo0YhALElL5:-Kn5WzWSJxo0YhALElL6:b-a84zxm) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L117)):*
> ```JavaScript
>   var fail = 'assertTrue(false);\n';
> 
>   generator.evaluateMarkedCode(fail + start + pass + end + fail);
> ```

This doesn't guarantee pass was called.  You'll need to set some state that you can test after the assignment.  Consider the following:

```
test_evaluateMarkedCode_simple.didRunPass = false;
// ...
var pass = 'test_evaluateMarkedCode_simple.didRunPass = true'
// ...
generator.evaluateMarkedCode(..)
assertTrue(test_evaluateMarkedCode_simple.didRunPass)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by AnmAtAnm** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/wfactory_input_test.js, line 98 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WdbfMZpbT9FesVrj:-Kn5ZciIu1fqttp656Br:b-o08289) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L98)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

As before, I don't see that this adds value over test_addEscapeWithWords_ordered. And the same note about randomness in tests.
</blockquote></details>

Erik suggests "supercalifragilisticexpialidocious" and "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by chynu** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/factory_utils.js, line 1009 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5Ue1xwxF9ufIPfO9Y:-Kn5lYQlXcCYtZZ6vVNg:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/src/factory_utils.js#L1009)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Since this function specifically outputs JavaScript strings concatenated, name the function as such.
Also, add a TODO to support multiline XML input, with pretty printing indent preserved.
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 1048 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5U3DvQGK-m_CpyOke:-Kn5kTWI_iSLmRginGVM:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/src/factory_utils.js#L1048)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Either add a parameter to denote which style of quote you are using, or edit the doc comment to specify it is intended for single quoted strings (in which case, also delete the double quote case, below).
</blockquote></details>

Done.

---

*[tests/wfactory_input_test.js, line 78 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5W0oOBhdPRu3C9MXb:-Kn5kWn11s4V8jTnVtIS:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L78)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm not sure this add value to what the prior test does.  Also, random tests aren't reproducible tests, and may be a "flaky" test if a small subset of cases aren't repeatable (sometime succeeds, sometimes fails, given the same build and input).

Since, you have the other test, remove this one.
</blockquote></details>

Done.

---

*[tests/wfactory_input_test.js, line 98 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WdbfMZpbT9FesVrj:-Kn5kXQXYVCoC2TvCkjw:b-4ctsav) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L98)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Erik suggests "supercalifragilisticexpialidocious" and "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch"
</blockquote></details>

Removed this function.

---

*[tests/wfactory_input_test.js, line 117 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WzWSJxo0YhALElL5:-Kn5kcY6nZmedkRGTRK1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L117)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This doesn't guarantee pass was called.  You'll need to set some state that you can test after the assignment.  Consider the following:

```
test_evaluateMarkedCode_simple.didRunPass = false;
// ...
var pass = 'test_evaluateMarkedCode_simple.didRunPass = true'
// ...
generator.evaluateMarkedCode(..)
assertTrue(test_evaluateMarkedCode_simple.didRunPass)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by AnmAtAnm** [comment]
Reviewed 2 of 3 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/wfactory_input_test.js, line 117 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WzWSJxo0YhALElL5:-Kn5zQo_fpclX9NIjpQD:b-n5yqwu) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L117)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`var passedTest = false` inside the function is not the same as `test_evaluateMarkedCode_simple.didRunPass = false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1007 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn60ZzOsA_fQWQCJbMd:-Kn60ZzPOTIrPxivNb4N:b-pjjawp) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1007)):*
> ```JavaScript
>  * @param {string} xmlString XML code to be turned into a JS string.
>  * @returns {string} XML string as string concatenation without unnecessary
>  * whitespace between tags.
> ```

nit: Indent an additional four spaces.

---

*[src/factory_utils.js, line 1025 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn61RzlXOlOcfOfRhQ3:-Kn61RzlXOlOcfOfRhQ4:b-l0vjzq) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1025)):*
> ```JavaScript
>       } else if (cursor === '\n') {
>         totalString += '\'';
>         if (i+1 !== xmlString.length) totalString += ' +\n    ';
> ```

Put the contents of the if on a new line, and add braces.

---

*[src/factory_utils.js, line 1025 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn61_ICPc04kP_btggS:-Kn61_ICPc04kP_btggT:b2r7snr) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1025)):*
> ```JavaScript
>       } else if (cursor === '\n') {
>         totalString += '\'';
>         if (i+1 !== xmlString.length) totalString += ' +\n    ';
> ```

`i+1` should be `i + 1`

---

*[src/factory_utils.js, line 1027 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn63wkH20u7_yOyYz6T:-Kn63wkH20u7_yOyYz6U:b-2q0c5o) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1027)):*
> ```JavaScript
>         if (i+1 !== xmlString.length) totalString += ' +\n    ';
>         newline = true;
>       } else totalString += cursor;
> ```

Newline and braces.

---

*[src/factory_utils.js, line 1037 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn63zQ6_gJe0r6hqSJ9:-Kn63zQ6_gJe0r6hqSJA:bi8aj38) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1037)):*
> ```JavaScript
>         outside = true; // Leave xml tag.
>         // Add escapes to xml tag, add to total string.
>         totalString += FactoryUtils.addEscape(xmlString.substring(start, i+1));
> ```

Spaces in `i+1`

---

*[tests/wfactory_input_test.js, line 28 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn6Cz5OGQUTeP-oyHCC:-Kn6Cz5OGQUTeP-oyHCD:bsd9est) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L28)):*
> ```JavaScript
> 'use strict';
> 
> // JS special characters that need escape sequences
> ```

Put these variables inside a single object to minimize pollution of the global namespace.

(Grab me when you get to this comment and we can chat about what I mean, if it's unclear.)

---

*[tests/wfactory_input_test.js, line 50 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn64RggPpVsMwwRcNsB:-Kn64RggPpVsMwwRcNsC:bunx2r3) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L50)):*
> ```JavaScript
> function test_addEscape_simple() {
>   for (var i = 0; i < specialChars.length; i++) {
>     assertEquals('a$' + charLiteral[i] + 'b@%$@#^',
> ```

What are `a$` and `b@%$@#^` doing?

---

*[tests/wfactory_input_test.js, line 65 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn64YjCTCBW6NJIe_Qh:-Kn64YjCTCBW6NJIe_Qi:b-c3byi6) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L65)):*
> ```JavaScript
>     let charIndex = i;
> 
>     assertEquals(words[wordIndex] + symbols[symbolIndex] + charLiteral[charIndex],
> ```

Make a variable for `words[wordIndex] + symbols[symbolIndex] + charLiteral[charIndex]`, and use it here.  Same for the next two asserts as well.

Since you're asserting in a loop you're not going to know exactly what failed for a given assert.  Add a message telling you what `i` was, and the value of each variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by AnmAtAnm** [comment]
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1007 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn60ZzOsA_fQWQCJbMd:-Kn6EJJhmtNc4e5sl15B:bcbp5kr) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1007)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: Indent an additional four spaces.
</blockquote></details>

Clarification: indent just the wrapper line starting at "whitespace"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by chynu** [comment]
Review status: 5 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1007 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn60ZzOsA_fQWQCJbMd:-Kn6EJvcqW17ms_VZIU1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1007)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: Indent an additional four spaces.
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 1025 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn61RzlXOlOcfOfRhQ3:-Kn6ETWoUWFRvj0-MMg-:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1025)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Put the contents of the if on a new line, and add braces.
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 1025 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn61_ICPc04kP_btggS:-Kn6EdAB0AaXoLKJ_GAm:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1025)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

`i+1` should be `i + 1`
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 1027 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn63wkH20u7_yOyYz6T:-Kn6EghcoLa4DLIVmGbe:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1027)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Newline and braces.
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 1037 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn63zQ6_gJe0r6hqSJ9:-Kn6EqiWFLaskiUiOaOt:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/src/factory_utils.js#L1037)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Spaces in `i+1`
</blockquote></details>

Done.

---

*[tests/wfactory_input_test.js, line 117 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn5WzWSJxo0YhALElL5:-Kn6Me21hC_IkPGl2GGS:b-b8zc9f) ([raw file](https://github.com/google/blockly-devtools/blob/72533432d6ae38d70fc25bb44ac1385ee078fa5d/tests/wfactory_input_test.js#L117)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`var passedTest = false` inside the function is not the same as `test_evaluateMarkedCode_simple.didRunPass = false`.
</blockquote></details>

Changed variable to `test_evaluateMarkedCode.passedTest`.

---

*[tests/wfactory_input_test.js, line 28 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn6Cz5OGQUTeP-oyHCC:-Kn6NTNRe8He2hZEXdpF:b-896fja) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L28)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Put these variables inside a single object to minimize pollution of the global namespace.

(Grab me when you get to this comment and we can chat about what I mean, if it's unclear.)
</blockquote></details>

Done!

---

*[tests/wfactory_input_test.js, line 50 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn64RggPpVsMwwRcNsB:-Kn6FzRC2c_13cvyDsh5:bev2ok9) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L50)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

What are `a$` and `b@%$@#^` doing?
</blockquote></details>

Removed. I put them in to test if the test worked, but they're no longer necessary.

---

*[tests/wfactory_input_test.js, line 65 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/41#-Kn64YjCTCBW6NJIe_Qh:-Kn6MWCl1xnqtSovAS4Q:b2s0cm4) ([raw file](https://github.com/google/blockly-devtools/blob/708d5ab50b1582d198906fe0eda170b8f7488843/tests/wfactory_input_test.js#L65)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Make a variable for `words[wordIndex] + symbols[symbolIndex] + charLiteral[charIndex]`, and use it here.  Same for the next two asserts as well.

Since you're asserting in a loop you're not going to know exactly what failed for a given assert.  Add a message telling you what `i` was, and the value of each variable.
</blockquote></details>

Done. Added a message (for `assertEquals`, the first parameter is the error message, apparently).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41)*

**Comment by AnmAtAnm** [comment]
LGTM.  Please wait for Rachel's review.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41#-:-Kn6R5iRUHlVttp9JmD_:b-b3xgea)*

**Comment by rachel-fenichel** [comment]
LGTM after the fix we discussed.

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/41#-:-Kn6Zg74tCnxuPOw5WDw:b-1bbz5w)*

**Pull request merged**
