### PR TITLE
Workspace Editor: Workspace Config

### PR DESCRIPTION
**Pull request by chynu**
Workspace config portion of workspace editor is now working.

Users will not know about the divide between WorkspaceContents and WorkspaceConfiguration unless they look at the code. UI has been changed so that they are unified under the title "Workspace." This is because they are in the same editor.

Also: tiny UI fixes (removed tabs, since all three editors are now working and can be navigated via the navtree).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/195)

### CODE REVIEW

**Comment by chynu** [comment]
(Not ready for review yet... somehow this branch also has commits from branch `toolbox-lib`. Must have accidentally checked out a new branch from that branch instead of `develop`. :disappointed:)

**Comment by svouse** [comment]
Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/factory_utils.js, line 758 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_1ppU7iV-ZYO-pq8:-Kqx_1ppU7iV-ZYO-pq9:b-xzgd94) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/factory_utils.js#L758)):*
> ```JavaScript
>  * Parses a block definition get the type of the block it defines.
>  * @param {string} blockDef A single block definition.
>  * @return {string} Type of block defined by the given definition.
> ```

@throws

---

*[src/controller/app_controller.js, line 262 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_OUO2lVp14eAHWUV:-Kqx_OUO2lVp14eAHWUW:b40s2px) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/app_controller.js#L262)):*
> ```JavaScript
>   initProject(projectName) {
>     this.project = new Project(projectName);
>     // this.project.addWorkspaceContents(new WorkspaceContents('MyContents'));
> ```

Remove commented-out code

---

*[src/controller/app_controller.js, line 380 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_as47xp1WncN4IHN:-Kqx_as47xp1WncN4IHO:b-9hfxw3) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/app_controller.js#L380)):*
> ```JavaScript
>     if (name) {
>       const workspaceContents =
>         this.projectController.createWorkspaceContents(name);
> ```

indent 4 spaces (currently 2 I think?)

---

*[src/controller/toolbox_controller.js, line 503 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaHJmg4eTJ5ZsDUWU:-KqxaHJmg4eTJ5ZsDUWV:bs3lj5) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/toolbox_controller.js#L503)):*
> ```JavaScript
>    * Updates the editor toolbox to have categories for user-defined block libraries.
>    */
>   updateEditorToolbox() {
> ```

Reason for having the same method in toolbox_controller and workspace_controller?//could this be moved or marked with a TODO to condense in the future?

---

*[src/controller/workspace_controller.js, line 208 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaSGiYUyfg0AVArjt:-KqxaSGiYUyfg0AVArju:b-86eegm) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/workspace_controller.js#L208)):*
> ```JavaScript
> 
>   /**
>    *
> ```

JSDoc

---

*[src/controller/workspace_controller.js, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaU-XY812CyH2N8yo:-KqxaU-XY812CyH2N8yp:b-86eegm) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/workspace_controller.js#L218)):*
> ```JavaScript
> 
>   /**
>    *
> ```

JSDoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195)*

**Comment by chynu** [comment]
Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/app_controller.js, line 262 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_OUO2lVp14eAHWUV:-Kqy0MubmXgu4im9mjOw:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/app_controller.js#L262)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Remove commented-out code
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 380 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_as47xp1WncN4IHN:-Kqy0RDhqHc3AmwCtz0L:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/app_controller.js#L380)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

indent 4 spaces (currently 2 I think?)
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 208 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaSGiYUyfg0AVArjt:-Kqy0xOAF-pvch0jusVc:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/workspace_controller.js#L208)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaU-XY812CyH2N8yo:-Kqy0xdbI8DsoFPN2AGv:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/workspace_controller.js#L218)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/factory_utils.js, line 758 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-Kqx_1ppU7iV-ZYO-pq8:-Kqy1VsUdcdLB9YMmnH8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/factory_utils.js#L758)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

@throws
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 503 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaHJmg4eTJ5ZsDUWU:-Kqy1swrJdJ4M-FIEZbZ:b9a8iet) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/toolbox_controller.js#L503)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Reason for having the same method in toolbox_controller and workspace_controller?//could this be moved or marked with a TODO to condense in the future?
</blockquote></details>

I think Rachel and I had this discussion earlier and briefly contemplated having it in ShadowController. I'll make an issue (#198) for it, though, since there are a lot of similarities between the toolbox and workspace editors that don't strictly have to do with shadow blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195)*

**Comment by svouse** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 503 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqxaHJmg4eTJ5ZsDUWU:-KqyFfJAbklOOpiEQsVo:bdeavht) ([raw file](https://github.com/google/blockly-devtools/blob/1b9bd74ab700e3052005d8a60f9fd5fafae5ec79/src/controller/toolbox_controller.js#L503)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think Rachel and I had this discussion earlier and briefly contemplated having it in ShadowController. I'll make an issue (#198) for it, though, since there are a lot of similarities between the toolbox and workspace editors that don't strictly have to do with shadow blocks.
</blockquote></details>

:fire: 

---

*[src/model/workspace_contents.js, line 53 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGc3kYlfyzVKKaEY-:-KqyGc3lXiFyfANvHPtx:bwdbefg) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/model/workspace_contents.js#L53)):*
> ```JavaScript
>     this.shadowBlocks = [];
> 
>     this.config = new WorkspaceConfiguration(this.name);
> ```

Not an issue with this PR, but could you make an issue to condense the config and contents? (I don't think it's a priority given demo timeline, but should be on record)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195)*

**Comment by rachel-fenichel** [comment]
one nit, but then lgtm

---

Reviewed 5 of 19 files at r1, 8 of 12 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 210 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyHhMwAfuM5Hlg5HBe:-KqyHhMwAfuM5Hlg5HBf:b-brrkcl) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/controller/workspace_controller.js#L210)):*
> ```JavaScript
>   /**
>    * Loads WorkspaceContents onto editor workspace.
>    * @param {!WorkspaceContents} wsContents WorkspaceContents to load.\
> ```

Nit: delete the slash at the end of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195#-:-KqyIFhEU4A-fW45i-JI:b-rmlj7a)*

**Comment by AnmAtAnm** [comment]
Minor nits, then :lgtm: 

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[app.html, line 21 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGP8DdyqocnAZtQoQ:-KqyGP8DdyqocnAZtQoR:bprb33c) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/app.html#L21)):*
> ```HTML
> <body>
>   <div>
>     <h1 id="devTools">Blockly Developer Tools</h1>
> ```

The window chrome should already have a title.  We shouldn't need this. Or, for that matter, the help button which can be found in the menus.

---

*[src/factory_utils.js, line 762 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGq0N3rgzT8ZJv12D:-KqyGq0N3rgzT8ZJv12E:bo46efs) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/factory_utils.js#L762)):*
> ```JavaScript
>  */
> FactoryUtils.getBlockTypeFromJsDefinition = function(blockDef) {
>   var indexOfStartBracket = blockDef.indexOf('[\'');
> ```

I suggest looking for "Blockly.Blocks[" and "] =" on the same line, for more certainty you are extracting the right thing.  Also, the quotes in the JavaScript might possibly be double quotes.

Feel free to put this in a follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195#-:-KqyIllqX_ZZOYa08edZ:buitv5b)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[app.html, line 21 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGP8DdyqocnAZtQoQ:-KqyfzOJE1l0YDe1gvY8:bj4828) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/app.html#L21)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The window chrome should already have a title.  We shouldn't need this. Or, for that matter, the help button which can be found in the menus.
</blockquote></details>

Done (removed title and help button and also modified the title of the window to just say "Blockly Developer Tools" intsead of "Blockly Demo: Blockly Developer Tools").

---

*[src/factory_utils.js, line 762 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGq0N3rgzT8ZJv12D:-KqyifxOVHBikRV98ri2:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/factory_utils.js#L762)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I suggest looking for "Blockly.Blocks[" and "] =" on the same line, for more certainty you are extracting the right thing.  Also, the quotes in the JavaScript might possibly be double quotes.

Feel free to put this in a follow-up PR.
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 210 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyHhMwAfuM5Hlg5HBe:-KqyfVAWMki2qJFYAxcS:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/controller/workspace_controller.js#L210)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Nit: delete the slash at the end of this.
</blockquote></details>

Done.

---

*[src/model/workspace_contents.js, line 53 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/195#-KqyGc3kYlfyzVKKaEY-:-KqyfZxBZNG_fdMlwwxt:b-n199m7) ([raw file](https://github.com/google/blockly-devtools/blob/08ab24f0d7f4c105a40adaf2975dce181dab4914/src/model/workspace_contents.js#L53)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Not an issue with this PR, but could you make an issue to condense the config and contents? (I don't think it's a priority given demo timeline, but should be on record)
</blockquote></details>

Made issue #201.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/195)*

**Pull request merged**
