### PR TITLE
Block Editor: User Flow / Popups

### PR DESCRIPTION
**Pull request by chynu**
Part 1 of 2 to finalize block editor user flow. Created popup for new project, but is not currently active in DevTools (i.e. it does not pop up on load). (Can be triggered by clicking "new project" under menu bar.)

Can:
 - Create a new library
 - Create a new block

Cannot:
 - Switch between blocks by clicking in navtree.

Next PR:
 - Tackling more bugs in creating a block/library, switching between blocks, and changing options within the block editor (e.g. JSON vs. JS block definitions, etc.).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/162)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Minor cleanup, then LGTM

---

Reviewed 10 of 22 files at r1.
Review status: 8 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 75 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5ASCK4Nd9G24Jb6C:-KqZ5ASCK4Nd9G24Jb6D:b-rzsiut) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L75)):*
> ```JavaScript
>     this.hiddenWorkspace = hiddenWorkspace;
> 
>     // this.refreshPreviews();
> ```

Either remove, or add a TODO with explaination

---

*[src/controller/block_editor_controller.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5IKrQVCWNxMskk2M:-KqZ5IKrQVCWNxMskk2N:brhumzt) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L122)):*
> ```JavaScript
>   refreshPreviews() {
>     const format = $('#format').val();
>     // Blockly.Xml.domToWorkspace(this.view.blockDefinition.getXml(), this.view.editorWorkspace);
> ```

Same here.

---

*[src/controller/block_editor_controller.js, line 152 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5JH2ypKz5ojsX09_:-KqZ5JH2ypKz5ojsX09a:b-1kzc9c) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L152)):*
> ```JavaScript
>     this.projectController.rename(
>         currentBlock, rootBlock.getFieldValue('NAME'));
>     // currentBlock.setXml(Blockly.Xml.blockToDom(rootBlock));
> ```

And here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162#-:-KqZ5RbRWfOZh27-oSP1:b-x7lpap)*

**Comment by AnmAtAnm** [comment]
Reviewed 12 of 22 files at r1.
Review status: 17 of 22 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162)*

**Comment by chynu** [comment]
Review status: 17 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 75 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5ASCK4Nd9G24Jb6C:-KqZDavXjXXc_HyvHi7z:bss4a2b) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L75)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Either remove, or add a TODO with explaination
</blockquote></details>

Removed.

---

*[src/controller/block_editor_controller.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5IKrQVCWNxMskk2M:-KqZDhnRgCSdfgtBQNLl:bss4a2b) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L122)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Removed.

---

*[src/controller/block_editor_controller.js, line 152 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ5JH2ypKz5ojsX09_:-KqZDnr-WvqucM3UJUcR:bss4a2b) ([raw file](https://github.com/google/blockly-devtools/blob/f74a8617e58339a18859ac79c201c57e41955a18/src/controller/block_editor_controller.js#L152)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162)*

**Comment by rachel-fenichel** [comment]
Reviewed 16 of 22 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/factory_utils.js, line 1404 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZKDiQnKFEdnMtJyj:-KqZZKDiQnKFEdnMtJyk:b-vc6azo) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/factory_utils.js#L1404)):*
> ```JavaScript
>  */
> FactoryUtils.cleanResourceName = function(resourceName) {
>   // TODO: Clean names of resources (given by users) to minimize errors.
> ```

TODO number is missing.

---

*[src/controller/app_controller.js, line 175 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZRVsxsV6iRa9R4wS:-KqZZRVsxsV6iRa9R4wT:b-4s781g) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L175)):*
> ```JavaScript
>     this.initProject('MyProject');
>     // Creates popup.
>     // this.createPopup(PopupController.NEW_BLOCK);
> ```

Commented-out code?

---

*[src/controller/app_controller.js, line 342 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZZ7h4oJKRDSNPHd8:-KqZZZ7h4oJKRDSNPHd9:b-3u4at3) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L342)):*
> ```JavaScript
>     }
>     // Create popup.
>     if (popupMode === PopupController.NEW_BLOCK) {
> ```

It looks like you'll call `this.popupController.show();` regardless of the type of your popup.  If so you can do it after the if/else, instead of in every branch.

---

*[src/controller/app_controller.js, line 380 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZhUILAIDoR7dBA-I:-KqZZhUILAIDoR7dBA-J:bmeb199) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L380)):*
> ```JavaScript
>    */
>   createBlockDefinition() {
>     // this.switchEnvironment('block', null);
> ```

Delete commented out code.

---

*[src/view/app_view.js, line 139 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ_t9rEXlFTcHrXTrb:-KqZ_t9rEXlFTcHrXTrc:bouxsom) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/app_view.js#L139)):*
> ```JavaScript
> 
>     // Show the current view.
>     // this.currentView.show(this.currentView.blockDefinition.type());
> ```

Remove commented out code.

---

*[src/view/app_view.js, line 168 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ_qpg59wcq-mu4Xqs:-KqZ_qpg59wcq-mu4Xqt:bbjhum) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/app_view.js#L168)):*
> ```JavaScript
>    */
>   showNewProject() {
>     // TODO: Fill in action.
> ```

Unnecessary TODO?  Here and below.

---

*[src/view/block_editor_view.js, line 125 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZa1LR9rOxlFepknQJ:-KqZa1LR9rOxlFepknQK:bmejjng) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/block_editor_view.js#L125)):*
> ```JavaScript
>     Blockly.svgResize(this.previewWorkspace);
> 
>     // TODO: Make editor show the @param block (when user clicks
> ```

TODO is done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/factory_utils.js, line 1404 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZKDiQnKFEdnMtJyj:-KqZemVt9eCpf1V1v2-C:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/factory_utils.js#L1404)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

TODO number is missing.
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 175 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZRVsxsV6iRa9R4wS:-KqZewDyYqfPC_Lvl2fE:bjwge1l) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L175)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Commented-out code?
</blockquote></details>

Removed. If we ever decide to make the popup show up on load, we can always add it in again.

---

*[src/controller/app_controller.js, line 342 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZZ7h4oJKRDSNPHd8:-KqZgemQyIf1FsG9Eiww:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L342)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

It looks like you'll call `this.popupController.show();` regardless of the type of your popup.  If so you can do it after the if/else, instead of in every branch.
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 380 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZZhUILAIDoR7dBA-I:-KqZgwqn75ZsEd-U46mS:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/b83045efefc1f707c69af03c59b5aa7d0906946b/src/controller/app_controller.js#L380)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Delete commented out code.
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 139 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ_t9rEXlFTcHrXTrb:-KqZh515NW2McNLR5yxH:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/app_view.js#L139)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove commented out code.
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 168 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZ_qpg59wcq-mu4Xqs:-KqZh6Q-5l26QieTQpcg:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/app_view.js#L168)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Unnecessary TODO?  Here and below.
</blockquote></details>

Done.

---

*[src/view/block_editor_view.js, line 125 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/162#-KqZa1LR9rOxlFepknQJ:-KqZhJP8lRiZioPaALse:b4rhjsh) ([raw file](https://github.com/google/blockly-devtools/blob/0fbe05361273c95a8bdce655f5bcb1fdfc5a8c4b/src/view/block_editor_view.js#L125)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

TODO is done?
</blockquote></details>

Not yet -- switching views via navtree isn't implemented yet, I believe. Switching via tabs is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162)*

**Comment by AnmAtAnm** [comment]
Still :lgtm: 

---

Review status: 18 of 22 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162#-:-Kq_DzXH1eftYqzvQ3-1:b-dbkjmx)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/162#-:-Kq_F-K0JMOWMkraK4_G:bnfp4nl)*

**Pull request merged**
