### PR TITLE
Switching Tabs

### PR DESCRIPTION
**Pull request by chynu**
Can now switch between the three tabs. Displays proper static views (but will break if you click around). Editing functionality not yet in tact (in upcoming PR).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/120)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/editor_controller.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSMUYyWBugZL8OnRsU:-KpSMUYz33SaLVKpnhIC:b43ouly) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/controller/editor_controller.js#L88)):*
> ```JavaScript
>   /**
>    * Switches editors (both view and controllers).
>    * @param {string} editorMode String which represents which editor to switch to.
> ```

If you're expected to know which editor you want, anyway, why not just pass the editor view itself?

---

*[src/view/app_view.js, line 377 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSMlfiPVfPG9z6ywqB:-KpSMlfiPVfPG9z6ywqC:b3fy74t) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/app_view.js#L377)):*
> ```JavaScript
>   /**
>    * Switches editor views in application.
>    * @param {string} editorName Name of editor to switch to.
> ```

Same as above.
But also, wouldn't you only need a resource to determine type? Rather than giving the editor name

---

*[src/view/block_editor_view.js, line 110 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSN9442nreG_DQpBhl:-KpSN9442nreG_DQpBhm:bs2lder) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/block_editor_view.js#L110)):*
> ```JavaScript
> 
>   /**
>    * Removes elements of this editor view from application view. Used when switching
> ```

'Removes elements' feels mildly vague

---

*[src/view/toolbox_editor_view.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSNLagOdY1G1ZuCL4h:-KpSNLagOdY1G1ZuCL4i:b-ya81ng) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/toolbox_editor_view.js#L103)):*
> ```JavaScript
> 
>   /**
>    * Removes elements of this editor view from application view. Used when switching
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120)*

**Comment by chynu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/editor_controller.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSMUYyWBugZL8OnRsU:-KpSOhL2AwEfyQdCpnVe:b-6y5u32) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/controller/editor_controller.js#L88)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

If you're expected to know which editor you want, anyway, why not just pass the editor view itself?
</blockquote></details>

I did a bit of a hack where the string is the same as the tab 
(edit: oh oops i didn't finish writing this comment and I don't remember where I was going ;__;)

---

*[src/view/app_view.js, line 377 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSMlfiPVfPG9z6ywqB:-KpSS9QZ65-RXnQWblHz:bfv97qv) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/app_view.js#L377)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same as above.
But also, wouldn't you only need a resource to determine type? Rather than giving the editor name
</blockquote></details>

True. I changed `switchView()` and `switchEditor()` to pass in the view and editor objects as parameters, respectively. The editorView is necessary as a parameter for `switchView()` because in the future, we'll be using the navtree as navigation between views and the navtree provides only the name of the resource object (and not the Resource object itself).

...Though I guess we could use the prefixes to infer editor type, I think passing in the editor is more explicit.

---

*[src/view/block_editor_view.js, line 110 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSN9442nreG_DQpBhl:-KpSOyvvPU_59MBxF3qX:b-f809re) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/block_editor_view.js#L110)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

'Removes elements' feels mildly vague
</blockquote></details>

Changed to 'Removes contents'?

---

*[src/view/toolbox_editor_view.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSNLagOdY1G1ZuCL4h:-KpSP0wD0_IFuCtwsUEn:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/4470c93ff35bb57ed5c64bc17a253213028d5fc7/src/view/toolbox_editor_view.js#L103)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/block_editor_view.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpS_APZ9s3IAPo81Tu3:-KpS_APZ9s3IAPo81Tu4:b-wii4iu) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/block_editor_view.js#L73)):*
> ```JavaScript
> 
>     // Disable delete button by default.
>     this.deleteButton.disabled = true;
> ```

In the new model, can we get to the view without the block having been saved (i.e., not deletable)?

---

*[src/view/block_editor_view.js, line 126 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpS_dlxXClu4svpAVl0:-KpS_dlxXClu4svpAVl1:b-wh6gev) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/block_editor_view.js#L126)):*
> ```JavaScript
>    * @param {string} blockName Name of block to populate into block editor view.
>    */
>   show(blockName) {
> ```

Pass in the whole BlockDefinition model object. You'll eventually need it to populate the UI.

---

*[src/view/toolbox_editor_view.js, line 120 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSa2K4QHdhzfEMfDu5:-KpSa2K4QHdhzfEMfDu6:b24jvc0) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/toolbox_editor_view.js#L120)):*
> ```JavaScript
>    *     shown.
>    */
>   show(toolboxName) {
> ```

Similarly, pass in the whole Toolbox model object.

---

*[src/view/workspace_editor_view.js, line 118 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSaAIvW5u1zkvQ_u9c:-KpSaAIvW5u1zkvQ_u9d:bdyif91) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/workspace_editor_view.js#L118)):*
> ```JavaScript
>    *     workspace editor view when shown.
>    */
>   show(wsContentsName) {
> ```

Again, pass in the model object.  I think you'll need both the contents and the config, or some container class for both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120#-:-KpSbXHqaFZAc_SRHMKy:bnfp4nl)*

**Comment by chynu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/block_editor_view.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpS_APZ9s3IAPo81Tu3:-KpSd5OR3FJMA4jom4g7:b3f03b6) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/block_editor_view.js#L73)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

In the new model, can we get to the view without the block having been saved (i.e., not deletable)?
</blockquote></details>

Ohh, true. I removed this line of code. 

Although we will probably get rid of the buttons altogether and have the blocks just auto-save and populate into the navtree whenever the user makes changes. That way, they don't have to manually save a block or other Resource type every time they want to switch an editor. 

---

*[src/view/block_editor_view.js, line 126 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpS_dlxXClu4svpAVl0:-KpSdRmwDJRe81AbY9-l:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/block_editor_view.js#L126)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Pass in the whole BlockDefinition model object. You'll eventually need it to populate the UI.
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 120 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSa2K4QHdhzfEMfDu5:-KpSdSAstvrwjbj42yRn:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/toolbox_editor_view.js#L120)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Similarly, pass in the whole Toolbox model object.
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 118 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSaAIvW5u1zkvQ_u9c:-KpSdScK7NBjkbmrxpnu:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/61831627e8500ed385bafbd0b063ca9e8721801c/src/view/workspace_editor_view.js#L118)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Again, pass in the model object.  I think you'll need both the contents and the config, or some container class for both.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120)*

**Comment by rachel-fenichel** [comment]
Small comments, but :lgtm: once you address them.

---

Reviewed 2 of 8 files at r1, 4 of 9 files at r2, 4 of 4 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/editor_controller.js, line 82 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSeX2iZlJKH0rO4J8v:-KpSeX2iZlJKH0rO4J8w:btp630v) ([raw file](https://github.com/google/blockly-devtools/blob/5809c5cb100e79e609ac3f3e6845e22bb7c8b778/src/controller/editor_controller.js#L82)):*
> ```JavaScript
>     this.currentEditor = null;
> 
>     // Determines which editor to show on load.
> ```

// Show the block editor on page load.

---

*[src/view/block_editor_view.js, line 73 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/120#-KpSf8061T4jxG9A7Oo-:-KpSf8061T4jxG9A7Oo0:b-ilr55k) ([raw file](https://github.com/google/blockly-devtools/blob/5809c5cb100e79e609ac3f3e6845e22bb7c8b778/src/view/block_editor_view.js#L73)):*
> ```JavaScript
> 
>     /**
>      * Whether user is creating rtl or ltr blocks.
> ```

Nit: RTL, LTR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/120#-:-KpSfZcjyXf7MOqdnVop:b5j0qr9)*

**Pull request merged**
