### PR TITLE
Save interface

### PR DESCRIPTION
**Pull request by svouse**
- All files save, defaults for non-project resources in place
- Saving UI updated
- Project directory input required
- Files contain appropriate data
- Temporary disable of ReadWriteController.hasSaved (but will be restored post-import reqiring)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/204)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTGu63uJjNd6n_Bug:-KqzTGu63uJjNd6n_Buh:b4pwc6x) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/read_write_controller.js#L122)):*
> ```JavaScript
>     var xmlStorageVariable = 'WORKSPACE_CONTENTS_XML';
>     let data = `
> var ${xmlStorageVariable} = ${xmlStorageVariable} || null;
> ```

Move this line between the DO NOT EDIT comments.  Same on other files.

---

*[src/controller/read_write_controller.js, line 185 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzUEaSM5NKRKynEzmj:-KqzUEaSM5NKRKynEzmk:b-176j0r) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/read_write_controller.js#L185)):*
> ```JavaScript
>   /**
>    * Write the project's metadata file.
>    */
> ```

TODO: Pass in list of platforms ids (strings) for this save/export pass.

---

*[src/controller/save_project_popup_controller.js, line 41 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzUGbZR51YYs4eLnFE:-KqzUGbZR51YYs4eLnFF:b-176j0r) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L41)):*
> ```JavaScript
>    * the session, used to write files.
>    * @param {Array.<Object>} toWrite Array of project elements to be written.
>    */
> ```

TODO: Pass in list of platforms ids (strings) for this save/export pass.

---

*[src/controller/save_project_popup_controller.js, line 53 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSm1VcfWbMm7Ft8_y:-KqzSm1VcfWbMm7Ft8_z:bgrayjd) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L53)):*
> ```JavaScript
>     /**
>      * Array of project elements to be written.
>      * @type {Array.<Object>}
> ```

Nit: `Array<Object>` is shorter and means the same thing.

---

*[src/controller/save_project_popup_controller.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSYvdnbWcd05ffQbw:-KqzSYvdnbWcd05ffQbx:b-tin1cp) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L62)):*
> ```JavaScript
>      * keys.
>      * Filled in by this.makeProjectPopupContents().
>      * @type {Array.<string>}
> ```

Nit: `Array<string>` is shorter and means the same thing.

---

*[src/controller/save_project_popup_controller.js, line 64 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSWqr7crmAXvXtR8G:-KqzSWqr7crmAXvXtR8H:b9f1dm9) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L64)):*
> ```JavaScript
>      * @type {Array.<string>}
>      */
>     this.viewDivs = [];
> ```

viewDivIds

---

*[src/controller/save_project_popup_controller.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzRPKohC3SqEm2H8yl:-KqzRPKohC3SqEm2H8ym:bf6025z) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L94)):*
> ```JavaScript
>                 this.readWriteController.getDivName(this.appController.project);
>             const projectLocation =
>                 this.readWriteController.directoryMap.get(projectDiv)
> ```

NIT: semicolon

---

*[src/controller/save_project_popup_controller.js, line 95 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzStWmzmZE0F00XODV:-KqzStWmzmZE0F00XODW:bl08sqv) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L95)):*
> ```JavaScript
>             const projectLocation =
>                 this.readWriteController.directoryMap.get(projectDiv)
>             localStorage.setItem(div, projectLocation);
> ```

Correct indent.

---

*[src/view/save_project_popup_view.js, line 80 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTrJrcxmGAOZOrlvc:-KqzTrJrcxmGAOZOrlvd:b-riex5) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L80)):*
> ```JavaScript
>     $('#submit').click(() => {
>       const projectDiv = this.controller.readWriteController.getDivName(
>               this.controller.appController.project)
> ```

Nit: semicolon

---

*[src/view/save_project_popup_view.js, line 111 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTk3gcoxNrVj4HH_3:-KqzTk3gcoxNrVj4HH_4:b-k17shh) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L111)):*
> ```JavaScript
>       $('#warning_text').html('Please select a project directory.');
>     } else {
>       $('#warning_text').html('');
> ```

Not CSS `display: none;`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by svouse** [comment]
Review status: 0 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 122 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTGu63uJjNd6n_Bug:-Kr1Fqlfd9u0o0oyh4kD:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/read_write_controller.js#L122)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Move this line between the DO NOT EDIT comments.  Same on other files.
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 185 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzUEaSM5NKRKynEzmj:-Kr1LwtJnLLzbpC6csz8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/read_write_controller.js#L185)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Pass in list of platforms ids (strings) for this save/export pass.
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 41 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzUGbZR51YYs4eLnFE:-Kr1M9RfuzHNeqHFiN4E:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L41)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Pass in list of platforms ids (strings) for this save/export pass.
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 53 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSm1VcfWbMm7Ft8_y:-Kr1MLulBeCkwLebHbQb:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L53)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: `Array<Object>` is shorter and means the same thing.
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSYvdnbWcd05ffQbw:-Kr1MOM-vj9GycvFwMGU:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L62)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: `Array<string>` is shorter and means the same thing.
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 64 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzSWqr7crmAXvXtR8G:-Kr1MX_7EQrMr7uHPKXW:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L64)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

viewDivIds
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzRPKohC3SqEm2H8yl:-Kr1MYMFORmH9cNyh3Sw:b-853vso) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L94)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

NIT: semicolon
</blockquote></details>

rip. Done

---

*[src/controller/save_project_popup_controller.js, line 95 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzStWmzmZE0F00XODV:-Kr1MnmZ6Q2jENmY0zTk:b9meiq9) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/controller/save_project_popup_controller.js#L95)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Correct indent.
</blockquote></details>

removed local storage setting

---

*[src/view/save_project_popup_view.js, line 80 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTrJrcxmGAOZOrlvc:-Kr1MsV2z2lazewfxNAE:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L80)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: semicolon
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 6 files at r2.
Review status: 1 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 100 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr1tJx9N2XiXiJC0sPZ:-Kr1tJx9N2XiXiJC0sP_:bps9e1z) ([raw file](https://github.com/google/blockly-devtools/blob/bb43fa60b1d660ac666acf2335232f44803e6e32/src/controller/read_write_controller.js#L100)):*
> ```JavaScript
>     const filename = this.getDivName(library) + '.js';
>     let fileData = 'Blockly.defineBlocksWithJsonArray( // BEGIN JSON EXTRACT \n' +
>         blockData + ');';
> ```

You're missing the matching END JSON EXTRACT comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by svouse** [comment]
Review status: 1 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 111 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTk3gcoxNrVj4HH_3:-Kr1wxLWzYL2KWcL4c6L:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L111)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Not CSS `display: none;`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 100 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr1tJx9N2XiXiJC0sPZ:-Kr20Pdaa-SyA5uBtx0_:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/bb43fa60b1d660ac666acf2335232f44803e6e32/src/controller/read_write_controller.js#L100)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

You're missing the matching END JSON EXTRACT comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204#-:-Kr2170epLvf4AUYmnmK:bnfp4nl)*

**Comment by chynu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/factory.css, line 618 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr1ylZ5fT8E36kMK3wQ:-Kr1ylZ5fT8E36kMK3wR:b89crvl) ([raw file](https://github.com/google/blockly-devtools/blob/bb43fa60b1d660ac666acf2335232f44803e6e32/src/factory.css#L618)):*
> ```CSS
> 
> #projectResources {
>   border-style: solid;
> ```

Totally a nit but you could do this in one line as `border: solid 1px #e0e0e0` (though not sure whether you were following google style, in which case please ignore me)

---

*[src/view/save_project_popup_view.js, line 111 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTk3gcoxNrVj4HH_3:-Kr2dfEoEVJVAZbmB1c4:b1katbu) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L111)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Super nit but you could also do `$(thing).show()` and `$(thing).hide()` and it would do the same thing + readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/factory.css, line 618 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr1ylZ5fT8E36kMK3wQ:-Kr32XmEZXlR-mg_YExY:bcams94) ([raw file](https://github.com/google/blockly-devtools/blob/bb43fa60b1d660ac666acf2335232f44803e6e32/src/factory.css#L618)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Totally a nit but you could do this in one line as `border: solid 1px #e0e0e0` (though not sure whether you were following google style, in which case please ignore me)
</blockquote></details>

Oh no that was just a relic of me fiddling (it's also not in alphabetical order which was a goof)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 111 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/204#-KqzTk3gcoxNrVj4HH_3:-Kr32nDCr8WGee70jN-s:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/5b8dd8aaab5d96f2bd2f44cfd215b9b82321d01f/src/view/save_project_popup_view.js#L111)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Super nit but you could also do `$(thing).show()` and `$(thing).hide()` and it would do the same thing + readability.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Comment by AnmAtAnm** [comment]
Minor nits, then :lgtm: 

---

Reviewed 4 of 9 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr369TrZaev-MYMwhhj:-Kr369TrZaev-MYMwhhk:b-hp9xsh) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/read_write_controller.js#L28)):*
> ```JavaScript
> goog.require('SaveProjectPopupController');
> 
> var BLOCKLY_OPTIONS = {};
> ```

`Object.create(null);`

---

*[src/controller/read_write_controller.js, line 205 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr37G2NWvJ56_21O6mW:-Kr37G2NWvJ56_21O6mX:bl8emal) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/read_write_controller.js#L205)):*
> ```JavaScript
>   /**
>    * Save the project's metadata file.
>    * TODO #205:  Pass in list of platforms ids (strings) for this save/export pass.
> ```

Keep TODOs out of doc comments.  Make a // comment just below.

---

*[src/controller/save_project_popup_controller.js, line 41 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr375YsbPEtSfJJ-0dL:-Kr375YsbPEtSfJJ-0dM:bl8emal) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/save_project_popup_controller.js#L41)):*
> ```JavaScript
>    * the session, used to write files.
>    * @param {Array<Object>} toWrite Array of project elements to be written.
>    * TODO #205: Pass in list of platforms ids (strings) for this save/export pass.
> ```

Keep TODOs out of doc comments.  Make a // comment just below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204#-:-Kr383gM04bAaAqio_pu:buitv5b)*

**Comment by svouse** [comment]
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 28 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr369TrZaev-MYMwhhj:-Kr39zPNaZ_K9ocxZpWz:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/read_write_controller.js#L28)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`Object.create(null);`
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 205 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr37G2NWvJ56_21O6mW:-Kr3A-HCDfpenvp3UAew:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/read_write_controller.js#L205)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Keep TODOs out of doc comments.  Make a // comment just below.
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 41 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/204#-Kr375YsbPEtSfJJ-0dL:-Kr3A-oo_5M0eODZOdJ0:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/34a672eb7f88095ad28034c22f01774460cba5e7/src/controller/save_project_popup_controller.js#L41)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Keep TODOs out of doc comments.  Make a // comment just below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/204)*

**Pull request merged**
