### PR TITLE
Toolbox Editor (4/4): Shadow Blocks

### PR DESCRIPTION
**Pull request by chynu**
Can now add/remove shadow blocks in toolbox editor. Accounts for most edge cases in enabling/disabling "add/remove shadow block" button, as well as warning text appearing/disappearing.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/146)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 586 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq98taoizPteQ_77kfF:-Kq98taoizPteQ_77kfG:b-r8jwxx) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L586)):*
> ```JavaScript
>    * If the currently selected block is a user-generated shadow block, this
>    * function makes it a normal block again, removing it from the list of
>    * shadow blocks and loading the workspace again. Updates the preview again.
> ```

Nit: "Updates the preview again" => "Updates the preview"

---

*[src/controller/toolbox_controller.js, line 607 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9C2FejVjfQAIPmTOW:-Kq9C2FejVjfQAIPmTOX:b619w2j) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L607)):*
> ```JavaScript
>    * Checks the currently selected block if it is breaking any shadow block rules.
>    * Sets warning text to user if it is breaking a rule, and removes warning
>    * text if it not.
> ```

"if it not" => "if it is not" or "if not"

---

*[src/controller/toolbox_controller.js, line 753 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9CtmwL31VUxAbHCHT:-Kq9CtmwL31VUxAbHCHU:b-pkbppo) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L753)):*
> ```JavaScript
>   saveStateFromWorkspace() {
>     this.view.toolbox.getSelected().saveFromWorkspace(this.view.editorWorkspace);
>     this.view.toolbox.setXml(this.generateToolboxXml()); // celine
> ```

reason for this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146)*

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 586 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq98taoizPteQ_77kfF:-Kq9NcYv89vOwc3bungt:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L586)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: "Updates the preview again" => "Updates the preview"
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 607 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9C2FejVjfQAIPmTOW:-Kq9NcHTErJ6mjM5I7qq:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L607)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

"if it not" => "if it is not" or "if not"
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 753 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9CtmwL31VUxAbHCHT:-Kq9NXoHQ-pPMsmw7SVb:bom22px) ([raw file](https://github.com/google/blockly-devtools/blob/28f3279afdef67a19e685a5f3ad8bfda566062d5/src/controller/toolbox_controller.js#L753)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

reason for this comment?
</blockquote></details>

Oops... I forgot to remove this. It was to bookmark something to look at later, haha..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146)*

**Comment by svouse** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/toolbox_controller.js, line 585 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9QTE6qDNBr-uJ6NOC:-Kq9QTE6qDNBr-uJ6NOD:bwkxs5q) ([raw file](https://github.com/google/blockly-devtools/blob/f9460fcf677e45ccf16476f05a623e78f3705d36/src/controller/toolbox_controller.js#L585)):*
> ```JavaScript
>    * If the currently selected block is a user-generated shadow block, this
>    * function makes it a normal block again, removing it from the list of
>    * shadow blocks and loading the workspace again. Updates the preview.
> ```

Nit: "loading the workspace again" => "reloading the workspace"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146)*

**Comment by svouse** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146#-:-Kq9RLrUr-E7jRR2NPGb:bnfp4nl)*

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/toolbox_controller.js, line 585 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9QTE6qDNBr-uJ6NOC:-Kq9TBDcC4p5gqRzxfya:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/f9460fcf677e45ccf16476f05a623e78f3705d36/src/controller/toolbox_controller.js#L585)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: "loading the workspace again" => "reloading the workspace"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146)*

**Comment by AnmAtAnm** [comment]
One suggestion and then :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 559 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9Xy15T-ryMLOsLEnz:-Kq9Xy16WVsIYq0Likeo:b-q9pbg0) ([raw file](https://github.com/google/blockly-devtools/blob/e9e6e32f39600162e383cbc036c0672fd7093003/src/controller/toolbox_controller.js#L559)):*
> ```JavaScript
>    * preview when done.
>    */
>   addShadow() {
> ```

Rename `setSelectedAsShadowBlock()`.

---

*[src/controller/toolbox_controller.js, line 587 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9Y6cPaJHUA25J3GAN:-Kq9Y6cPaJHUA25J3GAO:b-chk05z) ([raw file](https://github.com/google/blockly-devtools/blob/e9e6e32f39600162e383cbc036c0672fd7093003/src/controller/toolbox_controller.js#L587)):*
> ```JavaScript
>    * preview when done.
>    */
>   removeShadow() {
> ```

And `unsetSelectedAsShadowBlock()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146#-:-Kq9smWy94N0lS86Ymof:b-2bpz55)*

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/controller/toolbox_controller.js, line 559 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9Xy15T-ryMLOsLEnz:-KqA-xvIZkaERr2dew1C:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e9e6e32f39600162e383cbc036c0672fd7093003/src/controller/toolbox_controller.js#L559)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Rename `setSelectedAsShadowBlock()`.
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 587 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/146#-Kq9Y6cPaJHUA25J3GAN:-KqA-xSgJRKVu3V1MDwE:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e9e6e32f39600162e383cbc036c0672fd7093003/src/controller/toolbox_controller.js#L587)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

And `unsetSelectedAsShadowBlock()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/146)*

**Pull request merged**
