### PR TITLE
Refactor: Popup show/hide

### PR DESCRIPTION
**Pull request by chynu**
Fixed links to bring back new block popup (added some files along the way). Popup now opens and closes. The block editor does not populate correctly (will work on in next PR, but I felt like this was getting very long already).
 - `NewBlockPopupController` and `NewBlockPopupView` extend `PopupController` and `PopupView`, respectively.
 - There was an issue where `AppController` was creating multiple editor views. Fixed.

Note: comparing against the `popup` branch instead of `develop` because the feature is not fully functioning quite yet. (Will remove `console.log`s when feature is fully fixed.)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/107)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/factory_utils.js, line 1209 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-8ulIVdPvr4nIEIE:-Kp2-8ulIVdPvr4nIEIF:beoib0s) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/factory_utils.js#L1209)):*
> ```JavaScript
>  * @param {string} blockTypeName Name of block, given by user.
>  * @param {string} blockStarterText Starter text to place on block, given by user (optional).
> */
> ```

Nit: space

---

*[src/controller/new_block_popup_controller.js, line 38 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-Sb_rHXH_C7Yw-Wr:-Kp2-Sb_rHXH_C7Yw-Ws:b7s4suq) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/new_block_popup_controller.js#L38)):*
> ```JavaScript
>   /**
>    * @constructor
>    * @param {AppController}
> ```

Param description (also I'm wondering if for now the type of this should be AppController2?)

---

*[src/controller/new_block_popup_controller.js, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-eNnNCy_fe3vASKB:-Kp2-eNnNCy_fe3vASKC:b-y4uj6u) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/new_block_popup_controller.js#L101)):*
> ```JavaScript
>     this.view.show();
>   }
> }
> ```

Nit: newline

---

*[src/controller/popup_controller.js, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-mTMpXwi1DMndbMY:-Kp2-mTMpXwi1DMndbMZ:b-dxwqrc) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L39)):*
> ```JavaScript
>   /**
>    * @constructor
>    * @param {!AppController} appController AppController object which will send
> ```

Nit "will send" -> "sends"

---

*[src/controller/popup_controller.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-yfzn89vnMv6peGI:-Kp2-yfzn89vnMv6peGJ:blqwxfz) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L63)):*
> ```JavaScript
>    * between popups. Preview popup is the popup of a developer's sample application
>    * before export.
>    * @return {!string}
> ```

Return description 

---

*[src/controller/popup_controller.js, line 73 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp20HWvaDbBKkXM4q3W:-Kp20HWvaDbBKkXM4q3X:b-ya81ng) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L73)):*
> ```JavaScript
>    * between popups. The New Block popup allows developers to initialize their
>    * block before going right into the Block Editor.
>    * @return {!string}
> ```

Same as above

---

*[src/controller/popup_controller.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp20JLMz_oO7CTR_4Oz:-Kp20JLMz_oO7CTR_4P-:b-ya81ng) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L83)):*
> ```JavaScript
>    * between popups. The new config popup allows developers to click through
>    * a checkbox to configure their WorkspaceConfiguration.
>    * @return {!string}
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by chynu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/factory_utils.js, line 1209 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-8ulIVdPvr4nIEIE:-Kp24bxEqsIZ70luHK6X:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/factory_utils.js#L1209)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: space
</blockquote></details>

Done.

---

*[src/controller/new_block_popup_controller.js, line 38 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-Sb_rHXH_C7Yw-Wr:-Kp256eYayC3b5LrevPN:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/new_block_popup_controller.js#L38)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Param description (also I'm wondering if for now the type of this should be AppController2?)
</blockquote></details>

Done.

---

*[src/controller/new_block_popup_controller.js, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-eNnNCy_fe3vASKB:-Kp259O-zMQHKPJZ9pUZ:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/new_block_popup_controller.js#L101)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: newline
</blockquote></details>

Done.

---

*[src/controller/popup_controller.js, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-mTMpXwi1DMndbMY:-Kp25GZjxQpD90JrQB5T:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L39)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit "will send" -> "sends"
</blockquote></details>

Done.

---

*[src/controller/popup_controller.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp2-yfzn89vnMv6peGI:-Kp25n9FJWmc4mF_4uli:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L63)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Return description 
</blockquote></details>

Done.

---

*[src/controller/popup_controller.js, line 73 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp20HWvaDbBKkXM4q3W:-Kp25naTpdjkmJfqwcc4:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L73)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/controller/popup_controller.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp20JLMz_oO7CTR_4Oz:-Kp25nzivUe3L0IL9k1b:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7f23c6cb5d39a1b64d6f068986305e05a1cdeadb/src/controller/popup_controller.js#L83)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by svouse** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 382 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp279OxdyGTwde1kePV:-Kp279OxdyGTwde1kePW:bc4qa22) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/app_controller_2.js#L382)):*
> ```JavaScript
>    * changes and refreshes or leaves the page, confirm that they want to do so
>    * before actually refreshing.
>    * @param {Event} event beforeunload event.
> ```

Nit: capitalization 

---

*[src/controller/workspace_controller.js, line 60 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp27vwnst4oib88jHfP:-Kp27vwnst4oib88jHfQ:b-nrnwsa) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/workspace_controller.js#L60)):*
> ```JavaScript
>     /**
>      * WorkspaceEditorView associated with this instance of WorkspaceController.
>      * @type {!WorkspaceView}
> ```

Should the type be WorkspaceEditorView?

---

*[src/view/block_editor_view.js, line 34 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp28LkKn0-Vx_sORROS:-Kp28LkKn0-Vx_sORROT:b-c3csn0) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/block_editor_view.js#L34)):*
> ```JavaScript
> 
> class BlockEditorView {
>   constructor(blockDefinition) {
> ```

Constructor JSDoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by chynu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 382 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp279OxdyGTwde1kePV:-Kp292yUudfhRkHKIRxQ:b-7ega31) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/app_controller_2.js#L382)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: capitalization 
</blockquote></details>

Done. (I think `beforeunload` is a key word)

---

*[src/controller/workspace_controller.js, line 60 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp27vwnst4oib88jHfP:-Kp29W1q77aguZTDZTSL:b-bva4xa) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/workspace_controller.js#L60)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Should the type be WorkspaceEditorView?
</blockquote></details>

Ah, it should. Done.

---

*[src/view/block_editor_view.js, line 34 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp28LkKn0-Vx_sORROS:-Kp29lzb2GKkDFPELe6r:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/block_editor_view.js#L34)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Constructor JSDoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/popup_view.js, line 79 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29u5_89B0w_-ZBtzq:-Kp29u5_89B0w_-ZBtzr:bl0ln3j) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/popup_view.js#L79)):*
> ```JavaScript
>   hide() {
>     $('.popup').html('');
>     $('.popup').css('display', 'none');
> ```

http://api.jquery.com/hide/ ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by svouse** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/popup_controller.js, line 33 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29aV7MhnMfotvzea2:-Kp29aV7MhnMfotvzea3:bqhqxp3) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/popup_controller.js#L33)):*
> ```JavaScript
> 
> goog.require('NewBlockPopupView');
> goog.require('ProjectController');
> ```

Does PopupController still require ProjectController?

---

*[src/view/app_view.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29xkfQglI8UXC0TrX:-Kp29xkfQglI8UXC0TrY:ba48v2n) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/app_view.js#L32)):*
> ```JavaScript
> 
> goog.require('BlockDefinition');
> goog.require('BlockEditorView');
> ```

Does AppView still require BlockEditorView?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107#-:-Kp2AE0cwFyf5OtuXhg0:bnfp4nl)*

**Comment by svouse** [comment]
Post-remaining comments :lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107#-:-Kp2AjoOSdX0xIC-Uzo1:b-nyesh2)*

**Comment by chynu** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/popup_controller.js, line 33 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29aV7MhnMfotvzea2:-Kp2B5Xy8ZXZ-YJUXPUt:b-cwoplm) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/controller/popup_controller.js#L33)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Does PopupController still require ProjectController?
</blockquote></details>

Oooh, it doesn't anymore. Thanks..!

---

*[src/view/app_view.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29xkfQglI8UXC0TrX:-Kp2BH29eC-MnRRIPgkt:bzi1hnh) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/app_view.js#L32)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Does AppView still require BlockEditorView?
</blockquote></details>

Nope, removed.

---

*[src/view/popup_view.js, line 79 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/107#-Kp29u5_89B0w_-ZBtzq:-Kp2BIZSr4uFz478SiBe:b-h0rc9k) ([raw file](https://github.com/google/blockly-devtools/blob/c1cd56b89c0e49c60ee11bf18da8b4024995fa0f/src/view/popup_view.js#L79)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

http://api.jquery.com/hide/ ?
</blockquote></details>

Oohh. Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/107)*

**Pull request merged**
