### PR TITLE
Refactor: Implementing EditorController

### PR DESCRIPTION
**Pull request by chynu**
Implemented 4/4 functions in `editor_controller.js`.
Also:
 - Rearranged some functions in `toolbox_controller.js` for readability.
 - Implemented one or two functions that were closely linked to functions in `EditorController`.
 - Moved some functions from `EditorController` to `ToolboxController` and `WorkspaceController`.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/93)

### CODE REVIEW

**Comment by svouse** [comment]
*[src/view/workspace_editor_view.js, line 118 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/93#-KoUWPnFkbXC4SQzQTgB:-KoUWPnFkbXC4SQzQTgC:bejgs1i) ([raw file](https://github.com/google/blockly-devtools/blob/e2f533a91d011e655039212f38233d30fc06c108/src/view/workspace_editor_view.js#L118)):*
> ```JavaScript
>      * TODO: Move in from wfactory_view.js:setBaseOptions()
>      */
>     throw 'Unimplemented: initBaseConfigs()';
> ```

Nit; throw is for initBaseConfigs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/93)*

**Comment by chynu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/workspace_editor_view.js, line 118 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/93#-KoUWPnFkbXC4SQzQTgB:-KoUeT8wFeEkkao2n0fM:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e2f533a91d011e655039212f38233d30fc06c108/src/view/workspace_editor_view.js#L118)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit; throw is for initBaseConfigs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/93)*

**Comment by rachel-fenichel** [comment]
LGTM.

Note: There are some chunks of code that are moving around but don't seem to be changing.  It makes the diff a bit hard to read.

---

Reviewed 4 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/93#-:-KoUgC7Rr6EP2Dft7a3J:bb0xl73)*

**Comment by chynu** [comment]
Noted, I'll make code-rearrangements into separate PR's (which I think will happen because some of the files are hard to read and some functions could be grouped by functionality).

**Comment by rachel-fenichel** [comment]
You can also just leave a note that says "I moved this function from here to here but didn't change it" if it's just a few that you moved on the way.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/93#-:-KoUiqZ4Rr48qyaYHSMq:blrm9jg)*

**Pull request merged**
