### PR TITLE
Project metadata

### PR DESCRIPTION
**Pull request by svouse**
Rough development PR for project metadata

Goals: Verify tentative Resource/Project metadata structure.

Details:This PR is made with the expectation that upcoming PRs will refactor the saving code in to new classes (along with developing fucntionalty further, of course), names TBD, which will provide more organization.

Accomplishes:
- creates nested folders
- creates project metadata file*
- minor debug of add button closing (out of sheer annoyance"

Non-goals (for this PR): 
- movement of saving code to appropriate classes

* Here's the file it currently creates:
name: A Project
resourceType: Project
web_export: true
ios_export: false
android_export: false
resources: 
platform: web

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/159)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/app_controller.js, line 169 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqV-OG-ECSWpTpk2bb9:-KqV-OG-ECSWpTpk2bbA:b-mvnjff) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/app_controller.js#L169)):*
> ```JavaScript
>      * Location where the project directory is saved.
>      */
>     this.storageLocation = localStorage.getItem('devToolsProjectLocation');
> ```

Where does this `localStorage` reference come from?

---

*[src/controller/app_controller.js, line 272 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUyiBRriYI3KBlPyRY:-KqUyiBRriYI3KBlPyRZ:bdfx3dk) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/app_controller.js#L272)):*
> ```JavaScript
>   saveProject() {
>     // Check for viable save location.
>     if (this.storageLocation == undefined) {
> ```

`if (!this.storageLocation)`

---

*[src/controller/save_project_popup_controller.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzkwKorud59eUPhIO:-KqUzkwKorud59eUPhIP:braw2qs) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/save_project_popup_controller.js#L63)):*
> ```JavaScript
>       let data = Object.create(null);
>       this.appController.project.buildMetaData(data);
>       let dataString = this.appController.project.getDataString(data);
> ```

Are you planning on implementing `getDataString()` in future PR's? I only see it in Resource.

---

*[src/model/resource.js, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqV-jy-0jjsNMmSGZ3P:-KqV-jy-0jjsNMmSGZ3Q:b58kxig) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L48)):*
> ```JavaScript
>      * @type {string}
>      */
>     this.resourceType = resourceType || null;
> ```

Doesn't the second half execute if `resourceType` is `null` anyway?

---

*[src/model/resource.js, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzyOeYAhIULHbzDD6:-KqUzyOfa1aURbP8nK3_:b-g4bxxz) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L113)):*
> ```JavaScript
>    * @return {!Object} The resource metadata.
>    */
>   getDataString(obj) {
> ```

Why does `buildMetaData()` and `getDataString()` have the same jsdoc? I'm a little confused as to what does what.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/app_controller.js, line 169 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqV-OG-ECSWpTpk2bb9:-KqV0mdav9PSEG7CHgR7:b-vgshgz) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/app_controller.js#L169)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Where does this `localStorage` reference come from?
</blockquote></details>

localStorage is a nifty preexisting Javascript object: http://htmldog.com/guides/javascript/advanced/localstorage/

---

*[src/controller/app_controller.js, line 272 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUyiBRriYI3KBlPyRY:-KqV25qhh1Z7j2Brl79J:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/app_controller.js#L272)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`if (!this.storageLocation)`
</blockquote></details>

Done.

---

*[src/controller/save_project_popup_controller.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzkwKorud59eUPhIO:-KqV26aeq7pnmZIWynTO:b31sa5t) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/save_project_popup_controller.js#L63)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Are you planning on implementing `getDataString()` in future PR's? I only see it in Resource.
</blockquote></details>

Nope; the resource method should be sufficient, and thus when all resources call the method it'll default to the super

---

*[src/model/resource.js, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqV-jy-0jjsNMmSGZ3P:-KqV2HLWtYMY1bItzPos:bl63gea) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L48)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Doesn't the second half execute if `resourceType` is `null` anyway?
</blockquote></details>

whoops meant to be 'Resource'

---

*[src/model/resource.js, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzyOeYAhIULHbzDD6:-KqV2RM2ZQzvNhqH1MFr:b-tgkye) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L113)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Why does `buildMetaData()` and `getDataString()` have the same jsdoc? I'm a little confused as to what does what.
</blockquote></details>

b/c of a *~spicy~* copy pasta ^.-  
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
*[src/controller/save_project_popup_controller.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzkwKorud59eUPhIO:-KqV45KoCKEhPFwTNGVc:b-sgmzon) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/controller/save_project_popup_controller.js#L63)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nope; the resource method should be sufficient, and thus when all resources call the method it'll default to the super
</blockquote></details>

*any rather than all

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by rachel-fenichel** [comment]
Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/app_controller.js, line 258 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVD2v3vJ2P0H_Z8vzf:-KqVD2v4K1fpn5Kc5W_T:b-agqnff) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L258)):*
> ```JavaScript
>     const toolboxDir = projectDir + '/' + PREFIXES.TOOLBOX;
>     const workspaceDir = projectDir + '/' + PREFIXES.GENERAL_WORKSPACE;
>     const dirs = [ projectDir, libraryDir, toolboxDir, workspaceDir];
> ```

nit: remove space after `[`

---

*[src/controller/app_controller.js, line 283 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVDGPiSaDh1I6gTDh5:-KqVDGPiSaDh1I6gTDh6:b-lbiayh) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L283)):*
> ```JavaScript
>       let dataString = this.project.getDataString(data);
>       fs.writeFileSync(
>           this.storageLocation + '/' + this.project.name + '/' +  this.project.name,
> ```

So if the project is named TheBestProject the metadata will be in `<dir>/TheBestProject/TheBestProject`, yes?  I'd rather it be in a file named metadata so that you can always look for the same filename regardless of which project you are opening.

---

*[src/controller/save_project_popup_controller.js, line 54 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVDr1p6T_vaocA-xEd:-KqVDr1p6T_vaocA-xEe:b-8rq8gq) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/save_project_popup_controller.js#L54)):*
> ```JavaScript
>     });
> 
>     const view = this.view;
> ```

Why create this variable and then use `this.view` for the rest of the function/

---

*[src/model/project.js, line 282 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVE1Pa6qHoDPRXqnUG:-KqVE1Pa6qHoDPRXqnUH:bgboylp) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/project.js#L282)):*
> ```JavaScript
>    * @return {!Object} The project metadata.
>    */
>   buildMetaData(obj) {
> ```

I'd prefer `buildMetadata` but can live with this.

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVEFgt97DRTUKwt6Mt:bwyxy3g) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
> ```JavaScript
>     obj.name = this.name;
>     obj.resourceType = this.resourceType;
>     obj.file = '';
> ```

What is `file`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
Review status: 10 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/controller/app_controller.js, line 253 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVD1UgOQQXGdpkwObf:-KqVD1UgOQQXGdpkwObg:b-568vlu) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L253)):*
> ```JavaScript
>    * Creates the properly nested directory in which to save the project.
>    */
>   initProjectDirectory() {
> ```

I suggest doing this on a per file-to-save basis. That is, if a directory doesn't exist, create As mentioned before, the user's desired structure may be very different. These defaults are better left in the UI (possibly a save dialog) when the user first saves things.

---

*[src/controller/app_controller.js, line 283 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVDGPiSaDh1I6gTDh5:-KqVFnqalqzv-Rs2dO8X:b-lucprw) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L283)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

So if the project is named TheBestProject the metadata will be in `<dir>/TheBestProject/TheBestProject`, yes?  I'd rather it be in a file named metadata so that you can always look for the same filename regardless of which project you are opening.
</blockquote></details>

+1 in the project root.  No two projects should be in the same directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 10 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/controller/app_controller.js, line 253 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVD1UgOQQXGdpkwObf:-KqVI3wG0LYYJS-sZ2cS:b-8udav0) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L253)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I suggest doing this on a per file-to-save basis. That is, if a directory doesn't exist, create As mentioned before, the user's desired structure may be very different. These defaults are better left in the UI (possibly a save dialog) when the user first saves things.
</blockquote></details>

sgtm; made issue #161 , and will implement this as part of the next saving PR

---

*[src/controller/app_controller.js, line 258 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVD2v3vJ2P0H_Z8vzf:-KqVG00Pq_7wp9nMoVA5:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L258)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: remove space after `[`
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 283 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVDGPiSaDh1I6gTDh5:-KqVG6jSikgXWb0bVjef:b3z915l) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/app_controller.js#L283)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

So if the project is named TheBestProject the metadata will be in `<dir>/TheBestProject/TheBestProject`, yes?  I'd rather it be in a file named metadata so that you can always look for the same filename regardless of which project you are opening.
</blockquote></details>

sgtm; done

---

*[src/controller/save_project_popup_controller.js, line 54 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVDr1p6T_vaocA-xEd:-KqVGfK3JSIJjodoQEFX:b-idlqml) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/controller/save_project_popup_controller.js#L54)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Why create this variable and then use `this.view` for the rest of the function/
</blockquote></details>

Whoops (a debugging relic); removed

---

*[src/model/project.js, line 282 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVE1Pa6qHoDPRXqnUG:-KqVGCxDJYZb5miTvPHe:b499q7j) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/project.js#L282)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I'd prefer `buildMetadata` but can live with this.
</blockquote></details>

Changed

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVHK_pP3dpcB1tyqt0:b-b5q0yb) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

What is `file`?
</blockquote></details>

A pointer to the file which contains the data associated with the name (irrelevant for project//removed); should I rename the field for clarity?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVMoJQ95OYiEvqOUrk:bmzmyxs) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

A pointer to the file which contains the data associated with the name (irrelevant for project//removed); should I rename the field for clarity?
</blockquote></details>

filepath?  @anmatanm do you have opinions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/app_controller.js, line 283 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVKktxIoPJdA_aPVJi:-KqVKktxIoPJdA_aPVJj:b-qomx4n) ([raw file](https://github.com/google/blockly-devtools/blob/cd405023a6fd81f83f65cdf7c58231ce16d093c3/src/controller/app_controller.js#L283)):*
> this.storageLocation + '/' + this.project.name + '/' +  'metadata',

`this.storageLocation + path.sep + 'blockly-proj.json'`

If the user chose to store files in the a directory named after `project.name`, then store that location in the `storageLocation`.  It gives them the flexibility of storing a file in a different structure.

---

*[src/controller/save_project_popup_controller.js, line 34 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVLRN52ViPF7488bDj:-KqVLRN52ViPF7488bDk:bi0lwcb) ([raw file](https://github.com/google/blockly-devtools/blob/cd405023a6fd81f83f65cdf7c58231ce16d093c3/src/controller/save_project_popup_controller.js#L34)):*
> ```JavaScript
>  * @author celinechoo (Celine Choo), sagev (Sage Vouse)
>  */
> class SaveProjectPopupController extends PopupController {
> ```

This dialog feels like a barrier to the save process, not adding much, but I haven't figured out a way use NWJS file open and save dialogs without the `<input>` button.

It could be made useful by listing everything that is about to be saved (a confirmation, of sorts).

Fine for now.

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVMJR26SUtpW3wSJ7b:b7tq4yd) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

filepath?  @anmatanm do you have opinions?
</blockquote></details>

I prefer `filepath`.

It should be explicit that this is a web specific file.

```
obj.web = {
   filepath: '
}
```

Also, Some `Resource`s, like `ResourceSet`s  do not have save files.  (Discussed offline)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 10 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/controller/app_controller.js, line 283 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVKktxIoPJdA_aPVJi:-KqVUNUeTo1Aog9aptdy:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/cd405023a6fd81f83f65cdf7c58231ce16d093c3/src/controller/app_controller.js#L283)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

> this.storageLocation + '/' + this.project.name + '/' +  'metadata',

`this.storageLocation + path.sep + 'blockly-proj.json'`

If the user chose to store files in the a directory named after `project.name`, then store that location in the `storageLocation`.  It gives them the flexibility of storing a file in a different structure.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
Review status: 8 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/app_controller.js, line 283 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVKktxIoPJdA_aPVJi:-KqVYt22A27heaHmNXjJ:bneehp5) ([raw file](https://github.com/google/blockly-devtools/blob/cd405023a6fd81f83f65cdf7c58231ce16d093c3/src/controller/app_controller.js#L283)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove this.project.name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
Reviewed 1 of 3 files at r4.
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVZ9X8jmCZhmyaD7j7:b-nillwa) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I prefer `filepath`.

It should be explicit that this is a web specific file.

```
obj.web = {
   filepath: '
}
```

Also, Some `Resource`s, like `ResourceSet`s  do not have save files.  (Discussed offline)

</blockquote></details>

Remove obj.filepath above, since we have it below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/app_controller.js, line 283 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVKktxIoPJdA_aPVJi:-KqVZAfuza4q8Rm0a5x1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/cd405023a6fd81f83f65cdf7c58231ce16d093c3/src/controller/app_controller.js#L283)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Remove this.project.name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/resource.js, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzyOeYAhIULHbzDD6:-KqVZYo1cnRnfripalfs:bjtxp3t) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L113)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

b/c of a *~spicy~* copy pasta ^.-  
fixed
</blockquote></details>

Are you trying to build `JSON.stringify()` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/resource.js, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqVEFgt97DRTUKwt6Ms:-KqVZY8ZdAy2cSaHdnJ6:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/21d58e78af776128cd7480443ae0dbbfaf5959c2/src/model/resource.js#L102)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Remove obj.filepath above, since we have it below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by svouse** [comment]
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/model/resource.js, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/159#-KqUzyOeYAhIULHbzDD6:-KqVaNJKnQoFatdID196:b-qh9o6i) ([raw file](https://github.com/google/blockly-devtools/blob/9b924b5517f7d945a94f1655c8a983e6675ddb82/src/model/resource.js#L113)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Are you trying to build `JSON.stringify()` here?
</blockquote></details>

Whoops; changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/159#-:-KqVarjBJ5CuF07WIbHH:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
