### PR TITLE
Block exporter refactor

### PR DESCRIPTION
**Pull request by svouse**
The new DevTools will have no need for the block_exporter tools, controller, or view. As a result, classes which extend from Resource are being given the capability to get the data necessary for their export, which will presumably be used by their controllers/ the getter for Project.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/76)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
One nit then LGTM.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/project_controller.js, line 80 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/76#-KoJuifNKviWrd35zr0X:-KoJuifOhLzUWd3bMT0D:b-kspbix) ([raw file](https://github.com/google/blockly-devtools/blob/41d225ef8951f4e78baffb9e68dce19b2d3c4ea8/src/controller/project_controller.js#L80)):*
> ```JavaScript
> 
>   /**
>    * Creates new toolbox to this.project's toolbox set.
> ```

Adds, not creates.  (Looks like an old typo.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76#-:-KoJvFDImIymUqPn0WrU:brj327x)*

**Comment by chynu** [comment]
*[src/model/toolbox.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/76#-KoJv0_x0ejg2MyszAB5:-KoJv0_x0ejg2MyszAB6:b-fzkuog) ([raw file](https://github.com/google/blockly-devtools/blob/41d225ef8951f4e78baffb9e68dce19b2d3c4ea8/src/model/toolbox.js#L88)):*
> ```JavaScript
>    * @returns {string} String representation of XML file to be exported.
>    */
>   getExportXml() {
> ```

I have a PR coming up that renames this to `generateXml()`, so maybe change to that to minimize merge conflicts? Also what is the difference between `getExportXml()` and `getExportData()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76)*

**Comment by svouse** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/project_controller.js, line 80 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/76#-KoJuifNKviWrd35zr0X:-KoJxS2wq_VP321pcPTA:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/41d225ef8951f4e78baffb9e68dce19b2d3c4ea8/src/controller/project_controller.js#L80)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Adds, not creates.  (Looks like an old typo.)
</blockquote></details>

Done.

---

*[src/model/toolbox.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/76#-KoJv0_x0ejg2MyszAB5:-KoJxT2SSYSVY8kvLK65:b4ga86k) ([raw file](https://github.com/google/blockly-devtools/blob/41d225ef8951f4e78baffb9e68dce19b2d3c4ea8/src/model/toolbox.js#L88)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I have a PR coming up that renames this to `generateXml()`, so maybe change to that to minimize merge conflicts? Also what is the difference between `getExportXml()` and `getExportData()`?
</blockquote></details>

Will do; also I wasn't necessarily sure in this refactor, but expected somewhere down the line that getExportData would essentially replace it (largely just by virtue of it being a method inherited from Resource)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76)*

**Comment by rachel-fenichel** [comment]
Looks good to me, but wait for Celine's okay.

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76#-:-KoJyZuuVj-p1hy79bSA:be2zvts)*

**Comment by chynu** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/toolbox.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/76#-KoJv0_x0ejg2MyszAB5:-KoJyajkEo-lJUS4_NLG:b-n21xtf) ([raw file](https://github.com/google/blockly-devtools/blob/41d225ef8951f4e78baffb9e68dce19b2d3c4ea8/src/model/toolbox.js#L88)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Will do; also I wasn't necessarily sure in this refactor, but expected somewhere down the line that getExportData would essentially replace it (largely just by virtue of it being a method inherited from Resource)
</blockquote></details>

Makes sense! Thanks for clarifying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76)*

**Comment by chynu** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/76)*

**Comment by chynu** [comment]
LGTM!

**Pull request merged**
