### PR TITLE
Block Editor: Renaming Blocks

### PR DESCRIPTION
**Pull request by chynu**
Can now rename blocks and will reflect in navtree. Does not reflect for every character change, but will update once user clicks out of the block/field. 
(This is because jstree slows down when it is overloaded with change information for every character.)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/181)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/project_controller.js, line 308 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqe_qfBldHYHW7e7gcY:-Kqe_qfBldHYHW7e7gcZ:b-kzor4g) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/controller/project_controller.js#L308)):*
> ```JavaScript
>    * @param {!BlockDefinition} block BlockDefinition object to change.
>    * @param {string} newName New name of block.
>    * @param {boolean=} opt_suppress Whether to suppress changes in the tree (to
> ```

?boolean, and maybe !string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/block_definition.js, line 61 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqea2lo2Qyqn-jt1Fqq:-Kqea2lo2Qyqn-jt1Fqr:bhlzzk0) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_definition.js#L61)):*
> ```JavaScript
>     // TODO(#180): Remove references to setType() to be setName() to follow object
>     // inheritance.
>     this.setName(type);
> ```

setting the name sets the type due to the type() getter method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/block_library.js, line 66 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaCh4Mzht09s053BU:-KqeaCh4Mzht09s053BV:b-nycbfs) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library.js#L66)):*
> ```JavaScript
>   /**
>    * Returns the BlockDefinition within this library of the given name.
>    * @param {string} blockName Name of block to be found.
> ```

nit: !string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_library_set.js, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaHm_3d20LVZ4h_cu:-KqeaHman8vg97QJRTqm:b-s94jja) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library_set.js#L60)):*
> ```JavaScript
>    *     to the corresponding BlockDefinition object.
>    */
>   getAllBlocks() {
> ```

all sets have a resources object; reason you're creating another object?//I think using resources should be sufficient

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_library_set.js, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaHm_3d20LVZ4h_cu:-KqeaQoET-EhmgQqAD71:b-tyd732) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library_set.js#L60)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

all sets have a resources object; reason you're creating another object?//I think using resources should be sufficient
</blockquote></details>

oh whoops you're looking for definitions; disregard, but I would rather you use the getBlockDefinitionsMap method or delete it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/project_controller.js, line 308 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqe_qfBldHYHW7e7gcY:-KqeaV2CEcxTuC-cq2Xf:b-cjob6x) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/controller/project_controller.js#L308)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

?boolean, and maybe !string?
</blockquote></details>

The original type annotations are correct.

---

*[src/model/block_library.js, line 66 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaCh4Mzht09s053BU:-Kqeaj7pl4HJU2wZ-dS-:b-8rmyn1) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library.js#L66)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

nit: !string
</blockquote></details>

strings are always not null, in the Closure type system: https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/block_library.js, line 66 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaCh4Mzht09s053BU:-Kqeav-Tk_5RRKVm75n7:b-uqwk5e) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library.js#L66)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

strings are always not null, in the Closure type system: https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System
</blockquote></details>

oh cool thanks

---

*[src/model/project.js, line 221 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeafhwULBG4wyK8iq0:-KqeafhwULBG4wyK8iq1:b-v0y7hm) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/project.js#L221)):*
> ```JavaScript
>    */
>   getBlockDefinition(blockName) {
>     return this.librarySet.getAllBlocks()[blockName];
> ```

use the preexisting library set method (or get rid of it). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/project_controller.js, line 308 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqe_qfBldHYHW7e7gcY:-Kqeay2Ywr4iUqujMLVP:b-na8l62) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/controller/project_controller.js#L308)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The original type annotations are correct.
</blockquote></details>

my bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by rachel-fenichel** [comment]
+1 to sage's comments about using existing functions.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 194 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeatLLbF20W7TAtD3q:-KqeatLLbF20W7TAtD3r:bx4308f) ([raw file](https://github.com/google/blockly-devtools/blob/c79dafac0cd93ac339067a7ed0fa3f59617f75c3/src/controller/block_editor_controller.js#L194)):*
> ```JavaScript
>     if (!suppressTreeChange &&
>         this.projectController.getProject().hasBlockDefinition(newName)) {
>       rootBlock.setWarningText('There is already a block under this name.\n' +
> ```

If there's already a block under that name I expect this to return early and without calling the projectController method.  I know the projectController method is a no-op in that case, but you know ahead of time that you don't need to make that call.

---

*[src/controller/project_controller.js, line 311 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqebO5yx-HM2qIAjTx5:-KqebO5yx-HM2qIAjTx6:bhoxnaw) ([raw file](https://github.com/google/blockly-devtools/blob/c79dafac0cd93ac339067a7ed0fa3f59617f75c3/src/controller/project_controller.js#L311)):*
> ```JavaScript
>    *     avoid overloading JSTree with commands for every workspace change).
>    */
>   renameBlockDefinition(block, newName, opt_suppress) {
> ```

Missing @return annotation, but it also doesn't look like you're using the return value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181#-:-KqecEPUXPCplVuwcntd:b-p2fvaz)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/block_definition.js, line 61 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqea2lo2Qyqn-jt1Fqq:-Kqeca6sAqCdfJWTJK91:b-jygu6l) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_definition.js#L61)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

setting the name sets the type due to the type() getter method
</blockquote></details>

Per Neil's suggestions, we should avoid getter methods for anything other than constants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 194 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeatLLbF20W7TAtD3q:-KqemxQJSY4wW3eu7ASl:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c79dafac0cd93ac339067a7ed0fa3f59617f75c3/src/controller/block_editor_controller.js#L194)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

If there's already a block under that name I expect this to return early and without calling the projectController method.  I know the projectController method is a no-op in that case, but you know ahead of time that you don't need to make that call.
</blockquote></details>

Done.

---

*[src/controller/project_controller.js, line 311 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqebO5yx-HM2qIAjTx5:-KqendEoh1yTX7d4Kh-9:bmuzaex) ([raw file](https://github.com/google/blockly-devtools/blob/c79dafac0cd93ac339067a7ed0fa3f59617f75c3/src/controller/project_controller.js#L311)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Missing @return annotation, but it also doesn't look like you're using the return value.
</blockquote></details>

Removed return.

---

*[src/model/block_definition.js, line 61 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-Kqea2lo2Qyqn-jt1Fqq:-Kqeng7c2k-6dGPLTgdZ:b-1h9wwo) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_definition.js#L61)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Per Neil's suggestions, we should avoid getter methods for anything other than constants.
</blockquote></details>

This was mostly a nit type of change--it doesn't affect functionality, but in the case that we ever need to add something on top of setting the name, it would probably be best to keep it consistent with the rest of the model function's `setName()`, since it is inherited from `Resource` anyway.

---

*[src/model/block_library_set.js, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeaHm_3d20LVZ4h_cu:-KqemOC9BjilxaXy1iQk:b9vsh75) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/block_library_set.js#L60)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

oh whoops you're looking for definitions; disregard, but I would rather you use the getBlockDefinitionsMap method or delete it
</blockquote></details>

Oooh, I must have skipped over it bc it wasn't implemented, oops. I put it into getBlockDefinitionsMap().

---

*[src/model/project.js, line 221 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/181#-KqeafhwULBG4wyK8iq0:-Kqemc8XtC35rIFac8V_:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/6bb85a039fd2c0551d311387d5f5345f7dd04386/src/model/project.js#L221)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

use the preexisting library set method (or get rid of it). 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181#-:-KqhliL_PrrdVIw0ZSHj:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3.
Review status: 5 of 8 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/181#-:-KqiEZJPRfST8Wzyyqxp:bnfp4nl)*

**Pull request merged**
