### PR TITLE
Removing the top row of buttons in the WorkspaceEditor.

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Moved the shadow toggle buttons just above the editor workspace.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/229)

### CODE REVIEW

**Comment by svouse** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/229#-:-Kr6ykhd19z3fsW3BMVG:bnfp4nl)*

**Review by svouse — APPROVED** [review]

**Comment by chynu** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/workspace_editor_view.js, line 431 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/229#-Kr6zksEhhM-toiGEbva:-Kr6zksEhhM-toiGEbvb:b3nsppp) ([raw file](https://github.com/google/blockly-devtools/blob/2195194251ff2eddcd4c8fc04c1d41b3d7d569ac/src/view/workspace_editor_view.js#L431)):*
> ```JavaScript
>   </div>
>   <section id="workspace_section">
>     <div style="float: right">
> ```

Nit: I believe the `<aside></aside>` tags are right-floating (defined in `factory.css`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/229#-:-Kr6ziPCJqUpH8P95OK1:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/workspace_editor_view.js, line 431 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/229#-Kr6zksEhhM-toiGEbva:-Kr7-EkdzHCbAMkWvY2P:bt9spet) ([raw file](https://github.com/google/blockly-devtools/blob/2195194251ff2eddcd4c8fc04c1d41b3d7d569ac/src/view/workspace_editor_view.js#L431)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: I believe the `<aside></aside>` tags are right-floating (defined in `factory.css`).
</blockquote></details>

There is a semantic meaning to "aside" that doesn't apply here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/229)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/workspace_editor_view.js, line 431 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/229#-Kr6zksEhhM-toiGEbva:-Kr7-Ktq1NPVKxCkSKGX:b-2q2pk5) ([raw file](https://github.com/google/blockly-devtools/blob/2195194251ff2eddcd4c8fc04c1d41b3d7d569ac/src/view/workspace_editor_view.js#L431)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

There is a semantic meaning to "aside" that doesn't apply here.
</blockquote></details>

(It doesn't apply to the preview, either, for that matter.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/229)*

**Pull request merged**
