### PR TITLE
Workspace contents

### PR DESCRIPTION
**Pull request by svouse**
**Summary:** Updates the methods of WorkspaceContents.

**Goal:** Pair down to reflect former concept as well as required function.

**Specifically Includes:**
- Removal of methods which are unnecessary
-Implementation of remaining methods

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/129)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/workspace_contents.js, line 28 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-KppbEKuoeU8G7pQTNL8:-KppbEKuoeU8G7pQTNL9:b-brbp9w) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L28)):*
> ```JavaScript
> 
> /**
>  * @class Workspacecontents contains a set of positioned blocks
> ```

Nit: `WorkspaceContents` (capital).
Also "and used to initialize an app's workspace" => "to load onto a Blockly workspace upon initialization" ?

---

*[src/model/workspace_contents.js, line 49 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-Kpp_8jdnZcejI5CmPAa:-Kpp_8jdnZcejI5CmPAb:b5785w2) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L49)):*
> ```JavaScript
>     /**
>      * Block types in the project's libraries.
>      * @type {Array.<string>}
> ```

Would it be more useful to have an array of `BlockDefinitions` instead, since a `BlockDefinition` would give more information (e.g. the XML)? That way, if we need the XML of an individual block within this `WorkspaceContents` class we don't need an additional reference to `project` or something in order to access the XML?
(Not entirely sure myself--or even if there is access to the `BlockDefinition`s when `libBlockTypes` is set.

---

*[src/model/workspace_contents.js, line 51 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-Kppb10Gw2ZYIOk6wwbs:-Kppb10Gw2ZYIOk6wwbt:b-eqkrry) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L51)):*
> ```JavaScript
>      * @type {Array.<string>}
>      */
>     this.libBlockTypes = [];
> ```

Also, when would `this.libBlockTypes` be used? I am wondering if having a `has()` function or other access functions might be useful in this case.

---

*[src/model/workspace_contents.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-KppaLo8abfCXX0CfFfy:-KppaLo8abfCXX0CfFfz:bgr7moj) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L97)):*
> ```JavaScript
>     const workspaceContentsJson = $.extend(true, super.getJson(),
>       {'id': PREFIXES.WORKSPACE_CONTENTS});
>     return workspaceContentsJson;
> ```

I think that there may be worth in having the JSON be a field in this class. We can have a `this.json` field that executes the `$.extend()` function within the constructor, so that the jQuery function does not have to be executed every time `getTreeJson()` is called. That way, this function can just be one like that just does `return this.json;`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129)*

**Comment by svouse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/workspace_contents.js, line 28 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-KppbEKuoeU8G7pQTNL8:-KpqAGreev3QGME-dJXX:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L28)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: `WorkspaceContents` (capital).
Also "and used to initialize an app's workspace" => "to load onto a Blockly workspace upon initialization" ?
</blockquote></details>

Done.

---

*[src/model/workspace_contents.js, line 49 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-Kpp_8jdnZcejI5CmPAa:-KpqD7Y2ZFKKBcSbcKJy:b6nxhlj) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L49)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Would it be more useful to have an array of `BlockDefinitions` instead, since a `BlockDefinition` would give more information (e.g. the XML)? That way, if we need the XML of an individual block within this `WorkspaceContents` class we don't need an additional reference to `project` or something in order to access the XML?
(Not entirely sure myself--or even if there is access to the `BlockDefinition`s when `libBlockTypes` is set.
</blockquote></details>

I didn't think so, since then you'd have to deal with updating definitions as they changed, etc. and it felt a little messy

---

*[src/model/workspace_contents.js, line 51 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-Kppb10Gw2ZYIOk6wwbs:-Kpq9yA15S_9U-bncYh9:bss6wtx) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L51)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Also, when would `this.libBlockTypes` be used? I am wondering if having a `has()` function or other access functions might be useful in this case.
</blockquote></details>

Scrapped because it had only been used in the (former) isDefinedBlockType(blockType) method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129)*

**Comment by svouse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_contents.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-KppaLo8abfCXX0CfFfy:-KpveugMI7pvvXMTTID3:b649d9b) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L97)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think that there may be worth in having the JSON be a field in this class. We can have a `this.json` field that executes the `$.extend()` function within the constructor, so that the jQuery function does not have to be executed every time `getTreeJson()` is called. That way, this function can just be one like that just does `return this.json;`.
</blockquote></details>

(Discussed) leaving it for now//can add field if the need arises

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129)*

**Comment by chynu** [comment]
:lgtm: after Very Minor nit.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/workspace_contents.js, line 28 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/129#-KppbEKuoeU8G7pQTNL8:-KprAxjiO74IZlqqjNly:bpc0xit) ([raw file](https://github.com/google/blockly-devtools/blob/1642bbc26eaba1c33a0a7c254e0b42bbfb05a70d/src/model/workspace_contents.js#L28)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

0: I think reviewable isn't updating correctly or maybe you missed a commit q.q

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129#-:-Kpvk_02UtHxI6Bxumkd:b-1bni3t)*

**Comment by AnmAtAnm** [comment]
No references to the deleted methods in other files? If so, :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129#-:-KpvoZSpekeSS_01F9lL:bna1n15)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/129#-:-KpvrURvkr0ZPMnLlYD3:bnfp4nl)*

**Pull request merged**
