### PR TITLE
Toolbox Editor (3/4): Edit categories

### PR DESCRIPTION
**Pull request by chynu**
Can now:
 - Edit a category name
 - Edit a category's color
 - Clear toolbox workspace
 - Reorder categories (up/down arrows)

Cannot:
 - Display shadow blocks properly.
 - Make shadow blocks.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/143)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 359 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq08Q_tsqY0xotV5juI:-Kq08Q_tsqY0xotV5juJ:bodxr2t) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L359)):*
> ```JavaScript
>    */
>   clear() {
>     /**
> ```

Nit: /*

---

*[src/controller/toolbox_controller.js, line 848 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq09axVMryIUYL5l1qu:-Kq09axVMryIUYL5l1qv:b6xsora) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L848)):*
> ```JavaScript
>    */
>   isUserGenShadowBlock(blockId) {
>     // TODO: Move in from wfactory_controller.js
> ```

can we remove this TODO?

---

*[src/controller/toolbox_controller.js, line 1254 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0A99KboX8afv9DI5U:-Kq0A99KboX8afv9DI5V:b4690ww) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L1254)):*
> ```JavaScript
>     }
> 
>     // Return is color is not valid.
> ```

'is'=>'if'?

---

*[src/view/toolbox_editor_view.js, line 225 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0Aa9gzdrz4W-R0o5k:-Kq0Aa9gzdrz4W-R0o5l:b-a0au7s) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/view/toolbox_editor_view.js#L225)):*
> ```JavaScript
>   initClickHandlers_(controller) {
>     // From wfactory_init.js:assignWorkspaceFactoryClickHandlers_()
>     $('#modalShadow').click(() => {
> ```

add a comment for this listener as well?

---

*[src/view/toolbox_editor_view.js, line 516 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq06-WZfhzO9ccywOOo:-Kq06-WZfhzO9ccywOOp:b-xzgd94) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/view/toolbox_editor_view.js#L516)):*
> ```JavaScript
>    * @param {string} id The ID of the category to move.
>    * @param {number} newIndex The index to move the category to.
>    * @param {number} oldIndex The index the category is currently at.
> ```

@throws

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143)*

**Comment by chynu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 359 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq08Q_tsqY0xotV5juI:-Kq0CLFO_Q2w1RIqRRUp:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L359)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: /*
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 848 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq09axVMryIUYL5l1qu:-Kq0CXtmzaFbabH_Bayd:bpp5hvy) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L848)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

can we remove this TODO?
</blockquote></details>

Ooh, right. I marked it as refactored.

---

*[src/controller/toolbox_controller.js, line 1254 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0A99KboX8afv9DI5U:-Kq0Chwla65i3YqhsS9j:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/controller/toolbox_controller.js#L1254)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

'is'=>'if'?
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 225 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0Aa9gzdrz4W-R0o5k:-Kq0Cuq8f9xi57hkfqk2:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/view/toolbox_editor_view.js#L225)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

add a comment for this listener as well?
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 516 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq06-WZfhzO9ccywOOo:-Kq0D9-lflc_iykgKO1S:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0cc6d5739b2038bcd3216af9d7dd27956cb2e8d3/src/view/toolbox_editor_view.js#L516)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

@throws
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143)*

**Comment by svouse** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143#-:-Kq0FYiPYrsHi7mzaaC3:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
One nit, then :lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/factory_utils.js, line 1145 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0JX61ZDWGlVyRaJ1q:-Kq0JX61ZDWGlVyRaJ1r:bj4f1fn) ([raw file](https://github.com/google/blockly-devtools/blob/fa0b39bdf3f770504976a0d1c4061209d2079e6c/src/factory_utils.js#L1145)):*
> ```JavaScript
>  */
> FactoryUtils.isValidHex = function(hex) {
>   const shortHexFormat = /^#[0-9A-F]{3}$/i;
> ```

Move constants out of the function

---

*[src/controller/toolbox_controller.js, line 240 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0IQHdKgAN2lRumDdq:-Kq0IQHdKgAN2lRumDdr:bmx25xy) ([raw file](https://github.com/google/blockly-devtools/blob/fa0b39bdf3f770504976a0d1c4061209d2079e6c/src/controller/toolbox_controller.js#L240)):*
> ```JavaScript
>    * @param {string} promptString Prompt for the user to enter a name.
>    * @param {string=} opt_oldName The current name.
>    * @return {?string} Valid name for a new category, or null if cancelled.
> ```

Optional arguments should always be last. Is this nullable arg optional? If so, name it and annotate it as such. If not, move it up one. (Possible follow-up PR.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143#-:-Kq0LHkl4EaiL-yDgxhK:b296f8f)*

**Comment by chynu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/factory_utils.js, line 1145 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0JX61ZDWGlVyRaJ1q:-Kq0OEGLFz9_G1_m6xtw:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/fa0b39bdf3f770504976a0d1c4061209d2079e6c/src/factory_utils.js#L1145)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Move constants out of the function
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 240 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/143#-Kq0IQHdKgAN2lRumDdq:-Kq0OhpWAa_TWMRiWxZP:bu7l80d) ([raw file](https://github.com/google/blockly-devtools/blob/fa0b39bdf3f770504976a0d1c4061209d2079e6c/src/controller/toolbox_controller.js#L240)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Optional arguments should always be last. Is this nullable arg optional? If so, name it and annotate it as such. If not, move it up one. (Possible follow-up PR.)
</blockquote></details>

(resolved via offline discussion)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143)*

**Comment by AnmAtAnm** [comment]
Still :lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/143#-:-Kq0P35LX5nCBIylikr6:b-dbkjmx)*

**Pull request merged**
