### PR TITLE
Block Editor: Fixing Small Issues

### PR DESCRIPTION
**Pull request by chynu**
Minor changes to make it easier for Sage to do view-side edits.

Still not fixed: block editor workspace collapses text when exiting the new block popup from another editor view ( #137 ).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/144)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/factory_utils.js, line 1221 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0QOCEar23novBdze_:-Kq0QOCFKymWIe8eyLX5:bw2jn47) ([raw file](https://github.com/google/blockly-devtools/blob/520d85aed5e9238681080bcab4a3467aa653d760/src/factory_utils.js#L1221)):*
> ```JavaScript
>  * @param {string} inputType Type of input (statement, value, dummy).
>  * @param {string} blockTypeName Name of block, given by user.
>  * @param {string} opt_blockStarterText Starter text to place on block, given by
> ```

{string=}

---

*[src/controller/block_editor_controller.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0QcT5G8nMnVUDbNc0:-Kq0QcT6QjrhEfMYFwoJ:bw2jn47) ([raw file](https://github.com/google/blockly-devtools/blob/520d85aed5e9238681080bcab4a3467aa653d760/src/controller/block_editor_controller.js#L103)):*
> ```JavaScript
>    * @param {string} inputType Type of input (statement, value, dummy).
>    * @param {string} blockTypeName Name of block, given by user.
>    * @param {string} opt_blockStarterText Starter text to place on block, given
> ```

{string=}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by chynu** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/factory_utils.js, line 1221 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0QOCEar23novBdze_:-Kq0RybcBEzWOm9G6WEo:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/520d85aed5e9238681080bcab4a3467aa653d760/src/factory_utils.js#L1221)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

{string=}
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0QcT5G8nMnVUDbNc0:-Kq0S2Jy9aKHYRFe1c1y:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/520d85aed5e9238681080bcab4a3467aa653d760/src/controller/block_editor_controller.js#L103)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

{string=}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by svouse** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144#-:-Kq0SS3yZf7i7X8azZmY:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/project_controller.js, line 91 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0gSoXTtYSN9duxi21:-Kq0gSoXTtYSN9duxi22:b-yd4kjo) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/controller/project_controller.js#L91)):*
> ```JavaScript
>    * @param {string} blockType Name of the block to add to the project.
>    * @param {!string} libraryName The library to add it to.
>    *
> ```

Nit: Remove line between `@param` and `@return`

---

*[src/model/block_library.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0gegoQyERS_DiwiFi:-Kq0gegoQyERS_DiwiFj:brueqey) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/model/block_library.js#L73)):*
> ```JavaScript
>       types.push(blockType);
>     }
>     return types;
> ```

What is the point of this change? It looks like it does the same thing in more lines.

---

*[src/view/block_editor_view.js, line 45 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0hAZF-QaRssCYmYjs:-Kq0hAZF-QaRssCYmYjt:bj3yrvk) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/view/block_editor_view.js#L45)):*
> ```JavaScript
>    *     BlockDefinition is in.
>    */
>   constructor(blockDefinition, blockLibrary) {
> ```

Why does the block editor _**view**_ need to know about the library?
I don't see it used below, nor would I expect it to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by chynu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/controller/project_controller.js, line 91 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0gSoXTtYSN9duxi21:-Kq3cZhbNaP97E5aWv9w:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/controller/project_controller.js#L91)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: Remove line between `@param` and `@return`
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0gegoQyERS_DiwiFi:-Kq3cfBLBxTflzdfp-ps:bmevm6s) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/model/block_library.js#L73)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

What is the point of this change? It looks like it does the same thing in more lines.
</blockquote></details>

Ohh, this was actually part of an attempt to debug something that had to do with `getBlockTypes()`. It turned out that the loop itself wasn't the issue, but I suppose I forgot to revert the changes here. I changed it back to the original code.

---

*[src/view/block_editor_view.js, line 45 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0hAZF-QaRssCYmYjs:-Kq3dwmGhSaXuERwzzfQ:bcfsftc) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/view/block_editor_view.js#L45)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Why does the block editor _**view**_ need to know about the library?
I don't see it used below, nor would I expect it to be.
</blockquote></details>

When adding a block through the project controller, we need to specify which library it should be added to. Without a "current library" kind of reference, there is no way to tell which library the current BlockDefinition belongs to. I wasn't sure where to place the library, so I put it in the BlockEditorView to be consistent with the "current [ResourceName]" being in the editor views (i.e. the current toolbox is `this.toolbox` in `ToolboxEditorView`, etc.). That being said, it did feel a little strange putting in the library within the view, since it isn't really shown in the editor.

Another thing that we can do is have a dropdown of library choices in the new block popup. Presumably the user would always have to use the new block popup to create a block anyway. Perhaps it is better to remove the blockLibrary reference and use the popup to know which library to add a block to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/block_editor_view.js, line 45 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0hAZF-QaRssCYmYjs:-Kq3oCWKOD3co3fPeh9a:b-ejo7q) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/view/block_editor_view.js#L45)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

When adding a block through the project controller, we need to specify which library it should be added to. Without a "current library" kind of reference, there is no way to tell which library the current BlockDefinition belongs to. I wasn't sure where to place the library, so I put it in the BlockEditorView to be consistent with the "current [ResourceName]" being in the editor views (i.e. the current toolbox is `this.toolbox` in `ToolboxEditorView`, etc.). That being said, it did feel a little strange putting in the library within the view, since it isn't really shown in the editor.

Another thing that we can do is have a dropdown of library choices in the new block popup. Presumably the user would always have to use the new block popup to create a block anyway. Perhaps it is better to remove the blockLibrary reference and use the popup to know which library to add a block to?
</blockquote></details>

But this view is concerned with the block editing.  It shouldn't be responsible for adding it to the project  / library. Allow the _**project**_ controller to add the block to the appropriate place in the _**project**_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by chynu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/block_editor_view.js, line 45 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/144#-Kq0hAZF-QaRssCYmYjs:-Kq3sZHBqQVyJb7yGJHJ:b-g2ulu7) ([raw file](https://github.com/google/blockly-devtools/blob/2a5eb470c8aaf1887eddb2e80f263c6707f8bb31/src/view/block_editor_view.js#L45)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

But this view is concerned with the block editing.  It shouldn't be responsible for adding it to the project  / library. Allow the _**project**_ controller to add the block to the appropriate place in the _**project**_.
</blockquote></details>

I see.. I removed the references to the block library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/144#-:-Kq404xoDHbf7UBGh6t8:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
