### PR TITLE
Toolbox Editor: Multiple Toolboxes & Bug Fixes

### PR DESCRIPTION
**Pull request by chynu**
Can create multiple toolboxes and switch between them in nav tree.
Resolved bug #158.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/172)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/toolbox_controller.js, line 374 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdBREyEntVP8jRJx16:-KqdBREyEntVP8jRJx17:b-hjdl4r) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/controller/toolbox_controller.js#L374)):*
> ```JavaScript
>      */
>     if (!opt_noWarning && !window.confirm('Are you sure you would like to clear ' +
>           'your toolbox editor workspace?')) {
> ```

This toolbox should have a resource name by now, right? I suggesting using it in the user message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/172#-:-KqdCoUk26pVbHLkpznS:bnfp4nl)*

**Comment by chynu** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/toolbox_controller.js, line 374 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdBREyEntVP8jRJx16:-KqdGKBORpju1osX7pv1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/controller/toolbox_controller.js#L374)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This toolbox should have a resource name by now, right? I suggesting using it in the user message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/172)*

**Comment by rachel-fenichel** [comment]
Reviewed 9 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/toolbox.js, line 297 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdH5thGmymvqz8sd5t:-KqdH5thGmymvqz8sd5u:byd41gz) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/model/toolbox.js#L297)):*
> ```JavaScript
>   /**
>    * Adds a custom tag to a category, updating state variables accordingly.
>    * Only accepts 'VARIABLE' and 'PROCEDURE' tags.
> ```

Add a todo on github that this custom tag can now be something other than VARIABLE and PROCEDURE (added in the past year).

---

*[src/view/toolbox_editor_view.js, line 173 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdHOItYN4ZyiWnmTrn:-KqdHOItYN4ZyiWnmTro:bufav5v) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/view/toolbox_editor_view.js#L173)):*
> ```JavaScript
>     Blockly.svgResize(this.previewWorkspace);
> 
>     // TODO: Make editor show the @param toolbox (when user clicks on a
> ```

Remove TODO if it's done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/172)*

**Comment by chynu** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/toolbox.js, line 297 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdH5thGmymvqz8sd5t:-KqdKMSe5cHtguTXdAam:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/model/toolbox.js#L297)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Add a todo on github that this custom tag can now be something other than VARIABLE and PROCEDURE (added in the past year).
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 173 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/172#-KqdHOItYN4ZyiWnmTrn:-KqdM9sY6oQSuN2JvNza:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e57b303425d3d6c03d343bd49e8c09e44c550b73/src/view/toolbox_editor_view.js#L173)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove TODO if it's done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/172)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/172#-:-KqdMRPXoGFQZRMLnHqX:bnfp4nl)*

**Pull request merged**
