### PR TITLE
Continued project implementation

### PR DESCRIPTION
**Pull request by svouse**
Work on projects removal methods and getters (up until and including clearLibrary, line 241 in the raw file). Addition of getTreeJson to resources (as per previous TODO) and the classes which directly extend from them.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/86)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 10 files at r1.
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_library_set.js, line 75 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPcHtgErKnictXD8cp:-KoPcHtgErKnictXD8cq:b-xm7p9z) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L75)):*
> ```JavaScript
>    */
>   getAllBlockTypes() {
>     throw "umimplemented: getAllBlockTypes";
> ```

Spelling of "umimplemented", here and in the rest of the PR.

---

*[src/model/block_library_set.js, line 117 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdWclz0cORShAr6P8:-KoPdWclz0cORShAr6P9:b-55mt0v) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L117)):*
> ```JavaScript
>    * @param {!BlockDefinition} blockDefinition The definition to be removed.
>    */
>   removeBlockDefinitionFromSet(blockDefinition) {
> ```

Either this means that you're doing comparison by comparing the full blockDefinition, or it means that two different blockDefinitions with the same name will both be deleted at the same time.  Is that what you want?

---

*[src/model/project.js, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdAAYaoO43QMEUMN5:-KoPdAAYaoO43QMEUMN6:b-wutckl) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L218)):*
> ```JavaScript
>   removeBlockDefinitionFromComponent(componentType, componentName, definition) {
>     if (componentType === "BlockLibrary") {
>       if(this.librarySet.isOnlyLocationOfBlockDef(componentName, definition)) {
> ```

Nit: space before (

---

*[src/model/project.js, line 224 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdFW5ytjLZrpPxUCe:-KoPdFW5ytjLZrpPxUCf:b-98d45x) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L224)):*
> ```JavaScript
>       }
>     }
>     if (componentType === "Toolbox") {
> ```

else if, here and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by chynu** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/block_library.js, line 204 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPeFrGbcfl3XNjGn8e:-KoPeFrGbcfl3XNjGn8f:bx2fvcb) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library.js#L204)):*
> ```JavaScript
>    * @return {!Object} The tree-specific JSON representation of the library.
>    */
>   getTreeJson() {
> ```

Would this make more sense to belong in the block library controller (or some sort of controller)? BlockLibrary should contain only block definitions and nothing else, I think. (But I could be wrong)

---

*[src/model/block_library_set.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfCLLeUI5tkbJNhOg:-KoPfCLLeUI5tkbJNhOh:behr9o1) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L140)):*
> ```JavaScript
> 
>   /**
>    * Returns whether or not a named library is the only location of a given
> ```

"Returns whether a given blockDefinition is unique to the given library"? Also, does this mean that a blockDefinition can be in multiple libraries? This may create complications with duplicate block names with different definitions.

---

*[src/model/project.js, line 177 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfjqd9jgzSahTtrl8:-KoPfjqd9jgzSahTtrl9:b-b68hkr) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L177)):*
> ```JavaScript
>   /**
>    * Returns a map of all block types in the project to their definitions.
>    * @return {!Object<string, BlockDefinition>} Map of all block types to their
> ```

`{!Object<string, !BlockDefinition>}`? (And below..) Assuming BlockDefinition won't be null.

---

*[src/model/workspace_contents_set.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPhk9HcR8EwBtMkfx2:-KoPhk9HcR8EwBtMkfx3:b-kbcjur) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/workspace_contents_set.js#L83)):*
> ```JavaScript
>    * @param {string} workspaceContentsName The name of the workspace contents
>    *     to remove the definition from.
>    * @param {BlockDefinition} blockDefinition The definition to be removed.
> ```

`{!BlockDefinition}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by AnmAtAnm** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/block_library.js, line 204 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPeFrGbcfl3XNjGn8e:-KoSR2Pn9EHodfwsGLSy:b9v0e6d) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library.js#L204)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Would this make more sense to belong in the block library controller (or some sort of controller)? BlockLibrary should contain only block definitions and nothing else, I think. (But I could be wrong)
</blockquote></details>

Or even the view, since I think the JSON here is very specific to the JSTree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by AnmAtAnm** [comment]
Review status: 2 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/block_library_set.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfCLLeUI5tkbJNhOg:-KoSxBRvl0RaA9dep_Xf:b-hn896c) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L140)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

"Returns whether a given blockDefinition is unique to the given library"? Also, does this mean that a blockDefinition can be in multiple libraries? This may create complications with duplicate block names with different definitions.
</blockquote></details>

`getAllBlockDefinitionsMap()` implies there is only one definition per block type name.  This is probably a reasonable constraint (even if technically allowed by blockly architecture).

---

*[src/model/project.js, line 115 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSwOBLzQ3d6TOpcSYl:-KoSwOBLzQ3d6TOpcSYm:bx86m6e) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L115)):*
> ```JavaScript
>    *     "WorkspaceConfiguration".
>    */
>   hasComponent(componentType, componentName) {
> ```

I feel like simple property getters for each set type (`project.librarySet`, 'project.toolboxSet`, etc.) would allow direct access to the underlying `has(..)` methods, without needing the 'componentType` param and comparisons.

---

*[src/model/project.js, line 216 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSy9I6xQDyV6luCNyn:-KoSy9I6xQDyV6luCNyo:b-b1ugjh) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L216)):*
> ```JavaScript
>    *     "BlockLibrary", "Toolbox", or "WorkspaceContents"
>    */
>   removeBlockDefinitionFromComponent(componentType, componentName, definition) {
> ```

Again, if the caller needs to know the componentType, why not just expect them to call through to the underlying set? `project.librarySet.remove(..)`

Also, toolboxes and WorkspaceContents have blocks, not block definitions. Did you mean to remove all blocks of the given definition?  What would happen to the descendant blocks of such a removed block?

---

*[src/model/toolbox_set.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSzT1cZPK37qM1FEwB:-KoSzT1cZPK37qM1FEwC:b-gtg53b) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/toolbox_set.js#L83)):*
> ```JavaScript
>    * @param {BlockDefinition} blockDefinition The definition to be removed.
>    */
>   removeBlockDefFromToolbox(toolboxName, blockDefinition) {
> ```

As mentioned before, toolboxes don't contain block definitions. Even if you just removed matching blocks, what happens to the descendant blocks of the removed blocks?

---

*[src/model/workspace_contents_set.js, line 85 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSzir2QxS5do5kmk1o:-KoSzir2QxS5do5kmk1p:b-axxjo2) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/workspace_contents_set.js#L85)):*
> ```JavaScript
>    * @param {BlockDefinition} blockDefinition The definition to be removed.
>    */
>   removeBlockDefFromWorkspaceContents(workspaceContentsName, blockDefinition) {
> ```

Workspaces don't contain block definitions. Even if you just removed matching blocks, what happens to the descendant blocks of the removed blocks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by svouse** [comment]
Review status: 2 of 10 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/block_library_set.js, line 75 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPcHtgErKnictXD8cp:-KoPeI3FvYv1nkMZYyOB:b-yo4u1e) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L75)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Spelling of "umimplemented", here and in the rest of the PR.
</blockquote></details>

I bring nothing but shame to Staples High School; fixed.

---

*[src/model/block_library_set.js, line 117 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdWclz0cORShAr6P8:-KoPgJk2j5enNc5VQ7Ci:b24fk7t) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L117)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Either this means that you're doing comparison by comparing the full blockDefinition, or it means that two different blockDefinitions with the same name will both be deleted at the same time.  Is that what you want?
</blockquote></details>

changed to type; added TODO

---

*[src/model/project.js, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdAAYaoO43QMEUMN5:-KoPenEfJdZ__st6hzyD:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L218)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Nit: space before (
</blockquote></details>

Done.

---

*[src/model/project.js, line 224 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPdFW5ytjLZrpPxUCe:-KoPetVKeVWwNZA-f44t:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L224)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

else if, here and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by svouse** [comment]
Review status: 1 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/model/block_library.js, line 204 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPeFrGbcfl3XNjGn8e:-KoTArPjrcffVRUUsFeJ:bazpg39) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library.js#L204)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Or even the view, since I think the JSON here is very specific to the JSTree.
</blockquote></details>

(after our discussions) leaving it for now, but can totally move it at any time if it works better elsewhere

---

*[src/model/block_library_set.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfCLLeUI5tkbJNhOg:-KoTES5GfnE3v3gurTlx:b-naqxbk) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L140)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`getAllBlockDefinitionsMap()` implies there is only one definition per block type name.  This is probably a reasonable constraint (even if technically allowed by blockly architecture).
</blockquote></details>

Yup; I've added TODOs to further define the constraints but am thinking that there'll be one definition per block type (which will certainly have implications for saving, i.e you would either change all blocks of the same type or would have to change your block type- this will probably involve some UI prompting element)

---

*[src/model/project.js, line 115 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSwOBLzQ3d6TOpcSYl:-KoTJLhtoYWuZijRv9ei:b-wwy2bo) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L115)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I feel like simple property getters for each set type (`project.librarySet`, 'project.toolboxSet`, etc.) would allow direct access to the underlying `has(..)` methods, without needing the 'componentType` param and comparisons.
</blockquote></details>

True; fixed

---

*[src/model/project.js, line 177 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfjqd9jgzSahTtrl8:-KoTHsnshZ9CUbZ-ZdT1:bss68o7) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L177)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`{!Object<string, !BlockDefinition>}`? (And below..) Assuming BlockDefinition won't be null.
</blockquote></details>

I dig it//fixed; I'm assuming it won't be//will take explicit steps such that it wont be

---

*[src/model/project.js, line 216 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSy9I6xQDyV6luCNyn:-KoTHiw7u_1AzWzm_Qi8:b-ua9wkk) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/project.js#L216)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Again, if the caller needs to know the componentType, why not just expect them to call through to the underlying set? `project.librarySet.remove(..)`

Also, toolboxes and WorkspaceContents have blocks, not block definitions. Did you mean to remove all blocks of the given definition?  What would happen to the descendant blocks of such a removed block?
</blockquote></details>

Fixed. 

Changed to type (added a TODO for descendants, but I think they should be removed, too?)

---

*[src/model/toolbox_set.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSzT1cZPK37qM1FEwB:-KoTGj2lPWzekODM9Zqe:b-hzq7gx) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/toolbox_set.js#L83)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

As mentioned before, toolboxes don't contain block definitions. Even if you just removed matching blocks, what happens to the descendant blocks of the removed blocks?
</blockquote></details>

Changed to type (and same inclination in above comment)

---

*[src/model/workspace_contents_set.js, line 83 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPhk9HcR8EwBtMkfx2:-KoTG-e1Eo8M18QUQWP7:bgeoq6m) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/workspace_contents_set.js#L83)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`{!BlockDefinition}`?
</blockquote></details>

Changed to type

---

*[src/model/workspace_contents_set.js, line 85 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoSzir2QxS5do5kmk1o:-KoTG1zgNb_q3Bwc7nme:b-hzq7gx) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/workspace_contents_set.js#L85)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Workspaces don't contain block definitions. Even if you just removed matching blocks, what happens to the descendant blocks of the removed blocks?
</blockquote></details>

Changed to type (and same inclination in above comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/block_library_set.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfCLLeUI5tkbJNhOg:-KoTKyhNVyzcu0P5iXVV:b6r7ksk) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L140)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Yup; I've added TODOs to further define the constraints but am thinking that there'll be one definition per block type (which will certainly have implications for saving, i.e you would either change all blocks of the same type or would have to change your block type- this will probably involve some UI prompting element)
</blockquote></details>

If we agree upon that constraint, does this function need to exist?

---

*[src/model/toolbox_set.js, line 73 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoTLwvHamhbFW9sNVZE:-KoTLwvHamhbFW9sNVZF:b-clmsyh) ([raw file](https://github.com/google/blockly-devtools/blob/84d047c31bd5a398fd2dcaedad9cf3d5625087f9/src/model/toolbox_set.js#L73)):*
> ```JavaScript
>    * @param {string} blockType The name of the block to remove.
>    */
>   removeBlockFromSet(blockDefinition) {
> ```

s/blockDefinition/blockType/ in declaration.

---

*[src/model/workspace_contents_set.js, line 75 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoTM2lonmbkH6yFkV4y:-KoTM2lonmbkH6yFkV4z:b-2p4cm1) ([raw file](https://github.com/google/blockly-devtools/blob/84d047c31bd5a398fd2dcaedad9cf3d5625087f9/src/model/workspace_contents_set.js#L75)):*
> ```JavaScript
>    * @param {string} blockType The name of the block to remove.
>    */
>   removeBlockFromSet(blockDefinition) {
> ```

s/blockDefinition/blockType/ in declaration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by svouse** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/block_library_set.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoPfCLLeUI5tkbJNhOg:-KoTTcqEF7lIIifE-oyx:bwgwmsb) ([raw file](https://github.com/google/blockly-devtools/blob/fb40e3b62be005036386bf52e8089494ef6505f5/src/model/block_library_set.js#L140)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

If we agree upon that constraint, does this function need to exist?
</blockquote></details>

I suppose I was inclined to keep it because in the event that you're trying to remove a block of a specified type from a single library, in the event that that library is the only owner of that block (rather than copies of it existing in other libraries) doesn't that mean you'd have to remove it from the project?

---

*[src/model/toolbox_set.js, line 73 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoTLwvHamhbFW9sNVZE:-KoTSnbH3wRor8OKh57s:b-n7glqd) ([raw file](https://github.com/google/blockly-devtools/blob/84d047c31bd5a398fd2dcaedad9cf3d5625087f9/src/model/toolbox_set.js#L73)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

s/blockDefinition/blockType/ in declaration.
</blockquote></details>

Fixed (here and in other files)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by svouse** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/workspace_contents_set.js, line 75 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/86#-KoTM2lonmbkH6yFkV4y:-KoTUnVVNeF1NRQedPe2:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/84d047c31bd5a398fd2dcaedad9cf3d5625087f9/src/model/workspace_contents_set.js#L75)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

s/blockDefinition/blockType/ in declaration
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/86#-:-KoTVJSmj5h70-iCLA6p:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
