### PR TITLE
Add button click handlers

### PR DESCRIPTION
**Pull request by svouse**
Adds click handlers for add button flyout. Currently being used for testing, thus hooked up to add elements by test names and switch to appropriate tab.
NOTE: Adding blocks doesn't work (pending restructuring of editor handling of libraries)

Upcoming development: saving these test elements to local storage, starting with toolbox

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/145)

### CODE REVIEW

**Comment by chynu** [comment]
One comment (not Necessary(TM) for this PR). Otherwise, :lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/app_view.js, line 455 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0WAn_FM6G_B3vMMbR:-Kq0WAn_FM6G_B3vMMbS:b-7m7uj1) ([raw file](https://github.com/google/blockly-devtools/blob/fe5cb6984c93dde40bb5bc74be73dc182423fa5d/src/view/app_view.js#L455)):*
> ```JavaScript
>     $('#addBlock').click(() => {
>       // TODO: prompt for name
>       this.appController.projectController.createBlockDefinition('test_block',
> ```

I think maybe also calling
```JavaScript
this.appController.editorController.switchEditor( /* relevant editor controller */ );
this.switchView( /* relevant editor view */ );
```
so that the editors switch along with the "add" function may be a good idea.

You probably would also have to set the view class's pointers to the model object (e.g. for `BlockEditorView`, it would be `this.blockDefinition`) to the newly created resource, as well?

(Not sure if this PR was supposed to cover these functionalities though)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145#-:-Kq0XIG2W6rlTCvjCfUF:btchuay)*

**Comment by svouse** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/app_view.js, line 455 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0WAn_FM6G_B3vMMbR:-Kq0YFLKk9n2mXEAnP2H:b57wpcv) ([raw file](https://github.com/google/blockly-devtools/blob/fe5cb6984c93dde40bb5bc74be73dc182423fa5d/src/view/app_view.js#L455)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think maybe also calling
```JavaScript
this.appController.editorController.switchEditor( /* relevant editor controller */ );
this.switchView( /* relevant editor view */ );
```
so that the editors switch along with the "add" function may be a good idea.

You probably would also have to set the view class's pointers to the model object (e.g. for `BlockEditorView`, it would be `this.blockDefinition`) to the newly created resource, as well?

(Not sure if this PR was supposed to cover these functionalities though)
</blockquote></details>

I dig it nonetheless; this is something I was planning to do/had to put in, anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by chynu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/app_view.js, line 457 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0dg-OXuT_dV9w2Bt0:-Kq0dg-OXuT_dV9w2Bt1:b-cz5a3f) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L457)):*
> ```JavaScript
>       const block = this.appController.projectController.createBlockDefinition(
>           'test_block','test_library');
>       this.appController.editorController.switchEditor(this);
> ```

Did you mean to pass in `this` as the parameter? I believe it should be `this.appController.editorController.blockEditorController`?

---

*[src/view/app_view.js, line 466 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0eGy7Sa8Uy0G24e-3:-Kq0eGy7Sa8Uy0G24e-4:b-uv64i3) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L466)):*
> ```JavaScript
>       const library = this.appController.projectController.createBlockLibrary(
>           'test_library');
>       this.appController.editorController.switchEditor();
> ```

Same comment/param as above (since block editor deals with both libraries and block definitions)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by chynu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/app_view.js, line 457 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0dg-OXuT_dV9w2Bt0:-Kq3mkqm6Oq25cAeSjnl:boo16v7) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L457)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Did you mean to pass in `this` as the parameter? I believe it should be `this.appController.editorController.blockEditorController`?
</blockquote></details>

(Just remembered but you should probably also have a line that creates a new block popup after you switch)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by chynu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/app_view.js, line 452 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq3n3YbNDIWO3a7TBrx:-Kq3n3YbNDIWO3a7TBry:b-v1tgd) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L452)):*
> ```JavaScript
>    * Assigns button click handlers for add button flyout.
>    */
>   assignAddFlyoutClickHandlers() {
> ```

It might be a good idea to make `$('#modalShadow')` visible while you have `$('#addOptions')` open, so that you can also add a listener to the modal shadow to hide the add options flyout on click (i.e. when you click outside of the flyout, make the flyout hidden).

---

*[src/view/app_view.js, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq3oYTjlEQq1QmweI3L:-Kq3oYTjlEQq1QmweI3M:b-jop9m6) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L459)):*
> ```JavaScript
>       this.appController.editorController.switchEditor(this);
>       this.switchView(this.blockEditorView);
>       this.blockEditorView.block = block;
> ```

It also might be a good idea to have a line that closes the flyout after you switch, here and below (for the other add clicks).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/app_view.js, line 452 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq3n3YbNDIWO3a7TBrx:-Kq4EMMOlSoPDtJd2v_T:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L452)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

It might be a good idea to make `$('#modalShadow')` visible while you have `$('#addOptions')` open, so that you can also add a listener to the modal shadow to hide the add options flyout on click (i.e. when you click outside of the flyout, make the flyout hidden).
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 457 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0dg-OXuT_dV9w2Bt0:-Kq3xXvK0llQ5_HyZbvu:b-mc8587) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L457)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

(Just remembered but you should probably also have a line that creates a new block popup after you switch)
</blockquote></details>

whoops yup; fixed and done

---

*[src/view/app_view.js, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq3oYTjlEQq1QmweI3L:-Kq4CCelpuMsYTE3tF4U:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L459)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

It also might be a good idea to have a line that closes the flyout after you switch, here and below (for the other add clicks).
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 466 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0eGy7Sa8Uy0G24e-3:-Kq4UAwVH_zFrPo21GJZ:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L466)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Same comment/param as above (since block editor deals with both libraries and block definitions)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/app_view.js, line 466 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0eGy7Sa8Uy0G24e-3:-Kq4Vcqj2ATCUqqZqOU9:byb76e4) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L466)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we need the new block popup for adding a library? This can do for now, but in the end I believe we will probably have a different UI for users to add libraries (probably just a different popup or a `window.prompt()`).

---

*[src/view/app_view.js, line 447 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4VKf5-WB1YwskS79g:-Kq4VKf5-WB1YwskS79h:bf3zh25) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L447)):*
> ```JavaScript
>     $('#modalShadow').click(() => {
>       FactoryUtils.closeModal(this.modalId_);
>       this.modalId_ = null;
> ```

I think you need to add `this.addFlyoutOpen = false;`. Otherwise there is a tiny bug in which, if you cancel out of the flyout by clicking on the modal shadow (and not the plus sign), you have to click on the add button twice in order for the flyout to open again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/view/app_view.js, line 463 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4bn1S01_PmLGlQgsz:-Kq4bn1S01_PmLGlQgt-:bej7gm1) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L463)):*
> ```JavaScript
> 
>     $('#addLibrary').click(() => {
>       // TODO: prompt for name
> ```

The name can be part of the popup.

---

*[src/view/app_view.js, line 466 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4c-Wd1KhPzRcszOPv:-Kq4c-Wd1KhPzRcszOPw:b-w3jpaj) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L466)):*
> ```JavaScript
>       const library = this.appController.projectController.createBlockLibrary(
>           'test_library');
>       const block = this.appController.projectController.createBlockDefinition(
> ```

Seems weird to click on create library and seeing a create block pop-up. I wonder if libraries should be created in other ways (when saving, copying, or moving blocks).

Good for now as we begin use testing.

---

*[src/view/app_view.js, line 468 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4csx6ZNncv4bWS_JM:-Kq4csx6ZNncv4bWS_JN:b-4kr9yq) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L468)):*
> ```JavaScript
>       const block = this.appController.projectController.createBlockDefinition(
>           'test_block','test_library');
>       this.switchEnvironment('block', block);
> ```

I think the project controller should call `switchEnvironment(..)` as a result of one of the above calls.  Same in the following click handlers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by AnmAtAnm** [comment]
Move the call to `swtichEnvironment(..)` and then :lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145#-:-Kq4dgNDMJxV5b336OGW:bxfxn9o)*

**Comment by svouse** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/app_view.js, line 466 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq0eGy7Sa8Uy0G24e-3:-Kq4WRugSU1NKqIKeCM6:b-9ncev2) ([raw file](https://github.com/google/blockly-devtools/blob/e1a076dfbd335dc006360da344158b60be19fd75/src/view/app_view.js#L466)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Do we need the new block popup for adding a library? This can do for now, but in the end I believe we will probably have a different UI for users to add libraries (probably just a different popup or a `window.prompt()`).
</blockquote></details>


I figured for now we'd have it since we don't have such an interface//a block will have to be created for a library, anyway

---

*[src/view/app_view.js, line 447 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4VKf5-WB1YwskS79g:-Kq4WOmOSebAUlaboYl8:b-gg81io) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L447)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think you need to add `this.addFlyoutOpen = false;`. Otherwise there is a tiny bug in which, if you cancel out of the flyout by clicking on the modal shadow (and not the plus sign), you have to click on the add button twice in order for the flyout to open again.
</blockquote></details>

True; good catch

---

*[src/view/app_view.js, line 468 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq4csx6ZNncv4bWS_JM:-Kq58pyeM6cH947nsVK5:b-gs7dt4) ([raw file](https://github.com/google/blockly-devtools/blob/2d09fc62443dcafd0580150e4dbe0f31399d407a/src/view/app_view.js#L468)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I think the project controller should call `switchEnvironment(..)` as a result of one of the above calls.  Same in the following click handlers.
</blockquote></details>

Done. (in AppController)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by AnmAtAnm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/app_controller.js, line 301 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq9HE3wMy53hBB1i5lo:-Kq9HE3wMy53hBB1i5lp:bwracl1) ([raw file](https://github.com/google/blockly-devtools/blob/e4490c41ef38bc9fe67241318018f662c88228f0/src/controller/app_controller.js#L301)):*
> ```JavaScript
>    */
>   createLibrary() {
>     // TODO: prompt for name, define behavior
> ```

Put this TODO on the controller side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/app_controller.js, line 301 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq9HE3wMy53hBB1i5lo:-Kq9HIcNmNN65CLw7zn4:b-qt1b9c) ([raw file](https://github.com/google/blockly-devtools/blob/e4490c41ef38bc9fe67241318018f662c88228f0/src/controller/app_controller.js#L301)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Put this TODO on the controller side.
</blockquote></details>

Err... the "prompt for name" part.

---

*[src/controller/app_controller.js, line 311 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/145#-Kq9HKoIY8TohEqRifix:-Kq9HKoIY8TohEqRifiy:brhumzt) ([raw file](https://github.com/google/blockly-devtools/blob/e4490c41ef38bc9fe67241318018f662c88228f0/src/controller/app_controller.js#L311)):*
> ```JavaScript
>    */
>   createToolbox() {
>     // TODO: prompt for name
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/145)*

**Pull request merged**
