### PR TITLE
Refactor: Fixing Dependencies

### PR DESCRIPTION
**Pull request by chynu**
Summary: fixed dependencies to make app run with less unexpected errors (still does not run fully).
 - Reordered a bunch of import statements in `all_libs_classes_stylesheets.js`.
 - Reordered lines in constructors (mostly `AppController2`).
 - Added `goog.provide` and `goog.require` to all new refactor files.

Also: fixed minor syntax errors encountered along the way that made the app break.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/102)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 28 files reviewed at latest revision, 19 unresolved discussions.

---

*[app.html, line 10 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyHWbCkFaVweWCebHo:-KoyHWbCkFaVweWCebHp:btohjnm) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L10)):*
> ```HTML
>     let blocklyFactory;
>     window.addEventListener('load', () => {
>       blocklyFactory = new AppController2();
> ```

General question//not an issue in this PR: when do we intend to just use AppController2 as AppControlller? I'm assuming after everything's moved?

---

*[app.html, line 23 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyH90_U5_1-ihZ1ooT:-KoyH90_U5_1-ihZ1ooU:b1ftbv2) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L23)):*
> ```HTML
>   <div id="tabContainer">
>     <div id="blockFactory_tab" class="tab tabon">Block Editor</div>
>     
> ```

Nit: Maybe tie to issue # for organization?

---

*[app.html, line 402 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyHJUgfCGyhZ_OH37f:-KoyHJUgfCGyhZ_OH37g:b-ya81ng) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L402)):*
> ```HTML
>    <div id="navigationTree"></div>
> 
>

**Comment by chynu** [comment]
Review status: 0 of 28 files reviewed at latest revision, 19 unresolved discussions.

---

*[app.html, line 10 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyHWbCkFaVweWCebHo:-KoyXja7rN8RHUdWf-9k:b-84z6jm) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L10)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

General question//not an issue in this PR: when do we intend to just use AppController2 as AppControlller? I'm assuming after everything's moved?
</blockquote></details>

I'm thinking of doing it in my next PR. Right now I'm also working on making the app work normally again and I'll rename it to `AppController` then.

---

*[app.html, line 23 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyH90_U5_1-ihZ1ooT:-KoyYANYK3DTUl_vrSOO:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L23)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: Maybe tie to issue # for organization?
</blockquote></details>

Done.

---

*[app.html, line 402 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyHJUgfCGyhZ_OH37f:-KoyYKk_S1IIiTJrIepU:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/app.html#L402)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/controller/app_controller_2.js, line 42 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyKPXN938DAwLqmGeq:-KoyYMTIstohaCbFv3Oe:bfv0pel) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/app_controller_2.js#L42)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

This'll need NavigationTree depending on the course of #101 but looks good for now
</blockquote></details>

Okay, I'll let you add that once this PR goes through so that we can just put more `goog.require`s as we add more dependencies.

---

*[src/controller/app_controller_2.js, line 49 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyW89STJZXv2BDz3XL:-KoyYWXRRDI7hUTWcuj7:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/app_controller_2.js#L49)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 37 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyWEzkIv4PpOnc3zGL:-KoyZNGS1K-kSrIzRWjI:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/block_editor_controller.js#L37)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/controller/editor_controller.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyVeuttYJR8g17SCNM:-KoyZ_3ZSxSYMoBxlP08:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/editor_controller.js#L33)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/controller/editor_controller.js, line 107 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyM5OmGZkJUWcTKOuX:-KoycCo2CZ7wXBWipI68:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/editor_controller.js#L107)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Could use for..of since index isn't being used
</blockquote></details>

Done.

---

*[src/controller/popup_controller.js, line 35 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyWLOrsvY-eO0ZxzON:-Koya3SjBDq0Kdu0QHBi:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/controller/popup_controller.js#L35)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/model/project.js, line 29 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyNr1i0tVHvB8msUAL:-Koya7d2qfR3EGydDvt7:b-b8jhqd) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/model/project.js#L29)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Project also requires Resource
</blockquote></details>

Good catch -- thanks!

---

*[src/view/app_view.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyOiSksxZ-Rjhcglyj:-KoyaAvSBGK5iToHVjhh:bs3zea1) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/app_view.js#L33)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

AppView doesn't need the tree anymore (again this is another post #101 thing, but is certain), but for this PR this makes sense
</blockquote></details>

Okay! I'll leave it here for now to keep things consistent within this PR but we can adjust once this goes through.

---

*[src/view/app_view.js, line 179 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyQQcjEYsMyAv7OskN:-KoyaYMd7gzdPP41Vgq5:b-ictjye) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/app_view.js#L179)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Can you elaborate on the temporary nature of this//add a TODO for concision? 
</blockquote></details>

Oh oops, this function is no longer necessary. I removed it.

---

*[src/view/block_editor_view.js, line 31 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyRGRePfn3a-nsrv82:-KoyayYU7UG2zP5SeKBm:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/block_editor_view.js#L31)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

requires BlockDefinition
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 24 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyRTlzRfSnhX_KNl-G:-Koyb-SpbvawIG7UuZyt:b-h0fvae) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/navigation_tree.js#L24)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

requires Project (post #101 will also require AppController, but as of this version still requires Project)
</blockquote></details>

Added Project.

---

*[src/view/toolbox_editor_view.js, line 36 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyVA1FKR1dNmNPMLBO:-KoybEYG1PSnAtN_r232:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/toolbox_editor_view.js#L36)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyTj5muIAy4MLX-3xf:-KoybYKqtuVIK4gxq12H:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_editor_view.js#L34)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: JSDoc for the constructor (mostly just to read param types without having to look inside)
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 112 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyTYgYR_qOuZmXSPru:-KoybiuFdg9tcOncoUQ7:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_editor_view.js#L112)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: add unimplemented throw
</blockquote></details>

Done.

---

*[src/view/workspace_preview_view.js, line 36 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyVW46DfQBcY60rCJg:-KoybxjH66b1c7G8mDAl:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_preview_view.js#L36)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JSDoc
</blockquote></details>

Done.

---

*[src/view/workspace_preview_view.js, line 45 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyT69-ObcEFGXg-wBQ:-Koyc-nZZfPMfBI99dfq:b-67fi5z) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_preview_view.js#L45)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: indent
</blockquote></details>

Since this is a multiline string, the funky indendation was actually on purpose to maintain the indentation within the HTML.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102)*

**Comment by svouse** [comment]
*[src/view/workspace_preview_view.js, line 45 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyT69-ObcEFGXg-wBQ:-KoydtPHy2xauTGMpnJe:b-wzpso) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_preview_view.js#L45)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Since this is a multiline string, the funky indendation was actually on purpose to maintain the indentation within the HTML.
</blockquote></details>

Rip cool sorry about that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102)*

**Comment by chynu** [comment]
Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/workspace_preview_view.js, line 45 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyT69-ObcEFGXg-wBQ:-KoyeqO0aoHqsZMoJfYG:bwpi9os) ([raw file](https://github.com/google/blockly-devtools/blob/366b1a11bd18422f1e165812a0a078e5f7aed9ec/src/view/workspace_preview_view.js#L45)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Rip cool sorry about that
</blockquote></details>

Haha, it's no problem! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102)*

**Comment by AnmAtAnm** [comment]
Correct the indent in the `.html`, and then maybe two other details. Then :lgtm: !

---

Reviewed 15 of 28 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app.html, line 8 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-Koyg8-immZJTHtQXcdG:-Koyg8-immZJTHtQXcdH:b-2ciwtx) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/app.html#L8)):*
> ```HTML
>   <script src="src/all_libs_classes_stylesheets.js"></script>
>   <script>
>     let blocklyFactory;
> ```

Might want to test if this can be renamed.

---

*[app.html, line 407 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-Koyg6ArGlTYlTmLJznK:-Koyg6ArGlTYlTmLJznL:bl08sqv) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/app.html#L407)):*
> ```HTML
>               Blockly.inject(). -->
>    <div style="display:none;">
>     <div id="toolboxDiv"></div>
> ```

Correct indent.

---

*[res/devtools_toolboxes.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoygMbeeFvGURiFoD1O:-KoygMbeeFvGURiFoD1P:b8exbt) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/res/devtools_toolboxes.js#L57)):*
> ```JavaScript
>   const blockLibraryXmls = '';
>   // If null, no additional library category is created.
>   if (blockLibraryList !== null || blockLibraryList !== undefined) {
> ```

Simply `if (blockLibraryList)` should work for objects and arrays.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102#-:-Koyi62lNwGX_JQmyS5k:b9rk6z1)*

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/view/toolbox_editor_view.js, line 26 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyhmUjI_vOHGURVG1E:-KoyhmUjI_vOHGURVG1F:bcr4elx) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/src/view/toolbox_editor_view.js#L26)):*
> ```JavaScript
> 
> goog.require('FactoryUtils');
> ```

Also Requires Toolbox

---

*[src/view/workspace_editor_view.js, line 24 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyhsYCpe-NTFPhQL09:-KoyhsYCpe-NTFPhQL0A:b-7qgq1k) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/src/view/workspace_editor_view.js#L24)):*
> ```JavaScript
> 
> goog.provide('WorkspaceEditorView');
> ```

Requires WorkspaceContents and WorkspaceConfiguration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102)*

**Comment by chynu** [comment]
Review status: 23 of 28 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[app.html, line 8 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-Koyg8-immZJTHtQXcdG:-KoykRzWCAjVUa1hE_zk:b9bh2g3) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/app.html#L8)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Might want to test if this can be renamed.
</blockquote></details>

Renamed to `DevTools` and it still works!

---

*[app.html, line 407 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-Koyg6ArGlTYlTmLJznK:-KoykUMSt-yKBS6ckv5X:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/app.html#L407)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Correct indent.
</blockquote></details>

Done.

---

*[res/devtools_toolboxes.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoygMbeeFvGURiFoD1O:-KoykV-ITmMfqCZs1RR1:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/res/devtools_toolboxes.js#L57)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Simply `if (blockLibraryList)` should work for objects and arrays.
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 26 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyhmUjI_vOHGURVG1E:-Koyk_0lsi77wFJj9clt:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/src/view/toolbox_editor_view.js#L26)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Also Requires Toolbox
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 24 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/102#-KoyhsYCpe-NTFPhQL09:-KoykeqMJguElAfudMJb:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3700102a13733a8fbe42c86b797aabcee742d732/src/view/workspace_editor_view.js#L24)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Requires WorkspaceContents and WorkspaceConfiguration
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/102)*

**Review by svouse — APPROVED** [review]
Solid; LGTM

**Pull request merged**
