### PR TITLE
Saving

### PR DESCRIPTION
**Pull request by svouse**
- Changes the saving UI such that you can choose multiple directory locations
- Creates the ReadWriteController, where the rest of my resource-specific methods are going

(for all of these upcoming ones I'm shooting to break them down in bits of ~100 lines or so)
Next PR:
- Implementing the data creation in model
- Making project directory actually required (you'll note that my code is written with the requirement that it is, but the only thing that currently suggests so is a red *. That's bad)

The one after it:
- Implementing writing files for the different resource types on the controller level
(This PR signals the official end of saving)

The ones after that: Reading

Reading 1:
- Implement the required ReadWriteController functions, with error handling

Reading 2:
- Hook up reading such that it's part of loading the initial app

Reading 3:
- Creating a v basic UI for importing (hooked up to the menu)

That about sums up my evening/pre tomorrow demo plans

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/167)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_Nqsed5OZRtQsG33M:-Kq_Nqsed5OZRtQsG33N:bhu117l) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L88)):*
> ```JavaScript
>      * @type {?string}
>      */
>     this.hasSaved = localStorage.getItem('hasSavedProjectBefore');
> ```

Perhaps a better concept could be 

---

*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-Kq_SKVF2sG1SxqtGM23:bsa4t2r) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
> ```JavaScript
> 	<form>
>     Project<span class="red">*</span>
>       <input type="file" nwdirectory id="projectDirectory"></input><br><br>
> ```

Hm, how would the user be able to configure where exactly the sub-resources are saved if the project folder hasn't been created yet? I see that it is optional. Does this mean that the optional file locations are when a user wants to save the resources outside of the project folder?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by chynu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_Nqsed5OZRtQsG33M:-Kq_TGMYr3EuWIcUSoUv:b7lmdar) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L88)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Perhaps a better concept could be 
</blockquote></details>

er, please ignore this comment he he.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/save_project_popup_controller.js, line 64 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_TU_epA6Sb3S9sKkZ:-Kq_TU_epA6Sb3S9sKk_:big4zc7) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/save_project_popup_controller.js#L64)):*
> ```JavaScript
>     this.view.on('submit', () => {
>       // Save location for each directory, or, if none chosen, set a default.
>       for (let directory of Object.getOwnPropertyNames(DIRECTORIES)) {
> ```

Is this another place where you should be using Object.create(null)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by svouse** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_Nqsed5OZRtQsG33M:-Kq_U4yGdbbo-zzeAMQB:bdeavht) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L88)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

er, please ignore this comment he he.
</blockquote></details>

:fire: 

---

*[src/controller/save_project_popup_controller.js, line 64 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_TU_epA6Sb3S9sKkZ:-Kq_UBoIxDb7gtBqEZWK:boqf9oz) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/save_project_popup_controller.js#L64)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Is this another place where you should be using Object.create(null)?
</blockquote></details>

Definitely feels like it; I suppose I was wondering how I'd do so but still be able to define a class with static getters and whatnot? I like the convenience/clarity of its declaration, but inheritance is the pits/it feels sloppy to work around it like I do. 

---

*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-Kq_TWrKyz6gBq8MuUuq:b-o3are9) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Hm, how would the user be able to configure where exactly the sub-resources are saved if the project folder hasn't been created yet? I see that it is optional. Does this mean that the optional file locations are when a user wants to save the resources outside of the project folder?
</blockquote></details>

Yup :ok_hand: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by chynu** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-Kq_UuXBaQk9Uy4FNW5S:badmmb1) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Yup :ok_hand: 
</blockquote></details>

Hm, I think it would be useful to have some sort of help text there, then, since it is rather unclear as of now what the other three mean.

In the interest of time this isn't a priority, but it probably would be even better to make this a part of a second popup view that you only see when you click a button along the lines of "save in separate places" or something. 0:

:fried_egg:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by svouse** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-Kq_VbfLezHuQpfUJyzy:b-ohf7am) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Hm, I think it would be useful to have some sort of help text there, then, since it is rather unclear as of now what the other three mean.

In the interest of time this isn't a priority, but it probably would be even better to make this a part of a second popup view that you only see when you click a button along the lines of "save in separate places" or something. 0:

:fried_egg:
</blockquote></details>

sgtm! Added issue #170 ; feel free to add any comments about things I should add to the comment and whatnot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_VzjunUa6fkPBNmgv:-Kq_VzjunUa6fkPBNmgw:b-6w5ehp) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L86)):*
> ```JavaScript
>     /**
>      * Whether or not the user has saved before.
>      * @type {?string}
> ```

Boolean

---

*[src/controller/read_write_controller.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_W4Lm9YovcjEiZNMl:-Kq_W4Lm9YovcjEiZNMm:b-ma2ca3) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L103)):*
> ```JavaScript
>    * Creates the properly nested directory in which to save the project.
>    * @param {!string} directory The resource directory to check (must be one of
>    * the get methods in DIRECTORIES)
> ```

indent +4 spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-Kq_X0OsFEbyxmvaj60e:bvee7sm) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

sgtm! Added issue #170 ; feel free to add any comments about things I should add to the comment and whatnot
</blockquote></details>

wait o i meant for the user, so that they don't get confused about it. though documentation in code is also important as well (!!). just a sentence or something along the lines of "optional: saving library/whatever outside of project folder"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_XoDjVpP4bXI-PTqq:-Kq_XoDjVpP4bXI-PTqr:b1ifrze) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L97)):*
> ```JavaScript
>     delete DIRECTORIES.name;
>     delete DIRECTORY_LOCAL_STORAGE_KEYS.length;
>     delete DIRECTORY_LOCAL_STORAGE_KEYS.name;
> ```

Remove these.  They seem sketchy and I'm not sure they will work everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by svouse** [comment]
*[src/view/save_project_popup_view.js, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_SKVF2sG1SxqtGM22:-KqcdF51vgOMAXDFlerl:br23lky) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/view/save_project_popup_view.js#L50)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

wait o i meant for the user, so that they don't get confused about it. though documentation in code is also important as well (!!). just a sentence or something along the lines of "optional: saving library/whatever outside of project folder"?
</blockquote></details>

Oh cool I totally agree; that's in post-today plans

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by svouse** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_VzjunUa6fkPBNmgv:-Kq_Xz95EhZ7-pVJotgW:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L86)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Boolean
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_XoDjVpP4bXI-PTqq:-Kq_XzcJkZifDoK9I_vN:b-m7eywu) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L97)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Remove these.  They seem sketchy and I'm not sure they will work everywhere.
</blockquote></details>

Done. (Also per our discussion I've switched to using maps)

---

*[src/controller/read_write_controller.js, line 103 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_W4Lm9YovcjEiZNMl:-Kq_Y-Stqo9UQHn_OyFL:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L103)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

indent +4 spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by svouse** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kq_XoDjVpP4bXI-PTqq:-KqcdLBSzVkl-dbz8YIG:btdehhe) ([raw file](https://github.com/google/blockly-devtools/blob/090087f47a29cd39b2371b6b71dcf2f5f0b2d8b4/src/controller/read_write_controller.js#L97)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done. (Also per our discussion I've switched to using maps)
</blockquote></details>

* a map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kqciz0t4smIdambLRN3:-Kqciz0t4smIdambLRN4:b9ehti7) ([raw file](https://github.com/google/blockly-devtools/blob/593af04f2de2b853a7c199efb85546206b5944b8/src/controller/read_write_controller.js#L106)):*
> ```JavaScript
>    */
>   saveBlock() {
>     //TODO: fill in
> ```

smol nit: `console.warn()` for unimplemented void functions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167#-:-Kqcito9I9XL3QmEv60S:bnfp4nl)*

**Review by chynu — APPROVED** [review]

**Comment by AnmAtAnm** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/save_project_popup_controller.js, line 78 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/167#-KqcuFQ4DdeSNsFFDAsp:-KqcuFQ4DdeSNsFFDAsq:bn44hp8) ([raw file](https://github.com/google/blockly-devtools/blob/593af04f2de2b853a7c199efb85546206b5944b8/src/controller/save_project_popup_controller.js#L78)):*
> ```JavaScript
>            * directory of the same name as the local storage tag under the
>            * directory specified for the project.
>            */
> ```

Indent this comment to match the block it is within.
My personal preference is to use multiple `//` on anything that isn't a documentation comment (multiple if need be, like here), so that the documentation stands out.  Your call.

---

*[src/view/save_project_popup_view.js, line 56 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/167#-KqcugQL86ttaRfTf6AD:-KqcugQL86ttaRfTf6AE:b-90c2vh) ([raw file](https://github.com/google/blockly-devtools/blob/593af04f2de2b853a7c199efb85546206b5944b8/src/view/save_project_popup_view.js#L56)):*
> ```JavaScript
>       <input type="file" nwdirectory id="toolboxDirectory"></input><br><br>
>     Workspace
>       <input type="file" nwdirectory id="workspaceDirectory"></input><br><br>
> ```

These aims for one directory per resource type, but in the Tuesday meeting we talked about one filepath per resource in the metadata file. That leaves a number of possible file-path combos that could not be represented by this UI.

Generate this HTML based upon the actual resources that are too be saved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by AnmAtAnm** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kqcw2s7ilhhGN-yMwku:-Kqcw2s7ilhhGN-yMwkv:b-kxphuw) ([raw file](https://github.com/google/blockly-devtools/blob/593af04f2de2b853a7c199efb85546206b5944b8/src/view/save_project_popup_view.js#L87)):*
> ```JavaScript
>       this.toolbox = $('#toolboxDirectory').val();
>       this.general_workspace = $('#workspaceDirectory').val();
>     	this.hide();
> ```

Correct the indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by AnmAtAnm** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/view/save_project_popup_view.js, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/167#-Kqcw2s7ilhhGN-yMwku:-KqcwLsyX6AOeZbWKM3Q:b-w9yt8t) ([raw file](https://github.com/google/blockly-devtools/blob/593af04f2de2b853a7c199efb85546206b5944b8/src/view/save_project_popup_view.js#L87)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Correct the indent.
</blockquote></details>

Also, this file has tab characters in it, here and above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/167#-:-Kqe5ntPIXgaN7TYvwFN:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
