### PR TITLE
Refactor: New res Folder

### PR DESCRIPTION
**Pull request by chynu**
Created new `res/` folder to contain any static files (e.g. `DevToolsToolboxes`, etc.). Also cleaned up minor code nits.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/78)

### CODE REVIEW

**Comment by svouse** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/78#-:-KoKC2jpJfZf0JPoNtIM:bnfp4nl)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[res/factory_utils.js, line 1 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/78#-KoKDC_ujHXSw_jJKxLR:-KoKDC_v1Z4yxXCog0b9:bd6bxu9) ([raw file](https://github.com/google/blockly-devtools/blob/110e0e24973f30bdc488877f09f4dfdafebab32c/res/factory_utils.js#L1)):*
> ```JavaScript
> /**
> ```

Leave this in src.

---

*[res/list_element.js, line 2 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/78#-KoKDGaurEWvhAB8zAPY:-KoKDGaurEWvhAB8zAPZ:bd6bxu9) ([raw file](https://github.com/google/blockly-devtools/blob/110e0e24973f30bdc488877f09f4dfdafebab32c/res/list_element.js#L2)):*
> ```JavaScript
> /**
>  * @license
> ```

Leave this in src.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/78)*

**Comment by chynu** [comment]
Moved `FactoryUtils` and `ListElements` back.

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/78#-:-KoKPrrhNq_yY5lt5CqQ:bnfp4nl)*

**Pull request merged**
