### PR TITLE
Small JSON change

### PR DESCRIPTION
**Pull request by svouse**
Modifies JSON such that it doesn't have newlines, project metadata resources properly populate

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/188)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 179 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/188#-Kqj59BgJmF-edXLno4q:-Kqj59BgJmF-edXLno4r:b-lom8d0) ([raw file](https://github.com/google/blockly-devtools/blob/bfba142538ed9b2c932da4a13f2eda44e7251c22/src/controller/block_editor_controller.js#L179)):*
> ```JavaScript
>     const blockXml = '<xml>' + Blockly.Xml.domToText(Blockly.Xml.blockToDom(rootBlock)) + '</xml>';
>     currentBlock.setXml(Blockly.Xml.textToDom(blockXml));
>     currentBlock.json = '[' + FactoryUtils.getBlockDefinition(
> ```

Please put the inner expression into its own variable and then do the join and add the brackets.  It's hard to read right now.

---

*[src/model/project.js, line 284 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/188#-Kqj51_CZDyhwFnpgOyM:-Kqj51_CZDyhwFnpgOyN:bwd7k7r) ([raw file](https://github.com/google/blockly-devtools/blob/bfba142538ed9b2c932da4a13f2eda44e7251c22/src/model/project.js#L284)):*
> ```JavaScript
>    */
>   getFullResourceList() {
>     return this.librarySet.getMetadata().concat(this.toolboxSet.getMetadata(),
> ```

I prefer the other version, tbh. It's much easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/188)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 179 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/188#-Kqj59BgJmF-edXLno4q:-KqjBIAkM9vu97frz6Ks:b-14pryi) ([raw file](https://github.com/google/blockly-devtools/blob/bfba142538ed9b2c932da4a13f2eda44e7251c22/src/controller/block_editor_controller.js#L179)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Please put the inner expression into its own variable and then do the join and add the brackets.  It's hard to read right now.
</blockquote></details>

I ran into this bug on my branch (#189, [diff here](https://github.com/google/blockly-devtools/pull/189/files#diff-0570b8022ef641331784c313e1d75da4R197)) and fixed it by using `JSON.parse(jsonString)`, which might be a better idea since I used it for functionality and it worked for me (in defining blocks to show in the editor workspaces)?

Also, the json field is marked as `@type {!Object}`, and this is a string, no?

Perhaps we can store it as a JSON and convert it to string whenever we need it as a string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/188)*

**Comment by svouse** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 179 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/188#-Kqj59BgJmF-edXLno4q:-KqjBf8FC4XV2up8k4kb:b-4kf8kv) ([raw file](https://github.com/google/blockly-devtools/blob/bfba142538ed9b2c932da4a13f2eda44e7251c22/src/controller/block_editor_controller.js#L179)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I ran into this bug on my branch (#189, [diff here](https://github.com/google/blockly-devtools/pull/189/files#diff-0570b8022ef641331784c313e1d75da4R197)) and fixed it by using `JSON.parse(jsonString)`, which might be a better idea since I used it for functionality and it worked for me (in defining blocks to show in the editor workspaces)?

Also, the json field is marked as `@type {!Object}`, and this is a string, no?

Perhaps we can store it as a JSON and convert it to string whenever we need it as a string?
</blockquote></details>

now JSON.parse, added an issue #190 

---

*[src/model/project.js, line 284 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/188#-Kqj51_CZDyhwFnpgOyM:-KqjEY9Uc7WW4IeB5JWD:b-7ql1td) ([raw file](https://github.com/google/blockly-devtools/blob/bfba142538ed9b2c932da4a13f2eda44e7251c22/src/model/project.js#L284)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I prefer the other version, tbh. It's much easier to read.
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/188)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/188#-:-KqjEgK9V0XLCtT7f71b:bnfp4nl)*

**Pull request merged**
