### PR TITLE
Export: Sample Web Application

### PR DESCRIPTION
**Pull request by chynu**
Very hard-coded (but tried to make it easily extendable) -- upon exporting as sample blockly application, user is prompted to download an html file which loads the first toolbox and first workspace contents/config. 

Retrieves compressed files from appspot link.

(Will follow up with using fs/node to use locally downloaded compressed files).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/218)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/project_controller.js, line 459 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3gzbCrKRCYGLEtojA:-Kr3gzbCrKRCYGLEtojB:b-rh67dc) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/project_controller.js#L459)):*
> ```JavaScript
>   
>   <script>
>   ${blockDefScript}</script>
> ```

Oh.... I was expecting this would use <script src="..."/>, referencing the `.js` files generated during saving.

Good enough for tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by rachel-fenichel** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/factory_utils.js, line 387 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3gceky-fCAeCEAzl5:-Kr3gcel3UMhqZRn9xmG:b-ub1x0d) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/factory_utils.js#L387)):*
> ```JavaScript
>   code.push('};');
>   const definition = code.join('\n');
>   console.log(definition);
> ```

Get rid of the log or just revert this file.

---

*[src/controller/block_editor_controller.js, line 473 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3grjdGlY0UcQlRc7H:-Kr3grjdGlY0UcQlRc7I:brk98r1) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/block_editor_controller.js#L473)):*
> ```JavaScript
>     const allBlocks = this.projectController.getProject().
>         librarySet.getAllBlockDefinitionsMap();
>     console.log(allBlocks);
> ```

Remove log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/app_controller.js, line 313 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3i4n2-VYGgrMFjIfk:-Kr3i4n2-VYGgrMFjIfl:b-7w2xt4) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/app_controller.js#L313)):*
> ```JavaScript
>     const injectFileContents = this.projectController.generateInjectString();
>     // Get file name from user.
>     const fileName = prompt('File name for sample Blockly workspace code:',
> ```

As a sample HTML, this can be hard coded. No one is expecting the user to make this exact file their application.

---

*[src/controller/app_controller.js, line 319 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3iEb_u6uFUXgo7mwa:-Kr3iEb_u6uFUXgo7mwb:bep8il0) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/app_controller.js#L319)):*
> ```JavaScript
>     }
> 
>     FactoryUtils.createAndDownloadFile(injectFileContents,
> ```

TODO: Replace with node style file writing in the project's web export directory.

---

*[src/controller/project_controller.js, line 452 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3hQz2WBbj56v_UPwi:-Kr3hQz2WBbj56v_UPwj:b-meyiqo) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/project_controller.js#L452)):*
> ```JavaScript
> <head>
>   <title>Sample Application: ${this.project.name}</title>
>   
> ```

TODO: Replace with web files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/view/app_view.js, line 239 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3ifAYtxBxaaRbIfiP:-Kr3ifAZDeqnVq1alKz5:b-3cfpsz) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/view/app_view.js#L239)):*
> ```JavaScript
>    */
>   createWeb() {
>     this.appController.saveSampleApplication('WEB');
> ```

FYI - Supporting sample apps of other platforms is near zero chance.  The project structures on Android and iOS change too quickly for us to keep up with.  I'd remove the platform argument to avoid hinting that this is a goal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/view/app_view.js, line 239 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3ifAYtxBxaaRbIfiP:-Kr3jTCw65c2k78aT22q:b9q58sy) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/view/app_view.js#L239)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

FYI - Supporting sample apps of other platforms is near zero chance.  The project structures on Android and iOS change too quickly for us to keep up with.  I'd remove the platform argument to avoid hinting that this is a goal.
</blockquote></details>

Actually, the function doesn't take any arguments. Please remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/factory_utils.js, line 387 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3gceky-fCAeCEAzl5:-Kr6mP22RZo2x6oWvpZa:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/factory_utils.js#L387)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Get rid of the log or just revert this file.
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 313 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3i4n2-VYGgrMFjIfk:-Kr6la2wv1wiUDZ1TqWL:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/app_controller.js#L313)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

As a sample HTML, this can be hard coded. No one is expecting the user to make this exact file their application.
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 319 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3iEb_u6uFUXgo7mwa:-Kr6lh43hZGP8Dlkbms_:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/app_controller.js#L319)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Replace with node style file writing in the project's web export directory.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 473 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3grjdGlY0UcQlRc7H:-Kr6lglARp42f52FCOA8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/block_editor_controller.js#L473)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove log
</blockquote></details>

Done.

---

*[src/controller/project_controller.js, line 452 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3hQz2WBbj56v_UPwi:-Kr6mXHbodyHATMOar1-:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/project_controller.js#L452)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Replace with web files.
</blockquote></details>

Done.

---

*[src/controller/project_controller.js, line 459 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3gzbCrKRCYGLEtojA:-Kr6m6qiwnCDq-PRdC0b:bbwmx3s) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/controller/project_controller.js#L459)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Oh.... I was expecting this would use <script src="..."/>, referencing the `.js` files generated during saving.

Good enough for tomorrow.
</blockquote></details>

Oops, I can get that working after other demo things are prepared.

---

*[src/view/app_view.js, line 239 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/218#-Kr3ifAYtxBxaaRbIfiP:-Kr6mAVEHqEP4vJpKrFx:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c645222cff0a21c4b8d7c1cd6889a22ffe7dd128/src/view/app_view.js#L239)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Actually, the function doesn't take any arguments. Please remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/218#-:-Kr70Mo5uy4CM9kZRbjJ:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
