### PR TITLE
Workspace configs

### PR DESCRIPTION
**Pull request by svouse**
**Summary:** Implements all non-export WorkspaceConfiguration methods, removes unnecessary methods where appropriate.

**Goals:** Maintaining functionality, update workspace_configuration.js

**Specifically Includes:**
- addition of generateInjectString method (previously in wfactory_generator.js)
- removal of unnecessary/outdated methods

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/131)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 40 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuwi6ubY4fsxoWZyat:-Kpuwi6ubY4fsxoWZyau:b-msf4p2) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L40)):*
> ```JavaScript
>   constructor(workspaceConfigName) {
>     /*
>      * TODO: fully implement
> ```

I think you can probably remove this TODO now? 0: Or is there more to add to the constructor?

---

*[src/model/workspace_configuration.js, line 65 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuv6RnZeZtKgyUqXOu:-Kpuv6RnZeZtKgyUqXOv:b-aas760) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L65)):*
> ```JavaScript
>    */
>   reset() {
>     this.options = new Object(null);
> ```

Should we reset to null or reset it by giving it some set of default values? This might run into problems if a user mistakenly resets a config and then tries to inject. I'm not entirely sure if this actually crashes Blockly.inject, but I think it might be a good idea to set it to some default config rather than making it an empty object.

---

*[src/model/workspace_configuration.js, line 93 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpuvkHnGb-K5uxMIbCS:-KpuvkHnGb-K5uxMIbCT:b-opy4u0) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L93)):*
> ```JavaScript
>    * @return {string} String representation of starter code for injecting.
>    */
>   generateInjectString() {
> ```

If this is refactored possibly mark where it came from? Just so that, at least before refactoring is completely over, we can look back at the old code if we ever need to (and also mention what the old function name was as well even if it is the same fcn name)

(resolved over pm)

---

*[src/model/workspace_configuration.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuw6sEBSMJNwOCy4RL:-Kpuw6sEBSMJNwOCy4RM:b-fhhy8n) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L94)):*
> ```JavaScript
>    */
>   generateInjectString() {
>     var addAttributes = function(obj, tabChar) {
> ```

This might be more readable if it were a private helper function (not Super Important, but just a thought).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by svouse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 40 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuwi6ubY4fsxoWZyat:-KpvfCV94dFvNaLlT0kz:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L40)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think you can probably remove this TODO now? 0: Or is there more to add to the constructor?
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 65 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuv6RnZeZtKgyUqXOu:-Kpvg0HV2AnDy1dz-bFc:bl3c9ao) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L65)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Should we reset to null or reset it by giving it some set of default values? This might run into problems if a user mistakenly resets a config and then tries to inject. I'm not entirely sure if this actually crashes Blockly.inject, but I think it might be a good idea to set it to some default config rather than making it an empty object.
</blockquote></details>

It should still give default values via generating the inject string/shouldn't break anything

---

*[src/model/workspace_configuration.js, line 93 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpuvkHnGb-K5uxMIbCS:-KpvgAhtzdgvgtI3Z8Wd:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L93)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

If this is refactored possibly mark where it came from? Just so that, at least before refactoring is completely over, we can look back at the old code if we ever need to (and also mention what the old function name was as well even if it is the same fcn name)

(resolved over pm)
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuw6sEBSMJNwOCy4RL:-KpvgMpst1C4f-Ln6j5F:b3od6d6) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L94)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

This might be more readable if it were a private helper function (not Super Important, but just a thought).
</blockquote></details>

I like it//done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/workspace_configuration.js, line 65 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpuv6RnZeZtKgyUqXOu:-KpvksgR-Hv2i-HvBdUo:b-bnilkx) ([raw file](https://github.com/google/blockly-devtools/blob/196572f1713f504d6894fd4a32140722f9163821/src/model/workspace_configuration.js#L65)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

It should still give default values via generating the inject string/shouldn't break anything
</blockquote></details>

Okay cool, makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131#-:-KpvlDussNiGopd4EgnA:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 44 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvph06XHPp2jz0zsD8:-Kpvph06XHPp2jz0zsD9:b-7irv7h) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L44)):*
> ```JavaScript
>       * Options object to be configured for Blockly inject call.
>       */
>      this.options = new Object(null);
> ```

I think you mean `Object.create(null)` in these cases.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object), the Object constructor takes the object value as its input, and I'd guess by calling it via such constructor gives it the prototype you're trying to avoid.

---

*[src/model/workspace_configuration.js, line 60 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpvqeO9atQa6_m_hldj:-KpvqeO9atQa6_m_hldk:bukue31) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L60)):*
> ```JavaScript
>    */
>   reset() {
>     this.options = new Object(null);
> ```

`Object.create(null)` here to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 44 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvph06XHPp2jz0zsD8:-KpvrJjXYeKjmNf8ArSc:b-r5msxm) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L44)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I think you mean `Object.create(null)` in these cases.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object), the Object constructor takes the object value as its input, and I'd guess by calling it via such constructor gives it the prototype you're trying to avoid.
</blockquote></details>

As Rachel pointed out, `(new Object(null)).__proto__ != null`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpvrdEASc8PoPinNiey:-KpvrdEASc8PoPinNiez:b-yood34) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L87)):*
> ```JavaScript
>    * used to inject the workspace.
>    * @param {!Object} obj Object representing the options selected in the current
>    * configuration.
> ```

Indent the wrapped `@param` by 4 spaces.

---

*[src/model/workspace_configuration.js, line 90 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvrgf4tIkNBCEArRMK:-Kpvrgf4tIkNBCEArRML:b-eurxf1) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L90)):*
> ```JavaScript
>    * @param {string} tabChar The tab character.
>    * @return {string} String representation of the workspace configuration's
>    * options.
> ```

On the `@return`, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by rachel-fenichel** [comment]
+1 to Andrew's comments.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 44 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvph06XHPp2jz0zsD8:-KpvurEoNX_QDsPb-Qy0:b-nkue3h) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L44)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

As Rachel pointed out, `(new Object(null)).__proto__ != null`.
</blockquote></details>

My bad for telling you to use the wrong thing last week and creating confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131#-:-KpvvRVKPir5LvK0qste:b-npz4wt)*

**Comment by svouse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 44 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvph06XHPp2jz0zsD8:-KpzwZzjaJKaBIRzK-Tf:bkrem25) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L44)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

My bad for telling you to use the wrong thing last week and creating confusion.
</blockquote></details>

np np; in the old code the options had been new Object(null), so you're good/no confusion

---

*[src/model/workspace_configuration.js, line 60 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpvqeO9atQa6_m_hldj:-KpzwzQ5Ml3Js5vCY2yc:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L60)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`Object.create(null)` here to.
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpvrdEASc8PoPinNiey:-Kpzx3zFzyNGFSE0QkoC:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L87)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Indent the wrapped `@param` by 4 spaces.
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 90 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/131#-Kpvrgf4tIkNBCEArRMK:-Kpzx4QocjcZHWEuShN_:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/1d9ca335574fba60c2a3ece6562e31434ebb88ce/src/model/workspace_configuration.js#L90)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

On the `@return`, too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Comment by AnmAtAnm** [comment]
One trivial nit and then :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 137 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpzzRLdSNj5yvkZjKQX:-KpzzRLdSNj5yvkZjKQY:bfvihhx) ([raw file](https://github.com/google/blockly-devtools/blob/539e46f9d72f26ecc50773c6bd173ff1e75a4b66/src/model/workspace_configuration.js#L137)):*
> ```JavaScript
>   document.onload = function() {
>     /* Inject your workspace */
>     var workspace = Blockly.inject(/* TODO: Add ID of div to inject Blockly into */, BLOCKLY_OPTIONS);
> ```

 Wrap line or put TODO on previous line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131#-:-KpzzVcU9VlKFlpDpQrS:b-nqnmyx)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by svouse** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration.js, line 137 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/131#-KpzzRLdSNj5yvkZjKQX:-Kq--kVj1CVPNSiFcesh:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/539e46f9d72f26ecc50773c6bd173ff1e75a4b66/src/model/workspace_configuration.js#L137)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

 Wrap line or put TODO on previous line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/131)*

**Pull request merged**
