### PR TITLE
Beginning of Model Refactor

### PR DESCRIPTION
**Pull request by svouse**
Completion of resource, references and functions added to BlockLibrary, Toolbox, and WorkspacePreload. Updated documentation in model files.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/57)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/block_library.js, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngW0Nau6PVFK22_Nhf:-KngW0Nau6PVFK22_Nhg:b-lxctrj) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L86)):*
> ```JavaScript
>   /**
>    * Returns map of each block type to its corresponding XML stored in the
>    *     block library.
> ```

TODO: What happens if a block type requested is not in this library?

---

*[src/model/block_library.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngWrHibunX7SIV8zNp:-KngWrHjZ2gJWz_JUb_y:b-gp63iq) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L88)):*
> ```JavaScript
>    *     block library.
>    * @param {!Array.<string>} blockTypes Types of blocks.
>    * @return {!Object} Map of block type to corresponding XML.
> ```

!Object<string, Element>  (I think)

---

*[src/model/block_library.js, line 90 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngWFkXtRwA71BxCPLa:-KngWFkXtRwA71BxCPLb:bumez1v) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L90)):*
> ```JavaScript
>    * @return {!Object} Map of block type to corresponding XML.
>    */
>   getBlockXmlMap(blockTypes) {
> ```

I feel like this functionality is covered by a combination of other methods.  Maybe it is particularly useful for some common operation, and is implemented in the other operations. 

---

*[src/model/block_library.js, line 147 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngX2K8qLlQc3V62KMn:-KngX2K8qLlQc3V62KMo:b-n4vs57) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L147)):*
> ```JavaScript
>   /**
>    * Returns array of all block types stored in the block library.
>    * @return {!Array.<string>} Map of block type to corresponding XML text.
> ```

Method says "Map", but this isn't a map.

---

*[src/model/block_library.js, line 149 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngVg3508TC5juD8UAY:-KngVg3508TC5juD8UAZ:b-od45j6) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L149)):*
> ```JavaScript
>    * @return {!Array.<string>} Map of block type to corresponding XML text.
>    */
>   getBlockXmlTextMap() {
> ```

This will eventually refactor into JSON text, right?

---

*[src/model/resource.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngXZ4bZJPVG1kAmUlo:-KngXZ4bZJPVG1kAmUlp:bm04g6q) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L33)):*
> ```JavaScript
>  *     remove them, get their definitions, verify their presence, confirm or
>  *     or deny empty status, have their names changed, save/load from local
>  *     storage, and return whether or not they contain unsaved changes.
> ```

Hmmm... I'm still skeptical that is useful based on the variety of data structures.  I don't see enough similarity or where a variable might refer to a unspecified resource type.

---

*[src/model/resource.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngYLbcV6CByp-gXmnA:-KngYLbcV6CByp-gXmnB:bckoqrn) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L62)):*
> ```JavaScript
>    * @return {Element} The XML that represents the blockType or null.
>    */
>   getBlockXml(blockType) {
> ```

BlockLibraries are groups of block definitions, which should eventually be stored as JSON. This is in contrast to the block instances in Toolboxes and the workspace.
In the toolbox and workspace case, you can have multiple blocks of the same type name, which this interface doesn't capture.
What would you return if the block of the specified type was only a child or a shadow?  That is, it wasn't a top level block, but rather connected to some other block.

---

*[src/model/resource.js, line 71 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngZRQ7qOZBcY9sJ7Rw:-KngZRQ7qOZBcY9sJ7Rx:b-e2tnt2) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L71)):*
> ```JavaScript
>    * @return {!Object} Map of block type to corresponding XML.
>    */
>   getBlockXmlMap() {
> ```

All the same comments as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/project.js, line 254 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnikouXX_WEqXcoEEUg:-KnikouXX_WEqXcoEEUh:b-55sc8j) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/project.js#L254)):*
> ```JavaScript
>   setName(newName) {
>     /*
>      * TODO: impliment
> ```

Nit: Spelling "implement" here and kinda everywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by rachel-fenichel** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/block_library.js, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnmKHBF8ekrQR5yDkGo:-KnmKHBF8ekrQR5yDkGp:b-xmok3p) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L26)):*
> ```JavaScript
>  *      are changed based upon user interaction with the DevTools Application,
>  *      rather than the definitions contained within the other structures under
>  *      Project. Moreover, block libraries cannot contain multiple blocks with
> ```

Style: prefer brevity here.

"A BlockLibrary stores one or more block definitions. User interactions with the DevTools Application change definitions in the BlockLibrary.  A BlockLibrary cannot contain multiple blocks with the same type and definition."

(Can it contain multiple blocks with the same type but different definitions?  Same definition but different types?  I think it's that it can't contain multiple blocks with the same name.)

---

*[src/model/resource.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngXZ4bZJPVG1kAmUlo:-KnmLewnURPFOGGgbMA-:b-qzusn3) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L33)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Hmmm... I'm still skeptical that is useful based on the variety of data structures.  I don't see enough similarity or where a variable might refer to a unspecified resource type.
</blockquote></details>

I'm with Andrew here: Resources should just provide load, save, and isDirty.  All the rest of the functions are not-quite-the-same between the other classes.

---

*[src/model/workspace_contents.js, line 100 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnmNL9XACoc9CxCgN5S:-KnmNL9XACoc9CxCgN5T:b-hpoxo8) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/workspace_contents.js#L100)):*
> ```JavaScript
>    * @return {!Object} Map of block types to corresponding XML.
>    */
>   getBlockXmlMap(blockTypes) {
> ```

Let's chat about this method in person.  I'm confused about what it's trying to do in the context of workspace contents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by svouse** [comment]
Review status: 2 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/block_library.js, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnmKHBF8ekrQR5yDkGo:-Knoi6GUsUP53WnZRVjd:bit5ecn) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L26)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Style: prefer brevity here.

"A BlockLibrary stores one or more block definitions. User interactions with the DevTools Application change definitions in the BlockLibrary.  A BlockLibrary cannot contain multiple blocks with the same type and definition."

(Can it contain multiple blocks with the same type but different definitions?  Same definition but different types?  I think it's that it can't contain multiple blocks with the same name.)
</blockquote></details>

Yup-the restriction is on type. Fixed excessive length.

---

*[src/model/block_library.js, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngW0Nau6PVFK22_Nhf:-Knomf8zvv8D16_gujgd:bht1dxd) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L86)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: What happens if a block type requested is not in this library?
</blockquote></details>

Added TODO; I'm thinking we'll check its type against the blocks in this.blocks and if it's not there not add a field at all.  Alternatively, depending on how we wind up using this method post-refactor, I may just scrap the param and only get the definitions from this.blocks.

---

*[src/model/block_library.js, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngWrHibunX7SIV8zNp:-KnonTzEcIAgGS1KnscO:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L88)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

!Object<string, Element>  (I think)
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 90 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngWFkXtRwA71BxCPLa:-KnonjMioOQjhElfT9i1:b4hlxs3) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L90)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I feel like this functionality is covered by a combination of other methods.  Maybe it is particularly useful for some common operation, and is implemented in the other operations. 
</blockquote></details>

I'm a little confused as to your meaning here. The method definitely exists; as per the TODO it's to be moved from block_library_storage.js. Are you saying there are multiple methods with the same/similar functionality which can be combined in to one?

---

*[src/model/block_library.js, line 147 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngX2K8qLlQc3V62KMn:-KnofuwLvVTMKe5v7YzV:bt2vr1b) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L147)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Method says "Map", but this isn't a map.
</blockquote></details>

Fixed.

---

*[src/model/block_library.js, line 149 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngVg3508TC5juD8UAY:-KnoflE2l7AALssKTUt5:b-vaachc) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L149)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This will eventually refactor into JSON text, right?
</blockquote></details>

Yup; updated. Talked it out with Celine and we figured we'll keep getBlockXmlMap for now in case we need it, but replace getBlockXmlTextMap with getBlockJsonMap on account of the fact that we will indeed be changing the definition. Additionally, we intend to phase out getBlockXmlMap and getBlockXml altogether.

---

*[src/model/project.js, line 254 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnikouXX_WEqXcoEEUg:-KnofoKqb50WG_pysUHI:b5i21fc) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/project.js#L254)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: Spelling "implement" here and kinda everywhere
</blockquote></details>

Eek (*108). Fixed.

---

*[src/model/resource.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngXZ4bZJPVG1kAmUlo:-KnopRbg3pyhPgp7c_mL:bo3d9rw) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L33)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I'm with Andrew here: Resources should just provide load, save, and isDirty.  All the rest of the functions are not-quite-the-same between the other classes.
</blockquote></details>

Fixed//definitely makes more sense.

---

*[src/model/resource.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngYLbcV6CByp-gXmnA:-KnowwxUynWfyJVz3bOG:bav4zmh) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L62)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

BlockLibraries are groups of block definitions, which should eventually be stored as JSON. This is in contrast to the block instances in Toolboxes and the workspace.
In the toolbox and workspace case, you can have multiple blocks of the same type name, which this interface doesn't capture.
What would you return if the block of the specified type was only a child or a shadow?  That is, it wasn't a top level block, but rather connected to some other block.
</blockquote></details>

Fixed; resource now only contains save, load, and isDirty. I also removed the getters/has from Toolbox and WorkspaceContents and added a TODO for them.

---

*[src/model/workspace_contents.js, line 100 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnmNL9XACoc9CxCgN5S:-KnopXwReTHsvAy3cEUh:b-6hxker) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/workspace_contents.js#L100)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Let's chat about this method in person.  I'm confused about what it's trying to do in the context of workspace contents.
</blockquote></details>


Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by svouse** [comment]
Review status: 2 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/resource.js, line 71 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngZRQ7qOZBcY9sJ7Rw:-Knp50jd1Ayr42jO81y8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L71)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

All the same comments as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by AnmAtAnm** [comment]
Reviewed 2 of 6 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/model/block_library.js, line 90 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngWFkXtRwA71BxCPLa:-Knp8EQsQ3LMVFClsmc1:beent31) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/block_library.js#L90)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

I'm a little confused as to your meaning here. The method definitely exists; as per the TODO it's to be moved from block_library_storage.js. Are you saying there are multiple methods with the same/similar functionality which can be combined in to one?
</blockquote></details>

I see. I was looking at the methods you have declared here, and seeing lots of similarity.

Be careful, because the prior XML representation is the one used for the Blockly-based Block editor.

---

*[src/model/block_library.js, line 153 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-Knp8d73DPPx3O9rVevS:-Knp8d73DPPx3O9rVevT:b-7kz775) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/block_library.js#L153)):*
> ```JavaScript
> 
>   /**
>    * Returns array of all block JSON stored in the block library.
> ```

Method docs says "Returns array", but the @return is now an Object.

---

*[src/model/project.js, line 219 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-Knp97HaMis7uK-b0C6c:-Knp97HbVGe77eKkv8fL:baachy8) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/project.js#L219)):*
> ```JavaScript
> 
>   /**
>    * Removes current block from project.
> ```

What defines the current block? Similar question for other methods below, referencing the "current".

This isn't really a response to this PR, but it is a question I think you'll run into. 

---

*[src/model/workspace_configuration.js, line 31 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAYXux7iHDLI5e2tL:-KnpAYXux7iHDLI5e2tM:b-hyfkaf) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L31)):*
> ```JavaScript
>  * @class WorkspaceConfiguration stores workspace presets.
>  */
> class WorkspaceConfiguration {
> ```

extend Resource, now that Resource is not about Blocks?

---

*[src/model/workspace_configuration.js, line 38 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAFMjiDh1aMPPVxbX:-KnpAFMjiDh1aMPPVxbY:bu1h8s0) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L38)):*
> ```JavaScript
>    * @return {boolean} True if same as init options, false otherwise.
>    */
>   isUnset() {
> ```

Maybe consider isDefault(), or its opposite, isCustomized()

---

*[src/model/workspace_configuration.js, line 64 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAUmMhAea760T5Fpq:-KnpAUmMhAea760T5Fpr:b-mstc21) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L64)):*
> ```JavaScript
>    * @param {string} newName New name of the workspace configuration.
>    */
>   setName(newName) {
> ```

Is name a quality or Resource? Would this be set with a constructor, like the other model classes?

---

*[src/model/workspace_contents.js, line 100 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnmNL9XACoc9CxCgN5S:-KnpB9nzlQK5-2yPEO2D:b-55siyv) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/workspace_contents.js#L100)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

Hmmm... We kinda have a model class for this. Maybe `goog.inherits(WorkspaceContents, Blockly.Workspace)`, just adding the necessary `Resource` methods.

Rachel says "no. it should just be the XML."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by AnmAtAnm** [comment]
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/resource.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngXZ4bZJPVG1kAmUlo:-KnpqWbXRt1LYyfqNJOi:b-74ez4g) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L33)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Fixed//definitely makes more sense.
</blockquote></details>

Remove @fileoverview.

---

*[src/model/resource.js, line 28 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpqalRZSjINRjnmlRp:-KnpqalRZSjINRjnmlRq:bn2wq4e) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/resource.js#L28)):*
> Resource provides method requirements for the Toolbox, BlockLibrary, and WorkspaceContents classes.

Replace with "A Resource is the top level interface for the parts of a project, including the project itself."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by svouse** [comment]
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/model/block_library.js, line 153 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-Knp8d73DPPx3O9rVevS:-KnpgqU52ry89mtt6Tq8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/block_library.js#L153)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Method docs says "Returns array", but the @return is now an Object.
</blockquote></details>

Done.

---

*[src/model/project.js, line 219 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-Knp97HaMis7uK-b0C6c:-KnpgsvU8jU7PUCGG0jg:b-cu8eud) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/project.js#L219)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

What defines the current block? Similar question for other methods below, referencing the "current".

This isn't really a response to this PR, but it is a question I think you'll run into. 
</blockquote></details>

Removed "current" for removal/updated comment for save (I'll be editing these as of post-refactor project functionality); this had been because the methods called through the blockLibraryController reference the current block as being the one being displayed/edited. 

---

*[src/model/resource.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KngXZ4bZJPVG1kAmUlo:-KnqG2IqHEh3_HOHxRKX:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7b3ebc8350e21b4be2f6f5efb175c56d3aecfa2b/src/model/resource.js#L33)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Remove @fileoverview.
</blockquote></details>

Done.

---

*[src/model/resource.js, line 28 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpqalRZSjINRjnmlRp:-KnqG1pLX2wFu1pw4wBz:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/resource.js#L28)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

> Resource provides method requirements for the Toolbox, BlockLibrary, and WorkspaceContents classes.

Replace with "A Resource is the top level interface for the parts of a project, including the project itself."

</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 31 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAYXux7iHDLI5e2tL:-KnppHUTuwAdBzFWkTWr:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L31)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

extend Resource, now that Resource is not about Blocks?
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 38 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAFMjiDh1aMPPVxbX:-KnppTXIBG6xvWfMaXWV:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L38)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Maybe consider isDefault(), or its opposite, isCustomized()
</blockquote></details>

Done.

---

*[src/model/workspace_configuration.js, line 64 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnpAUmMhAea760T5Fpq:-Knpphn6H2Nx61Qnv_6n:bxfvapi) ([raw file](https://github.com/google/blockly-devtools/blob/59cee5b35168d95fcf812df5befe67fd70397be2/src/model/workspace_configuration.js#L64)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Is name a quality or Resource? Would this be set with a constructor, like the other model classes?
</blockquote></details>

(reading 'or' as 'of') I'm thinking it ought to be a property of Resource// put it in as such in a new constructor for Resource, now called in the constructors of the classes which inherit from it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/resource.js, line 36 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/57#-KnqJgYmxagJ_VGDpJKt:-KnqJgYmxagJ_VGDpJKu:b-sda3gw) ([raw file](https://github.com/google/blockly-devtools/blob/a40315203a8e953794522546910258736081a6b5/src/model/resource.js#L36)):*
> ```JavaScript
>      * @type {string}
>      */
>      this.name = resourceName;
> ```

We'll eventually want the `setName()` method as well.  Fine for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/57#-:-KnqKHXb-i_B6o5mc4Ah:bnfp4nl)*

**Pull request merged**
