### PR TITLE
NavTree: Switching between WorkspaceContents

### PR DESCRIPTION
**Pull request by chynu**
Can now create multiple WorkspaceContents and switch between them in navtree.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/182)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Fix some copy pasta, then :lgtm: 

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/app_controller.js, line 393 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqhmRAKLgvHtLT1WBjq:-KqhmRAKLgvHtLT1WBjr:bdybqa0) ([raw file](https://github.com/google/blockly-devtools/blob/d5ea3f597d0bbaa42cd0b1c55dfcd1212bb26f2d/src/controller/app_controller.js#L393)):*
> ```JavaScript
>       isEmpty = name && name.trim() ? false : true;
>       if (isDuplicate) {
>         errorText = 'This toolbox already exists.\n';
> ```

"Toolbox"?  Copy pasta?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/182#-:-Kqhmtu-GwemQSBTwSax:bnxs0ed)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by chynu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/app_controller.js, line 393 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqhmRAKLgvHtLT1WBjq:-Kqhq2aXxuH3LVHjzFEH:b-qjh3te) ([raw file](https://github.com/google/blockly-devtools/blob/d5ea3f597d0bbaa42cd0b1c55dfcd1212bb26f2d/src/controller/app_controller.js#L393)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

"Toolbox"?  Copy pasta?
</blockquote></details>

Done. :spaghetti: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/182)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller.js, line 393 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqhmRAKLgvHtLT1WBjq:-KqiEs1cs-_omLa2JX65:b-ythmko) ([raw file](https://github.com/google/blockly-devtools/blob/d5ea3f597d0bbaa42cd0b1c55dfcd1212bb26f2d/src/controller/app_controller.js#L393)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done. :spaghetti: 
</blockquote></details>

Mm, pasta.

---

*[src/controller/app_controller.js, line 384 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqiEtgBWcaRP9p0wav3:-KqiEtgBWcaRP9p0wav4:b22qzh9) ([raw file](https://github.com/google/blockly-devtools/blob/67f40380e99b93b721b0205369116f4040462c1c/src/controller/app_controller.js#L384)):*
> ```JavaScript
>    */
>   createWorkspaceContents() {
>     // TODO: prompt for name
> ```

Remove todo

---

*[src/view/workspace_editor_view.js, line 153 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqiF7ZVwr3mgWdE27Eh:-KqiF7ZVwr3mgWdE27Ei:b22qzh9) ([raw file](https://github.com/google/blockly-devtools/blob/67f40380e99b93b721b0205369116f4040462c1c/src/view/workspace_editor_view.js#L153)):*
> ```JavaScript
>     Blockly.svgResize(this.previewWorkspace);
> 
>     // TODO: Make editor show WorkspaceContents when
> ```

Remove todo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/182)*

**Comment by chynu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller.js, line 384 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqiEtgBWcaRP9p0wav3:-KqiGvFc5J9ZrkDRX0yS:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/67f40380e99b93b721b0205369116f4040462c1c/src/controller/app_controller.js#L384)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove todo
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 153 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/182#-KqiF7ZVwr3mgWdE27Eh:-KqiGzuFULMmmee0itIl:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/67f40380e99b93b721b0205369116f4040462c1c/src/view/workspace_editor_view.js#L153)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove todo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/182)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/182#-:-KqiHcmN2YlZIPJbf3Af:bnfp4nl)*

**Pull request merged**
