### PR TITLE
NavTree: Auto-Select and Expand Nodes

### PR DESCRIPTION
**Pull request by chynu**
Auto-expands nodes as resources are created. Also auto-selects a newly created resource in navtree.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/177)

### CODE REVIEW

**Comment by svouse** [comment]
*[src/view/navigation_tree.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeDrmh5c0_CHPF9Szy:-KqeDrmh5c0_CHPF9Szz:b-85tyvq) ([raw file](https://github.com/google/blockly-devtools/blob/b71875f555f45f390638224fee7108731be63135/src/view/navigation_tree.js#L96)):*
> ```JavaScript
> 
>   /**
>    *
> ```

JsDoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by chynu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/navigation_tree.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeDrmh5c0_CHPF9Szy:-KqeEKQjgyt1U2sVytjj:bdqgnmp) ([raw file](https://github.com/google/blockly-devtools/blob/b71875f555f45f390638224fee7108731be63135/src/view/navigation_tree.js#L96)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

JsDoc
</blockquote></details>

AAAAA. jsdoc will haunt me forever. done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by rachel-fenichel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/navigation_tree.js, line 174 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeFHaNLtyMu5Ok4mQH:-KqeFHaNLtyMu5Ok4mQI:b-ahwvjj) ([raw file](https://github.com/google/blockly-devtools/blob/41b89e9be0b7988029fe41800d9726a9e25a3fc2/src/view/navigation_tree.js#L174)):*
> ```JavaScript
>         'text': componentName
>       };
>     this.getTree().create_node(parentName, data, 'last', null);
> ```

Does create_node return the newly created node?  I expect that it would, and then you could avoid the immediate get_node call.

---

*[src/view/navigation_tree.js, line 176 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeFMvA5I0RD0AJ90bV:-KqeFMvA5I0RD0AJ90bW:bkpnsgj) ([raw file](https://github.com/google/blockly-devtools/blob/41b89e9be0b7988029fe41800d9726a9e25a3fc2/src/view/navigation_tree.js#L176)):*
> ```JavaScript
>     this.getTree().create_node(parentName, data, 'last', null);
>     const node = this.getTree().get_node(id);
>     this.getTree().open_node(prefix);
> ```

Stash getTree() in a variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by chynu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/navigation_tree.js, line 174 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeFHaNLtyMu5Ok4mQH:-KqeG54lUv3yZFi116MC:bfiwkum) ([raw file](https://github.com/google/blockly-devtools/blob/41b89e9be0b7988029fe41800d9726a9e25a3fc2/src/view/navigation_tree.js#L174)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Does create_node return the newly created node?  I expect that it would, and then you could avoid the immediate get_node call.
</blockquote></details>

Unfortunately it returns the ID and not the node object itself. Though that node variable was never used, so I have now removed it.

---

*[src/view/navigation_tree.js, line 176 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeFMvA5I0RD0AJ90bV:-KqeGM--Eyp8AXUcRV_U:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/41b89e9be0b7988029fe41800d9726a9e25a3fc2/src/view/navigation_tree.js#L176)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Stash getTree() in a variable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177#-:-KqeJBeUckhxb5POhQ4j:bnfp4nl)*

**Comment by svouse** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/navigation_tree.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeDrmh5c0_CHPF9Szy:-KqeK2LPSoeR00iEr6f2:b-s7f042) ([raw file](https://github.com/google/blockly-devtools/blob/b71875f555f45f390638224fee7108731be63135/src/view/navigation_tree.js#L96)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

AAAAA. jsdoc will haunt me forever. done!
</blockquote></details>

Nit: maybe make more specific than 'returns jstree object', mainly just specifying what the object is used for or where it comes from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177#-:-KqeP07Q_RAKkV7Dv3wD:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by chynu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/view/navigation_tree.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/177#-KqeDrmh5c0_CHPF9Szy:-KqePTkzqmpm6XkgIr2g:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/b71875f555f45f390638224fee7108731be63135/src/view/navigation_tree.js#L96)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: maybe make more specific than 'returns jstree object', mainly just specifying what the object is used for or where it comes from
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/177)*

**Comment by chynu** [comment]
(Resolves #174)

**Pull request merged**
