### PR TITLE
Name framework

### PR DESCRIPTION
**Pull request by svouse**
Debug of block addition: fixes adding blocks to tree/giving them proper names
(known bug: apparently there is an undefined extra block created, which doesn't show up in the tree but yields a console error)
Adds file stubs for new resource popup views. Controllers are assumed to follow in subsequent PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/153)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/factory_utils.js, line 1246 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOUXdex4WpbXrwNaY6:-KqOUXdfkDPFSGXQjk34:b-r7tmqs) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/factory_utils.js#L1246)):*
> ```JavaScript
>   var textXmlStarter = '';
> 
>   if (opt_blockStarterText) {
> ```

Could we still keep the `.trim()` or is it happening before it is passed into this function? To avoid adding a text field with just whitespace.

---

*[src/controller/new_block_popup_controller.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOYQHo6D0S2ZGgTGoZ:-KqOYQHo6D0S2ZGgTGo_:b9cxncv) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/controller/new_block_popup_controller.js#L77)):*
> ```JavaScript
>           view.inputType, view.blockName, view.libraryName, view.blockText);
>       this.exit();
>       return;
> ```

Just curious -- why is there a `return`? Was there a bug when there wasn't? (Curious to know what that changes 0: )

---

*[src/model/block_definition.js, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOZBBq_Gr5ZCM-kWky:-KqOZBBq_Gr5ZCM-kWkz:b9g8xad) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/model/block_definition.js#L67)):*
> ```JavaScript
>    */
>   getJson() {
>     return {'id': this.type(), 'text': this.type()};
> ```

Nit: just occurred to me but would it perhaps be more readable if this were split into multiple lines (as json objects are usually represented)?

---

*[src/model/block_library_set.js, line 90 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOVMFadF2bl_4TCQKx:-KqOVMFadF2bl_4TCQKy:bjgwwh4) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/model/block_library_set.js#L90)):*
> ```JavaScript
>   getLibrary(blockType) {
>     for (let libraryName of this.getNames()) {
>       if (this.resources[libraryName].has(blockType).name) {
> ```

Doesn't `has()` return a boolean?

---

*[src/view/app_view.js, line 470 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOZt6MrI1Cb8VJptUj:-KqOZt6MrI1Cb8VJptUk:b-amibuh) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/app_view.js#L470)):*
> ```JavaScript
>    * @param {?Resource} resource The resource to display upon switching the view.
>    */
>   switchEnvironment(element, resource) {
> ```

I feel like `switchEnvironment()` belongs in AppController and that any view changes can be put into a function in AppView (perhaps still called switchEnvironment). To switch "environments" we would first call the method in AppController, but it would then implicitly call the "helper" function in the app view. What do you think?

(just for the MVC model)

---

*[src/view/app_view.js, line 472 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOWXDLfi21TKakp1Cy:-KqOWXDLfi21TKakp1Cz:banzdrk) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/app_view.js#L472)):*
> ```JavaScript
>   switchEnvironment(element, resource) {
>     var resourceReference;
>     if (element == 'workspaceContents' || element == 'workspaceConfig') {
> ```

I think these would be better put in constants under some class so that you don't run the risk of mistyping these? (Both when they are parameters and when used in comparison here)

---

*[src/view/new_block_popup_view.js, line 53 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqO_qrkbSZBUb5aWrdI:-KqO_qrkbSZBUb5aWrdJ:b-ptpkos) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_block_popup_view.js#L53)):*
> ```JavaScript
>     <span id="warning_text">This block already exists!</span><br><br>
>   Library<span class="red">*</span><br>
>     <input type="text" id="library" placeholder="my_library"></input>
> ```

Better yet, we could probably have a dropdown that updates with the current library names? That way we can avoid making the users have to check and type exactly character-by-character the name of their library.

---

*[src/view/new_library_popup_view.js, line 32 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOYppTPQ0ntCIbooHE:-KqOYppTPQ0ntCIbooHF:b-1fkl2k) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_library_popup_view.js#L32)):*
> ```JavaScript
>  * @author celinechoo (Celine Choo), sagev (Sage Vouse)
>  */
> class NewLibraryPopupView extends NewResourcePopupView {
> ```

There probably needs to be a new popup constant in `PopupController` if you are planning on creating more popups? For this class as well as the New Project/Toolbox/WorkspaceContents popup.

---

*[src/view/new_toolbox_popup_view.js, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOXzZiGXPclY2bE752:-KqOXzZiGXPclY2bE753:b-m11n6p) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_toolbox_popup_view.js#L34)):*
> ```JavaScript
> class NewToolboxPopupView extends NewResourcePopupView {
>   // TODO: Add functions.
> }
> ```

Nit: space at end of file? (not sure what that icon in Reviewable means but i think it means there is no space at the end of the file currently)

---

*[src/view/new_workspace_contents_popup_view.js, line 35 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOY66uF4-RD_xJIxlW:-KqOY66uF4-RD_xJIxlX:b-9rtmzs) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_workspace_contents_popup_view.js#L35)):*
> ```JavaScript
> class NewWorkspaceContentsPopupView extends NewResourcePopupView {
>   // TODO: Add functions.
> }
> ```

Nit: space at end of file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153)*

**Comment by svouse** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/factory_utils.js, line 1246 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOUXdex4WpbXrwNaY6:-KqObDlWBgdzSHW8Aby3:bb7ohn6) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/factory_utils.js#L1246)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Could we still keep the `.trim()` or is it happening before it is passed into this function? To avoid adding a text field with just whitespace.
</blockquote></details>

sgtm

---

*[src/controller/new_block_popup_controller.js, line 77 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOYQHo6D0S2ZGgTGoZ:-KqOd19GShi_gy71Xof0:b-fz9j3k) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/controller/new_block_popup_controller.js#L77)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Just curious -- why is there a `return`? Was there a bug when there wasn't? (Curious to know what that changes 0: )
</blockquote></details>

to my knowledge, nothing? Removed

---

*[src/model/block_definition.js, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOZBBq_Gr5ZCM-kWky:-KqOd6KcePLuVWlJtLRh:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/model/block_definition.js#L67)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: just occurred to me but would it perhaps be more readable if this were split into multiple lines (as json objects are usually represented)?
</blockquote></details>

Done.

---

*[src/model/block_library_set.js, line 90 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOVMFadF2bl_4TCQKx:-KqOjNvchQ1147gj9n-j:b-mmeayb) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/model/block_library_set.js#L90)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Doesn't `has()` return a boolean?
</blockquote></details>

(Fixed/intentionally broken as per our discussion)

---

*[src/view/app_view.js, line 470 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOZt6MrI1Cb8VJptUj:-KqOrqORxXluYKmVM0G8:b-7gc7l2) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/app_view.js#L470)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I feel like `switchEnvironment()` belongs in AppController and that any view changes can be put into a function in AppView (perhaps still called switchEnvironment). To switch "environments" we would first call the method in AppController, but it would then implicitly call the "helper" function in the app view. What do you think?

(just for the MVC model)
</blockquote></details>

Moved it all to AppController

---

*[src/view/app_view.js, line 472 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOWXDLfi21TKakp1Cy:-KqP1WpJu-TJwwrPerdO:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/app_view.js#L472)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think these would be better put in constants under some class so that you don't run the risk of mistyping these? (Both when they are parameters and when used in comparison here)
</blockquote></details>

Done.

---

*[src/view/new_block_popup_view.js, line 53 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqO_qrkbSZBUb5aWrdI:-KqOjpQWTlhyqfVqHIi1:b6zclho) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_block_popup_view.js#L53)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Better yet, we could probably have a dropdown that updates with the current library names? That way we can avoid making the users have to check and type exactly character-by-character the name of their library.
</blockquote></details>

sounds good//added an issue #155 

---

*[src/view/new_library_popup_view.js, line 32 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOYppTPQ0ntCIbooHE:-KqObPTFwLMPZP8MWB0S:bcxky2u) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_library_popup_view.js#L32)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

There probably needs to be a new popup constant in `PopupController` if you are planning on creating more popups? For this class as well as the New Project/Toolbox/WorkspaceContents popup.
</blockquote></details>

Yup; I figure in subsequent PRs I'll work something out controller side

---

*[src/view/new_toolbox_popup_view.js, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOXzZiGXPclY2bE752:-KqObMVVcQTHkUdo-XrK:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_toolbox_popup_view.js#L34)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: space at end of file? (not sure what that icon in Reviewable means but i think it means there is no space at the end of the file currently)
</blockquote></details>

Done.

---

*[src/view/new_workspace_contents_popup_view.js, line 35 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOY66uF4-RD_xJIxlW:-KqObMAnLaUDBz4B4EIX:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_workspace_contents_popup_view.js#L35)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: space at end of file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/app_controller.js, line 378 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqP_Nx3eZVxwpjsGAfN:-KqP_Nx3eZVxwpjsGAfO:b34am8t) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/controller/app_controller.js#L378)):*
> ```JavaScript
>       this.view[view][resourceReference] = resource;
>     }
>     this.view.switchView(this.view[view], resource);
> ```

Glub I feel like some parts of the tab switching/modal (line 378-381) belong in the view but also I've been known to confuse this boundary / not sure how Important distinguishing this boundary for this particular function actually is... so I suppose I will just say: I have vague feelings about this belonging in AppView (just the view/modal parts) and will wait for either Andrew or Rachel to ignore or address this. /__\

---

*[src/view/new_library_popup_view.js, line 32 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqOYppTPQ0ntCIbooHE:-KqPa9W7fsHDbdWf7yyQ:bdghy3p) ([raw file](https://github.com/google/blockly-devtools/blob/026f0a693a1b953c0b18bc4d785a98053996293f/src/view/new_library_popup_view.js#L32)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Yup; I figure in subsequent PRs I'll work something out controller side
</blockquote></details>

Yep. I'll probably be doing the popup PR's for the rest of today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153#-:-KqPaM8H7fvB-kTXis0L:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Reviewed 3 of 18 files at r1, 3 of 10 files at r2.
Review status: 6 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/factory_utils.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqPit48rYSSBVJLaTVa:-KqPit48rYSSBVJLaTVb:b-47tily) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/factory_utils.js#L1246)):*
> ```JavaScript
>   var textXmlStarter = '';
> 
>   if (opt_blockStarterText.trim()) {
> ```

Not your code, but it should be `optBlockStarterText` instead of `opt_blockStarterText`.

---

*[src/controller/app_controller.js, line 75 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqPij9YVduC5Bc-yWj0:-KqPij9YVduC5Bc-yWj1:b-cmkw7b) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/controller/app_controller.js#L75)):*
> ```JavaScript
> 
>   /* prefixes for classes when used in variable names */
>   static get variable_block() {
> ```

These behave as constants and should be named like constants, in all caps.

---

*[src/controller/app_controller.js, line 378 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqP_Nx3eZVxwpjsGAfN:-KqPwX_RRqA8ibl_9B1K:b-mtilav) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/controller/app_controller.js#L378)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Glub I feel like some parts of the tab switching/modal (line 378-381) belong in the view but also I've been known to confuse this boundary / not sure how Important distinguishing this boundary for this particular function actually is... so I suppose I will just say: I have vague feelings about this belonging in AppView (just the view/modal parts) and will wait for either Andrew or Rachel to ignore or address this. /__\
</blockquote></details>

I like this implementation. Most of the mapping from resource to editor view (the "business logic") is in the controller, while the view implementation details are handled by the view class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153)*

**Comment by AnmAtAnm** [comment]
One nit, then :lgtm: 

---

Review status: 6 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153#-:-KqPxMfsKqN5R4blRTXW:b296f8f)*

**Comment by AnmAtAnm** [comment]
Also... I can't count. (Two nits.)

---

Review status: 6 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153#-:-KqPxTMMXh4Ca3QL6lUj:bhcpq14)*

**Comment by rachel-fenichel** [comment]
LGTM after andrew's nits.

---

Reviewed 8 of 18 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153#-:-KqQ0Jv3Holjat77AyZI:bc8js54)*

**Comment by svouse** [comment]
Review status: 16 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/factory_utils.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqPit48rYSSBVJLaTVa:-KqQ-VeNO_5RMvYus-t3:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/factory_utils.js#L1246)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Not your code, but it should be `optBlockStarterText` instead of `opt_blockStarterText`.
</blockquote></details>

Done.

---

*[src/controller/app_controller.js, line 75 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/153#-KqPij9YVduC5Bc-yWj0:-KqQ0R-DWD1FwTyUxEPc:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3d2af1a8650706afda3b43a46abb4a0a6f22e585/src/controller/app_controller.js#L75)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

These behave as constants and should be named like constants, in all caps.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 16 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/153#-:-KqQ29eHfbHrNK-kqhpS:bnfp4nl)*

**Pull request merged**
