### PR TITLE
Resource and ResourceSet implementation

### PR DESCRIPTION
**Pull request by svouse**
**Summary:** Fills in unimplemented functions in resource.js and resource_set.js*. Establishes implications for saving and data management.

**Goal:** Doesn't break anything, implemented functions are valid. Implications for saving and data management are discussed and clear before other changes are pulled.

**Specifically Includes:**
- Basic implementation of remaining functions

**Reason for Isolation of Such Small Edits//Changes to Discuss:**
- Removal of isDirty from Resource classes, to be moved to either EditorController or the controllers it manages (after considering outdated block_library_Controller.js and a TODO on line 952 of factory_utils.js)
- Use of (formerly tree-specific) JSON for local storage and loading (NOTE: post-this PR, the json of Resource classes will be changed to provide information for retrieving the object itself)

**Immediately Following this PR:**
Implementations for methods in (in given order, broken in to PRs by class**):
- Project
- BlockLibrary
- Toolbox
- WorkspaceContents
- Workspace Configuration
- all ResourceSets (in same order as aforementioned classes, also broken up by class)

*except getExportData, as will be the case for the first round of model PRs
**meaning relevant Controller functions will be changed

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/121)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/resource.js, line 23 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSN46ZRnho87Bo84q6:-KpSN46ZRnho87Bo84q7:b2suhvl) ([raw file](https://github.com/google/blockly-devtools/blob/6e226616185ea4bcb47d1471767af977a0f67260/src/model/resource.js#L23)):*
> ```JavaScript
> 'use strict';
> 
> goog.provide('Resource');
> ```

`goog.require('goog.global')`?

---

*[src/model/resource.js, line 70 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSMvfQdP9E8dzmYids:-KpSMvfR-s9js0yvW5p2:bmequqr) ([raw file](https://github.com/google/blockly-devtools/blob/6e226616185ea4bcb47d1471767af977a0f67260/src/model/resource.js#L70)):*
> ```JavaScript
>    * @return {!Object} The JSON representation of the resource.
>    */
>   geJson() {
> ```

`getJson()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121)*

**Comment by svouse** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/resource.js, line 23 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSN46ZRnho87Bo84q6:-KpSOQpH4ov2DFCW-jmJ:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/6e226616185ea4bcb47d1471767af977a0f67260/src/model/resource.js#L23)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`goog.require('goog.global')`?
</blockquote></details>

Done.

---

*[src/model/resource.js, line 70 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSMvfQdP9E8dzmYids:-KpSORHJ6iEMgH31Zwaj:b-wksxhu) ([raw file](https://github.com/google/blockly-devtools/blob/6e226616185ea4bcb47d1471767af977a0f67260/src/model/resource.js#L70)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

`getJson()`?
</blockquote></details>

Rip I need to ge my life together

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121)*

**Comment by chynu** [comment]
:lgtm:

Also maybe add to the jsdoc in `getJson()` functions that it will be used for generating/loading metadata. (Sorry, forgot to comment this.)

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/resource.js, line 70 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSMvfQdP9E8dzmYids:-KpSVybHnWTUFDECAhPx:b-wexvda) ([raw file](https://github.com/google/blockly-devtools/blob/6e226616185ea4bcb47d1471767af977a0f67260/src/model/resource.js#L70)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Rip I need to ge my life together
</blockquote></details>

+1 that was a goo joke

---

*[src/model/resource_set.js, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSWINIHxLJPtHRb7sY:-KpSWINIHxLJPtHRb7sZ:bxbmq33) ([raw file](https://github.com/google/blockly-devtools/blob/f735dff9bfcfff31f692cc683e9b3ca0858fafa6/src/model/resource_set.js#L106)):*
> ```JavaScript
> 
>   /**
>    * Returns the JSON object for the  resource set's tree representation.
> ```

super duper Nit™ but i think there are two spaces between 'the' and 'resource' ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121#-:-KpSW3BzB3C6RNXRPY4e:bnfp4nl)*

**Comment by svouse** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/resource_set.js, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSWINIHxLJPtHRb7sY:-KpSYvbNVhNllljQX8Y5:b2wltm8) ([raw file](https://github.com/google/blockly-devtools/blob/f735dff9bfcfff31f692cc683e9b3ca0858fafa6/src/model/resource_set.js#L106)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

super duper Nit™ but i think there are two spaces between 'the' and 'resource' ?
</blockquote></details>

+1 good eyes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/resource.js, line 56 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSb5u-8stVzkFqtHU7:-KpSb5u-8stVzkFqtHU8:b-ffiymk) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource.js#L56)):*
> ```JavaScript
>    */
>   saveToLocalStorage() {
>     goog.global.localStorage[this.name] = this.getJson();
> ```

Copied from somewhere in the previous implementation, right?

---

*[src/model/resource_set.js, line 123 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSbOqUUIcmC0Qk3y63:-KpSbOqUUIcmC0Qk3y64:b-n8i77z) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource_set.js#L123)):*
> ```JavaScript
>   loadFromLocalStorage() {
>     const set = goog.global.localStorage[this.name];
>     this.resources = JSON.parse(set).children;
> ```

Add a TODO for input validation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121#-:-KpSbUBqydZYiorl_yon:bnfp4nl)*

**Comment by rachel-fenichel** [comment]
One question to consider, and LGTM

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/resource_set.js, line 77 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpScZBfJT2evhD_wudT:-KpScZBfJT2evhD_wudU:b-ulb9l3) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource_set.js#L77)):*
> ```JavaScript
>    */
>   remove(resourceName) {
>     delete this.resources[resourceName];
> ```

So deleting doesn't change what's on disk, only saving does?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121#-:-KpScgw3eLc64CWMCXqw:b-t1eogc)*

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/resource.js, line 56 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSb5u-8stVzkFqtHU7:-KpSgYnazXz77RdJ5acW:b6q91pt) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource.js#L56)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Copied from somewhere in the previous implementation, right?
</blockquote></details>

yup; block_library_storage.js (now noted) 

---

*[src/model/resource_set.js, line 77 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpScZBfJT2evhD_wudT:-KpSggrjV7DV42Xw5J-R:b-5hqsjt) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource_set.js#L77)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

So deleting doesn't change what's on disk, only saving does?
</blockquote></details>

Yup; although, we could totally change it if it proves annoying

---

*[src/model/resource_set.js, line 123 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/121#-KpSbOqUUIcmC0Qk3y63:-KpSgn3yx5SsaJIZtMIo:bb6un1j) ([raw file](https://github.com/google/blockly-devtools/blob/9fb99ca2d3f15630344b28ff3b7e7ad60884e9db/src/model/resource_set.js#L123)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Add a TODO for input validation.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/121#-:-KpShvWc5KxdMZuaDMK5:bnfp4nl)*

**Pull request merged**
