### PR TITLE
Toolbox/Workspace Editor: Block Library Categories

### PR DESCRIPTION
**Pull request by chynu**
Toolbox and workspace editor now display user-generated libraries as categories, so that they can add it into their toolbox.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/189)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[res/devtools_toolboxes.js, line 38 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjEzCAEDWzZPYM8QbN:-KqjEzCBQMyfbRssYg6O:bopkas3) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/res/devtools_toolboxes.js#L38)):*
> ```JavaScript
>  * @return {string} XML string of category which contains the blocks in the library.
>  */
> DevToolsToolboxes.createCategoryElement_ = function(libraryName, libraryXml) {
> ```

I can't find changes in any callers of this function.  Was the annotation wrong before?  If not, you'll need to change the callers.

---

*[src/factory_utils.js, line 745 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjG8vALF3CXjCicyys:-KqjG8vALF3CXjCicyyt:b-udfod3) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L745)):*
> ```JavaScript
> /**
>  * Get Blockly Block by rendering pre-defined block in workspace.
>  * @param {string} blockType Type of block that has already been defined.
> ```

Same question here (about modifying callers)

---

*[src/factory_utils.js, line 1222 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGSyGfdS2Emo9Y2To:-KqjGSyGfdS2Emo9Y2Tp:bdqld38) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1222)):*
> ```JavaScript
>  * @return {!Element} Category XML containing the given block types.
>  */
> FactoryUtils.generateCategoryXml = function(blocks, categoryName) {
> ```

The similarity in names between `getCategoryXml` and `generateCategoryXml` is confusing, given how different they actually are.  Considering changing the names.

---

*[src/factory_utils.js, line 1238 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGp-RsMoMKUkGxR1p:-KqjGp-RsMoMKUkGxR1q:b-hepk39) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1238)):*
> ```JavaScript
>   }
>   categoryElement.removeAttribute('xmlns');
>   categoryElement.setAttribute('colour', '260');
> ```

Hardcoded colour is surprising.  You may end up passing it in as an arg later.  Leaving it for now is fine.

---

*[src/factory_utils.js, line 1247 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjH95F0XrL9kSGVwVg:-KqjH95F0XrL9kSGVwVh:b-xjhxff) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1247)):*
> ```JavaScript
>  * @param {!Array.<!BlockDefinition>} blockDefinitions Array of BlockDefinition
>  *     objects to convert to Blockly blocks.
>  * @param {!Blockly.Workspace} workspace Hidden workspace used to generate Blockly
> ```

Used to generate Blockly.Block objects.

---

*[src/controller/workspace_controller.js, line 195 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjHi5T99yu4QSK-A0-:-KqjHi5T99yu4QSK-A00:b46sq6j) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/controller/workspace_controller.js#L195)):*
> ```JavaScript
>    */
>   updateEditorToolbox() {
>     const libraryXml = [];
> ```

Consider moving this function into shadowController.  It's the same here and in toolboxController.

---

*[src/model/block_definition.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjIIs6DcKXGY4UJXpa:-KqjIIs6DcKXGY4UJXpb:bm3r46u) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/model/block_definition.js#L62)):*
> ```JavaScript
> 
>   /**
>    * Defines block by adding it to the Blockly.Blocks map.
> ```

Add a note that if a block with this name is already defined, it will be overwritten. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by svouse** [comment]
+1 to Rachel's comments then :lgtm: 

---

Review status: 11 of 12 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189#-:-KqjLDpSXkLQV5AYLGoY:b6jbo50)*

**Comment by chynu** [comment]
Review status: 11 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[res/devtools_toolboxes.js, line 38 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjEzCAEDWzZPYM8QbN:-KqjLF04AUQorIKThDL9:b1cls4r) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/res/devtools_toolboxes.js#L38)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I can't find changes in any callers of this function.  Was the annotation wrong before?  If not, you'll need to change the callers.
</blockquote></details>

There are changes far up the call stack that eventually reach this point (it gets passed through as a parameter several times), but everything that passes through this function as `libraryXml` is indeed an XML object.

---

*[src/factory_utils.js, line 745 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjG8vALF3CXjCicyys:-KqjLWgCMWwHWymyGBpm:b4qvq9m) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L745)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Same question here (about modifying callers)
</blockquote></details>

This was a mistype. All calls to this method were actually strings.

---

*[src/factory_utils.js, line 1222 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGSyGfdS2Emo9Y2To:-KqjMHsvsVGMJP9HEV_e:b-vcji8x) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1222)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

The similarity in names between `getCategoryXml` and `generateCategoryXml` is confusing, given how different they actually are.  Considering changing the names.
</blockquote></details>

Removed `getCategoryXml()` because it is no longer used.

---

*[src/factory_utils.js, line 1238 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGp-RsMoMKUkGxR1p:-KqjMKx8IM707Q8Ol_Bc:b-djbn8o) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1238)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Hardcoded colour is surprising.  You may end up passing it in as an arg later.  Leaving it for now is fine.
</blockquote></details>

Hm, that is true. I kind of just copied what they did in the old version, but I made an issue for it (#192).

---

*[src/factory_utils.js, line 1247 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjH95F0XrL9kSGVwVg:-KqjMV1IarWgCgLotXqo:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1247)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Used to generate Blockly.Block objects.
</blockquote></details>

Done.

---

*[src/controller/workspace_controller.js, line 195 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjHi5T99yu4QSK-A0-:-KqjNkGJ65o7GWT1tIva:bqg6695) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/controller/workspace_controller.js#L195)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Consider moving this function into shadowController.  It's the same here and in toolboxController.
</blockquote></details>

As per pm, left as is (to preserve shadow controller's scope of responsibility)

---

*[src/model/block_definition.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjIIs6DcKXGY4UJXpa:-KqjNF-tC3GlWM9hV2xr:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/model/block_definition.js#L62)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Add a note that if a block with this name is already defined, it will be overwritten. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by rachel-fenichel** [comment]
One nit then lgtm

---

Review status: 9 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/block_definition.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjIIs6DcKXGY4UJXpa:-KqjOuU27NnVMAzeJ2sr:b-1rulv5) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/model/block_definition.js#L62)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm "Function is overwritten" is confusing.  "The previous entry in the Blockly.Blocks map will be overwritten..." is clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189#-:-KqjP0qJcxNIYDMOQK07:b-3of1rj)*

**Comment by chynu** [comment]
Review status: 9 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/model/block_definition.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjIIs6DcKXGY4UJXpa:-KqsaBElzArje1xISz0M:boirygr) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/model/block_definition.js#L62)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Hm "Function is overwritten" is confusing.  "The previous entry in the Blockly.Blocks map will be overwritten..." is clearer.
</blockquote></details>

Oh, actually I made it exit the function if the block was already defined, to avoid re-defining already defined functions. Does that contradict this statement? 0:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by AnmAtAnm** [comment]
Review status: 9 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[res/devtools_toolboxes.js, line 40 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxWKUk_aRgJr4l0gRA:-KqxWKUk_aRgJr4l0gRB:b-xxcadx) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/res/devtools_toolboxes.js#L40)):*
> ```JavaScript
> DevToolsToolboxes.createCategoryElement_ = function(libraryName, libraryXml) {
>   const categoryXml = `
>   ${Blockly.Xml.domToPrettyText(libraryXml)}
> ```

Why the backtick/template string if the entire string comes from the function call?

```
const categoryXml = Blockly.Xml.domToPrettyText(libraryXml);
```

---

*[src/model/block_definition.js, line 67 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXoJZkeuuvRMNHFOL:-KqxXoJZkeuuvRMNHFOM:b64bj0s) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L67)):*
> ```JavaScript
>   define() {
>     if (this.isDefined_) {
>       return;
> ```

Do we know the definition hasn't changed since last defined?  I don't see any timestamp or dirty flag to track this. It might be safest to always overwrite with the latest state.

---

*[src/model/block_definition.js, line 70 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXfif8U9me1Q86CS8:-KqxXfif8U9me1Q86CS9:bev6lyk) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L70)):*
> ```JavaScript
>     }
>     const json = this.json;
>     Blockly.Blocks[this.name || 'unnamed'] = {
> ```

No block definition should ever lack a name at this point. This should be an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by chynu** [comment]
Review status: 8 of 12 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[res/devtools_toolboxes.js, line 40 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxWKUk_aRgJr4l0gRA:-KqxZObXa4C1mUb-Pt55:bwgffp) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/res/devtools_toolboxes.js#L40)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Why the backtick/template string if the entire string comes from the function call?

```
const categoryXml = Blockly.Xml.domToPrettyText(libraryXml);
```
</blockquote></details>

Hm, not sure what I was thinking when I did this..

Also, this function is not necessary so I removed it.

---

*[src/model/block_definition.js, line 67 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXoJZkeuuvRMNHFOL:-KqxZxtPFF8D731cyMv1:b-m490dv) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L67)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Do we know the definition hasn't changed since last defined?  I don't see any timestamp or dirty flag to track this. It might be safest to always overwrite with the latest state.
</blockquote></details>

Oops, I didn't think about that. Removed the `isDefined` field.

---

*[src/model/block_definition.js, line 70 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXfif8U9me1Q86CS8:-Kqx_4oj6uxgl9tEB8GY:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L70)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

No block definition should ever lack a name at this point. This should be an error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by AnmAtAnm** [comment]
Review status: 8 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 201 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/189#-Kqxi-0bjBz0ExqMw31F:-Kqxi-0bjBz0ExqMw31G:bqqijpd) ([raw file](https://github.com/google/blockly-devtools/blob/8ad77b6a340001704fe83f71af8a369c7db24728/src/controller/block_editor_controller.js#L201)):*
> ```JavaScript
>     const jsonString = FactoryUtils.getBlockDefinition(
>           'JSON', this.view.editorWorkspace);
>     currentBlock.json = JSON.parse(jsonString);
> ```

I'd just store the JSON as a string in the BlockDefinition.

---

*[src/model/block_definition.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjIIs6DcKXGY4UJXpa:-KqxjW5HGcw9w43e5Abv:b-kux8xh) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/model/block_definition.js#L62)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Oh, actually I made it exit the function if the block was already defined, to avoid re-defining already defined functions. Does that contradict this statement? 0:
</blockquote></details>

Updated per below comment.

---

*[src/model/block_definition.js, line 70 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXfif8U9me1Q86CS8:-KqxjeIVuvx0eDgRvov1:b-tikaoq) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L70)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we actually throw error if `this.name` is not defined... just in case (before critically  adding to Blockly.Block).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by AnmAtAnm** [comment]
Review status: 8 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1238 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGp-RsMoMKUkGxR1p:-KqxmXajHAa2Nuwdxkdb:bxpo6zd) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1238)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Hm, that is true. I kind of just copied what they did in the old version, but I made an issue for it (#192).
</blockquote></details>

Add a TODO comment linking to the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 201 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/189#-Kqxi-0bjBz0ExqMw31F:-Kqxsql1eGx_pGhLFihZ:b-ds790j) ([raw file](https://github.com/google/blockly-devtools/blob/8ad77b6a340001704fe83f71af8a369c7db24728/src/controller/block_editor_controller.js#L201)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'd just store the JSON as a string in the BlockDefinition.
</blockquote></details>

The JSON is set in at least one other place, maybe more, so that would require changes to other callers.  (Not an objection, just an FYI.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by chynu** [comment]
Review status: 10 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/factory_utils.js, line 1238 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqjGp-RsMoMKUkGxR1p:-KqxvJB3DmNmVmanl3WB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/c9dfdf040b6b10b97883e42b728deec9e14cb456/src/factory_utils.js#L1238)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Add a TODO comment linking to the issue.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 201 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/189#-Kqxi-0bjBz0ExqMw31F:-KqxxnQ2PNliMPFEhAl2:b-bqgpdh) ([raw file](https://github.com/google/blockly-devtools/blob/8ad77b6a340001704fe83f71af8a369c7db24728/src/controller/block_editor_controller.js#L201)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

The JSON is set in at least one other place, maybe more, so that would require changes to other callers.  (Not an objection, just an FYI.)
</blockquote></details>

Converted to string.

---

*[src/model/block_definition.js, line 70 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/189#-KqxXfif8U9me1Q86CS8:-Kqxv353pL-fjACTGXUB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/6a3ce620af012a417c784ecca1641e330b288381/src/model/block_definition.js#L70)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Can we actually throw error if `this.name` is not defined... just in case (before critically  adding to Blockly.Block).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 8 of 12 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/189#-:-KqxyQ0RKeGbnS7lQxUo:bnfp4nl)*

**Review by svouse — APPROVED** [review]

**Pull request merged**
