### PR TITLE
Refactor: AppController

### PR DESCRIPTION
**Pull request by chynu**
Refactored all functions from `app_controller.js` into new refactor files. Once functions are all implemented, `app_controller_2.js` will replace `app_controller.js`.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/91)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 84 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTSRP_mSQLRbgy2zKK:-KoTSRP_mSQLRbgy2zKL:b1yyxvj) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/controller/app_controller_2.js#L84)):*
> ```JavaScript
>     this.BLOCK_FACTORY = 'BLOCK_FACTORY';
>     this.WORKSPACE_FACTORY = 'WORKSPACE_FACTORY';
>     this.EXPORTER = 'EXPORTER';
> ```

Being static constants, these should be values of `AppController2`, instead of `this`. Either fix or make a TODO.

---

*[src/controller/block_editor_controller.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTTFopvc-5cNdHiwPW:-KoTTFopvc-5cNdHiwPX:bi94s8e) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/controller/block_editor_controller.js#L166)):*
> ```JavaScript
>    * @private
>    */
>   getBlockTypeFromXml_(xmlText) {
> ```

TODO: Replace usage with JSON block definition.

---

*[src/view/app_view.js, line 115 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTTT_PK4WuCXXJzBzN:-KoTTT_PK4WuCXXJzBzO:b5fsxmp) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/view/app_view.js#L115)):*
> ```JavaScript
> 
>     /**
>      * Name of currently open modal.
> ```

Please clarify the docs a little more. Is it just a name? Are there a specific set of allowed/expected names? Are these the constants above? Do the names have other roles, such as &lt;div&gt; ids?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/91)*

**Comment by rachel-fenichel** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/91)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/app_controller_2.js, line 84 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTSRP_mSQLRbgy2zKK:-KoTkm5cUVhrBbbM3vim:b-txidbz) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/controller/app_controller_2.js#L84)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Being static constants, these should be values of `AppController2`, instead of `this`. Either fix or make a TODO.
</blockquote></details>

It seems like the only way to make truly static constants in JS is to either make `static get` functions that return a value or define constants at the very end of the file after the class is declared. I went for the former because the latter seems like a less readable option (since I presume the constant fields should be near the constructor).

---

*[src/controller/block_editor_controller.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTTFopvc-5cNdHiwPW:-KoTlZ_yzHUJg3-BzaeM:bjqbq7k) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/controller/block_editor_controller.js#L166)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Replace usage with JSON block definition.
</blockquote></details>

Added `TODO` comment.

---

*[src/view/app_view.js, line 115 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/91#-KoTTT_PK4WuCXXJzBzN:-KoTlce64PjrHDh3WAT8:b-f6iych) ([raw file](https://github.com/google/blockly-devtools/blob/3507a98099a40fc25e5abce2ad9f24a9cb568c82/src/view/app_view.js#L115)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Please clarify the docs a little more. Is it just a name? Are there a specific set of allowed/expected names? Are these the constants above? Do the names have other roles, such as &lt;div&gt; ids?
</blockquote></details>

Added to the JSdoc. I believe the modal field was meant to keep track of which dropdown menu was currently selected. It keeps track of dropdowns across editors in the app, which doesn't follow the new DevTools model. I kept it here for now but added a TODO to remove/fix after refactoring is finished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/91)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/91#-:-KoU2kBR8J6SVffsX0na:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
