### PR TITLE
Model: Removed Init Model Objects

### LINKED ISSUE #187: Eliminate 'MyFirstToolbox', WSContents', and 'WSConfig'
The project gets initialized with Toolbox, WorkspaceContents, and Workspaceconfiguration objects entitled 'MyFirstToolbox', WSContents', and 'WSConfig', respectively; however, they are not shown.

### PR DESCRIPTION
**Pull request by chynu**
Resolved #187. Eliminated dummy resource objects created upon loading application.

EDIT: Will now load sample resource objects into project on load.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/191)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/editor_controller.js, line 98 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqjKIpeWRuQBzKnjICI:-KqjKIpeWRuQBzKnjICJ:b-iz4vt9) ([raw file](https://github.com/google/blockly-devtools/blob/efcd8287f7f91d18286e08c1516d7be375d4e7c0/src/controller/editor_controller.js#L98)):*
> ```JavaScript
>     } else if (editor instanceof ToolboxController) {
>       this.currentEditor.loadToolbox(this.currentEditor.view.toolbox);
>       this.currentEditor.setResource(this.currentEditor.view.toolbox);
> ```

Irrelevant to this PR but I was heavily considering putting getCurrent<resource> methods somewhere (either the editorControllers or, as I was leaning towards, AppController). Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191)*

**Comment by svouse** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191#-:-KqjKei9U-_dSkCTaKgI:bnfp4nl)*

**Comment by chynu** [comment]
Will reopen after resolving what was discussed in #187.

**Comment by chynu** [comment]
### (PR update) Adding Sample Resources on Load

Sample resource objects loaded on jstree ready event. Dummy objects are still set to `null` within the editors on init, but are set afterwards within `NavigationTree`'s `populateTree()` function.

**Comment by chynu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/controller/editor_controller.js, line 98 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqjKIpeWRuQBzKnjICI:-KqyprVFV93PAuvBXIyN:b-nsld5b) ([raw file](https://github.com/google/blockly-devtools/blob/efcd8287f7f91d18286e08c1516d7be375d4e7c0/src/controller/editor_controller.js#L98)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Irrelevant to this PR but I was heavily considering putting getCurrent<resource> methods somewhere (either the editorControllers or, as I was leaning towards, AppController). Thoughts?
</blockquote></details>

Do you mean a getCurrentEditor() kind of method? It probably is better placed in AppController. There is a `this.currentEditor` field in EditorController, so adding it to that class would be a matter of changing references to a field (`this.currentEditor`) to references to a function (`this.getCurrentEditor()`). 
What led you to need this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191#-:-Kqyz3wyZC6cybt68Dhk:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/editor_controller.js, line 98 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqjKIpeWRuQBzKnjICI:-KqyxiKhpbUA0WZe0s81:b-j6h223) ([raw file](https://github.com/google/blockly-devtools/blob/efcd8287f7f91d18286e08c1516d7be375d4e7c0/src/controller/editor_controller.js#L98)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Do you mean a getCurrentEditor() kind of method? It probably is better placed in AppController. There is a `this.currentEditor` field in EditorController, so adding it to that class would be a matter of changing references to a field (`this.currentEditor`) to references to a function (`this.getCurrentEditor()`). 
What led you to need this function?
</blockquote></details>

AppController makes sense, field or method.

---

*[src/controller/workspace_controller.js, line 57 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/191#-Kqyz2PTZJ-cbcOdmt4V:-Kqyz2PTZJ-cbcOdmt4W:bcufcq3) ([raw file](https://github.com/google/blockly-devtools/blob/ee86ea7bb98914d711efcaae5f9eb9d5d058e43d/src/controller/workspace_controller.js#L57)):*
> ```JavaScript
>      * @type {!WorkspaceEditorView}
>      */
>     this.view = new WorkspaceEditorView(null, null);
> ```

If these are now null, we probably need null checking throughout the view class.

---

*[src/view/navigation_tree.js, line 127 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqyzL7pYVEj2R23PBhr:-KqyzL7pYVEj2R23PBhs:bqm4hsv) ([raw file](https://github.com/google/blockly-devtools/blob/ee86ea7bb98914d711efcaae5f9eb9d5d058e43d/src/view/navigation_tree.js#L127)):*
> ```JavaScript
>     projController.createToolbox('MyFirstToolbox');
>     projController.createWorkspaceContents('MyFirstWorkspace');
>     projController.createBlockLibrary('MyFirstBlockLibrary');
> ```

The `NavigationTree` isn't a good place to create model objects. Ideally, the `AppController` constructs these. Then the `AppController` registers the `JsTree` listener to call a populate method (within `AppController` or on `ProjectController`) that traverses the model to populate the tree (via `getNavTreeJson()`, most likely).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 57 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/191#-Kqyz2PTZJ-cbcOdmt4V:-KqzArIV2ytWgF5TUIpr:b-s17rvu) ([raw file](https://github.com/google/blockly-devtools/blob/ee86ea7bb98914d711efcaae5f9eb9d5d058e43d/src/controller/workspace_controller.js#L57)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

If these are now null, we probably need null checking throughout the view class.
</blockquote></details>

Done. If so I am figuring I will need to do this for the other classes as well (since they follow a similar structure).

---

*[src/view/navigation_tree.js, line 127 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqyzL7pYVEj2R23PBhr:-KqzADTa_oD-r_FQBezm:b-qq0qlz) ([raw file](https://github.com/google/blockly-devtools/blob/ee86ea7bb98914d711efcaae5f9eb9d5d058e43d/src/view/navigation_tree.js#L127)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The `NavigationTree` isn't a good place to create model objects. Ideally, the `AppController` constructs these. Then the `AppController` registers the `JsTree` listener to call a populate method (within `AppController` or on `ProjectController`) that traverses the model to populate the tree (via `getNavTreeJson()`, most likely).
</blockquote></details>

Moved to `AppController`. I created the model objects through the `create` functions in project controller, since they automatically handle adding to the navtree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191)*

**Comment by AnmAtAnm** [comment]
:lgtm:  for now with note about TODO for follow up.

---

Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/app_controller.js, line 273 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqzGph05GUHlISGpyJS:-KqzGph05GUHlISGpyJT:b-1v3yy5) ([raw file](https://github.com/google/blockly-devtools/blob/9239b2281fdd9cdb48e3e7a166cfe43eaab3e7ca/src/controller/app_controller.js#L273)):*
> ```JavaScript
>     // project controller.
>     this.tree.ready(() => {
>       this.populateTree();
> ```

TODO: Replace these `projController.create*(..)` methods below with model additions above. Then call some `projController` method to refresh the NavTree from the model.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191#-:-KqzHQZPOHQ-JlMNuKov:bfembj0)*

**Review by AnmAtAnm — APPROVED** [review]
LGTM for now with note about TODO for follow up.

**Comment by chynu** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/app_controller.js, line 273 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/191#-KqzGph05GUHlISGpyJS:-KqzIX3th5OZVCWNFwrw:b-rggjrg) ([raw file](https://github.com/google/blockly-devtools/blob/9239b2281fdd9cdb48e3e7a166cfe43eaab3e7ca/src/controller/app_controller.js#L273)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

TODO: Replace these `projController.create*(..)` methods below with model additions above. Then call some `projController` method to refresh the NavTree from the model.
</blockquote></details>

Added reference to #200.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/191)*

**Pull request merged**
