### PR TITLE
Tree fixes

### PR DESCRIPTION
**Pull request by svouse**
**Completed:**

- Tree displays appropriate text 
- The listener recognizes node types

**In progress:**
- Using context menus to complete basic operations (saving, deletion)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/112)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration_set.js, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpI9k1boVn4WRgmOFpW:-KpI9k1boVn4WRgmOFpX:b-baug6) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/model/workspace_configuration_set.js#L48)):*
> ```JavaScript
>    */
>   getJson() {
>     const workspaceConfigSetJson = {'id': 'WConf',
> ```

Nit: Fix spacing so that it's more readable?
e.g.
```JavaScript
const workspaceConfigSetJson = {
  'id': 'WConf',
  'text': 'Workspace Configurations',
  'children': super.getJson()
};
```

(And in other similar instances within this PR)

---

*[src/view/navigation_tree.js, line 280 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpIBAkO-2odoq6lFevZ:-KpIBAkO-2odoq6lFev_:bmcpk6u) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/view/navigation_tree.js#L280)):*
> ```JavaScript
>    * @param {string} id The id of the selected node.
>    */
>   respondToChoice(id) {
> ```

I feel like `respondToChoice(id)` is rather vague (kind of like `doThing()`) so maybe we can rename it to `switchViews(id)` or even `switchOnNavtreeClick(id)` or something a little more descriptive? Just for readability, haha /__\ 

---

*[src/view/navigation_tree.js, line 291 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpIAUy8sPZD3DOmxRTV:-KpIAUy8sPZD3DOmxRTW:b-pckv5f) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/view/navigation_tree.js#L291)):*
> ```JavaScript
>       //Here's where tab switching happens
>       console.log("Node type: Workspace Contents. No response has been coded.");
>     } else if (pref === WORKSPACE_CONFIG_PREFIX) {
> ```

Are we having separate views for `WorkspaceContents` and `WorkspaceConfiguration`s? I think if this is for tab switching, you can have one general one called `WORKSPACE` or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by svouse** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/workspace_configuration_set.js, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpI9k1boVn4WRgmOFpW:-KpL_U6tnZ4vLUQRJ722:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/model/workspace_configuration_set.js#L48)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: Fix spacing so that it's more readable?
e.g.
```JavaScript
const workspaceConfigSetJson = {
  'id': 'WConf',
  'text': 'Workspace Configurations',
  'children': super.getJson()
};
```

(And in other similar instances within this PR)
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 280 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpIBAkO-2odoq6lFevZ:-KpL_AGK6bJ5ADZ2MO3h:blnomoy) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/view/navigation_tree.js#L280)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I feel like `respondToChoice(id)` is rather vague (kind of like `doThing()`) so maybe we can rename it to `switchViews(id)` or even `switchOnNavtreeClick(id)` or something a little more descriptive? Just for readability, haha /__\ 
</blockquote></details>

I dig it; done.

---

*[src/view/navigation_tree.js, line 291 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpIAUy8sPZD3DOmxRTV:-KpL_K6YTykwl_QUNIgA:be42rzz) ([raw file](https://github.com/google/blockly-devtools/blob/d25fd08693f45545953f2ead78da17febcd00f7a/src/view/navigation_tree.js#L291)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Are we having separate views for `WorkspaceContents` and `WorkspaceConfiguration`s? I think if this is for tab switching, you can have one general one called `WORKSPACE` or something.
</blockquote></details>

I've changed the else if to accommodate for either within a single case; I'm keeping them separate because I'm using the prefix to configure the context menu

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112#-:-KpLkyYcG0_RMuid4jrl:bnfp4nl)*

**Review by chynu — APPROVED** [review]

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 7 files at r1, 5 of 6 files at r2, 4 of 5 files at r4.
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/project.js, line 57 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMAmIyMmCP_OCtxJhH:-KpMAmIyMmCP_OCtxJhI:byvlnpd) ([raw file](https://github.com/google/blockly-devtools/blob/790941307cdbb9f69462b7e6941e39c3b327bb17/src/model/project.js#L57)):*
> ```JavaScript
>      * @type {!BlockLibrarySet}
>      */
>     this.librarySet = new BlockLibrarySet("Library Set", this.name);
> ```

Single quotes, here and in the next few changed lines.

---

*[src/view/navigation_tree.js, line 285 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBEp3dmbuopI-2SbV:-KpMBEp3dmbuopI-2SbW:b-k1wuzg) ([raw file](https://github.com/google/blockly-devtools/blob/790941307cdbb9f69462b7e6941e39c3b327bb17/src/view/navigation_tree.js#L285)):*
> ```JavaScript
>     if (pref === LIBRARY_PREFIX) {
>       //Here's where tab switching happens
>       console.log("Node type: BlockLibray. No response has been coded.");
> ```

Single quotes.

---

*[src/view/navigation_tree.js, line 282 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBcanZbKoNEi0mg5h:-KpMBcanZbKoNEi0mg5i:b-k1wuzg) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L282)):*
> ```JavaScript
>    */
>   changeView(id) {
>     const pref = id.split("_")[0];
> ```

Single quotes.

---

*[src/view/navigation_tree.js, line 282 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBh6fKOLX2yMwkBnd:-KpMBh6fKOLX2yMwkBne:b-vb8pyr) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L282)):*
> ```JavaScript
>    */
>   changeView(id) {
>     const pref = id.split("_")[0];
> ```

Call this `const prefix` instead.  Calling it `pref` just makes it harder to understand.

---

*[src/view/navigation_tree.js, line 293 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBqSoddpLVxpifu9F:-KpMBqSoddpLVxpifu9G:b-tr5qbr) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L293)):*
> ```JavaScript
>       console.log("Node type: Workspace Contents or Configuration. No response has been coded.");
>     } else if (pref === BLOCK_PREFIX) {
>       //open the block
> ```

 Spaces after the slashes, capital letter at the beginning, and period at the end of the comment.

---

*[src/view/navigation_tree.js, line 303 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBvy0yLUfUVqbd8rm:-KpMBvy0yLUfUVqbd8rn:bevi1e1) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L303)):*
> ```JavaScript
>   makeTreeListener() {
>     $('#navigationTree').on('select_node.jstree', (e, data) => {
>       // collect id of first selected block
> ```

Comment formatting, here and below. 

---

*[src/view/navigation_tree.js, line 304 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBygYOniPOKV3H2bV:-KpMBygYOniPOKV3H2bW:b-k1wuzg) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L304)):*
> ```JavaScript
>     $('#navigationTree').on('select_node.jstree', (e, data) => {
>       // collect id of first selected block
>       const node = $('#navigationTree').jstree("get_selected")[0];
> ```

Single quotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by svouse** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/model/project.js, line 57 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMAmIyMmCP_OCtxJhH:-KpMCSv7Z7TtaLRHcPCB:b-886gsx) ([raw file](https://github.com/google/blockly-devtools/blob/790941307cdbb9f69462b7e6941e39c3b327bb17/src/model/project.js#L57)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Single quotes, here and in the next few changed lines.
</blockquote></details>

Fixed

---

*[src/view/navigation_tree.js, line 285 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBEp3dmbuopI-2SbV:-KpMD3Oz8eI3pWzp-Myq:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790941307cdbb9f69462b7e6941e39c3b327bb17/src/view/navigation_tree.js#L285)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Single quotes.
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 282 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBcanZbKoNEi0mg5h:-KpMCcIMUF2c-s0hFzC5:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L282)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Single quotes.
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 282 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBh6fKOLX2yMwkBnd:-KpMCmb8sRhdFE4KnyHf:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L282)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Call this `const prefix` instead.  Calling it `pref` just makes it harder to understand.
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 293 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBqSoddpLVxpifu9F:-KpMD8IedtOrfmyi6Vj8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L293)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

 Spaces after the slashes, capital letter at the beginning, and period at the end of the comment.
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 303 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBvy0yLUfUVqbd8rm:-KpMD8rS55YbDk1UrRDH:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L303)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Comment formatting, here and below. 
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 304 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMBygYOniPOKV3H2bV:-KpMDFNcWrwAQNrXW1p5:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/58af8d0ad9066c01640cc45e558c7745131d8f15/src/view/navigation_tree.js#L304)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Single quotes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by AnmAtAnm** [comment]
Review status: 4 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/project.js, line 62 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMC_XgUybboHIrf-9o:-KpMC_XgUybboHIrf-9p:bbyftlc) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/project.js#L62)):*
> ```JavaScript
>      * @type {!ToolboxSet}
>      */
>     this.toolboxSet = new ToolboxSet("Toolbox Set", this.name);
> ```

What is `'Toolbox Set'` used for?  Anything more than debugging?  How does it relate to the `id` and `text` in `toolboxSetJson`, below?

---

*[src/model/workspace_configuration_set.js, line 49 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMDnhrHEZg15tiXxE5:-KpMDnhsH9Lfi8oDEteD:bw1nvdd) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/workspace_configuration_set.js#L49)):*
> ```JavaScript
>   getJson() {
>     const workspaceConfigSetJson = {
>       'id': 'WConf',
> ```

Use the constant

---

*[src/model/workspace_contents_set.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpLvTG3aCUH1qhgJGWS:-KpLvTG3aCUH1qhgJGWT:b-mauom) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/workspace_contents_set.js#L57)):*
> ```JavaScript
>   getJson() {
>     const workspaceContentsSetJson = {
>       'id': 'WCont',
> ```

Use the WORKSPACE_CONTENTS_PREFIX constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 3 files at r5.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by svouse** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/project.js, line 62 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMC_XgUybboHIrf-9o:-KpMFxCdrz_X4ifm_Mx7:b-uc2fwz) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/project.js#L62)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

What is `'Toolbox Set'` used for?  Anything more than debugging?  How does it relate to the `id` and `text` in `toolboxSetJson`, below?
</blockquote></details>

It doesn't; I think I'm going to remove names of sets in the next PR

---

*[src/model/workspace_configuration_set.js, line 49 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMDnhrHEZg15tiXxE5:-KpMGMG599WK9l6mruIU:b-clqgxg) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/workspace_configuration_set.js#L49)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Use the constant
</blockquote></details>

The github preview of this comment looks like it's on a previous revision? 

---

*[src/model/workspace_contents_set.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpLvTG3aCUH1qhgJGWS:-KpMGwTV2XW_qff8D2Ia:b-ya81ng) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/workspace_contents_set.js#L57)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Use the WORKSPACE_CONTENTS_PREFIX constant.
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Comment by AnmAtAnm** [comment]
Minor comments making sure you use your constants (thats what they are there for). Also be consistent on the use of the `'_'` in the set ids (if they are remaining).

Beyond that, :lgtm: 

---

Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/model/block_library_set.js, line 86 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMI9I2IyfE4CGF7H9P:-KpMI9I2IyfE4CGF7H9Q:b-g3eagy) ([raw file](https://github.com/google/blockly-devtools/blob/ecdad5792f70c41c029ab5fed325db03b67968a1/src/model/block_library_set.js#L86)):*
> ```JavaScript
>   getJson() {
>     const librarySetJson = {
>       'id': 'BlockLibrary_',
> ```

I think this should be another constant use.

---

*[src/model/toolbox_set.js, line 76 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMILJFjtJLOHwjXIOm:-KpMILJFjtJLOHwjXIOn:b-lergep) ([raw file](https://github.com/google/blockly-devtools/blob/ecdad5792f70c41c029ab5fed325db03b67968a1/src/model/toolbox_set.js#L76)):*
> ```JavaScript
>   getJson() {
>     const toolboxSetJson = {
>       'id': 'Toolbox',
> ```

Other sets have a underscore. Change either to be consistent. I'm guessing it isn't necessary.

---

*[src/model/workspace_configuration_set.js, line 49 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMDnhrHEZg15tiXxE5:-KpMIn_eZ3YBtfM6ThHq:bd596hp) ([raw file](https://github.com/google/blockly-devtools/blob/9ba168c8920f429c99cbdcc0aa87ae3999acdf1a/src/model/workspace_configuration_set.js#L49)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

The github preview of this comment looks like it's on a previous revision? 
</blockquote></details>

You defined WORKSPACE_CONFIG_PREFIX and this looks like this and others should be using those constants.
(I probably replied before you made your last update.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112#-:-KpMJAHwP7QJ1_niWmyC:b-y29ori)*

**Comment by rachel-fenichel** [comment]
:lgtm: once you respond to Andrew's comments.

---

Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112#-:-KpMQ_6Y9XiXVlH2dQkY:bal0bx8)*

**Comment by svouse** [comment]
Review status: 1 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/model/block_library_set.js, line 86 at r5](https://reviewable.io:443/reviews/google/blockly-devtools/112#-KpMI9I2IyfE4CGF7H9P:-KpMOxJACQNP-6YOCzHK:b-1qobqg) ([raw file](https://github.com/google/blockly-devtools/blob/ecdad5792f70c41c029ab5fed325db03b67968a1/src/model/block_library_set.js#L86)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I think this should be another constant use.
</blockquote></details>

Oh cool-- fixed. Sorry for the misunderstanding. I changed the getJson methods so that they use a passed in prefix, such that the prefixes can be uniformly changed in the NavigationTree file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/112)*

**Pull request merged**
