### PR TITLE
Toolbox Editor (2/3): Add/Remove Categories, Separators

### PR DESCRIPTION
**Pull request by chynu**
Can now:
 - Add/remove a category (+ update preview)
 - Add/remove a separator (+ update preview)
 - Load the standard toolbox (+ update preview)
 - Load a standard category (+ update preview)

Cannot (for next PR):
 - Rename a category
 - Rearrange ordering of categories
 - Display shadow blocks correctly
 - Add color to categories

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/135)

### CODE REVIEW

**Comment by chynu** [comment]
Made identical pull request at #136.

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvqr-yH4FBBS9gmA6a:-Kpvqr-yH4FBBS9gmA6b:b-131kc8) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L96)):*
> ```JavaScript
>     // Transfers flyout blocks to category if creating the first category.
>     if (this.view.toolbox.getSelected().type == ListElement.TYPE_FLYOUT &&
>         this.view.editorWorkspace.getAllBlocks().length > 0) {
> ```

nit: you check this condition several times; would it be useful to make a function that just returns this value? (it's mostly just be a readability preference, and is tiny//okay if not done)

---

*[src/controller/toolbox_controller.js, line 143 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvvj946sK8oC-ePIY1:-Kpvvj946sK8oC-ePIY2:b1ab9xc) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L143)):*
> ```JavaScript
>     this.currentToolbox.getSelected().saveFromWorkspace(this.view.editorWorkspace);
>     this.view.selectTab(id, true);
>     this.view.toolbox.setXml(this.generateToolboxXml()); // bm
> ```

difference//need for this.currentToolbox? It doesn't seem to be used very much. Could you replace its references with this.view.toolbox? Or perhaps go the other route and use this.currentToolbox instead? (Although that'd be way more references to redo)

---

*[src/controller/toolbox_controller.js, line 1124 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvspezmCFYfUzdmqwz:-Kpvspf-TtPQ4XKRZbFr:bpr3fcf) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1124)):*
> ```JavaScript
>       // Update category editing buttons.
>       this.view.updateState(this.view.toolbox.getIndexById
>           (this.view.toolbox.getSelectedId()), this.view.toolbox.getSelected());
> ```

Nit: I'd keep getIndexById on the same line as its parameter, for readability

---

*[src/controller/toolbox_controller.js, line 1216 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvtQYWU3u2qZu9X_Wp:-KpvtQYWU3u2qZu9X_Wq:b-7cr5eh) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1216)):*
> ```JavaScript
>    * element is a separator.
>    * @param {string} color The color to change the selected category. Must be
>    *     a valid CSS string.
> ```

What happens if it isn't//where are we guaranteeing that it is?

---

*[src/model/toolbox.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvu2I3wAvO4YoyPERq:-Kpvu2I3wAvO4YoyPERr:br4rw8q) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/model/toolbox.js#L166)):*
> ```JavaScript
>     // Check if need to update flags.
>     this.hasVariableCategory = this.categoryList[index].custom == 'VARIABLE' ?
>         false : this.hasVariableCategory;
> ```

should these be functions//have parentheses?

---

*[src/view/toolbox_editor_view.js, line 426 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvuOiDLGifeI9n0EW3:-KpvuOiDLGifeI9n0EW4:b-tg8vny) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/view/toolbox_editor_view.js#L426)):*
> ```JavaScript
>    * tab map, and returns the tab.
>    * @param {string} id The ID of the separator.
>    * @param {!Element} The td DOM element representing the separator.
> ```

should this be @return?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvqr-yH4FBBS9gmA6a:-KpzshEGC7jFE5Kuv6sd:b-yheinc) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L96)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

nit: you check this condition several times; would it be useful to make a function that just returns this value? (it's mostly just be a readability preference, and is tiny//okay if not done)
</blockquote></details>

Good idea--thought of doing that but never really did. I now made a private helper function.

---

*[src/controller/toolbox_controller.js, line 143 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvvj946sK8oC-ePIY1:-KpzteuzV87zg37Dcc7a:bs72ws8) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L143)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

difference//need for this.currentToolbox? It doesn't seem to be used very much. Could you replace its references with this.view.toolbox? Or perhaps go the other route and use this.currentToolbox instead? (Although that'd be way more references to redo)
</blockquote></details>

Yeah, I'm beginning to think that we can get rid of the `this.currentToolbox` field altogether, since we have access to the view anyway. 

I removed the field and replaced all its references with `this.view.toolbox`.

---

*[src/controller/toolbox_controller.js, line 1124 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvspezmCFYfUzdmqwz:-KpzuhohvT2VXz96H0dE:b-5hy38l) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1124)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: I'd keep getIndexById on the same line as its parameter, for readability
</blockquote></details>

I put the first parameter on the same line (the second is on the next--it doesn't fit into 80char). (not sure if this helps/changes readability, oops)

---

*[src/controller/toolbox_controller.js, line 1216 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvtQYWU3u2qZu9X_Wp:-Kpzvevx1IQc4_omoxbO:bv1kllj) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1216)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

What happens if it isn't//where are we guaranteeing that it is?
</blockquote></details>

Ohh, good point. I can put something to check the input, but I'll probably do that in the next PR when I implement color picking (so I can actually test it correctly).  I'm fairly certain that the input is always a valid CSS string, since it's using `goog.ui.ColorPicker` (which gives the user a mini palette of colors to click/choose from), but it's definitely a good idea to check for that.

---

*[src/model/toolbox.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvu2I3wAvO4YoyPERq:-KpzwKxJmffkDWoD7TMm:b-mur9s3) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/model/toolbox.js#L166)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

should these be functions//have parentheses?
</blockquote></details>

Nope, this is the one-line if/else thing ([conditional ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator), apparently).

(Unless you were talking about the `this.hasVariableCategory`, which is a field and thus does not need parentheses?)

---

*[src/view/toolbox_editor_view.js, line 426 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvuOiDLGifeI9n0EW3:-KpzwtGaVPhFW-dPB6hQ:bd4ykzo) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/view/toolbox_editor_view.js#L426)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

should this be @return?
</blockquote></details>

Ohhh. you're right. Fixed jsdoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1124 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvspezmCFYfUzdmqwz:-Kq-1yG131OwY7VkYZyc:b-egl5ky) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1124)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I put the first parameter on the same line (the second is on the next--it doesn't fit into 80char). (not sure if this helps/changes readability, oops)
</blockquote></details>

it's a weird line tbh I don't think it's ever going to be pretty

---

*[src/controller/toolbox_controller.js, line 1216 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvtQYWU3u2qZu9X_Wp:-Kq-2BuO4JT2YSthHqSu:bb7ohn6) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1216)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Ohh, good point. I can put something to check the input, but I'll probably do that in the next PR when I implement color picking (so I can actually test it correctly).  I'm fairly certain that the input is always a valid CSS string, since it's using `goog.ui.ColorPicker` (which gives the user a mini palette of colors to click/choose from), but it's definitely a good idea to check for that.
</blockquote></details>

sgtm

---

*[src/model/toolbox.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvu2I3wAvO4YoyPERq:-Kq-2FKfu09ulTRlssCW:bjyutvv) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/model/toolbox.js#L166)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nope, this is the one-line if/else thing ([conditional ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator), apparently).

(Unless you were talking about the `this.hasVariableCategory`, which is a field and thus does not need parentheses?)
</blockquote></details>

cool just checking; thanks for the link!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 143 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvvj946sK8oC-ePIY1:-Kq-3OkVEHvyd8GM0RPF:b84tv1b) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L143)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Yeah, I'm beginning to think that we can get rid of the `this.currentToolbox` field altogether, since we have access to the view anyway. 

I removed the field and replaced all its references with `this.view.toolbox`.
</blockquote></details>

I suppose then a related query is will controllers get the current elements form their views in general? The workspace editor uses a current field, and I think the behavior should be the same across all controllers (unless there's specific reason not to)

---

*[src/controller/toolbox_controller.js, line 70 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-4UKdwPv-cCL4s5QN:-Kq-4UKdwPv-cCL4s5QO:b-iw13zx) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/controller/toolbox_controller.js#L70)):*
> ```JavaScript
> 
>     // Adds current toolbox to model.
>     this.projectController.addToolbox(this.view.toolbox);
> ```

reason ToolboxEditor updates the model but WorkspaceEditor does not?

---

*[src/controller/toolbox_controller.js, line 256 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-4jtnwmn3q5pEYvSU:-Kq-4jtnwmn3q5pEYvSV:b-dpvin6) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/controller/toolbox_controller.js#L256)):*
> ```JavaScript
>    * when switching from simple flyout to categories, or categories to simple
>    * flyout. More expensive than simply updating the flyout or toolbox.
>    * @param {!Element} Tree of XML elements
> ```

missing param name before description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 143 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvvj946sK8oC-ePIY1:-Kq-8iC3K5J5MwdL_gpW:b72rprx) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L143)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

I suppose then a related query is will controllers get the current elements form their views in general? The workspace editor uses a current field, and I think the behavior should be the same across all controllers (unless there's specific reason not to)
</blockquote></details>

Yep, good point. I removed the current fields across both controllers.

---

*[src/controller/toolbox_controller.js, line 1124 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-KpvspezmCFYfUzdmqwz:-Kq-2ke5bYaFy5IRrd-J:bskrtl4) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/controller/toolbox_controller.js#L1124)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

it's a weird line tbh I don't think it's ever going to be pretty
</blockquote></details>

Oops, oh well..!

---

*[src/controller/toolbox_controller.js, line 70 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-4UKdwPv-cCL4s5QN:-Kq-7siutIRstJ9zcTMD:b-165wlr) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/controller/toolbox_controller.js#L70)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

reason ToolboxEditor updates the model but WorkspaceEditor does not?
</blockquote></details>

!!! You're right, there were some major inconsistencies. I edited the toolbox controller/view here (and the workspace controller/view for #138) so that (1) there is no longer a "current" toolbox/workspace element field in the controllers, and (2) the controller uses the project controller's create functions (`createToolbox()`, etc.) when creating the first resource objects on load.

---

*[src/controller/toolbox_controller.js, line 256 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-4jtnwmn3q5pEYvSU:-Kq-8tuZjfff4fIAGpZR:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/controller/toolbox_controller.js#L256)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

missing param name before description
</blockquote></details>

Done.

---

*[src/model/toolbox.js, line 166 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kpvu2I3wAvO4YoyPERq:-Kq-3CBuT2GM7spHrHN2:blyphgc) ([raw file](https://github.com/google/blockly-devtools/blob/6f220839a27d900bee38a0e4e3247198ce6fcb96/src/model/toolbox.js#L166)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

cool just checking; thanks for the link!
</blockquote></details>

No problem!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/toolbox.js, line 197 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-IqU2xcQPB-kGAOhZ:-Kq-IqU2xcQPB-kGAOh_:bqk0rpg) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L197)):*
> ```JavaScript
>    * Given the ID of a list element, returns that ListElement object.
>    * @param {string} id The ID of element to search for.
>    * @return {ListElement} Corresponding ListElement object in toolboxList, or
> ```

?ListElement

---

*[src/model/toolbox.js, line 416 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-J64sl7MXLHpE8LTZ:-Kq-J64sl7MXLHpE8LT_:b-42rql2) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L416)):*
> ```JavaScript
>    * Determines if a category with the 'VARIABLE' tag exists.
>    * @return {boolean} True if there exists a category with the Variables tag,
>    * false otherwise.
> ```

indent second line of return

---

*[src/model/toolbox.js, line 426 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-J8MYVlCFN522XVlD:-Kq-J8MYVlCFN522XVlE:bfoc7ue) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L426)):*
> ```JavaScript
>    * Determines if a category with the 'PROCEDURE' tag exists.
>    * @return {boolean} True if there exists a category with the Procedures tag,
>    * false otherwise.
> ```

indent second line of return 

---

*[src/view/toolbox_editor_view.js, line 347 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-JYylcZeHRqC5P5Jm:-Kq-JYylcZeHRqC5P5Jn:b6pk0cz) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/view/toolbox_editor_view.js#L347)):*
> ```JavaScript
>    * the workspace.
>    * @param {boolean} disable True if the workspace should be disabled, false
>    * if it should be enabled.
> ```

indent second line of param

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/toolbox.js, line 197 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-IqU2xcQPB-kGAOhZ:-Kq-KtfYP-ZSx0KwJBVq:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L197)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

?ListElement
</blockquote></details>

Done.

---

*[src/model/toolbox.js, line 416 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-J64sl7MXLHpE8LTZ:-Kq-KydvtQsPylWUX13o:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L416)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

indent second line of return
</blockquote></details>

Done.

---

*[src/model/toolbox.js, line 426 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-J8MYVlCFN522XVlD:-Kq-Kz0RZyym-spQUb4f:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/model/toolbox.js#L426)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

indent second line of return 
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 347 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-JYylcZeHRqC5P5Jm:-Kq-L5F4HvUuzo3joY09:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3903afce4b72bb4c7cba6d97cf39cbc3bb746ad5/src/view/toolbox_editor_view.js#L347)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

indent second line of param
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Comment by AnmAtAnm** [comment]
Two tiny nits, and then :lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 170 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-Ve7c7QRuZXq4uX9t:-Kq-Ve7c7QRuZXq4uX9u:bfc0k0p) ([raw file](https://github.com/google/blockly-devtools/blob/987556f604798b55c22a7bd249e9293c07c79792/src/controller/toolbox_controller.js#L170)):*
> ```JavaScript
> 
>     // Check if user wants to remove current category.
>     const check = confirm('Are you sure you want to delete the currently selected '
> ```

window.confirm(..)

We should also talk about wrapping all confirm/prompt/alert with a callback interface API.  Not for this PR.

---

*[src/controller/toolbox_controller.js, line 196 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-W11sth30g1gEgmjf:-Kq-W11sth30g1gEgmjg:bdmrbp1) ([raw file](https://github.com/google/blockly-devtools/blob/987556f604798b55c22a7bd249e9293c07c79792/src/controller/toolbox_controller.js#L196)):*
> ```JavaScript
>     // set a default selected element not in toolbox list in the model.
>     if (!nextId) {
>       alert('You currently have no categories or separators. All your blocks' +
> ```

Also `window.alert(..)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135#-:-Kq-XD7UMWAYpR6_UTAY:b-drr1ht)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 170 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-Ve7c7QRuZXq4uX9t:-Kq-YzCNwNdMgOhhzeLB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/987556f604798b55c22a7bd249e9293c07c79792/src/controller/toolbox_controller.js#L170)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

window.confirm(..)

We should also talk about wrapping all confirm/prompt/alert with a callback interface API.  Not for this PR.
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 196 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/135#-Kq-W11sth30g1gEgmjf:-Kq-YzQzlztCmMVNzqIB:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/987556f604798b55c22a7bd249e9293c07c79792/src/controller/toolbox_controller.js#L196)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Also `window.alert(..)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/135)*

**Pull request merged**
