### PR TITLE
Modal data

### PR DESCRIPTION
**Pull request by svouse**
some model modal data

Implements remaining getExportData functions (preexisting ones left untouched for this PR, since this would require reworking of other app elements/break things immediately before demo)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/171)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/resource.js, line 112 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqdIcgpTU389-rhZv9w:-KqdIcgpTU389-rhZv9x:bo19zsk) ([raw file](https://github.com/google/blockly-devtools/blob/e9a4511360cddef7512a8ce9d02d540a83bd8836/src/model/resource.js#L112)):*
> ```JavaScript
>       };
>     } else if (!obj.web.filepath) {
>         obj.web.filebath = '';
> ```

filebath

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171)*

**Comment by svouse** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/resource.js, line 112 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqdIcgpTU389-rhZv9w:-Kqe6OFtdCKpzZnhFF5A:b-x3o6zl) ([raw file](https://github.com/google/blockly-devtools/blob/e9a4511360cddef7512a8ce9d02d540a83bd8836/src/model/resource.js#L112)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

filebath
</blockquote></details>

bathed code => clean code => healthy code, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/resource.js, line 112 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqdIcgpTU389-rhZv9w:-Kqe7elFymTH18Y4nEEu:bb7867m) ([raw file](https://github.com/google/blockly-devtools/blob/e9a4511360cddef7512a8ce9d02d540a83bd8836/src/model/resource.js#L112)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

bathed code => clean code => healthy code, right?
</blockquote></details>

Yup!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171#-:-Kqe7g4QZPDbsAgF9f5I:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_definition.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqeCM96ptWCMEmof8g3:-KqeCM96ptWCMEmof8g4:bsjqghg) ([raw file](https://github.com/google/blockly-devtools/blob/3aba6f3c0cc64b5fa9d0e6c7e2f87ab0581892db/src/model/block_definition.js#L99)):*
> ```JavaScript
>    * @return {!Object} The data needed to export the block.
>    */
>   getExportData() {
> ```

Blocks are not exported individually, so they don't have export data.  Remove this method.

---

*[src/model/block_library.js, line 157 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqeC_nFBBe16EiFLZTS:-KqeAux993SMAfP-9cMu:b-e1xme0) ([raw file](https://github.com/google/blockly-devtools/blob/3aba6f3c0cc64b5fa9d0e6c7e2f87ab0581892db/src/model/block_library.js#L157)):*
> ```JavaScript
>     let blockData = [];
>     for (let blockType of this.blocks) {
>       blockData.push(this.blocks[blockType].getExportData());
> ```

While you are quite there yet, replace getExportData() with getJson(), and rename this method to match.  You'll need it later.

---

*[src/model/block_library.js, line 169 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqeCUut_yGxDIvStBwT:-KqeCUut_yGxDIvStBwU:b-8muchr) ([raw file](https://github.com/google/blockly-devtools/blob/3aba6f3c0cc64b5fa9d0e6c7e2f87ab0581892db/src/model/block_library.js#L169)):*
> ```JavaScript
>     let data = Object.create(null);
>     super.buildMetadata(data);
>     data.blocks = getAllBlockData();
> ```

Don't iterate the blocks as part of the export data.

---

*[src/model/resource.js, line 112 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqdIcgpTU389-rhZv9w:-KqeBF-ans2z3QhNH4JI:b2nhg5f) ([raw file](https://github.com/google/blockly-devtools/blob/e9a4511360cddef7512a8ce9d02d540a83bd8836/src/model/resource.js#L112)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Yup!
</blockquote></details>

Ha!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171)*

**Comment by chynu** [comment]
:lgtm: :bathtub: 

---

Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171#-:-KqeE19jRxgWrhIW5ooD:b-drqhyv)*

**Comment by svouse** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_definition.js, line 99 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqeCM96ptWCMEmof8g3:-KqeDGWfSX7hmd4DOCWy:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3aba6f3c0cc64b5fa9d0e6c7e2f87ab0581892db/src/model/block_definition.js#L99)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Blocks are not exported individually, so they don't have export data.  Remove this method.
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 169 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/171#-KqeCUut_yGxDIvStBwT:-KqeGg7BcDrCw7_SI1DV:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3aba6f3c0cc64b5fa9d0e6c7e2f87ab0581892db/src/model/block_library.js#L169)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Don't iterate the blocks as part of the export data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171)*

**Comment by AnmAtAnm** [comment]
:lgtm: 

---

Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/171#-:-KqeO9xt8420h6oHPw5t:bg7igkv)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
