### PR TITLE
Popups: Modal Shadow Bugfix + New Block

### PR DESCRIPTION
**Pull request by chynu**
Fixed bug where modal shadow does not always appear on popups (now it does).
New block popup also checks for duplicates/invalid block type names.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/196)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/factory.css, line 748 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxY7QeCh7GFu1lBl1j:-KqxY7Qfk5CzFE268ScJ:bymqqbp) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/factory.css#L748)):*
> ```CSS
> }
> 
> #no_library_warning {
> ```

difference between no_library_warning and other warning text?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by rachel-fenichel** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/new_block_popup_view.js, line 130 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_ClwkDOS2qeqTCfM:-Kqx_ClwkDOS2qeqTCfN:b5el5b7) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L130)):*
> ```JavaScript
>    *     false if no param is given.
>    */
>   disable(opt_ifEnable) {
> ```

I don't like this API.  I was confused when I tried to read the code above, and couldn't understand why the choices were `disable()` and `disable(true)`.  I also don't like that the default param is false.

I prefer a required argument.  I'd be okay with keeping the name `disable`, or changing it to `setDisable`.

If this is an idiom that you've been seeing and copying and I just haven't noticed, let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/new_block_popup_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxZVtKFd50gJich50k:-KqxZVtKFd50gJich50l:b1jbtk1) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/controller/new_block_popup_controller.js#L97)):*
> if (hasWhitespace) {
>       this.view.showWarning(hasWhitespace, `Please enter a valid block type name.<br>
>           A block must not have whitespace in between characters. Use snake_case
>           or camelCase to differentiate between words in your block name.`);

I don't think we have a problem with whitespace in block names, though we don't use it for our own blocks. We should check that it does not trim() down to the empty string.
@rachel-fenichel ?

---

*[src/controller/popup_controller.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxZyYcEpuL27VsO_3D:-KqxZyYcEpuL27VsO_3E:b4oxv8t) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/controller/popup_controller.js#L54)):*
> ```JavaScript
>     this.view = null;
> 
>     $('#modalShadow').click(() => {
> ```

This will register the click handler every time a new popup is instantiated. 
I think you should unregister such handlers upon exit(), or register them once, centrally, in the AppView or AppController.

You can punt this for later with a TODO and issue.

---

*[src/view/new_block_popup_view.js, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_cwileGgoV6gHeLh:-Kqx_cwileGgoV6gHeLi:b-aoa6u5) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L109)):*
> ```JavaScript
>    * @param {string=} opt_warningMessage Message to present to user if warning
>    *     is shown. Defaults to 'This block name is already taken' if no param is
>    *     given.
> ```

That is an oddly specific default.  I recommend not making this parameter be optional.

---

*[src/view/new_block_popup_view.js, line 130 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_ClwkDOS2qeqTCfM:-Kqx_t46WV9xIFTmW4Du:bdznm1p) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L130)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I don't like this API.  I was confused when I tried to read the code above, and couldn't understand why the choices were `disable()` and `disable(true)`.  I also don't like that the default param is false.

I prefer a required argument.  I'd be okay with keeping the name `disable`, or changing it to `setDisable`.

If this is an idiom that you've been seeing and copying and I just haven't noticed, let me know.
</blockquote></details>

Strongly +1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by rachel-fenichel** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controller/new_block_popup_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxZVtKFd50gJich50k:-KqxbcsJB7EmQUjBpIRu:bbbxvl1) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/controller/new_block_popup_controller.js#L97)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

> if (hasWhitespace) {
>       this.view.showWarning(hasWhitespace, `Please enter a valid block type name.<br>
>           A block must not have whitespace in between characters. Use snake_case
>           or camelCase to differentiate between words in your block name.`);

I don't think we have a problem with whitespace in block names, though we don't use it for our own blocks. We should check that it does not trim() down to the empty string.
@rachel-fenichel ?
</blockquote></details>

What do you mean about trimming down to the empty string?  If the name is all whitespace I think we should disallow it, even if we're okay with whitespace in the names of blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/view/new_block_popup_view.js, line 130 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_ClwkDOS2qeqTCfM:-KqxcYXd5LzAQfBg6elQ:b-a9emnp) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L130)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Strongly +1
</blockquote></details>

I'd strongly prefer `setEnabled(boolean)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by rachel-fenichel** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/view/new_block_popup_view.js, line 130 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_ClwkDOS2qeqTCfM:-Kqxcm13J03oaacklzcb:b-ra74ya) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L130)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'd strongly prefer `setEnabled(boolean)`.
</blockquote></details>

Fine by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/factory.css, line 748 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxY7QeCh7GFu1lBl1j:-KqxbLd_8HRfDwOWHzKz:bd86qjr) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/factory.css#L748)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

difference between no_library_warning and other warning text?
</blockquote></details>

I don't think there's a difference? Also it's not used so I removed it.

---

*[src/controller/new_block_popup_controller.js, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxZVtKFd50gJich50k:-KqxsxTIXXA23pR6aOyC:b-9z0qjz) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/controller/new_block_popup_controller.js#L97)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

What do you mean about trimming down to the empty string?  If the name is all whitespace I think we should disallow it, even if we're okay with whitespace in the names of blocks.
</blockquote></details>

Removed whitespace catch.

---

*[src/controller/popup_controller.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxZyYcEpuL27VsO_3D:-Kqxnr4-K8qWKezbGorY:bz8ywiv) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/controller/popup_controller.js#L54)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

This will register the click handler every time a new popup is instantiated. 
I think you should unregister such handlers upon exit(), or register them once, centrally, in the AppView or AppController.

You can punt this for later with a TODO and issue.
</blockquote></details>

Done (added issue #197).

---

*[src/view/new_block_popup_view.js, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_cwileGgoV6gHeLh:-KqxfNiYRnTBWG_CNkAO:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L109)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

That is an oddly specific default.  I recommend not making this parameter be optional.
</blockquote></details>

Done.

---

*[src/view/new_block_popup_view.js, line 130 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/196#-Kqx_ClwkDOS2qeqTCfM:-KqxcOG3sgufmzyk9ZkF:bc4yusw) ([raw file](https://github.com/google/blockly-devtools/blob/ffc50f3ac709499d66da91daeb709d76674e6853/src/view/new_block_popup_view.js#L130)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Fine by me.
</blockquote></details>

Done (also this is the only instance of the convoluted disable/enable implementation).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 5 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/new_block_popup_controller.js, line 79 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxytI1x4NkGgwHV7s5:-KqxytI2BPEjcEQ721eP:bnuousx) ([raw file](https://github.com/google/blockly-devtools/blob/89bb3626fd9e9c7c610ed5b02faded6c85654440/src/controller/new_block_popup_controller.js#L79)):*
> ```JavaScript
> 
>   /**
>    * Checks if user-inputted block type is valid. Checks for duplicate, whitespace,
> ```

Remove comment about whitepace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by AnmAtAnm** [comment]
:lgtm: 

---

Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196#-:-KqxzXdqb2v4olht_Tdj:bg7igkv)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by chynu** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/new_block_popup_controller.js, line 79 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/196#-KqxytI1x4NkGgwHV7s5:-Kqxzr2GN1LaQiS5QsZ2:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/89bb3626fd9e9c7c610ed5b02faded6c85654440/src/controller/new_block_popup_controller.js#L79)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Remove comment about whitepace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/196#-:-Kqy-RlYhrckXEmDFxx2:bnfp4nl)*

**Pull request merged**
