### PR TITLE
Importing

### PR DESCRIPTION
**Pull request by svouse**
Adds resources from file to project

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/261)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 28 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHY5urZRTbUrbFcQUk:-KrHY5urZRTbUrbFcQUl:br1c4it) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L28)):*
> ```JavaScript
> goog.require('SaveProjectPopupController');
> goog.require('OpenProjectPopupController');
> goog.require('ImportResourcePopupController');
> ```

Alphabetical order of imports?

---

*[src/controller/read_write_controller.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYG-FgFi8-sSxe802:-KrHYG-FgFi8-sSxe803:b-kyv5ab) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L73)):*
> ```JavaScript
>     // TODO # 260: Eliminate need for buddyXml file.
>     this.buddyXmlLocations =
>       this.buddyXmlLocations = JSON.parse(localStorage.getItem('buddyXml')) ||
> ```

You put `this.buddyXmlLocations` twice?

---

*[src/controller/read_write_controller.js, line 108 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYMNsrjlY7wv0Ugoe:-KrHYMNsrjlY7wv0Ugof:bkjwvjo) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L108)):*
> ```JavaScript
>     let blockData = [];
>     for (let blockType of library.getBlockTypes()) {
>       // Issue #190
> ```

Perhaps better label this comment (as a TODO)?

---

*[src/controller/read_write_controller.js, line 178 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYoh4Ul7LSkFuahCW:-KrHYoh4Ul7LSkFuahCX:b-dk2gbf) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L178)):*
> ```JavaScript
> 
> BLOCKLY_OPTIONS['${workspaceConfig.name}'] =
>     '${attributes}';
> ```

Is this storing the options as a stringified version of JSON?

---

*[src/controller/read_write_controller.js, line 331 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHp_Wd0PZTqvvIW0eV:-KrHp_Wd0PZTqvvIW0eW:bgnnl3g) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L331)):*
> ```JavaScript
>     const pathElements = path.split('/');
>     let file = pathElements.slice(-1)[0];
>     file = file.replace('.js', '');
> ```

Consider using regular expressions to match `.js` at the end of the string (in case someone uses '.js' in the middle somehow, as well).

---

*[src/controller/read_write_controller.js, line 356 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHpuHwoTsKW6OKsd6P:-KrHpuHwoTsKW6OKsd6Q:bxs9nse) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L356)):*
> ```JavaScript
>     const pathElements = path.split('/');
>     let file = pathElements.slice(-1)[0];
>     file = file.replace('.js', '');
> ```

Same comment as above, with regex to match `.js` at the beginning. Here and in `constructWorkspaceContents()` and `constructWorkspaceConfig()` below.

---

*[src/controller/read_write_controller.js, line 397 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqOkYZxRCSFYVYwm6:-KrHqOkYZxRCSFYVYwm7:biawxg9) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L397)):*
> ```JavaScript
> 
>   /**
>    * Processes a string of library file data so that it can be parsed into JSON.
> ```

Perhaps add more detail as to what "processes" means (adding to the project model and displaying onto editor view, etc.), here and in similar functions below.

---

*[src/controller/read_write_controller.js, line 400 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqCAWRQunaASVLH_9:-KrHqCAWRQunaASVLH_A:b-kresu3) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L400)):*
> ```JavaScript
>    * @param {string} libraryName The name of the library.
>    * @param {string} dataString The string of the library's metadata.
>    * @param {Object<string,string>} buddyXml Object mapping block type to its xml.
> ```

Nit: `{!Object<string, string>}`?

---

*[src/controller/read_write_controller.js, line 481 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqrAuO5DEOusFZ4E_:-KrHqrAuO5DEOusFZ4Ea:b-i9gv78) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L481)):*
> ```JavaScript
>     refinedString = refinedString.replace('\';', '\'');
>     refinedString = refinedString.trim();
>     refinedString = refinedString.replace('document.onload = function() {', '');
> ```

Not a priority, but this may become an issue if a user uploads something that is not exactly as we expect it to be (e.g., if they have no spaces between assignment operator, or if they use 'let' instead of 'var,' etc. Perhaps add a TODO/file an issue (if there isn't one already) 

---

*[src/view/import_resource_controller.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHrGOFXbew05Q7tRXS:-KrHrGOFXbew05Q7tRXT:b-7r3y4b) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/view/import_resource_controller.js#L57)):*
> ```JavaScript
>     this.resourceType = resourceType;
> ```

Nit: delete extra newline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by svouse** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 28 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHY5urZRTbUrbFcQUk:-KrI-LzqDGSWnon6Bpfr:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L28)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Alphabetical order of imports?
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 73 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYG-FgFi8-sSxe802:-KrI-MJmpCgcfaRJQuML:bi0vcc) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L73)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

You put `this.buddyXmlLocations` twice?
</blockquote></details>

rippppppppp 

---

*[src/controller/read_write_controller.js, line 108 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYMNsrjlY7wv0Ugoe:-KrI-TkOIpJOFeQhKPfT:b-obdmsf) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L108)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Perhaps better label this comment (as a TODO)?
</blockquote></details>

Honestly the issue itself isn't really best represented there, so I removed it

---

*[src/controller/read_write_controller.js, line 178 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYoh4Ul7LSkFuahCW:-KrI00mZvSfHhLCcysyE:bj23638) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L178)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Is this storing the options as a stringified version of JSON?
</blockquote></details>

yup; it's the result of  'toolbox : BLOCKLY_TOOLBOX_XML[/* TODO: Insert name of ' +
        'imported toolbox to display here */],' + the result of stringifyOptions

---

*[src/controller/read_write_controller.js, line 331 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHp_Wd0PZTqvvIW0eV:-KrI3EBYI3-EaGMyMkyr:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L331)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Consider using regular expressions to match `.js` at the end of the string (in case someone uses '.js' in the middle somehow, as well).
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 356 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHpuHwoTsKW6OKsd6P:-KrI3DbFXFJKdToGyLXb:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L356)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Same comment as above, with regex to match `.js` at the beginning. Here and in `constructWorkspaceContents()` and `constructWorkspaceConfig()` below.
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 397 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqOkYZxRCSFYVYwm6:-KrI3PmnI7KYM0p12plT:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L397)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Perhaps add more detail as to what "processes" means (adding to the project model and displaying onto editor view, etc.), here and in similar functions below.
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 400 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqCAWRQunaASVLH_9:-KrI0MviXDqHMmaC0HfM:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L400)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: `{!Object<string, string>}`?
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 481 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHqrAuO5DEOusFZ4E_:-KrI0Rx0GlQQntOypCQA:bd55sfg) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L481)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Not a priority, but this may become an issue if a user uploads something that is not exactly as we expect it to be (e.g., if they have no spaces between assignment operator, or if they use 'let' instead of 'var,' etc. Perhaps add a TODO/file an issue (if there isn't one already) 
</blockquote></details>

I dig it/made a specific TODO 

---

*[src/view/import_resource_controller.js, line 57 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHrGOFXbew05Q7tRXS:-KrI3QzTc23RDFwY8qMR:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/view/import_resource_controller.js#L57)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: delete extra newline.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by chynu** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/read_write_controller.js, line 178 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrHYoh4Ul7LSkFuahCW:-KrI3r4JT0zf35Zg9XRu:bgpvvlo) ([raw file](https://github.com/google/blockly-devtools/blob/86b242f1dd11326de6254df772f9e1ed0edf21c8/src/controller/read_write_controller.js#L178)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

yup; it's the result of  'toolbox : BLOCKLY_TOOLBOX_XML[/* TODO: Insert name of ' +
        'imported toolbox to display here */],' + the result of stringifyOptions
</blockquote></details>

Aha, i see :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261#-:-KrI4KuTVGSyReoRjg3b:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Should import_resource_controller be in the `controller` directory?

---

Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 72 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrILgdWJ1ca0KsckaRt:-KrILgdWJ1ca0KsckaRu:b9nu9du) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/controller/read_write_controller.js#L72)):*
> ```JavaScript
>      */
>     // TODO # 260: Eliminate need for buddyXml file.
>     this.buddyXmlLocations = JSON.parse(localStorage.getItem('buddyXml')) ||
> ```

This should be a field of each BlockDefinition, avoiding the secondary mapping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261#-:-KrIP_3Fp6_pnM_ncOpB:b-es7szo)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/all_libs_classes_stylesheets.js, line 88 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIPlXhFdNqlYytbCeo:-KrIPlXhFdNqlYytbCep:bm4m10y) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/all_libs_classes_stylesheets.js#L88)):*
> ```JavaScript
>   appendScript('src/controller/project_controller.js');
>   appendScript('src/controller/popup_controller.js');
>   appendScript('src/controller/import_resource_controller.js');
> ```

The file added to git is not in this location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 327 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIY0G6OufJqUrCka5S:-KrIY0G6OufJqUrCka5T:bh0r0o8) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/controller/read_write_controller.js#L327)):*
> ```JavaScript
>   constructLibrary(path) {
>     const dataString = fs.readFileSync(path, 'utf8');
>     const pathElements = path.split('/');
> ```

Use [`path.sep`](https://nodejs.org/api/path.html#path_path_sep) to ensure Window compatibility.

There might be other functions from the `path` module that help out here. `path.parse` looks relevant.

---

*[src/controller/read_write_controller.js, line 352 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIYd_zmO44nyrYl7fG:-KrIYd_zmO44nyrYl7fH:b2nreh6) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/controller/read_write_controller.js#L352)):*
> ```JavaScript
>   constructToolbox(path) {
>     const dataString = fs.readFileSync(path, 'utf8');
>     const pathElements = path.split('/');
> ```

Same as above.

---

*[src/controller/read_write_controller.js, line 368 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIYgRl7Ls7IW0__g5d:-KrIYgRl7Ls7IW0__g5e:b-fmk49t) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/controller/read_write_controller.js#L368)):*
> ```JavaScript
>   constructWorkspaceContents(path) {
>     const dataString = fs.readFileSync(path, 'utf8');
>     const pathElements = path.split('/');
> ```

I see a pattern that looks like it needs a helper function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by AnmAtAnm** [comment]
Reviewed 2 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 401 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIZDSN4HJCkCrEyhvb:-KrIZDSN4HJCkCrEyhvc:b1lr79m) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/controller/read_write_controller.js#L401)):*
> ```JavaScript
>    * @param {Object<string, string>} buddyXml Object mapping block type to its xml.
>    */
>   // TODO #262: Make more robust.
> ```

Add: `TODO(#260): Eliminate buddyXml File for Library Import`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by AnmAtAnm** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/all_libs_classes_stylesheets.js, line 88 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/261#-KrIPlXhFdNqlYytbCeo:-Ku6baaZkDpE0c9mu1gg:bqdkzq7) ([raw file](https://github.com/google/blockly-devtools/blob/b059c7113d38508470dd180365317348508f7eb5/src/all_libs_classes_stylesheets.js#L88)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The file added to git is not in this location.
</blockquote></details>

Move the file.  Hoping the version checked in is the latest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/261#-:-Kvd42OcE7FLqPC5CvqF:bnfp4nl)*

**Pull request merged**
