### PR TITLE
Refactor: Block Factory

### PR DESCRIPTION
**Pull request by chynu**
Refactored 8/8 functions from `factory.js` into refactor files.

For future: implement functions.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/85)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOoCVu7_UROQN3Cwn:-KoPOoCVu7_UROQN3Cwo:bhv63mx) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L67)):*
> ```JavaScript
>    *
>    * @param {string} inputType Type of input (statement, value, dummy).
>    * @param {string} blockStarterText Starter text to place on block, given by user (optional).
> ```

Optional arguments should be the last arguments in a function's definition.

---

*[src/controller/block_editor_controller.js, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOwurhFoJpw4ZQwGR:-KoPOwurhFoJpw4ZQwGS:bmh5de7) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L104)):*
> ```JavaScript
> 
>   /**
>    * Render starter block (factory_base).
> ```

Fix jsdoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPPXk3e7JZbimvo9Ua:-KoPPXk3e7JZbimvo9Ub:bcmojw1) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L62)):*
> ```JavaScript
> 
>   /*
>    * The starting XML for the Block Factory main workspace. Contains the
> ```

"...Block Editor main workspace."

---

*[src/controller/block_editor_controller.js, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOoCVu7_UROQN3Cwn:-KoPPMNneMj3-JonQoQy:b2idcow) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L67)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Optional arguments should be the last arguments in a function's definition.
</blockquote></details>

I would also recommend using the `opt` prefix for such arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 62 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPPXk3e7JZbimvo9Ua:-KoPQdxtNIBEXSc-HQtu:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L62)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

"...Block Editor main workspace."
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOoCVu7_UROQN3Cwn:-KoPQdeWxp5WSNDHD4F4:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L67)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I would also recommend using the `opt` prefix for such arguments.
</blockquote></details>

Done.

---

*[src/controller/block_editor_controller.js, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOwurhFoJpw4ZQwGR:-KoPQz7mAnZdz1SYBbot:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L104)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Fix jsdoc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOwurhFoJpw4ZQwGR:-KoPRVX3u4i9saXsgVcL:b7aem1) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L104)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`disableEnableLink(..)` == **"Render start block."**?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by rachel-fenichel** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOwurhFoJpw4ZQwGR:-KoPVd48xzEVTSul8RKY:bfe4mmk) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L104)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`disableEnableLink(..)` == **"Render start block."**?
</blockquote></details>

Okay, next question is: does this function belong in the view instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85#-:-KoPYHT-4EtXissfXuZ5:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/85#-KoPOwurhFoJpw4ZQwGR:-KoSNc0QsPyve6oC3aau:bup2bov) ([raw file](https://github.com/google/blockly-devtools/blob/71e4461c2833d4ef21f2aed542164ddf706de266/src/controller/block_editor_controller.js#L104)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Okay, next question is: does this function belong in the view instead?
</blockquote></details>

Agreed.  It is manipulating the view state (buttons, in this case), presuming the 'Manual' bit is represented in the model.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/85)*

**Pull request merged**
