### PR TITLE
Workspace Editor

### PR DESCRIPTION
**Pull request by chynu**
Can now: 
 - Create a set of blocks to pre-load onto workspace.
 - Configure options for `Blockly.inject()`.
 - Reset WorkspaceConfiguration to default values via "Reset to Default" button.
 - Clear workspace editor (via "clear" button).

Cannot:
 - Import
 - Load to edit
 - Export

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/138)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 57 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpzsUnt1HCLgJZMr3O-:-KpzsUnt1HCLgJZMr3O0:b894jnc) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L57)):*
> ```JavaScript
>      * @type {!WorkspaceContents}
>      */
>     this.currentWorkspaceContents = new WorkspaceContents('WSContents');
> ```

Added a TODO #140 that I'll address in rewiring/multiples, outlining the sort of implications for development by the end of the week that stem from the current<element> structure

---

*[src/controller/workspace_controller.js, line 108 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kpzsrtkxpo5rlxz3xKG:-Kpzsrtkxpo5rlxz3xKH:b-ymxufo) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L108)):*
> ```JavaScript
>    * Used to completely reinject the contents/config preview. Used only
>    * when switching from simple flyout to categories, or categories to simple
>    * flyout. More expensive than simply updating flyout or toolbox.
> ```

Nit: is it necessary/useful to state that it's more expensive?

---

*[src/controller/workspace_controller.js, line 336 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztH7V7WZNLnEZxEAM:-KpztH7V7WZNLnEZxEAN:b-m0v9cj) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L336)):*
> ```JavaScript
>     // From wfactory_controller.js:generateNewOptions()
> 
>     // TODO: Add popup for workspace config so that preview is updated only when
> ```

Could this be made an issue?

---

*[src/controller/workspace_controller.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztU2fxTTM_4EjtAl_:-KpztU2fxTTM_4EjtAla:bpg9bqw) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L351)):*
> ```JavaScript
>    * @private
>    */
>   readOptions_() {
> ```

Potential rewiring nit for future consideration: maybe we could pass in the options object from the current configurations? 

---

*[src/view/app_view.js, line 138 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-1EDOXC7LPHZji4oJ:-Kq-1EDOXC7LPHZji4oK:bp8fe15) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/app_view.js#L138)):*
> ```JavaScript
>      * Moved in from app_controller.js
>      */
>     // TODO: Separate modal management into each editor (block definition editor,
> ```

Same TODO thing

---

*[src/view/app_view.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-1SMspvs165qgUatK:-Kq-1SMspvs165qgUatL:bi6stit) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/app_view.js#L351)):*
> ```JavaScript
>    * @param {string} label Name of MenuItem to enable/disable.
>    * @param {boolean} enable Whether to enable or disable the MenuItem (true is
>    * to enable).
> ```

indent second line of param by 4 spaces

---

*[src/view/workspace_editor_view.js, line 178 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpzuMEezXi9HzDceSGk:-KpzuMEezXi9HzDceSGl:bwpywv1) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/workspace_editor_view.js#L178)):*
> ```JavaScript
>   /**
>    * Add listeners for Workspace editor input elements. Used for creating/editing
>    * WorkspaceConfig objects.
> ```

mising param

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/138)*

**Comment by chynu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/workspace_controller.js, line 57 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpzsUnt1HCLgJZMr3O-:-Kq-4Ab80y9X8hgwXd5A:bpfk7c4) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L57)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Added a TODO #140 that I'll address in rewiring/multiples, outlining the sort of implications for development by the end of the week that stem from the current<element> structure
</blockquote></details>

Okay, maybe we can set up a quick meeting for this so we're on the same page about this.

---

*[src/controller/workspace_controller.js, line 108 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kpzsrtkxpo5rlxz3xKG:-Kq-4G9omplIIWxOh7X4:bneyrr8) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L108)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: is it necessary/useful to state that it's more expensive?
</blockquote></details>

Uhh to be quite honest I just pasted this in from the old code, but I think it's just to reiterate to future developers that we shouldn't reinject the preview every time there is a change (?).

---

*[src/controller/workspace_controller.js, line 336 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztH7V7WZNLnEZxEAM:-Kq-59v6Wr-Q1G3Hczn9:b8e2ev6) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L336)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Could this be made an issue?
</blockquote></details>

Oh, good point. Made new issue #141.

---

*[src/controller/workspace_controller.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztU2fxTTM_4EjtAl_:-Kq-5JgtbXfqaGvP_2Sd:bjvd57i) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L351)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Potential rewiring nit for future consideration: maybe we could pass in the options object from the current configurations? 
</blockquote></details>

But doesn't the controller have to read from user input at one point? We have to know what options from the checklist the user has checked (?). (Perhaps I am misunderstanding your suggestion)

---

*[src/view/app_view.js, line 138 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-1EDOXC7LPHZji4oJ:-Kq-5uUr7bHJstrVxrec:b-kq9t4t) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/app_view.js#L138)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Same TODO thing
</blockquote></details>

Oh, I forgot about this TODO. The TODO has been done, haha. I removed it :) 

---

*[src/view/app_view.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-1SMspvs165qgUatK:-Kq-62giCfTzXreCMyHF:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/app_view.js#L351)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

indent second line of param by 4 spaces
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 178 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpzuMEezXi9HzDceSGk:-Kq-69_aAFEZ3sM2eeye:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/view/workspace_editor_view.js#L178)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

mising param
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/138)*

**Comment by svouse** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/factory.css, line 451 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-LprmFQ7lgGWSPzfI:-Kq-LprmFQ7lgGWSPzfJ:b-mk076z) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/factory.css#L451)):*
> ```CSS
> }
> 
> #toolbox_section {
> ```

Nit: small comments to describe where these sections are/their purpose?

---

*[src/controller/workspace_controller.js, line 57 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpzsUnt1HCLgJZMr3O-:-KpzxdXCDIR2IyF2sF4E:b-ru678l) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L57)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Okay, maybe we can set up a quick meeting for this so we're on the same page about this.
</blockquote></details>

Sgtm; I'll probably hit you up closer to when it's immediately relevant to review the TODO (which I'll update as I think of things/feel free to update as well)

---

*[src/controller/workspace_controller.js, line 108 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kpzsrtkxpo5rlxz3xKG:-Kq-KRqSILH1MpmJlL-V:but51s5) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L108)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Uhh to be quite honest I just pasted this in from the old code, but I think it's just to reiterate to future developers that we shouldn't reinject the preview every time there is a change (?).
</blockquote></details>

I dig it

---

*[src/controller/workspace_controller.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztU2fxTTM_4EjtAl_:-Kq-L-stK7ccmDNjDEX2:b-shg6ba) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L351)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

But doesn't the controller have to read from user input at one point? We have to know what options from the checklist the user has checked (?). (Perhaps I am misunderstanding your suggestion)
</blockquote></details>

Oh I was wondering if we should pass in the options object to edit instead of creating the object to edit; I think the function itself/the functionality of it is solid- it's just a rewiring preference query

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/138)*

**Comment by chynu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/factory.css, line 451 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-Kq-LprmFQ7lgGWSPzfI:-Kq-PWnXHwjZddmP5yLc:bg72kgz) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/factory.css#L451)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nit: small comments to describe where these sections are/their purpose?
</blockquote></details>

I added a comment to section off the editor workspace related selectors (not sure if this was what you meant?)

---

*[src/controller/workspace_controller.js, line 351 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/138#-KpztU2fxTTM_4EjtAl_:-Kq-P0UsXQETu_RDzya7:bqgq4m3) ([raw file](https://github.com/google/blockly-devtools/blob/ee478644255d2eb431df86c9093487198753ff3e/src/controller/workspace_controller.js#L351)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Oh I was wondering if we should pass in the options object to edit instead of creating the object to edit; I think the function itself/the functionality of it is solid- it's just a rewiring preference query
</blockquote></details>

Oooooh I see. Left it for now (as decided in pm), will implement later if necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/138)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/138#-:-Kq00EwNEH_8HIIGc6XK:bnfp4nl)*

**Pull request merged**
