### PR TITLE
File processing

### PR DESCRIPTION
**Pull request by svouse**
Construct resource functions, filled in only to the point of processing files for filling in data. UI wiring.

pre final import PR

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/206)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/import_resource_popup_controller.js, line 34 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RtdRuTQxf5DFCo2j:-Kr3RtdSOZ9q0uhNyH7-:bmgr42e) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/import_resource_popup_controller.js#L34)):*
> ```JavaScript
>  * @author celinechoo (Celine Choo), sagev (Sage Vouse)
>  */
> class ImportResourcePopupController extends PopupController {
> ```

OpenProjectPopupController/View

---

*[src/controller/read_write_controller.js, line 284 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3QhVLxE5-62AFdAvZ:-Kr3QhVLxE5-62AFdAv_:b-p8dxsb) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L284)):*
> ```JavaScript
>       } else if (resource.resourceType == PREFIXES.WORKSPACE_CONFIG) {
>           this.constructWorkspaceConfig(resource[platform].filepath);
>       }
> ```

Log or throw error when unrecognized resource type is found.

---

*[src/view/app_view.js, line 89 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3R6tYiCXMH88dOwCQ:-Kr3R6tYiCXMH88dOwCR:bluyp4c) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L89)):*
> ```JavaScript
>         ['Save All', () => { this.appController.saveProject(); }],
>         ['Import', [
>           ['Project', () => {this.importProject()}],
> ```

Make this a top-level "Open project" menu item.
Import should be reserved for adding an existing project to the currently open project.

---

*[src/view/app_view.js, line 226 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RJCMNhudQpJsaaKr:-Kr3RJCMNhudQpJsaaKs:b-9lug6g) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L226)):*
> ```JavaScript
>    */
>   importLibrary() {
>     this.appController.readWriteController.importResource(PREFIXES.PROJECT);
> ```

import != open project.  Leave this unimplemented for now.
Better yet, add a console warning and a GitHub issue.
Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206)*

**Comment by AnmAtAnm** [comment]
Minor notes on Open vs Import. Otherwise :lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206#-:-Kr3Ss8nOk06_Vgr7RhT:b-83ns3y)*

**Comment by rachel-fenichel** [comment]
Are the things I commented on in readwriteController just setup for another PR?  If so, a few nits then LGTM.  If not, color me confused and then please explain.

---

Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/controller/import_resource_popup_controller.js, line 53 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3SdPH6A31vVQzhsrR:-Kr3SdPH6A31vVQzhsrS:b-tixeoo) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/import_resource_popup_controller.js#L53)):*
> ```JavaScript
>     /**
>      * Type of resource to import.
>      * @type {Array<Object>}
> ```

Should be string.

---

*[src/controller/read_write_controller.js, line 266 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr22-RTG4OSV817i-0K:-Kr22-RU5QfeiKv275X3:bbyzxzw) ([raw file](https://github.com/google/blockly-devtools/blob/90b369a3f573c98e197ae706f239be442180d8f3/src/controller/read_write_controller.js#L266)):*
> ```JavaScript
>         this.constructToolbox(resource.name, resource[platform].filepath);
>       } else if (resource.resourceType == PREFIXES.WORKSPACE_CONTENTS) {
>           this.constructWorkspaceContents(resource.name, resource[platform].filepath);
> ```

nit: indentation.  This line and the one two lines down.

---

*[src/controller/read_write_controller.js, line 294 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3T3-rIj7RB8QpRcqY:-Kr3T3-spr5XTU9BdsRh:b-12qeku) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L294)):*
> ```JavaScript
>    */
>   constructLibrary(path) {
>     const dataString = fs.readFileSync(path, 'utf8');
> ```

This doesn't do anything.

---

*[src/controller/read_write_controller.js, line 298 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3T9UOthOsHLVPRpj4:-Kr3T9UOthOsHLVPRpj5:b-ltclvb) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L298)):*
> ```JavaScript
> 
>   /**
>    * Construct a block based off of its metadata, and add it to the project.
> ```

A bunch of these say "based off of its metadata".  A block seems like it needs to be constructed from the file data, not the metadata.

---

*[src/controller/read_write_controller.js, line 311 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3TGWv5KVBEzVgIJFR:-Kr3TGWv5KVBEzVgIJFS:b-e825bp) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L311)):*
> ```JavaScript
>   constructToolbox(path) {
>     const dataString = fs.readFileSync(path, 'utf8');
>     let refinedString = this.processToolboxDataString(dataString);
> ```

This one and the next few also don't do anything?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206#-:-Kr3TmvU4zi1L_PxbArQ:b-h13yk7)*

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 266 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr22-RTG4OSV817i-0K:-Kr6pEXF8PA-vLnFGUNN:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/90b369a3f573c98e197ae706f239be442180d8f3/src/controller/read_write_controller.js#L266)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: indentation.  This line and the one two lines down.
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 284 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3QhVLxE5-62AFdAvZ:-Kr6pNZTJjX5nmQUNcyD:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L284)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Log or throw error when unrecognized resource type is found.
</blockquote></details>

Done.

---

*[src/controller/read_write_controller.js, line 294 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3T3-rIj7RB8QpRcqY:-Kr6qDoQE6_E2adduEm4:b-e48lhx) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L294)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This doesn't do anything.
</blockquote></details>

Yup-- not as of this PR

---

*[src/controller/read_write_controller.js, line 298 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3T9UOthOsHLVPRpj4:-Kr6q4aX7AIcgW9W0p-G:bu5bk4d) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L298)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

A bunch of these say "based off of its metadata".  A block seems like it needs to be constructed from the file data, not the metadata.
</blockquote></details>

Fixed (here and elsewhere)

---

*[src/controller/read_write_controller.js, line 311 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3TGWv5KVBEzVgIJFR:-Kr6qAomUSHU_irYCyCd:b-e48lhx) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/read_write_controller.js#L311)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This one and the next few also don't do anything?
</blockquote></details>

Yup-- not as of this PR

---

*[src/view/app_view.js, line 89 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3R6tYiCXMH88dOwCQ:-Kr6qH1qJhPhFfT0NpQs:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L89)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Make this a top-level "Open project" menu item.
Import should be reserved for adding an existing project to the currently open project.
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 226 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RJCMNhudQpJsaaKr:-Kr6qIxLiow3d5n-Dk7p:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L226)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

import != open project.  Leave this unimplemented for now.
Better yet, add a console warning and a GitHub issue.
Same below.
</blockquote></details>

Done.

---

*[src/controller/import_resource_popup_controller.js, line 34 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RtdRuTQxf5DFCo2j:-Kr6o2g0_t2kUipqlQZ7:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/import_resource_popup_controller.js#L34)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

OpenProjectPopupController/View
</blockquote></details>

Done.

---

*[src/controller/import_resource_popup_controller.js, line 53 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3SdPH6A31vVQzhsrR:-Kr6otrETz_lrep7x8XE:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/controller/import_resource_popup_controller.js#L53)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Should be string.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206)*

**Comment by AnmAtAnm** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 266 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr22-RTG4OSV817i-0K:-Kr6wM7lQ59t3K8J7Hhn:b3t3jsj) ([raw file](https://github.com/google/blockly-devtools/blob/90b369a3f573c98e197ae706f239be442180d8f3/src/controller/read_write_controller.js#L266)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Indentation in these else statements is still off.  Should only be two spaces.

---

*[src/view/app_view.js, line 226 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RJCMNhudQpJsaaKr:-Kr6w-JkblZwmM6DVe7C:bw04b8g) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L226)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`TODO(#228): ...`
And console warning for the unimplemented function, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206)*

**Comment by svouse** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/read_write_controller.js, line 266 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr22-RTG4OSV817i-0K:-Kr6wt0b99ZlDLvpzfIy:b903zt9) ([raw file](https://github.com/google/blockly-devtools/blob/90b369a3f573c98e197ae706f239be442180d8f3/src/controller/read_write_controller.js#L266)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Indentation in these else statements is still off.  Should only be two spaces.
</blockquote></details>

whoops fixed

---

*[src/view/app_view.js, line 226 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/206#-Kr3RJCMNhudQpJsaaKr:-Kr6x8Jo3CVjn25O77aY:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/790f179c5c71c9427c1b053bbd33184b04d98fd5/src/view/app_view.js#L226)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`TODO(#228): ...`
And console warning for the unimplemented function, please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206)*

**Comment by AnmAtAnm** [comment]
:lgtm_strong: 

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/206#-:-Kr6xlzGHex-niZCTYJb:b-uwkowd)*

**Review by AnmAtAnm — APPROVED** [review]
LGTM

**Pull request merged**
