### PR TITLE
Block Editor: Missing Features & Bug Fixes

### PR DESCRIPTION
**Pull request by chynu**
Block editor is fully functional. Can switch languages, block definition modes. Block preview also no longer collapses when switching views.

(Commit https://github.com/google/blockly-devtools/commit/8108a8d766e4692ddaee46f6f76aad2e18987a40 was meant to be a part of this PR.)

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/165)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 3 of 3 files at r1, 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_Gg6-lVQYT-PktDaN:-Kq_Gg6-lVQYT-PktDaO:b-tyg5b0) ([raw file](https://github.com/google/blockly-devtools/blob/969b346d3a2b239077aa2df84b4129826dde0323/src/controller/block_editor_controller.js#L140)):*
> ```JavaScript
>       Blockly.hideChaff();
>       mask.style.display = 'block';
>       languagePre.style.display = 'none';
> ```

languagePre.style.display is being set to none in both cases.  Seems suspicious.

---

*[src/controller/block_editor_controller.js, line 205 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_GNXn2VO_hVxMSK5s:-Kq_GNXn2VO_hVxMSK5t:b-qr9f5c) ([raw file](https://github.com/google/blockly-devtools/blob/969b346d3a2b239077aa2df84b4129826dde0323/src/controller/block_editor_controller.js#L205)):*
> ```JavaScript
>     const manual = format == BlockEditorController.FORMAT_MANUAL ? true : false;
> 
>     if (manual) {
> ```

It would be clearer to get rid of the variable and just do
`if (format == BlockEditorController.FORMAT_MANUAL) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165)*

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_Gg6-lVQYT-PktDaN:-Kq_Lz5y40t77NaYIUQA:b-uimm84) ([raw file](https://github.com/google/blockly-devtools/blob/969b346d3a2b239077aa2df84b4129826dde0323/src/controller/block_editor_controller.js#L140)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

languagePre.style.display is being set to none in both cases.  Seems suspicious.
</blockquote></details>

Hm, I see it as `'block'` and `'none'`? I changed it to jQuery to make it a bit more readable.

---

*[src/controller/block_editor_controller.js, line 205 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_GNXn2VO_hVxMSK5s:-Kq_M7NK69dA00cd-9Fx:b3fr35l) ([raw file](https://github.com/google/blockly-devtools/blob/969b346d3a2b239077aa2df84b4129826dde0323/src/controller/block_editor_controller.js#L205)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

It would be clearer to get rid of the variable and just do
`if (format == BlockEditorController.FORMAT_MANUAL) {`
</blockquote></details>

True -- done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165#-:-Kq_MzNMYm67CyYCLOd_:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 133 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_OZvv4VspETjvw2wD:-Kq_OZvv4VspETjvw2wE:bp2b1lx) ([raw file](https://github.com/google/blockly-devtools/blob/3dee1ca2c9f14c05fed5645a52ac85354d7297c3/src/controller/block_editor_controller.js#L133)):*
> ```JavaScript
>     const languagePre = $('#languagePre');
>     const languageTA = $('#languageTA');
>     if ($('#format').val() == BlockEditorController.FORMAT_MANUAL) {
> ```

Add a TODO to move a lot of this view manipulation code into the view class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller/block_editor_controller.js, line 140 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_Gg6-lVQYT-PktDaN:-Kq_PxuO37KbGbD9g8OG:b1o62yq) ([raw file](https://github.com/google/blockly-devtools/blob/969b346d3a2b239077aa2df84b4129826dde0323/src/controller/block_editor_controller.js#L140)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Hm, I see it as `'block'` and `'none'`? I changed it to jQuery to make it a bit more readable.
</blockquote></details>

Oh they're in different orders and I wasn't reading closely enough.  Don't mind me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165#-:-Kq_Q4YhlczKLGdxRlM0:bnfp4nl)*

**Comment by chynu** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller/block_editor_controller.js, line 133 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/165#-Kq_OZvv4VspETjvw2wD:-Kq_RAqgrk90aFnZsr4Y:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/3dee1ca2c9f14c05fed5645a52ac85354d7297c3/src/controller/block_editor_controller.js#L133)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Add a TODO to move a lot of this view manipulation code into the view class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/165)*

**Pull request merged**
