### PR TITLE
Project methods update

### PR DESCRIPTION
**Pull request by svouse**
Beginning of writing methods for Project. The methods up to and including those for adding elements have been updated (ending at line 172 of initial project.js, after addWorkspaceConfiguation(workspaceConfigNaame)) and the methods from other classes used in these methods have been updated as well.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/82)

### CODE REVIEW

**Comment by chynu** [comment]
Minor nits, otherwise lgtm.

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/block_library_set.js, line 74 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOYh4p64QbS1aq4Bo0:-KoOYh4p64QbS1aq4Bo1:b-2dsrhr) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/block_library_set.js#L74)):*
> ```JavaScript
>    *     the set.
>    */
>    getAllBlockTypes() {
> ```

If this returns all block types within a single library, wouldn't there need to be a parameter? Or did you mean for this function to get all block types across all libraries? (Since this is in `BlockLibrarySet`)

---

*[src/model/project.js, line 51 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOYu1pOqqWvPMW9rnh:-KoOYu1pOqqWvPMW9rni:b-ozp2zz) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/project.js#L51)):*
> ```JavaScript
>      * @type {!ToolboxSet}
>      */
>     this.toolboxes = new ToolboxSet();
> ```

Maybe to be clear we can name the field `this.toolboxSet`? since plural is kind of ambiguous. (and i suppose for all other fields below which are set types.)

---

*[src/model/resource_set.js, line 172 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOZuA5cHWX7wjcYdgY:-KoOZuA5cHWX7wjcYdgZ:bjuvbd1) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/resource_set.js#L172)):*
> ```JavaScript
>    * @return {boolean} Whether or not the resource is present in the set.
>    */
>    hasResource(resourceName) {
> ```

If the other sets (`ToolboxSet`, etc.) extend `ResourceSet`, I feel like perhaps keeping the `has()` function the same name would make things more consistent (?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/82#-:-KoO_JBkJKi3stm8hsmK:bud51tc)*

**Comment by svouse** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/block_library_set.js, line 74 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOYh4p64QbS1aq4Bo0:-KoOaUutU8ChXytZI7lh:bg8wyik) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/block_library_set.js#L74)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

If this returns all block types within a single library, wouldn't there need to be a parameter? Or did you mean for this function to get all block types across all libraries? (Since this is in `BlockLibrarySet`)
</blockquote></details>

Nope; as per the @return statement it returns the block types contained across all libraries in the set, so it's everything. Added the word 'set' to the JSDoc above this line to make it clearer (it previously just said library, which was incorrect)

---

*[src/model/project.js, line 51 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOYu1pOqqWvPMW9rnh:-KoOb8VPLkNnBNaYtc_A:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/project.js#L51)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Maybe to be clear we can name the field `this.toolboxSet`? since plural is kind of ambiguous. (and i suppose for all other fields below which are set types.)
</blockquote></details>

Done.

---

*[src/model/resource_set.js, line 172 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOZuA5cHWX7wjcYdgY:-KoOc4J-zwodvAEBnaip:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/resource_set.js#L172)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

If the other sets (`ToolboxSet`, etc.) extend `ResourceSet`, I feel like perhaps keeping the `has()` function the same name would make things more consistent (?).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/82)*

**Comment by AnmAtAnm** [comment]
Two nits, and celine's comments.

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/model/block_library.js, line 52 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOapEG9mTvFpqc5D-W:-KoOapEG9mTvFpqc5D-X:b-ec28u6) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/block_library.js#L52)):*
> ```JavaScript
>    *    saved.
>    */
>   addBlock(blockDefinition) {
> ```

Should this be renamed `addBlockDefinition(..)`?

---

*[src/model/project.js, line 56 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoObHdujVImC8mgqft6:-KoObHdujVImC8mgqft7:b-z3k8pn) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/project.js#L56)):*
> ```JavaScript
>      * @type {!WorkspaceContentsSet}
>      */
>     this.workspaceContents = new WorkspaceContents();
> ```

Declared (in JSDoc) as `WorkspaceContentsSet`, but you instantiated a `WorkspaceContents`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/82#-:-KoOcgagbWLJ2OTUOx0W:b-pj7990)*

**Comment by svouse** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/block_library.js, line 52 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoOapEG9mTvFpqc5D-W:-KoOctjVb4v4DO5S_doe:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/block_library.js#L52)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Should this be renamed `addBlockDefinition(..)`?
</blockquote></details>

Done.

---

*[src/model/project.js, line 56 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/82#-KoObHdujVImC8mgqft6:-KoOd0GQlUUjRg8VAeYj:bt2vr1b) ([raw file](https://github.com/google/blockly-devtools/blob/572f4437a932710e320bec8a13d5338bf2fe114a/src/model/project.js#L56)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Declared (in JSDoc) as `WorkspaceContentsSet`, but you instantiated a `WorkspaceContents`.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/82)*

**Review by chynu — APPROVED** [review]
LGTM!

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/82#-:-KoOgJZAO1HwNsW-YswJ:bnfp4nl)*

**Review by AnmAtAnm — APPROVED** [review]

**Pull request merged**
