### PR TITLE
View updates

### PR DESCRIPTION
**Pull request by svouse**
updates of view methods, adding necessary methods

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/94)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/block_definition.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUWqMVDytKc2wMek65:-KoUWqMVDytKc2wMek66:bkq5689) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_definition.js#L33)):*
> ```JavaScript
>    */
>   getJson() {
>   	throw "unimplemented: getJson";
> ```

two spaces. no tabs.

---

*[src/model/block_library.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUX9wLqhMdxChDAcub:-KoUX9wLqhMdxChDAcuc:b1wqxfx) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L54)):*
> ```JavaScript
>    *    saved.
>    */
>   addBlockDefinition(blockType, blockDefinition) {
> ```

The block definition should have a `type` field that you can use, instead of passing it in.

---

*[src/model/block_library.js, line 186 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUXr-qxz1_Tx7tleyj:-KoUXr-qxz1_Tx7tleyk:bf8tz15) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L186)):*
> ```JavaScript
>    */
>   setName(newName) {
>     this.name = newName;
> ```

If the implementation is this simple, can it be moved up to Resource?

---

*[src/model/block_library.js, line 204 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUY2bB1dA50gAQ6Lxp:-KoUY2bB1dA50gAQ6Lxq:bq58qct) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L204)):*
> ```JavaScript
>   makeBlockTypeJson() {
>     if (this.isEmpty()) {
>       return '';
> ```

I think this should return `[]`.  In fact you could move the `treeBlockTypeJson` above this `if`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by rachel-fenichel** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/block_library.js, line 207 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUb1i9OyNXt8z8unaN:-KoUb1i9OyNXt8z8unaO:b3y4dpy) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L207)):*
> ```JavaScript
>     }
>     const treeBlockTypeJson = [];
>     const types= this.getBlockTypes();
> ```

nit: space before `=`

---

*[src/model/block_library.js, line 213 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbNRiyc9ikxk9e3T2:-KoUbNRiyc9ikxk9e3T3:b3y4dpy) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L213)):*
> ```JavaScript
>     const blockType;
>     while (types[iterationIndex]) {
>       blockType= types[iterationIndex - 1];
> ```

nit: space before `=`

---

*[src/view/app_view.js, line 146 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbghkF1Wlkb78UXig:-KoUbghkF1Wlkb78UXih:b-wz4w27) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L146)):*
> ```JavaScript
>   /**
>    * Initializes the tree for the session.
>    * @param {!Project} The project the tree represents.
> ```

`} project The project`

(missing the parameter name)

---

*[src/view/app_view.js, line 368 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbzOs4mYTF75N-fSS:-KoUbzOs4mYTF75N-fST:b-435src) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L368)):*
> ```JavaScript
>    * @param {string} libraryName The name of the library to add.
>    */
>   addLibraryToTree(libraryName) {
> ```

I would expect this to take in a library object, not a name.  Does the app view have enough information to get the library object from the name?  Same question for the next few functions.

---

*[src/view/app_view.js, line 369 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUboNgpk-yh9hh5obs:-KoUboNgpk-yh9hh5obt:b-9ynade) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L369)):*
> ```JavaScript
>    */
>   addLibraryToTree(libraryName) {
>     console.warn("unimplemented: AppView.addLibraryToTree(libraryName)");
> ```

Did you mean to always print the string "libraryName", or did you want to print the value that was passed in?

If you want to print the value that was passed in, do
`console.warn("unimplemented: AppView.addToolboxToTree(" + toolboxName + ")");`

Same question for the next few functions.

---

*[src/view/app_view.js, line 468 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUcURp2g2rsAdJb4Jk:-KoUcURp2g2rsAdJb4Jl:bkkhs98) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L468)):*
> ```JavaScript
>    * @param {string} blockType Block to edit on block factory.
>    */
>    openBlock(blockType) {
> ```

Nit: looks like there's an extra space at the beginning of this line.

---

*[src/view/navigation_tree.js, line 29 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUcbBPJJ5oREsz7r3H:-KoUcbBPJJ5oREsz7r3I:b-q3tqk7) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/navigation_tree.js#L29)):*
> ```JavaScript
> /**
>  * NavigationTree Class
>  * @param {!Project} project The project the tree shall represent.
> ```

shall represent -> represents

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Review by chynu — APPROVED** [review]

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/block_definition.js, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUWqMVDytKc2wMek65:-KoUcBU1DnkBCtnxx0Sn:bg6iiej) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_definition.js#L33)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

two spaces. no tabs.
</blockquote></details>

Done ( I really ought to figure out my presets so I don't have to change it for each file)

---

*[src/model/block_library.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUX9wLqhMdxChDAcub:-KoUcZU29GFMrqKfkM-k:bqf1zn8) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L54)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The block definition should have a `type` field that you can use, instead of passing it in.
</blockquote></details>

Agreed/done

---

*[src/model/block_library.js, line 186 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUXr-qxz1_Tx7tleyj:-KoUco_AhcO_IAM6eOec:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L186)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

If the implementation is this simple, can it be moved up to Resource?
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 204 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUY2bB1dA50gAQ6Lxp:-KoUcpofcjOo6uMhs2U8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L204)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I think this should return `[]`.  In fact you could move the `treeBlockTypeJson` above this `if`.
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 207 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUb1i9OyNXt8z8unaN:-KoUcuXTB60KjeqwZ6JT:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L207)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: space before `=`
</blockquote></details>

Done.

---

*[src/model/block_library.js, line 213 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbNRiyc9ikxk9e3T2:-KoUd7-Tydo7-sH5Nao6:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L213)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

nit: space before `=`
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 146 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbghkF1Wlkb78UXig:-KoUdA3dz67L5vqXXIks:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L146)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

`} project The project`

(missing the parameter name)
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 368 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUbzOs4mYTF75N-fSS:-KoUgug0rmzFoCUftHrS:b-pl2ofd) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L368)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

I would expect this to take in a library object, not a name.  Does the app view have enough information to get the library object from the name?  Same question for the next few functions.
</blockquote></details>

Agreed/changed; the tree itself could've then asked the project for the actual object, but  it makes more sense to pass it.

---

*[src/view/app_view.js, line 369 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUboNgpk-yh9hh5obs:-KoUdjcvaSe5tq-iyS4B:b-aia843) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L369)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Did you mean to always print the string "libraryName", or did you want to print the value that was passed in?

If you want to print the value that was passed in, do
`console.warn("unimplemented: AppView.addToolboxToTree(" + toolboxName + ")");`

Same question for the next few functions.
</blockquote></details>

Changed to print value of the object's name
(Hadn't thought of doing so, but think it'll be more useful)

---

*[src/view/app_view.js, line 468 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUcURp2g2rsAdJb4Jk:-KoUd_5Pr_f_AfvvhGWE:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/app_view.js#L468)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Nit: looks like there's an extra space at the beginning of this line.
</blockquote></details>

Done.

---

*[src/view/navigation_tree.js, line 29 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUcbBPJJ5oREsz7r3H:-KoUdSqEpP2-DRKa31Jg:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/view/navigation_tree.js#L29)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

shall represent -> represents
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by chynu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/view/navigation_tree.js, line 92 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUmQg3Lh70NYriWfJg:-KoUmQg3Lh70NYriWfJh:bhyclu0) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/navigation_tree.js#L92)):*
> ```JavaScript
>    * Adds a block to the tree.
>    */
>   addBlockNode(blockType) {
> ```

Add `@param`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/model/block_definition.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUkTqttgeWKb_GCxZG:-KoUkTqttgeWKb_GCxZH:bk88c0y) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L32)):*
> ```JavaScript
>    */
>   constructor() {
>     this.type;
> ```

Is this supposed to do something?  Maybe the constructor needs an initial type name param?

Also, I think we can use the existing Resource.name for this.  Just make a property getter `typename` that is backed by `this.name`. That would mean passing the above suggested param to `super()`.

---

*[src/model/block_definition.js, line 40 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUm2e1zl4WAYCh3q7Y:-KoUm2e1zl4WAYCh3q7Z:bt74i1m) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L40)):*
> ```JavaScript
>    */
>   getJson() {
>     throw "unimplemented: getJson";
> ```

Google style guide dictates single quotes.  For all these `unimplemented` throws and warnings, I'll let it slide, but try to be mindful in the future.

(I get caught on this all the time, because I am always switching languages.)

---

*[src/model/block_library.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUX9wLqhMdxChDAcub:-KoUkiwinou_6Q8MQzul:b-ut6ztv) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L54)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Agreed/done
</blockquote></details>

Added in BlockDefinition, but still not used here.

---

*[src/model/resource.js, line 76 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUmK81SK7Kcq_inDlW:-KoUmK81SK7Kcq_inDlX:b-k1wuzg) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/resource.js#L76)):*
> ```JavaScript
>    */
>   getTreeJson() {
>     throw "abstract method: getTreeJson";
> ```

Single quotes.

---

*[src/view/block_editor_view.js, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUo3QL2eKcoFNcIOPc:-KoUo3QL2eKcoFNcIOPd:btisix5) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/block_editor_view.js#L106)):*
> ```JavaScript
>  openBlock(blockType) {
>   console.warn("unimplemented: BlockEditorView.openBlock(" + blockType + ")")
>  }
> ```

Indents are off.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/view/app_view.js, line 360 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUs7JfPxDWnugLwOKN:-KoUs7JfPxDWnugLwOKO:b-3g3jr3) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/app_view.js#L360)):*
> ```JavaScript
>    * @param {string} blockType The type of block to add.
>    */
>   addBlockToTree(blockType) {
> ```

Why would something call addTo / removeFromTree(..) on the AppView, instead of the NavigationTree directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by svouse** [comment]
Review status: 0 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/model/block_definition.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUkTqttgeWKb_GCxZG:-KohQLq3lJUQvgnxtpvc:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L32)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Is this supposed to do something?  Maybe the constructor needs an initial type name param?

Also, I think we can use the existing Resource.name for this.  Just make a property getter `typename` that is backed by `this.name`. That would mean passing the above suggested param to `super()`.
</blockquote></details>

Done.

---

*[src/model/block_definition.js, line 40 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUm2e1zl4WAYCh3q7Y:-KohPYZ4lX2KfiL-HWxN:baqybh6) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L40)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Google style guide dictates single quotes.  For all these `unimplemented` throws and warnings, I'll let it slide, but try to be mindful in the future.

(I get caught on this all the time, because I am always switching languages.)
</blockquote></details>

Thanks! (Also went about fixing at least some of them; the replacement wasn't too bad/I'll switch them as I find more

---

*[src/model/block_library.js, line 54 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUX9wLqhMdxChDAcub:-KohQL0hv9O4q_CIUTOP:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/d00c80a179ddbd1b535a22cc970ed1b65878d330/src/model/block_library.js#L54)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Added in BlockDefinition, but still not used here.
</blockquote></details>

Done.

---

*[src/model/resource.js, line 76 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUmK81SK7Kcq_inDlW:-KohQOdYtC3UFBW2Mid8:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/resource.js#L76)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Single quotes.
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 360 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUs7JfPxDWnugLwOKN:-KohQi0tOR5jelenzKFF:bvls97q) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/app_view.js#L360)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Why would something call addTo / removeFromTree(..) on the AppView, instead of the NavigationTree directly?
</blockquote></details>

I was acting under the assumption that other classes wouldn't have access to the tree//all calls to it would need to be made through AppView, but would it make more sense to just give tree access to the AppController? They methods themselves will just be making the calls to the tree, anyway.  In that case, does AppView need access to the tree at all?

---

*[src/view/block_editor_view.js, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUo3QL2eKcoFNcIOPc:-KohToFjBjyrAg5zbJq0:bt2vr1b) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/block_editor_view.js#L106)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Indents are off.
</blockquote></details>

Fixed.

---

*[src/view/navigation_tree.js, line 92 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUmQg3Lh70NYriWfJg:-KohU6Q0QS6g9lbBrY-X:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/navigation_tree.js#L92)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Add `@param`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/block_definition.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUkTqttgeWKb_GCxZG:-KohVyfzy80IArkARgu_:b-kd1eom) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L32)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Consider adding `get typename() { this.name; }` to this class (or just `type()`) as an alias.

---

*[src/view/app_view.js, line 360 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUs7JfPxDWnugLwOKN:-KohXVoRKkg0afbxABOS:bdpvg0c) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/app_view.js#L360)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

I was acting under the assumption that other classes wouldn't have access to the tree//all calls to it would need to be made through AppView, but would it make more sense to just give tree access to the AppController? They methods themselves will just be making the calls to the tree, anyway.  In that case, does AppView need access to the tree at all?
</blockquote></details>

I'm not sure if the AppView needs access to the tree.  I don't have an obvious example, but I'm not willing to rule it out.  I do think the controller knowing about the tree is sufficient for tree updates.

---

*[src/view/app_view.js, line 419 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KohY3WRyAC5OB3tdMAc:-KohY3WS0b4U6BujG7oi:b-g4nre1) ([raw file](https://github.com/google/blockly-devtools/blob/b10e2141460b0e189f2c52266d0b5f754afc9e53/src/view/app_view.js#L419)):*
> ```JavaScript
>    */
>   removeLibraryFromTree(library) {
>     console.warn('unimplemented: AppView.removeLibraryFromTree(' +  library.name
> ```

Nit: Prefer to start the entire string concatenation on the next line (indented by 4), if it will avoid splitting the string.  This comes from the principle of choosing the largest expression that will resolve the line length issue (the string concatenation expression will fit and is larger than just the last `+ ')'`).

Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Review by AnmAtAnm — APPROVED** [review]
LGTM after a couple it nitpick issues.
Let Rachel have a look, too.

**Comment by svouse** [comment]
Review status: 0 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/model/block_definition.js, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUkTqttgeWKb_GCxZG:-KohaHJPNYZSylJPlOCM:b-bu91xm) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L32)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Consider adding `get typename() { this.name; }` to this class (or just `type()`) as an alias.
</blockquote></details>

Updated

---

*[src/view/app_view.js, line 360 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUs7JfPxDWnugLwOKN:-KohaM4VmjHWqLCR7EAK:b8wklyv) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/view/app_view.js#L360)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm not sure if the AppView needs access to the tree.  I don't have an obvious example, but I'm not willing to rule it out.  I do think the controller knowing about the tree is sufficient for tree updates.
</blockquote></details>

I dig it; removed the AppView methods and moved the tree listener function back in to the tree for now

---

*[src/view/app_view.js, line 419 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KohY3WRyAC5OB3tdMAc:-KohastOZyUxLkZdx38P:b-vk3sgj) ([raw file](https://github.com/google/blockly-devtools/blob/b10e2141460b0e189f2c52266d0b5f754afc9e53/src/view/app_view.js#L419)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Nit: Prefer to start the entire string concatenation on the next line (indented by 4), if it will avoid splitting the string.  This comes from the principle of choosing the largest expression that will resolve the line length issue (the string concatenation expression will fit and is larger than just the last `+ ')'`).

Same below.
</blockquote></details>

Sounds good (these methods are gone, but I'll remember this is the future)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r2, 4 of 9 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/model/block_definition.js, line 40 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/94#-KoUm2e1zl4WAYCh3q7Y:-KoUq9EWrLjbwoFPH9Qc:b4vnqit) ([raw file](https://github.com/google/blockly-devtools/blob/0e689d3eb9d40669576bf97e7678314153870fb5/src/model/block_definition.js#L40)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Google style guide dictates single quotes.  For all these `unimplemented` throws and warnings, I'll let it slide, but try to be mindful in the future.

(I get caught on this all the time, because I am always switching languages.)
</blockquote></details>

+1.  I'll keep an eye on this for stuff other than unimplemented throws.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/94#-:-KohfPpf1bkZ-zm7WGTU:bnfp4nl)*

**Pull request merged**
