### PR TITLE
Refactor: Workspace factory init

### PR DESCRIPTION
**Pull request by chynu**
Refactored 7/7 empty functions from `wfactory_init.js` into new refactor files.

For future: implement functions.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/83)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/toolbox_editor_view.js, line 295 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOnSMRBvo5I6eLda5q:-KoOnSMSJ1qUhJ8hsnu5:b-zf69t5) ([raw file](https://github.com/google/blockly-devtools/blob/430919703318c9e1a5768a2a988be123e66edb2f/src/view/toolbox_editor_view.js#L295)):*
> ```JavaScript
> 
>   /**
>    * Converts from h,s,v values to a hex string
> ```

This looks like it belongs in utils.

---

*[src/view/toolbox_editor_view.js, line 313 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOn_Tr3QBBViv2qcjI:-KoOn_Tr3QBBViv2qcjJ:bar3f4d) ([raw file](https://github.com/google/blockly-devtools/blob/430919703318c9e1a5768a2a988be123e66edb2f/src/view/toolbox_editor_view.js#L313)):*
> ```JavaScript
>   /**
>    * Assign click handlers for Toolbox editor.
>    * @param {!FactoryController} controller The controller for the workspace
> ```

The annotation doesn't match the number of arguments, here and for initEventListeners_ and initColorPicker_.

Same for the workspace editor view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/83)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/toolbox_editor_view.js, line 295 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOnSMRBvo5I6eLda5q:-KoOqrAMyy0aI6qLkmte:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/430919703318c9e1a5768a2a988be123e66edb2f/src/view/toolbox_editor_view.js#L295)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This looks like it belongs in utils.
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 313 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOn_Tr3QBBViv2qcjI:-KoOqrUjo5dY6bhdPDwM:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/430919703318c9e1a5768a2a988be123e66edb2f/src/view/toolbox_editor_view.js#L313)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

The annotation doesn't match the number of arguments, here and for initEventListeners_ and initColorPicker_.

Same for the workspace editor view.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/83)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/83#-:-KoOsuRbpGg_EiiyHurl:bnfp4nl)*

**Review by svouse — APPROVED** [review]

**Comment by AnmAtAnm** [comment]
Two nits, then :lgtm_strong: 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/toolbox_editor_view.js, line 278 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOvJLLezvvc318dpQx:-KoOvJLLezvvc318dpQy:b-pnp5sa) ([raw file](https://github.com/google/blockly-devtools/blob/7dd350fbf0280c1612a4748f1c7d1c8a4a9c93d6/src/view/toolbox_editor_view.js#L278)):*
> in workspace factory.

"toolbox editor"?

---

*[src/view/workspace_editor_view.js, line 120 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOv_J1UZund0_mh0D1:-KoOv_J1UZund0_mh0D2:b-r5k49w) ([raw file](https://github.com/google/blockly-devtools/blob/7dd350fbf0280c1612a4748f1c7d1c8a4a9c93d6/src/view/workspace_editor_view.js#L120)):*
> ```JavaScript
> 
>   /**
>    * Add listeners for workspace factory options input elements.
> ```

s/factory/editor/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/83#-:-KoOvewNsuKH6Md6d-JI:b-51npiu)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/toolbox_editor_view.js, line 278 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOvJLLezvvc318dpQx:-KoOwT2jaXdZaXzy3lfJ:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7dd350fbf0280c1612a4748f1c7d1c8a4a9c93d6/src/view/toolbox_editor_view.js#L278)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

> in workspace factory.

"toolbox editor"?
</blockquote></details>

Done.

---

*[src/view/workspace_editor_view.js, line 120 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/83#-KoOv_J1UZund0_mh0D1:-KoOwTtUbqD4COhj12MH:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7dd350fbf0280c1612a4748f1c7d1c8a4a9c93d6/src/view/workspace_editor_view.js#L120)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

s/factory/editor/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/83)*

**Pull request merged**
