### PR TITLE
Add button

### PR DESCRIPTION
**Pull request by svouse**
Adds add button, without click handlers

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/139)

### CODE REVIEW

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[app.html, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq--s_TgNPWpiuDBMnd:-Kq--s_TgNPWpiuDBMne:b-3l2oe8) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/app.html#L50)):*
> ```HTML
>   <div id="addOptions">
>     <ul class="optionsList">
>       <li><button id="addBlock"><span>Block</span></button></li>
> ```

Is there a reason these are in `<span></span>` tags? They don't have an id/class so I am wondering what they are there for? 0:

---

*[src/factory.css, line 151 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-162nSeDqy-P-34hg:-Kq-162nSeDqy-P-34hh:b-tfw8v7) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L151)):*
> ```CSS
> }
> 
> #addButton {
> ```

Perhaps adding a small comment to section off just CSS related to the button might be helpful
(e.g. `/* Add resource button */`)

---

*[src/factory.css, line 152 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-02sPsQ1dlpJkKBoc:-Kq-02sPsQ1dlpJkKBod:b-eqh2h1) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L152)):*
> ```CSS
> 
> #addButton {
>   position: absolute;
> ```

I believe CSS attributes must be in alphabetical order (google style?).

---

*[src/factory.css, line 168 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-0UqDGyGy8qvLdA5c:-Kq-0UqDGyGy8qvLdA5d:b4k3tl6) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L168)):*
> ```CSS
>   bottom:75px;
>   background-color: #e8f1ff;
>   visibility: hidden;
> ```

I'm not entirely sure about this, but I'm wondering if making it `visibility: hidden;` affects users in clicking things that might be under the invisible add options menu (e.g. if someone makes 100 blocks for whatever reason, the nav tree will go on until the end of the page and the `visibility: hidden;` might keep a user from clicking on a resource that is located in the area that the add options menu is in?

I know that `display:none;` will actually remove the element from the page whereas `visibility:hidden;` will make it invisible but it will still take up the same space. I'm not very sure whether this affects z-index, though.

(Not sure if this makes sense; I can explain better offline if necessary)

---

*[src/view/app_view.js, line 469 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-1i12DRVeRvmToK-S:-Kq-1i12DRVeRvmToK-T:bs9jfa) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/view/app_view.js#L469)):*
> ```JavaScript
>    * Assign button click handlers for the block factory.
>    */
>   assignBlockFactoryClickHandlers() {
> ```

I probably pasted this part in I think, but since it came up in this PR.. Perhaps this could be better named as `assignClickHandlers()` in general since block factory is the old name for the block editor (which has its own set of click handlers assigned in `BlockEditorView`.

---

*[src/view/app_view.js, line 473 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-1_Is17YItC7KjrEU:-Kq-1_Is17YItC7KjrEV:b8pvfdb) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/view/app_view.js#L473)):*
> ```JavaScript
>     // Assign button event handlers for Block Factory.
>     $('#localSaveButton').click(() => {
>       console.log('rewire app_view.js assignBlockFactoryClickHandlers');
> ```

Should these be `console.warn()`? (Not that it Matters Immensely but a small nit)

(and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by svouse** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[app.html, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq--s_TgNPWpiuDBMnd:-Kq-7i0xSL6YMKiUsY7f:b-l4riwj) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/app.html#L50)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Is there a reason these are in `<span></span>` tags? They don't have an id/class so I am wondering what they are there for? 0:
</blockquote></details>

whoops no;removed

---

*[src/factory.css, line 151 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-162nSeDqy-P-34hg:-Kq-7cDl4sq7L2GFTIdL:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L151)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Perhaps adding a small comment to section off just CSS related to the button might be helpful
(e.g. `/* Add resource button */`)
</blockquote></details>

Done.

---

*[src/factory.css, line 152 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-02sPsQ1dlpJkKBoc:-Kq-6Tff7LNagylNcWwt:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L152)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I believe CSS attributes must be in alphabetical order (google style?).
</blockquote></details>

Done.

---

*[src/factory.css, line 168 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-0UqDGyGy8qvLdA5c:-Kq-7wP7Ng6bNBZ8YO1p:bz3vudb) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/factory.css#L168)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I'm not entirely sure about this, but I'm wondering if making it `visibility: hidden;` affects users in clicking things that might be under the invisible add options menu (e.g. if someone makes 100 blocks for whatever reason, the nav tree will go on until the end of the page and the `visibility: hidden;` might keep a user from clicking on a resource that is located in the area that the add options menu is in?

I know that `display:none;` will actually remove the element from the page whereas `visibility:hidden;` will make it invisible but it will still take up the same space. I'm not very sure whether this affects z-index, though.

(Not sure if this makes sense; I can explain better offline if necessary)
</blockquote></details>

Makes sense! Done.

---

*[src/view/app_view.js, line 469 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-1i12DRVeRvmToK-S:-Kq-8fCP56y_80zQb4mv:b-mzzve4) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/view/app_view.js#L469)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I probably pasted this part in I think, but since it came up in this PR.. Perhaps this could be better named as `assignClickHandlers()` in general since block factory is the old name for the block editor (which has its own set of click handlers assigned in `BlockEditorView`.
</blockquote></details>

Agreed/done. Also removed other handlers for now (I'll rewire them)

---

*[src/view/app_view.js, line 473 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-1_Is17YItC7KjrEU:-Kq-8imckbT0EhqGUKLm:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/84542e3f553fb87d3438c088bf99be95b5a50981/src/view/app_view.js#L473)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Should these be `console.warn()`? (Not that it Matters Immensely but a small nit)

(and below)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by chynu** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/app_view.js, line 428 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-JMIKWzPZECbarVAQ:-Kq-JMIKWzPZECbarVAR:bh9cjpu) ([raw file](https://github.com/google/blockly-devtools/blob/f2ae5024a427aca9fe367f22e312cbebac59e5de/src/view/app_view.js#L428)):*
> ```JavaScript
>        * listener for expanding.
>        */
>       function collapse() {
> ```

I think this collapse/expand function can be better implemented by storing a boolean field such as `this.addFlyoutIsOpen = false;` so that you can just check whether the flyout is open/closed before either expanding or collapsing?

Also, it might be better if you have some helper function outside of this method, such as `openAddFlyout_(open)` which is responsible for opening/closing it. That way you can explicitly deal with only listening/sending the command within the click handler.

This doesn't really affect functionality, but it might be cleaner/more readable code (?). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by chynu** [comment]
( :lgtm: After previous comment )

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139#-:-Kq-SffDNC9tIHWacJOK:b-6mxh2e)*

**Comment by svouse** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/view/app_view.js, line 428 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-JMIKWzPZECbarVAQ:-Kq-Z4B6iVJD7aRmRocN:b-65g09a) ([raw file](https://github.com/google/blockly-devtools/blob/f2ae5024a427aca9fe367f22e312cbebac59e5de/src/view/app_view.js#L428)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I think this collapse/expand function can be better implemented by storing a boolean field such as `this.addFlyoutIsOpen = false;` so that you can just check whether the flyout is open/closed before either expanding or collapsing?

Also, it might be better if you have some helper function outside of this method, such as `openAddFlyout_(open)` which is responsible for opening/closing it. That way you can explicitly deal with only listening/sending the command within the click handler.

This doesn't really affect functionality, but it might be cleaner/more readable code (?). 
</blockquote></details>

I dig it//great idea!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by chynu** [comment]
lgtm after Super Nits

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/app_view.js, line 439 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-cIoq2c-B8Re3Wr1x:-Kq-cIoq2c-B8Re3Wr1y:bn40h4b) ([raw file](https://github.com/google/blockly-devtools/blob/7af8f5825d7bbf529ff213f189f87e69d46f7cf0/src/view/app_view.js#L439)):*
> ```JavaScript
>     const opt = document.getElementById('addOptions');
>     this.addFlyoutOpen = true;
>     opt.className= 'expanded';
> ```

Nit: space between assignment operator

---

*[src/view/app_view.js, line 447 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-cMjIloxJfbRiahXM:-Kq-cMjIloxJfbRiahXN:b-lqvh9e) ([raw file](https://github.com/google/blockly-devtools/blob/7af8f5825d7bbf529ff213f189f87e69d46f7cf0/src/view/app_view.js#L447)):*
> ```JavaScript
>   assignClickHandlers() {
>     $('#addButton').click(() => {
>       if(this.addFlyoutOpen == true) {
> ```

Nit: just `if (this.addFlyoutOpen)`? (also space after `if`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139#-:-Kq-cf9nrU48_v57cxsT:b-85yph2)*

**Comment by svouse** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/view/app_view.js, line 439 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-cIoq2c-B8Re3Wr1x:-Kq-crPMy80s_N57H9lm:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7af8f5825d7bbf529ff213f189f87e69d46f7cf0/src/view/app_view.js#L439)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: space between assignment operator
</blockquote></details>

Done.

---

*[src/view/app_view.js, line 447 at r3](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-cMjIloxJfbRiahXM:-Kq-cxxBIXJMKruHijdD:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/7af8f5825d7bbf529ff213f189f87e69d46f7cf0/src/view/app_view.js#L447)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Nit: just `if (this.addFlyoutOpen)`? (also space after `if`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by AnmAtAnm** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[app.html, line 56 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-gmpPFEbsGoWfdIWt:-Kq-gmpPFEbsGoWfdIWu:bk1llt3) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/app.html#L56)):*
> ```HTML
>       <li><button id="addWorkspaceConfig">Workspace Configuration</button></li>
>     </ul>
>   </div>
> ```

Would it be easier to align these together if they were in their own absolutely positioned `<div>`?

---

*[src/factory.css, line 157 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-h45StGLwlXWBSjWG:-Kq-h45StGLwlXWBSjWH:b-ou9jap) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L157)):*
> ```CSS
>   cursor: pointer;
>   font-size: 48px;
>   height: 5%;
> ```

We probably don't want this resizing with the browser window size.  Choose an absolute size.

---

*[src/factory.css, line 169 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-hTHZjOs_ypLdovf0:-Kq-hTHZjOs_ypLdovf1:b4hyi1v) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L169)):*
> ```CSS
>   position: absolute;
>   display: none;
>   width:200px;
> ```

Can this adapt to the text width?

---

*[src/factory.css, line 173 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-g_J6fWkFporCAfZ2:-Kq-g_J6fWkFporCAfZ3:bwmq5ld) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L173)):*
> ```CSS
> 
> #addOptions.expanded {
>   display: initial;
> ```

`block`?

---

*[src/view/material_icons_add_circle.png, line 0 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-hz0XLdH6oj7CJkrd:-Kq-hz0XLdH6oj7CJkre:bgdcsp7) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/view/material_icons_add_circle.png#L0)):*
Alternatively, the `add` icon without the circle, allowing the div to be the circle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by AnmAtAnm** [comment]
SEveral comments, but the only one of importance is replacing the use of `display: initial`. :lgtm: 

---

Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139#-:-Kq-iWGFv3BCEvYxrnBK:bgcvdgw)*

**Comment by AnmAtAnm** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/factory.css, line 153 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-ih736qFob7Gi0lmU:-Kq-ih736qFob7Gi0lmV:b-r9csu8) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L153)):*
> ```CSS
> /* Add resource button */
> #addButton {
>   border-radius: 50%;
> ```

Did you want a `background-color` to go with that `border-radius`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by svouse** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[app.html, line 56 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-gmpPFEbsGoWfdIWt:-Kq-uP5ZPb6fKk4iEowr:b-w5no0f) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/app.html#L56)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Would it be easier to align these together if they were in their own absolutely positioned `<div>`?
</blockquote></details>

Indeed; done

---

*[src/factory.css, line 153 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-ih736qFob7Gi0lmU:-Kq-uR0LMaQ5XV1M6GvX:b-d8y080) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L153)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Did you want a `background-color` to go with that `border-radius`?
</blockquote></details>

Nope; removed 

---

*[src/factory.css, line 157 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-h45StGLwlXWBSjWG:-Kq-uTwg1tc9nsD7fMVf:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L157)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

We probably don't want this resizing with the browser window size.  Choose an absolute size.
</blockquote></details>

Done.

---

*[src/factory.css, line 173 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-g_J6fWkFporCAfZ2:-Kq-uY46DBxsNHl_sjXD:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L173)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`block`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Comment by svouse** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/factory.css, line 153 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-ih736qFob7Gi0lmU:-Kq-xoyJvQ7Pqiz_ZpuS:bh22o2t) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L153)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Nope; removed 
</blockquote></details>

jk re-added for hover color area

---

*[src/factory.css, line 169 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-hTHZjOs_ypLdovf0:-Kq-xDXmqeHDXSZuo-mi:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/src/factory.css#L169)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Can this adapt to the text width?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Review by AnmAtAnm — APPROVED** [review]

**Comment by AnmAtAnm** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[app.html, line 56 at r4](https://reviewable.io:443/reviews/google/blockly-devtools/139#-Kq-gmpPFEbsGoWfdIWt:-Kq01XUHvQiidE8LMSc1:bkxjl69) ([raw file](https://github.com/google/blockly-devtools/blob/38317c8b9688bf9f44d7f432d71983be432bf61b/app.html#L56)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

Indeed; done
</blockquote></details>

discussed offline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/139)*

**Pull request merged**
