### PR TITLE
Toolbox Editor: Export (JS/XML)

### PR DESCRIPTION
**Pull request by chynu**
Can now export toolboxes as JS or XML. Other export/import functions not working yet.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-devtools/150)

### CODE REVIEW

**Comment by svouse** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1202 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqAApptOAZsAS2_4zjP:-KqAApptOAZsAS2_4zjQ:b-l3io2z) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/controller/toolbox_controller.js#L1202)):*
> ```JavaScript
> 
>   /**
>    * Creates file with toolbox contents, prompts user, then downloads onto user's
> ```

specify what the user is being prompted for

---

*[src/controller/toolbox_controller.js, line 1233 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqAAwhySR9zgq6zqSyW:-KqAAwhySR9zgq6zqSyX:b-6h6y6q) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/controller/toolbox_controller.js#L1233)):*
> ```JavaScript
>    * Generates JavaScript string representation of toolbox for user to download.
>    * Does not deal with popups or file system access; just generates content.
>    *
> ```

missing param

---

*[src/view/toolbox_editor_view.js, line 348 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqABC6giKnvRMXEP-nd:-KqABC6giKnvRMXEP-ne:b-1myloq) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/view/toolbox_editor_view.js#L348)):*
> ```JavaScript
> 
>   /**
>    * Refreshes any information in the view (such as the name of the currently
> ```

looks like (at least at the current moment) this only refreshes the name?

---

*[src/view/toolbox_editor_view.js, line 360 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqABeLix0nJUqSKWeeu:-KqABeLix0nJUqSKWeev:b-kbvvoc) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/view/toolbox_editor_view.js#L360)):*
> ```JavaScript
>    *     otherwise.
>    */
>   displayAddShadow(show) {
> ```

same #149 comment about duplicate methods across the toolbox and workspace editors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by chynu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1202 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqAApptOAZsAS2_4zjP:-KqAOWm_jobe0SR7sftU:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/controller/toolbox_controller.js#L1202)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

specify what the user is being prompted for
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 1233 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqAAwhySR9zgq6zqSyW:-KqAGIGm-wZpGgJx7Xml:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/controller/toolbox_controller.js#L1233)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

missing param
</blockquote></details>

Done.

---

*[src/view/toolbox_editor_view.js, line 348 at r1](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqABC6giKnvRMXEP-nd:-KqAGKQtJkDNNie0OAxa:bc9ylub) ([raw file](https://github.com/google/blockly-devtools/blob/75e905658f1c39a9dc79d2c8d27c705d2574eace/src/view/toolbox_editor_view.js#L348)):*
<details><summary><i>Previously, svouse wrote…</i></summary><blockquote>

looks like (at least at the current moment) this only refreshes the name?
</blockquote></details>

Yeah, for now it just refreshes the name. We can add in any other information later on if we decide to do so (?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by svouse** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150#-:-KqOZABsGAS76tPe6Dbc:bnfp4nl)*

**Comment by rachel-fenichel** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1211 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOq_IzO_S6qpt6s5kD:-KqOq_IzO_S6qpt6s5kE:bsxu4fi) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1211)):*
> ```JavaScript
>   export(toolbox, type) {
>     // Prompt user for file name.
>     const fileName = prompt('File name for toolbox:',
> ```

This is user input and needs some error checking.  

---

*[src/controller/toolbox_controller.js, line 1218 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqhLyzuoB5RuACcTO:-KqOqhLz8uPpqbpadv62:bkxgpxy) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1218)):*
> ```JavaScript
>     }
> 
>     let fileContents = Blockly.Xml.domToPrettyText(toolbox.getExportData());
> ```

You're generating the XML version, then overriding it with the JS version if that's what's needed.  Only generate the XML version if the type was TYPE_XML.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1218 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqhLyzuoB5RuACcTO:-KqOrtcf9PrpkC9o08yB:b-kwl8sp) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1218)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

You're generating the XML version, then overriding it with the JS version if that's what's needed.  Only generate the XML version if the type was TYPE_XML.
</blockquote></details>

The JS version is based on the XML version.

---

*[src/controller/toolbox_controller.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqrrAuvRKWqIj80jR:-KqOqrrAuvRKWqIj80jS:b-o8cy1z) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1246)):*
> ```JavaScript
> if (!${xmlStorageVariable}) {
>   ${xmlStorageVariable} = {};
> }
> ```

Idiomatic way to do this (using `Object.create()`) is:

    ${xmlStorageVariable} = ${xmlStorageVariable} || Object.create(null);

And I wouldn't add the comment in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1218 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqhLyzuoB5RuACcTO:-KqOsM0f67zu9O3WbSBi:bcrerc9) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1218)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

The JS version is based on the XML version.
</blockquote></details>

Ignore my comment. Though it is true, that first XML is not used in the call to `generateToolboxFile`

---

*[src/controller/toolbox_controller.js, line 1237 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOsZc_O8zKlVEKAS1A:-KqOsZc_O8zKlVEKAS1B:bbov5qf) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1237)):*
> ```JavaScript
>    * @returns {string} String representation of JS file to be exported.
>    */
>   generateToolboxFile(toolbox) {
> ```

`generateToolboxJsFile`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1211 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOq_IzO_S6qpt6s5kD:-KqOtiLAqgtPiDUj9-5S:bu57nvd) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1211)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

This is user input and needs some error checking.  
</blockquote></details>

I realized that since toolboxes will now have names (since we are supporting multiple toolboxes), we probably won't need the popup anyway. (Removed the prompt)

---

*[src/controller/toolbox_controller.js, line 1218 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqhLyzuoB5RuACcTO:-KqOtw7Jy8sm1Bsqb7ob:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1218)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Ignore my comment. Though it is true, that first XML is not used in the call to `generateToolboxFile`
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 1237 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOsZc_O8zKlVEKAS1A:-KqOu-EnSh3hUch0-OQo:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1237)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

`generateToolboxJsFile`?
</blockquote></details>

Done.

---

*[src/controller/toolbox_controller.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqrrAuvRKWqIj80jR:-KqOu9lRr86B-E0zNhHb:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1246)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Idiomatic way to do this (using `Object.create()`) is:

    ${xmlStorageVariable} = ${xmlStorageVariable} || Object.create(null);

And I wouldn't add the comment in this case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150#-:-KqP7xkMsyF1TL48_7Xg:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1211 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOq_IzO_S6qpt6s5kD:-KqP8ClJ9mghpUiYrkW7:b-euv4qk) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1211)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

I realized that since toolboxes will now have names (since we are supporting multiple toolboxes), we probably won't need the popup anyway. (Removed the prompt)
</blockquote></details>

Then you need either error check on that name, or a way to map the name to platform friendly filename (web: no spaces, android: lowercase, etc).  A placeholder conversion function with a TODO is fine for now.

---

*[src/controller/toolbox_controller.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqrrAuvRKWqIj80jR:-KqP7voIzHO6cL_s4RGh:b-raldvo) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1246)):*
<details><summary><i>Previously, chynu (celine choo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Whoops... I forgot to add `var ` in front of it.  You'll need it in case the var doesn't exist yet (and it is okay if it does already exist).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by chynu** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/controller/toolbox_controller.js, line 1211 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOq_IzO_S6qpt6s5kD:-KqPIHWUgCNfZykTaYbj:bvhhb29) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1211)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Then you need either error check on that name, or a way to map the name to platform friendly filename (web: no spaces, android: lowercase, etc).  A placeholder conversion function with a TODO is fine for now.
</blockquote></details>

Ohh, I see. I created an issue #156 and an empty function in `FactoryUtils.escapeForFileSystem()`.

---

*[src/controller/toolbox_controller.js, line 1246 at r2](https://reviewable.io:443/reviews/google/blockly-devtools/150#-KqOqrrAuvRKWqIj80jR:-KqPCduR9kfDJZq17rEx:b-896fix) ([raw file](https://github.com/google/blockly-devtools/blob/35d2a19d94c3c5108cdd70ad026d2a6edde7225d/src/controller/toolbox_controller.js#L1246)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Whoops... I forgot to add `var ` in front of it.  You'll need it in case the var doesn't exist yet (and it is okay if it does already exist).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-devtools/150)*

**Comment by chynu** [comment]
Merged this PR into #152 because of similar code/concepts.

**Pull request closed without merging**
